### ISSUE TITLE
Glitch in API docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#1008]
Similar to https://github.com/strongloop/loopback/issues/2534 we have http://apidocs.strongloop.com/loopback-datasource-juggler/#if.  In this case, I think we just need to change https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L336 to be plain comment `/*` rather than doc comment `/**` .

@superkhau Sound right?

**Comment by superkhau** [comment]
@crandmck Correct. Just use `//` and that should fix the problem.

**Comment by crandmck** [comment]
Fixed by f1ed1ee023d06edf9acd1ad3c8b56a22834abe63 but I'm going to wait til republish to npm to close this.
