### ISSUE TITLE
EMFILE error on bulk data insert

### ISSUE THREAD

**Issue by manojkumar71** [strongloop/loopback-datasource-juggler#1014]
Hi all,
I'm developing an loopback application to get data using oracledb npm module from ORACLE and convert it to JSON format to be stored in MONGODB.
MONGODB is accessed using "loopback-connector-mongodb".
The data to be stored would be around for 100 collections as of for 100 tables from ORACLE. 
I'm pushing data with http request row by row for the entire collection list from node server from my local application to another server application on remote machine using http-request through remote method call.

When the data write operation the remote machine application stops throwing an error showing "EMFILE error". 

I googled and some reference showed that it is because of the maximum number of opened files/sockets. Hence i tried disconnecting the DataSource for each request. Still i'm getting the same error.

Please help me on this!!

Thanks.

**Comment by loay** [comment]
Hi @manojkumar71 
Are you still experiencing the same issue? If so, can you please provide a sample project so I can help reproduce and debug? Thanks. 
[Report Bug](http://loopback.io/doc/en/contrib/Reporting-issues.html)
