### ISSUE TITLE
Async Operation hooks triggered from 'loaded' change order of find results

### ISSUE THREAD

**Issue by quarkboy** [strongloop/loopback-datasource-juggler#1015]
When using the "Computed" mixin I noticed that "order" was no longer working correctly with async functions as the computed callback functions.

As all computed mixin does is add in an observer to "loaded", it shouldn't be able to affect the order of the objects returned from find, therefor this has to be some issue with dao.js or observer.js...

**Comment by quarkboy** [comment]
I've managed to reproduce the issue without the Computed mixin, with just a simple 'loaded' observe hook:

```
Volume.observe('loaded', function(ctx, next) {
    var Attachment = Volume.app.models.Attachment;
    var filter = {
      where: {
        modelType: 'Volume',
        foreignKey: ctx.instance.id.toString()
      }
    };
    Attachment.find(filter, function (err, atts) {
      if(err) next(err);
      ctx.instance.attachments = atts;
      next()
    });
  });
```
Setting the observer causes the return order of results for find to return incorrect order, both from scopes and from direct order queries.

**Comment by Amir-61** [comment]
I believe this is fixed in `loopback-datasource-juggler@2.47.0`

https://github.com/strongloop/loopback-datasource-juggler/pull/999

**Comment by quarkboy** [comment]
Yup, that's exactly where I was looking.  fixed 10 days ago?  I'll look to upgrading versions then.

**Comment by Amir-61** [comment]
>fixed 10 days ago?
Yes

I'm going to close this ticket now. Please feel free to re-open it if you see any more issues.

Thanks
