### ISSUE TITLE
Validatable.validatesFormatOf incorrect example on the docs

### ISSUE THREAD

**Issue by alexjoverm** [strongloop/loopback-datasource-juggler#1025]
On the [docs](https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validatesformatof) you see the example is:

```javascript
User.validatesFormat('name', {with: /\w+/});
```

Is missing the *`Of`* part, it should be:

```javascript
User.validatesFormatOf('name', {with: /\w+/});
```

Not a big deal, but seems it needs a fix.

**Comment by Amir-61** [comment]
Fixed in this PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1032

Thanks!
