### ISSUE TITLE
Incorrect processing of the zero filter.limit parameter

### ISSUE THREAD

**Issue by angfal** [strongloop/loopback-datasource-juggler#1038]
The dao.js code:

```
/*
 * Normalize the filter object and throw errors if invalid values are detected
 * @param {Object} filter The query filter object
 * @returns {Object} The normalized filter object
 * @private
 */
DataAccessObject._normalize = function(filter) {
    ...
    if (filter.limit || filter.skip || filter.offset) {
      var limit = Number(filter.limit || 100);
      var offset = Number(filter.skip || filter.offset || 0);
      if (isNaN(limit) || limit <= 0 || Math.ceil(limit) !== limit) {
        err = new Error(util.format('The limit parameter %j is not valid',
          filter.limit));
        err.statusCode = 400;
        throw err;
      }
      if (isNaN(offset) || offset < 0 || Math.ceil(offset) !== offset) {
        err = new Error(util.format('The offset/skip parameter %j is not valid',
            filter.skip || filter.offset));
        err.statusCode = 400;
        throw err;
      }
      filter.limit = limit;
      filter.offset = offset;
      filter.skip = offset;
    }
  ...
}
```

The filter limit can be both string (if we received the filter from HTTP request) and integer (if we execute find() request mannually).

If limit is 0, in the first case its ok, we receive 'The limit parameter is not valid' error, but in the second case we have no error. It's because 'filter.limit' in the first 'if' in the first case returns 'true' (boolean value of string "0" is true), but in the second case it returns false (boolean value of integer 0 is 'false')

**Comment by superkhau** [comment]
Would you like to submit a PR with some test cases instead?

**Comment by Amir-61** [comment]
@angfal It would be perfect to send a PR and discuss the issue there with adding test cases which fail with current implementation. Also please link the issue to the PR in case if you make one.

Thanks!
