### ISSUE TITLE
Package dependency error

### ISSUE THREAD

**Issue by PhilippeCorreges** [strongloop/loopback-datasource-juggler#1066]
Hello,
When npm install loopback-datasource-juggle, the following warning is thrown : 

deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by davidcheung** [comment]
@PhilippeCorreges Looks like this is from `fs-sync`, if you dont mind could you perhaps make a pull request against https://github.com/kaelzhang/node-fs-sync to use a newer version of `glob`
```
└─┬ strong-globalize@2.6.9 
    ├── async@1.5.2 
    ├── esprima@2.7.3 
    ├── estraverse@4.2.0 
    ├─┬ fs-sync@1.0.2 
    │ ├─┬ glob@4.5.3 
    │ │ ├─┬ inflight@1.0.5 
    │ │ │ └── wrappy@1.0.2 
    │ │ ├── minimatch@2.0.10 

```

**Comment by dhmlau** [comment]
It's been updated to minimatch 3.0.2.  Closing this issue.
