### ISSUE TITLE
Polymorphic hasMany inverse relation doesn't work on include filter

### ISSUE THREAD

**Issue by alexpls** [strongloop/loopback-datasource-juggler#1079]
Using an include filter where the included relation is a polymorphic hasMany with invert set to true does not correctly take into account the invert option when figuring out which model to query, causing no records for the relation to return.

Given these model definitions:

``` js
Picture = db.define('Picture', { name: String });
Author = db.define('Author', { name: String });
PictureLink = db.define('PictureLink', {});

Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });
```

When running the below code snippet an empty array will always return for pictures, even if it actually contains valid entries:

``` js
Author.findOne({ include: 'pictures' }...); // this will not work, pictures will always be empty
```

However when querying the relation directly like this, things work fine:

``` js
// Given an author instance...
author.pictures(); // this will work, pictures will include all pictures
```

Here is the failing test case I wrote which shows this behaviour. Please correct me if I have misunderstood how the inverse relations should work:

``` js
  describe('polymorphic hasMany', function() {
    before(function(done) {
      Picture = db.define('Picture', { name: String });
      Author = db.define('Author', { name: String });
      PictureLink = db.define('PictureLink', {});

      Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
      Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });

      db.automigrate(['Picture', 'Author', 'PictureLink'], done);
    });

    it('should properly query through an inverted relationship', function(done) {
      Author.create({ name: 'Steve' }, function(err, author) {
        author.pictures.create({ name: 'Steve pic 1' }, function(err, pic) {
          Author.findOne({ include: 'pictures' }, function(err, author) {
            if (err) { return done(err); }
            assert.equal(author.pictures().length, 1);
            assert.equal(author.pictures()[0].name, 'Steve pic 1');
            done();
          });
        });
      });
    });
  });
```

This issue might be related to #927, but I'm not sure.

**Comment by devpascoe** [comment]
Could we have this merged? Really need it 😆

**Comment by jannyHou** [comment]
@devpascoe I will take a look of the PR, let's move discussion there.

**Comment by proreact-mj** [comment]
What is the outlook to get this in a release version of 2.x?

**Comment by jannyHou** [comment]
@proreact-mj https://github.com/strongloop/loopback-datasource-juggler/pull/1296 is still in progress.

**Comment by proreact-mj** [comment]
Confirmed fixed in 2.55.1 (though tested in 2.55.2)

**Comment by jannyHou** [comment]
thanks! I am closing this issue now.

**Comment by iamraphson** [comment]
@jannyHou check we have this in 3.x or master? This feature only exists in 2.x
