### ISSUE TITLE
Support JOIN when using relational databases.

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-datasource-juggler#1092]
I create this issue for public discussion of supporting "JOIN" among related models.

**Comment by jannyHou** [comment]
Related issue: 
- Design the query signature: https://github.com/strongloop/loopback-datasource-juggler/issues/1042

- Apply filters on property: https://github.com/strongloop/loopback/issues/683

**Comment by jeff3yan** [comment]
Was this previous pull request related? https://github.com/strongloop/loopback-connector/pull/40
