### ISSUE TITLE
validateNumericality does nullCheck and therefore limits utility

### ISSUE THREAD

**Issue by C3realGuy** [strongloop/loopback-datasource-juggler#1106]
Because validateNumericality checks if an attribute is set, and if not, fails, it limits the way you can use this validator.
For example you have an attribute which is optional, but, if it's set, it should be a number. You can't use validatesNumericalityOf because it flags err() even if the attribute is not set.
I think it would be better to stick to the concept, one validator checks one thing and you apply multiple validators to do what you need.
If you want that the attribute is set and numerical, just use validatesPresenceOf + validatesNumericalityOf.

**Comment by Amir-61** [comment]
@C3realGuy 

I see your point... Would you like to send a PR and we discuss there?

**Comment by C3realGuy** [comment]
I will give it a try.
https://github.com/strongloop/loopback-datasource-juggler/pull/1109

**Comment by C3realGuy** [comment]
@Amir-61 
i figured out, this is actually not a bug. This is well expected behaviour. See https://github.com/strongloop/loopback-datasource-juggler/issues/541
But still i discovered some fishy things:

`  describe('numericality', function() {
    it('dummmy should test', function() {
      var t = true;
      t.should.be.false; // does not fail?!
    });
...`

**Comment by Amir-61** [comment]
Thanks for clarification @C3realGuy. I'll work with our doc expert to document `allowNull`, `allowBlank`, `if` and`unless` which are explained in https://github.com/strongloop/loopback-datasource-juggler/issues/541  to avoid more confusion.
