### ISSUE TITLE
nullCheck checks first for null, later if attribute is defined

### ISSUE THREAD

**Issue by C3realGuy** [strongloop/loopback-datasource-juggler#1111]
in the moment [nullCheck](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/validations.js#L629) checks first if attribute == null and after that if it's blank (undefined).

There are 2 Problems:
1. Using two equals with an null check (if foo == null) means it's false if foo is undefined or foo is null. So this already fails for undefined attributes even before we check for blank (undefined).
2. We should first check if blank and after that if null.

**Comment by C3realGuy** [comment]
See https://github.com/strongloop/loopback-datasource-juggler/pull/1109 for tests which fail on the current commit due to this issue. Wrong errors are raised.

**Comment by Amir-61** [comment]
>Using two equals with an null check (if foo == null) means it's false if foo is undefined or foo is null. 

Not sure what you mean; please see:
```
> null == undefined
true
```
Are you fixing what you are proposing in https://github.com/strongloop/loopback-datasource-juggler/pull/1109 ?

**Comment by C3realGuy** [comment]
> Not sure what you mean; please see:

> null == undefined
true
Could you please clarify that?

```
> null == undefined
true
> null == null
true
> null === undefined
false
> null === null
true
```

nullCheck basically distinguishs between "is null" and "is blank/undefined". But because it first checks for "is null" with two equals it already fails here for for undefined attributes.
So if you have an undefined attribute, you will never get to the "is blank" check, because it fails already on the wrong implemented "is null" check. Therefore you need to use 3 equals to make sure it's really null and not only a type conversion in js.

This isse and https://github.com/strongloop/loopback-datasource-juggler/issues/1112 are fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1109. Put the numericality tests in the current release and you will see that those tests fail which make sure that the correct error is "raised". 
Sorry for my clumsy language, i'm not an english speaking guy...

**Comment by C3realGuy** [comment]
Fixed in https://github.com/strongloop/loopback-datasource-juggler/commit/662458dc2c78c0066ae9b122e189270ec9513470

**Comment by Amir-61** [comment]
Thanks @C3realGuy
