### ISSUE TITLE
validateNumericality not checking for isNaN and no tests

### ISSUE THREAD

**Issue by C3realGuy** [strongloop/loopback-datasource-juggler#1112]
validateNumericality is only checking for the type of the attribute, which is not enough. It's also needed to check if it's not NaN.
Also there were no tests for this validator.
See this PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1109

**Comment by Amir-61** [comment]
Connect to: https://github.com/strongloop/loopback-datasource-juggler/pull/1109

**Comment by Amir-61** [comment]
Closing this issue since it is fixed now by #1109
