### ISSUE TITLE
Add test coverage for `validatesNumericalityOf `

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-datasource-juggler#1120]

**Comment by C3realGuy** [comment]
Do you miss anything in https://github.com/strongloop/loopback-datasource-juggler/pull/1109 ? I don't use should.js framework because it's simply not working for me. Please tell me if 'dummy for should framework which should fail' fails for you. If so, something's wrong with mit install.

**Comment by Overdrivr** [comment]
@C3realGuy It's because you forgot the parentheses, the syntax is `false.should.be.true()`.
