### ISSUE TITLE
Add test coverage for `validatesExclusionOf`

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-datasource-juggler#1121]

**Comment by Overdrivr** [comment]
I am interested in implementing this, let me know if that's ok.

**Comment by superkhau** [comment]
@Overdrivr PRs are always welcome. ;)

**Comment by Overdrivr** [comment]
Cool ! Made a PR ;) Let me know if changes need to be made.

**Comment by jannyHou** [comment]
Closing since the fix pr checked in. :+1:
