### ISSUE TITLE
Update links to documentation

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#1124]
There are links to `docs.strongloop.com` in various places in the code that we should replace with links to the new doc site `loopback.io/doc`.

https://github.com/strongloop/loopback-datasource-juggler/search?utf8=%E2%9C%93&q=%22docs.strongloop.com%22&type=Code

NOTE: The new site will remain around for a while, but it is deprecated for LoopBack, so we _should_ update the links.  

**This issue is specifically for URLs embedded in code, not in README, etc.**

In general, there is a direct mapping of old URLs to new URLs, e.g. `https://docs.strongloop.com/display/public/LB/Installing+StrongLoop` -->
`http://loopback.io/doc/en/lb2/Installing-StrongLoop.html`.  
The same mapping is true for pages in the APIC space: `https://docs.strongloop.com/display/public/APIC/Installing+StrongLoop` -->
`http://loopback.io/doc/en/lb2/Installing-StrongLoop.html`.

For 3.0-specific features, replace `lb2` with `lb3` in the URL.

There may be one or two pages that don't map that way... But all the new URLs should look like http://loopback.io/doc/en/lb2/xxx.html.

**Comment by crandmck** [comment]
Let's keep this open until we fix or it is no longer relevant.

**Comment by dhmlau** [comment]
issue not fixed. reopening it.
