### ISSUE TITLE
upsertWithWhere bug in JSDoc

### ISSUE THREAD

**Issue by cojack** [strongloop/loopback-datasource-juggler#1132]
There is:

```
 * * @param {Object} [where]  `where` filter, like
```

should be:

```
 * @param {Object} [where]  `where` filter, like
```

Because of this in generated documentation (http://apidocs.strongloop.com/loopback/#persistedmodel-upsertwithwhere), first argument `where` doesn't apear.

Regards.

**Comment by superkhau** [comment]
Would you like to submit a PR for the fix? See https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L121

**Comment by Amir-61** [comment]
Fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/1133
