### ISSUE TITLE
embeds and forceId issues 

### ISSUE THREAD

**Issue by BoLaMN** [strongloop/loopback-datasource-juggler#1148]
Hey guys,

Since forceId dropped it seems to be having huge impacts on embedded relations around validation errors with creates\updates.

Since forceId is too disallow id's being submitted through http is there any reason why it cant be added to strong-remoting instead? 

Seems odd to have this forced restriction on the dao layer and not as a remoting hook.

Furthermore it would be nice to see these sorts of features being refactored into mixins with a default mixins section in model-config.json so it's able to be toggled off instead of causing more forks due to incompatibilities.

Just an idea to enable this platform to be more modular and flexiable, instead of becoming unmanageable in the future.

Cheers

**Comment by Amir-61** [comment]
>Since forceId dropped

Could you elaborate that? AFAIC the default is set to true for relational databases.

@jannyHou could you provide more info?

**Comment by jannyHou** [comment]
hey @BoLaMN , really appreciate your suggestion and feedback to make loopback more flexible and easier to use.

---

> having huge impacts on embedded relations around validation errors with creates\updates.

From my understanding embeded relations are more suitable for NoSQL dbs like mongodb, and you can simply set `forceId: false` in config file `model.json` to remove the restriction.

Or did you run into any setId restriction with embeded relation even after you set `forceId: false`? If this is the case, could you provide a sample app (you can fork [sandbox](https://github.com/strongloop/loopback-sandbox))or explain more about it? I will file a bug then.


---

> Since forceId is too disallow id's being submitted through http is there any reason why it cant be added to strong-remoting instead?
 
Interesting..Theoretically it looks reasonable to me but I just could not think of a good use case...Could you provide me a scenario that "when creating instance with id provided, users can NOT do it remotely but code should be able to do it"?

**Comment by BoLaMN** [comment]
Hey @jannyHou 

Thanks for the response, it's more around the embedded items. 

The rough flow is 

Create Order (parent)
Create Content (embed of Order) 
Create File (embed of Content) 
Update Order (receive id error)

I'll try put together a sandbox application to make it easier to see in the next few days.

Reason I suggested moving it to strong-remoting and my use case is I have 3 loopback servers that communicate with each other through either sqs or a redis pub sub system.

My sqs messages are to allow a queued stream of update or create events from other servers which could be a proxy of an update\create event.

My redis pubsub system is for my websocket servers to be able to keep the user sockets in sync which provide the id so the id is the same across all the servers in a live connector\model 

Another possible use case would be creating fixtures where you wish to set the id via a seed file but not allow users to submit their own eg before save slugifying of a field.
Just seems odd to restrict the server from running commands where it seems this is a http type validation.

Cheers
