### ISSUE TITLE
Be able to order data with case-insensitive option

### ISSUE THREAD

**Issue by tfsamaral** [strongloop/loopback-datasource-juggler#1161]
Hey guys,

So I am in need to order some results independent of the letter case.
I want **aA->zZ** and not **A->Z | a->z**, in this case ASC.

Is there anyway I can do this?
As far as I can tell loopback doesn't support it and I couldn't find any help online.

Thanks!

**Comment by Amir-61** [comment]
Hey @tfsamaral,

I believe this feature is not supported by LoopBack; however you may go a head and use native sql queries if you are using relational database; please see: http://loopback.io/doc/en/lb2/Executing-native-SQL.html

**Comment by Amir-61** [comment]
I hope https://github.com/strongloop/loopback-datasource-juggler/issues/1161#issuecomment-262065523 helps you; I'm closing this issue now...
