### ISSUE TITLE
idInjector: false seemingly ignored w/mongodb connector

### ISSUE THREAD

**Issue by CNSKnight** [strongloop/loopback-datasource-juggler#1164]
```
├── loopback@3.0.0 
├── loopback-boot@2.22.0
├── loopback-connector-mongodb@1.15.2
├── loopback-datasource-juggler@2.51.0
```
YAML Sample:
```
...
      _id:
        id: true
        $ref: '#/definitions/ObjectID'
    required:
      - title
      - _id
    idInjection: false
    additionalProperties: true
  x-any:
    properties: {}
  ObjectID:
    type: string
    pattern: '^[a-fA-F\d]{1,24}$'
```
Sample PUT Request:
```
_id: 32 (| "32")
title: "Test"
```
Response _always_ returns eg:
```
_id: 32
id: "58263bd276e41b07d690ba80"
```
And stores eg:
```
{
  "_id" : ObjectId("58263bd276e41b07d690ba80"),
}
````

Additionally, I've tried _id as an integer with same results (likely a mongo reserved thing)
Also, API Designer reports **Additional properties not allowed: idInjection** but saves the YAML
(I typically ``$ slc deploy...``)

**Comment by Amir-61** [comment]
This issue was moved to strongloop/strongloop#332

**Comment by Amir-61** [comment]
This issue was moved to strongloop/loopback-connector-mongodb#311
