### ISSUE TITLE
includeOneToOne crash server !

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback-datasource-juggler#1167]
I have user model, user model has many transaction and transaction belongTo user model.
When I query owner of transaction with include filter (scope, fields) my server crash and show error:
 
`TypeError: Cannot read property 'toString' of undefined  
0|server   |     at linkOneToMany (/home/node_modules/loopback-datasource-juggler/lib/include.js:811:50)  
0|server   |     at /home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13  
0|server   |     at _each (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)  
0|server   |     at Object.async.each (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)  
0|server   |     at targetLinkingTask (/home/node_modules/loopback-datasource-juggler/lib/include.js:808:17)  
0|server   |     at /home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:723:21  
0|server   |     at /home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:391:17  
0|server   |     at /home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13  
0|server   |     at _each (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)  
0|server   |     at async.each (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)  
0|server   |     at _asyncMap (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)  
0|server   |     at Object.map (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)  
0|server   |     at _parallel (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:721:20)  
0|server   |     at Object.async.parallel (/home/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:751:9)  
0|server   |     at /home/node_modules/loopback-datasource-juggler/lib/include.js:106:11  
0|server   |     at _combinedTickCallback (internal/process/next_tick.js:67:7)  
0|server   |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)  `

**Comment by Amir-61** [comment]
To make the triage process easier and more efficient please follow this [guidelines for reporting issues](http://loopback.io/doc/en/contrib/Reporting-issues.html).

Please provide a sample repo using [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue.
