### ISSUE TITLE
Misleading documentation on embedsMany

### ISSUE THREAD

**Issue by sebastianhaas** [strongloop/loopback-datasource-juggler#1174]
At https://loopback.io/doc/en/lb2/Embedded-models-and-relations.html#embedsmany :

> Treat embedsMany as an actual relation, no different from hasMany, for example. This means that you cannot just POST the full object with embedded/nested data to create everything all at once. So using the example above to add a Customer and multiple email addresses would require two POST operations, one for the Customer record and **one for the multiple email address data.**

As far as I can tell, loopback doesn't support posting arrays to embedded model relations, so this is maybe a bit misleading?

@crandmck I saw you working on documentation a lot, so maybe you can help out?

**Comment by Amir-61** [comment]
Thanks for brining this to our attention. @crandmck could you please rephrase the sentence to avoid the confusion here. Thanks 🙇

**Comment by sebastianhaas** [comment]
Thanks!

> As far as I can tell, loopback doesn't support posting arrays to embedded model relations [...]

Should actually be more like "doesn't support posting arrays of objects without ids", it is fine to post an array of objects that already have unique ids assigned. You probably know what I mean. 

Maybe it's more about
> Treat embedsMany as an actual relation, no different from hasMany

in the end.

**Comment by crandmck** [comment]
OK, I reworded the note as follows:

> **Note**: You cannot POST the full object with embedded/nested data to create everything all at once.
So the example above in which a Customer has multiple email addresses, adding an instance would require two POST operations, one for the Customer record and one for the multiple email address data.

Does that clear it up?  If not, please suggest other specific changes.  Thanks!

**Comment by sebastianhaas** [comment]
> Does that clear it up?

For me, it wouldn't have made it clearer I guess.
I think that
> and one for the multiple email address data.

made me start to think, "ok I can just put an array of address data, just as in any other `create`", but that doesn't really work because ids won't be generated and so you have to handle it quite differently from any other `create` in the end.

Sorry I can't put it in any better words because frankly speaking I don't really get how this is supposed to work and I actually think its broken. See #1173 or #677

**Comment by crandmck** [comment]
> ...  I don't really get how this is supposed to work and I actually think its broken

Hm, OK... @Amir-61 can you please comment and/or clarify?  I don't want to spend any more time on this until I  I (we) understand better how it's supposed to work and I confirm that it's actually working as it should...

**Comment by kjdelisle** [comment]
@raymondfeng Should this behave in this way, or should it not allow the posting of arrays?

**Comment by crandmck** [comment]
This was never resolved, and there's no reason to close it afaict.

**Comment by sebastianhaas** [comment]
> This was never resolved, and there's no reason to close it afaict.

**Comment by kjdelisle** [comment]
@raymondfeng what's the word on this issue? You're the final word on the expected behavior here.

**Comment by kjdelisle** [comment]
@raymondfeng Please take a look at this.

**Comment by kjdelisle** [comment]
Marking this as a bug because:
- It stops stalebot from closing it
- If the docs are in fact misleading, they should be fixed.

**Comment by raymondfeng** [comment]
@sebastianhaas I agree with you. For embedsMany relation, there is only one physical document. For example, a customer with embedded emails looks like the following json object:
```js
{
  id: 'c1',
  name: 'John',
  emails: [
    {label: 'work', id: 'john@example.com'},
    {label: 'home', id: 'john@gmail.com'}
  ]
}
```

The embedsMany relation serves as convenient methods to handle emails array inside the customer instance (in memory). From persistence perspective, the whole document will be saved/loaded/updated/deleted in one operation.

**Comment by sebastianhaas** [comment]
Don't.
