### ISSUE TITLE
`updateOrCreate` does not work with default value of forceId: true

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-datasource-juggler#1185]
`forceId` is set to true by default by https://github.com/strongloop/loopback-datasource-juggler/pull/982 . `updateOrCreate` does not work with default value of forceId set to true when we want to update an instance and provide the PK of instance in data object.

Failure: `ValidationError: The 'Model' instance is not valid. Details: 'id' can't be set (value: 9)`

/cc: @jannyHou @bajtos

**Comment by jannyHou** [comment]
👍  Thanks.

**Comment by ssh24** [comment]
Closing this. Please follow here: https://github.com/strongloop-internal/scrum-apex/issues/82

**Comment by bajtos** [comment]
I am reopening this issue because of https://github.com/strongloop/loopback-datasource-juggler/pull/982#issuecomment-289599727 by @luncht1me:

>This change breaks UPSERT methods...
> When you Upsert with an ID, you want to PATCH/PUT that existing instance to update it in the database.
> And if it doesn't have an ID, then you create a new one.
>
> Upsert is just completely broken because of this id enforcement not accounting for the use-case and intended behavior of Upsert.
> Why not have Upsert check if there's an ID, if there is make sure the document exists, error if it doesn't saying id can't be set. But if the document exists, update the damn thing. Having to double the amount of code for CRUD management in our projects when there `used` to be a method that handled it seems a step backwards to me.

Here is my reply for completeness:

> I think the issue you are observing is very similar to #1235 which was fixed by #1210 and https://github.com/strongloop/loopback-connector/issues/73.
>
> Would you like to contribute the fix yourself, using the two linked pull requests for inspiration?

cc @loay @jannyHou @strongloop/sq-lb-apex
