### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by sarkiroka** [strongloop/loopback-datasource-juggler#1193]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead

### Expected result

no warning

### Actual result (if bug)

warning showed

### Additional information (Node.js version, LoopBack version, etc)

node 6.7.0
loopback-datasource-juggler 2.53.0

**Comment by dhmlau** [comment]
In the latest version of `loopback-datasource-juggler`, it's using `uuid`.  Closing the issue.
