### ISSUE TITLE
Support composite id in CRUD operations

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-datasource-juggler#121]
Add support for multiple id columns to CRUD operations.

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback-datasource-juggler/pull/405

**Comment by zetflo** [comment]
Do you have an idea when this feature will be available?

**Comment by csvan** [comment]
+1

**Comment by infonion** [comment]
Could some one confirm that Composite issue in loopback-juggler is not occuring now. I'm facing the issue in development. Your help will be really appreciated. Thanks!!!

**Comment by mitai** [comment]
+1

**Comment by Paulmolin** [comment]
+1

**Comment by HanDaber** [comment]
+1

**Comment by nelsonec87** [comment]
+1

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback/issues/2046

**Comment by bajtos** [comment]
And also https://github.com/strongloop/loopback/issues/126
