### ISSUE TITLE
Relation through: as string not coerced to Model object

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#1237]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

For some reason, updating from 2.53.0 to 2.53.1 caused the following declaration to fail:

```
Restaurant.hasMany('reviewers', { through: 'RestaurantReview' });
```

This used to work before, although I cannot seem to find any trace of changes in this regard. Internally, the string `'RestaurantReview'` should be looked-up, just like `model` is done.

This is not the case, but could be easily fixed to use the `lookupModelTo` or `lookupModel` functions for this purpose.

### Actual result (if bug)

```
Uncaught TypeError: Cannot create property '_scopeMeta' on string 'RestaurantReview'
```

### Additional information (Node.js version, LoopBack version, etc)

Node 6, Juggler 2.35.1 (2.35.0 was fine)

**Comment by dhmlau** [comment]
@fabien , I'm trying to reproduce your problem.  Wanna make sure I'm doing the same thing as yours.  Are you calling the snippet above in Restaurant.js ?

**Comment by fabien** [comment]
@dhmlau thanks for getting in touch. Yes, this is in `common/models/restaurant.js`.

**Comment by dhmlau** [comment]
@fabien, I actually got an error saying something like `Restaurant.hasMany is not a function`.  Switching from 2.35.1 to 2.35.0 doesn't help either. 
Better yet, could you please provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by mohebifar** [comment]
@fabien Try passing the models instead of their names:

```js
Restaurant.hasMany(app.models.reviewers, { through: app.models.RestaurantReview });
```

**Comment by fabien** [comment]
@mohebifar yes, this has been my workaround since I discovered this issue. Thanks for chiming in!

**Comment by mohebifar** [comment]
Oops, I actually didn't read the second paragraph. Sorry.
