### ISSUE TITLE
Document connector version / LB version compatibility

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#1238]
Document which connector version to use with each LoopBack version; cf https://github.com/strongloop/loopback-connector-mongodb/issues/296.

We could do this either with a note for each connector or with a table that lists all connectors (TBD).

**Comment by kjdelisle** [comment]
Todo: Go through CI and make a matrix that lists each connector and which versions are being tested.

**Comment by smartmouse** [comment]
where in CI can we get the information? Does not seem to be obvious. Each connector is different and has different info.


https://cis-jenkins.swg-devops.com/ and 
http://ci.strongloop.com/


<img width="1072" alt="screen shot 2017-02-13 at 4 19 37 pm" src="https://cloud.githubusercontent.com/assets/4519627/22904206/878b401e-f209-11e6-87c2-cab82ba1392c.png">

<img width="1204" alt="screen shot 2017-02-13 at 3 57 23 pm" src="https://cloud.githubusercontent.com/assets/4519627/22904426/786d7ca4-f20a-11e6-993a-93f3a66c40f4.png">

Shouldn't it be easier to just look at the package.json dependencies?
many CI jobs are red for connectors, the build seems to be different too.

**Comment by smartmouse** [comment]
@crandmck  where should this information be created? Please send me the URL and the format you have in mind . Thank you.

**Comment by smartmouse** [comment]
After second thought, I think documenting this is time consuming and versions keep updated, I wonder if we can generate the contents from the package.json of the connectors dynamically to reduce our work. Can't keep up with the version changes.

**Comment by crandmck** [comment]
> where should this information be created? Please send me the URL and the format you have in mind .

Sorry, I missed this earlier...  I think generating it programmatically is a great idea.

I suggest creating a new .md file in this repo, something like `Compatibility.md`. 
The documentation can then use the script that we have to "pull down" this file and include it into the docs.

I'm not entirely sure what the best format would be, perhaps something like this:

| Juggler version  | loopback-connector-.. |
|--|--|
| 3.x | cloudant 1.1.x | 
| 2.x | cloudant 1.0.x |
| 3.x | dashdb 1.x |
| 2.x | dashdb 1.x |

NOTE: Above data is _fictional_ and just for illustration purposes.

I'm assuming that changes in compatibility normally occur for major releases, so there would only be a few entries for each connector.

**Comment by crandmck** [comment]
Let's keep this open. This would be valuable IMHO.

**Comment by crandmck** [comment]
Keep it open.
