### ISSUE TITLE
Feature request : Model.update(query, data, cb)

### ISSUE THREAD

**Issue by pandaiolo** [strongloop/loopback-datasource-juggler#124]
## Feature request

Current `Model.upsert()`  creates or update a single model instance in underlying storage (as expected)

There is currently no API facility to update multiple model instances, which can be pretty handy for example to update status fields on a large amount of lines, or such purpose.

**New `Model` feature proposed by raymond [here](https://groups.google.com/forum/#!topic/loopbackjs/Q3J7gfT2mWA) :**

```
Model.update(query, data, cb)
```

`query` param would have the same definition as in find-like methods

`data` param would contain model field in the same format accepted by `updateAttributes`

**Comment by acao** [comment]
Stumbled across this. If you are looking for this capability, see this:

https://apidocs.strongloop.com/loopback/#persistedmodel-updateall
