### ISSUE TITLE
DataAccessObject.upsert doesn't pass options to Model.findOne

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback-datasource-juggler#1253]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

On [lib/dao.js#L638](https://github.com/strongloop/loopback-datasource-juggler/blob/0cf863a483090b8927c76290da218817718b278c/lib/dao.js#L638), `upsert` creates a new `opts` object with a 'notify: false' and optionally with the transaction object.

### Expected result

`Model.find()` should have access to all given options.

### Actual result (if bug)

This results in that other entries like `accessToken` will not be visible in subsequent `findOne`call. The original `options` is only visible in the next `save()` or `updateAttributes()`

### Additional information (Node.js version, LoopBack version, etc)

lb3

**Comment by bajtos** [comment]
@azatoth As I said on Gitter, this is a bug and I am pretty sure there will be more places like this one where are not passing the options through.

I am proposing to use the following approach in places where we need to modify the `options` object before it's passed down:

```js
var opts = Object.create(options);
opts.notify = false;
// add any other overrides as needed
Model.findOne({where: ctx.query.where}, opts, function(err, inst) {
  // ...
});
```
