### ISSUE TITLE
Using non existent properties in fields filter, removes last property of actual documents

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-datasource-juggler#1256]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
When a model has properties **A** and **B** but you make a find request using:

```
filter: { fields: { C: false } }
```
it will remove the last property of the model (`B`) from the result document

### Expected result
It should ignore the non existent property for exclusion

### Actual result (if bug)
It will remove the last property

### Additional information (Node.js version, LoopBack version, etc)

**Datasource juggler version: 2.54.0**

**Comment by mitsos1os** [comment]
Should this be closed since Pull request [1257](https://github.com/strongloop/loopback-datasource-juggler/pull/1257) was merged???

**Comment by ssh24** [comment]
Closing this as PR #1257 is merged with the fix.
