### ISSUE TITLE
Transaction is not used while performing modelInstance.destroy()

### ISSUE THREAD

**Issue by McAronDev** [strongloop/loopback-datasource-juggler#1258]
### Bug or feature request

- [ x] Bug
- [ ] Feature request

When performing `modelInstance.destroy({transaction: tx})` transaction is not used. [Here](https://github.com/strongloop/loopback-datasource-juggler/blob/d8092607999b66c369c08e99b8974bf311e14958/lib/dao.js#L2769), where actually deleting performed, specified options object is not used.

**Comment by dhmlau** [comment]
@McAronDev , you might want to use `destroyall` which takes in the option as the first parameter. 
http://apidocs.strongloop.com/loopback/#persistedmodel-destroyall

If I understand correctly, you're using the `destroy` method which does not support a filter
http://apidocs.strongloop.com/loopback/#persistedmodel-prototype-destroy

I'm closing this issue.  If you find `destoryall` doesn't fit your need, please reopen.

**Comment by McAronDev** [comment]
No. I don't want to use filters, i want to use DB transaction as explained here:   [https://loopback.io/doc/en/lb3/Using-database-transactions.html](url)
