### ISSUE TITLE
timeout on connection startup fails - does not get caught and crashes 

### ISSUE THREAD

**Issue by alexmac131** [strongloop/loopback-datasource-juggler#1260]
### Bug or feature request

- [x ] Bug

### Description of feature (or steps to reproduce if bug)
Using the coffee shop learning demo, create an extra mysql  connector to a non-existing database or first up the example as is without a network connect.  The app will time out and crash attempting to get to the database in question.  The specific issue: it does not bubble up to be caught and handled outside of the module.

contained in lib/datasource.js line 341 to 345

### Expected result

Be able to catch the error in the application layer and not have to modify the node code,.

### Actual result (if bug)

Example crashes, either there is a bug in the code or the documentation for catching these bits of code.

### Additional information (Node.js version, LoopBack version, etc)

Strongloop coffee example in getting started (coffee shop)..

**Comment by kjdelisle** [comment]
This is not a bug; if you add a datasource that does not exist, then it will crash your application.

Datasources are evaluated as a part of the boot process and are not handled in application logic outside of the typical `server/server.js` (or wherever you have your boot scripts if you've customized them).

**Comment by alexmac131** [comment]
The error does not leave the node module to be handled in boot or server.  This is the issue. So if you have more than 1 data source and the service happens to be done and you have adaptive code to not offer that one service it should not kill entire server.
