### ISSUE TITLE
discoverSchema makes table lower camel case columns to be completely lowercase

### ISSUE THREAD

**Issue by ariskemper** [strongloop/loopback-datasource-juggler#1268]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
1. Mysql table with camel case columns
2. Use discoverSchema to make json model

if table column name is for example zipCode, it will be named zipcode

### Expected result

Properties part of json model schema

    "emailVerified": {
      "type": "Boolean",
      "required": false,
      "length": null,
      "default": 0,
      "mysql": {
        "columnName": "emailVerified",
        "dataType": "tinyint",
        "dataLength": 1,
        "nullable": "Y"
      }
    },

### Actual result (if bug)
Properties part of json model schema

    "emailverified": {
      "type": "Boolean",
      "required": false,
      "length": null,
      "default": 0,
      "mysql": {
        "columnName": "emailVerified",
        "dataType": "tinyint",
        "dataLength": 1,
        "nullable": "Y"
      }
    },

### Additional information (Node.js version, LoopBack version, etc)

Additional information (Node.js version, LoopBack version, etc)

Node.js: 6.9.2
loopback: 3.4.0
loopback-datasource-juggler: 3.2.0
loopback-connector-mysql: 3.0.0

**Comment by jannyHou** [comment]
Hi @ariskemper the dependency version has `loopback-connector-mysql` while your `model.json` file is using `mssql` as db specific config. I assume it's a typo but please make sure the config name is the identified to your connector.

@raymondfeng when user discovers a lower camel case property in mssql (e.g. `emailVerified`), loopback generates an all lowercase property in model (e.g. `emailverified`), even though the camel case name is mapped in db specific config. Could you confirm is it expected behavior or a bug? Thanks.

**Comment by jannyHou** [comment]
@raymondfeng Also users are interested in providing a custom naming convention in migration/discovery. details see issue: https://github.com/strongloop/loopback-connector-mysql/issues/57

Does loopback has its naming convention documented somewhere? Or any link of the strategy we can follow? 
If not I am thinking of document it, therefore confirm the strategy with you first :)
And any thought about the suggestion "provide custom naming convention function"?

**Comment by ariskemper** [comment]
@jannyHou its not connector specific, because code in loopback-datasource-juggler does this.

**Comment by raymondfeng** [comment]
Please note that discoverSchema allows `options.nameMapper` to provide custom name mapping. See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1304

**Comment by jannyHou** [comment]
@ariskemper please check comment https://github.com/strongloop/loopback-datasource-juggler/issues/1268#issuecomment-289496738
Will `options.nameMapper` solve your problem?

**Comment by ariskemper** [comment]
I know, it provides options.nameMapper, but i think that camel case named columns should stay camel cased?

**Comment by sureshkodur** [comment]
Hi, I have same issue.

**Comment by agnes512** [comment]
please check [#3343](https://github.com/strongloop/loopback-next/issues/3343)
