### ISSUE TITLE
Issue with incorrect include on HasManyThrough relation.

### ISSUE THREAD

**Issue by nikooiko** [strongloop/loopback-datasource-juggler#1275]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
There is a bug when someone sends a request with incorrect `include` filter containing "fields" equal to a String instead of an Object/Array on a model that has a relation HasManyThrough.

eg: 
```
{
  "include": {
    "relation": "oneExistingRelation",
    "scope": {
      "fields": "dummyStringProperty"
    }
  }
}
```

### Link to sample repo to reproduce issue (if bug)
https://github.com/nikooiko/loopback-sandbox

You just have to `npm start` && send this request:

```
http://0.0.0.0:3000/api/AppUsers?filter=%7B%22include%22%3A%20%7B%22relation%22%3A%20%22roles%22%2C%20%22scope%22%3A%20%7B%22fields%22%3A%20%22dummyField%22%7D%7D%7D
```

### Expected result
Application should probably return the results with the included field containing only the "id" and the "dummyStringProperty" 

### Actual result (if bug)
After a request like this the application simply dies after receiving this error:
TypeError: Cannot read property 'toString' of undefined
   at linkManyToMany: ...

(you can see the actual error at provided sandbox).

### Additional information (Node.js version, LoopBack version, etc)
node v7.7.0

### Related issues

Can be related to #951

**Comment by mitsos1os** [comment]
This is indeed a bug, as not only it does not return the proper results by properly filtering the returned db data, but it also crashes the server when the code tries to access the `toString` function of an undefined object at `lib/include.js` [line](https://github.com/strongloop/loopback-datasource-juggler/blob/77c4cd7b01fd43140175b53f60e62390f88b3b32/lib/include.js#L484)

When user input crashes the whole app I would consider this as major bug
