### ISSUE TITLE
Should process the fromColumnValue / toColumnValues (not taken into account)

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-datasource-juggler#1281]
Converting /coerce types fail in dao.js line [lib/dao.js#L1741](https://github.com/strongloop/loopback-datasource-juggler/blob/68b93e1074cd8a6759f5898a91b537a76b40eae5/lib/dao.js#L1741)

@tatemz
and
@kurtiscc 
(from walmart)

@bajtos @raymondfeng @kjdelisle

**Comment by jannyHou** [comment]
@ritch Do we have a ticket filed with details? Or any steps to reproduce the error? Thanks.

**Comment by bajtos** [comment]
I think this may have been already fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/1266

**Comment by tatemz** [comment]
@bajtos - I will test the current setup we have against #1266.

**Comment by tatemz** [comment]
@ritch & @bajtos - #1266 worked against our test. Specifically, our test was working with GET and POST on all plural forms of models, but not when performing a GET on singular records by IDs (the ID in the URI was not coercing through our connector).

Updating to `"loopback-datasource-juggler": "^3.2.0"` solved the issue.

👍 😅
