### ISSUE TITLE
Add a new property to model to store user-desired relations config

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-datasource-juggler#1282]
### Bug or feature request

- [x] Feature request

### Related issues
https://github.com/strongloop/loopback/issues/3308
https://github.com/strongloop/loopback/issues/3307

### Description of feature (or steps to reproduce if bug)

In https://github.com/strongloop/loopback/pull/3265 we are implementing a health check function called along with `app.enableAuth()`.
This was started by @bajtos in https://github.com/strongloop/loopback/pull/3231.

The purpose of this health check is to detect incorrect configs of LoopBack auth models, and display a message to help the user debugging the config.

In this feature, we use the two following ways to check model relations:

1. `someModel.settings.relations.someRelation`
2. `someModel.relations.someRelation` 

(1) contains the relation definition as per the JSON spec

(2) contains the relation as ultimately set up, after these successive optional steps [initial setup as per the JSON spec, model creation using `createModel`, programatic definition of relation using model prototype methods such as `hasMany`, `belongsTo`, etc.]

In the health check we'd like to compare the relation as requested by the user (via any of aforementioned means), and the actual relation set up.

The issue is that (1) represents the definition as per the spec and does not change along the app lifetime to keep track of user's action to make it change.
And (2) only represents the final definition, which can ultimately be undefined if the relation config is inconsistent.

neither (1) or (2) represents for sure the config actually desired by the user, which is problematic to build a consistent health check feature. People start to face situations related to this inconsistency (see referenced issues).

We'd like to add a new property to model to store the user-desired relations config, as the result of all possible config steps.

This issue is meant to discuss this and keep track of investigations on how to implement this.

cc: @superkhau , @bajtos , @raymondfeng

**Comment by bajtos** [comment]
How I see the problem, there are two ways how to define relations:
 - via JSON config (`MyModel.settings.relations`)
 - by calling API like `MyModel.hasMany`

The latter does not update `settings.relations`, which is probably correct. Even if it was not, changing that behaviour would be very likely to break existing code - consider the difference between calling `MyModel.hasMany` from inside `MyModel.setup` vs. outside of `MyModel.setup`. The former will be inherited by subclassed models, the latter won't (at least as far as my understanding goes). IIRC, `MyModel.settings.relations` is always inherited.

Now in the health check code mentioned by @ebarault, we need to inspect all relations, regardless of how they were defined. In my understanding, the goal of this issue is to find and/or implement a reliable solution for inspecting relations.

> And (2) only represents the final definition, which can ultimately be undefined if the relation config is inconsistent.

I find this surprising, can you provide more details please?

**Comment by ebarault** [comment]
Inputs are expected to:
- Build a common understanding
- Validate the requirement as a requisite to build an efficient health check system for LoopBack, and rank its priority
- Ensure the requirement is not already covered
- Gather insights on best options to cover the requirement

**Comment by ebarault** [comment]
>> And (2) only represents the final definition, which can ultimately be undefined if the relation config is inconsistent.

> I find this surprising, can you provide more details please?

according to my experience, `someModel.relations.someRelation` is only defined if the relation itself can be set up. Passing wrong config to build `someRelation` between `someModel` and `someOtherModel` will result in `someModel.relations.someRelation`being undefined. Otherwise we have there the expression of the relation as desired by the developper

**Comment by raymondfeng** [comment]
Model relations are set up lazily upon the attachment of datasources that support CRUD operations as most of the relation based methods assume `PersistedModel`. We can probably change how it works as follows:

1. Validate if all involved models for a relation (source/through/target) are persisted models
2. If one of the models is not attached to a data source, the runtime exception will throw the same way for a `PersistedModel`.
3. If necessary, we can introduce a flag on the `Relation` to indicate if it's fully resolved.

**Comment by ebarault** [comment]
Thx @raymondfeng for your advice

> 1. Validate if all involved models for a relation (source/through/target) are persisted models

- this is not possible for polymorphic relations `belongsTo` where the target model is not known upfront.
- models for `embedded` relations inherit `Transient` model instead of `PersistedModel`

So IMO this option is not possible with a full coverage. We could exclude Transient models from the validation though.

> 3. If necessary, we can introduce a flag on the Relation to indicate if it's fully resolved.

In some cases (if not all? i need to check), the Relation object for a given relation name is undefined if the. In that case we could add the relation recipe as a property of the relation object and with an additional flag indicating that the relation is NOT fully resolved.
But wouldn't that conflict with other validations if the relation object exists whereas the relation is not set up?
