### ISSUE TITLE
How to create array of reference Question

### ISSUE THREAD

**Issue by kethan** [strongloop/loopback-datasource-juggler#1283]
How do i refer array of reference? Can anybody please help. 
```javascript
var DataSource = require('loopback-datasource-juggler').DataSource;
var ModelBuilder = require('loopback-datasource-juggler').ModelBuilder;
var ds = new DataSource('memory', ModelBuilder);

var Post = ds.createModel('Post', {
    title: { type: String, length: 255 }
});

var User = ds.createModel('User', {
    name: { type: String, required: true },
    bio: { type: String, required: true }
},
    {
        relations: {
            posts: {
                type: 'hasMany',
                model: 'Post',
                foreignKey: 'id'
            }
        }
    });

Post.create({ title: 'sometitle' }, function (err, post1) {
    if (err) {
        console.log(err);
        return;
    }
    Post.create({ title: 'sometitle' }, function (err, post2) {
        if (err) {
            console.log(err);
            return;
        }
        User.create({ name: 'some', bio: 'developer', posts: [post1.id, post2.id] }, function (err, user) {
            if (err) {
                console.log(err);
                return;
            }
            User.find({ include: 'posts' }, function (err, users) {
                console.log('user', JSON.stringify(users));
            })
        })
    });
})
```

Output : 
user [{"name":"some","bio":"developer","id":1,"posts":[]}]

Here i am getting an empty array i don't know why. :(

**Comment by ssh24** [comment]
@kethan Could you please specify the `loopback` version you used to create this app? I did a reproduction of your steps (using v3) and I got back an array of posts: 
```
user [{"name":"some","bio":"developer","id":1,"posts":[{"title":"sometitle","id":1}]}]
```

**Comment by kethan** [comment]
@ssh24 
I am using "loopback-datasource-juggler": "^3.2.0".
If you see your output i see only 1 posts and not two.

**Comment by kethan** [comment]
Can anybody please help me? I am totally struck at this

**Comment by 0candy** [comment]
@kethan Can you provide a sample repo so we can reproduce your issue?

**Comment by kethan** [comment]
@0candy 
https://gist.github.com/kethan/27c16b6ee650558e9353254ffe3a932e

**Comment by 0candy** [comment]
@kethan I am getting the same result as @ssh24 with one post in the output. I think you are missing the relation post belongs to user. Is there a reason why you don't just use the loopback generator to generate the model and relations?
https://loopback.io/doc/en/lb2/HasMany-relations.html

Please take a look at this example between customer and order.
https://github.com/strongloop/loopback-example-relations

**Comment by 0candy** [comment]
Also, you should leave the foreign key field as empty. `id` will conflict with the row id column of the model.
As well, maybe rename your relation to something other than `posts` as that might conflict with the model name.
The include filter should be `{ include: {relation: 'relation_name'} }`. Replace with your `relation_name`.

**Comment by kethan** [comment]
s@0candy I tried as you said but still no luck...
I am coming from mongoDB and mongoose world so i am confused with realtions.
```javascript
var Post = Schema({
    title: { type: String, length: 255 }
});

var User = Schema({
    name: { type: String, required: true },
    bio: { type: String, required: true },
    posts: [{ type: Schema.Types.ObjectId, ref: 'Post' }]
});
```
And when i add a data to Post in Loopback Model it is not resulting posts id references but when i add in mongoose it does.

I am not using JSON format because i am creating models dynamically from GUI. I am trying to create BaaS like framework with loopback. 

Can you give very simple example how to do relationship in Loopback using code and adding multiple reference Key?

**Comment by 0candy** [comment]
@kethan Here is an example of what you're trying to do:
https://gist.github.com/0candy/9c6b9d90e44e46bbef083a4560eed523
Hope that helps!

**Comment by kethan** [comment]
@0candy 

Thanks that helped me but i few questions to clear my doubt if you are kind enough to reply.

1. Why is the reference id is not shown while adding the data.
2. Why cannot i do one way reference. Is belongsTo required?
3. At a single go can i refer multiple id as array ?

Thank You.

**Comment by 0candy** [comment]
@kethan Those are valid questions.
1. You can specify a reference id, however, I would not suggest using `id` as that is the default row id column name. Please choose something else.
2. BelongsTo is not required if you only need to the query the api one way and not both ways.
3. You can specify multiple id as an array.

See gist which shows one way reference with multiple id as array.
https://gist.github.com/0candy/1479dd03fc0adc6220748532a7f9590b

**Comment by kethan** [comment]
@0candy 
Wonderful thanks for being polite answering my questions. :+1: 

Now I understood, But 1 final question 

Why can't I Create Posts first and then add User because User has many posts not Post has many Users?
If I can do that What should I point ? posts : [reference Ids] or UserId's ??
Eg : 
https://runkit.com/kethan/loopback

**Comment by 0candy** [comment]
@kethan 
The reason is because you have User has many Posts. The reference id is the userid in the post model. When you create the post model, you didn't specify that userid so it doesn't know that they are linked. Hope this helps. If your issue has been resolved, please kindly close it.

**Comment by kethan** [comment]
@0candy 

Thanks for your support ! Glad it helped me a lot :+1:
