### ISSUE TITLE
Can not set query property with new object in operational hook ACCESS

### ISSUE THREAD

**Issue by frankorama** [strongloop/loopback-datasource-juggler#1285]
### Bug or feature request
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I have a model "Document".  The model has 2 relations:
- team (belongsTo)
- revisions (embedsMany)

I have observed the following behavior when setting the query property in the operational hook Access:

When creating a new query object and setting it to the query property of the context, the include clause is not applied
```
Document.observe('access', (ctx, next)=>{

  // this does not work:  include query clause not applied
  var newQueryObject = {
    include: [
      {relation: 'team'},
      {relation: 'revisions'},
    ],
  };
  ctx.query = newQueryObject;
  next();
});
```

### Expected result
Setting the query property to a new object should have the same effect as modifying the existing query property.

### Actual result (if bug)
The include statement is not applied:  the result does not contain a 'revisions' or 'team' property,.

### Additional information (Node.js version, LoopBack version, etc)
Loopback: 2.37.1

When i set the include property directly, it works:  the include property is applied and I see 'team' and 'revisions' in my result
```
Document.observe('access', (ctx, next)=>{
  // this works:  I see 'revisions' and 'team' in my query results
  ctx.query.include = [
    {relation: 'team'},
    {relation: 'revisions'},
  ];
  next();
});
```

**Comment by 0candy** [comment]
@frankorama Does it work if you do this?
```Document.observe('access', (ctx, next)=>{

  // this does not work:  include query clause not applied
  var newQueryObject = {
    include: ['team', 'revisions'],
  };
  ctx.query = newQueryObject;
  next();
});
```

**Comment by bajtos** [comment]
@frankorama to me, this looks like a bug in our implementation. What is the method/API which is not honouring the changed `ctx.query` property? AFAICT, most of the code in [lib/dao.js](https://github.com/strongloop/loopback-datasource-juggler/blob/539b317ccb876bc34468ebc78c1eaa923d2d2257/lib/dao.js) is always picking up the new object stored in `ctx.query`. Are you using geo/near conditions in the requested `filter` or `where`?

A small app reproducing the issue (see our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)) would be perfect!

**Comment by frankorama** [comment]
@bajtos When I look at the returned models in Document.observe('loaded') and Document.afterRemote('find'), the 'team' and 'revisions' properties are not present in the implementation i described that does not work.  They are present when i set the properties of the existing query (and not replace it with a new object).

No 'geo' or 'near' clauses in the query.  Just basic include statements.  The goal was to perform more complex queries, but if I can't get the 'include' clause to work then we'll implement the queries another way.

I'll set some break-points in lib/dao.js and try to figure out what is going on.

F

**Comment by frankorama** [comment]
Sorry for the delay.  Work.

I snooped around in /lib/dao.js and it looks like it's the implementation.  In the DataAccessObject.find() function there is an _allCb_ function that is called on the callback of the _**access**_ observable.  The problem is that this _allCb_ function is using the original query object created in the dao.js file and not the query returned from the 'access' observable.

**/lib/dao.js**
```
DataAccessObject.find = function find(query, options, cb) {
    var allCb = function(err, data) {
      // code deleted for brevity

      // here the query object is the original object of the function, not the updated object returned in the context.
      if (query && query.include) {
         // ...
      }

   });
 });
```

## Proposal
```
// On the callback from the 'access' observable, update the outer query object
  var context =  {
    Model: this,
    query: query,
    hookState: hookState,
    options: options,
  };
  this.notifyObserversOf('access', context, function(err, ctx) {
    if (err) return cb(err);

    // NEW: update the query object with the returned context query object //
    query = ctx.query
    // END NEW //

    connector.all.length === 4 ?
      connector.all(self.modelName, ctx.query, options, allCb) :
      connector.all(self.modelName, ctx.query, allCb);
  });
```

**Comment by bajtos** [comment]
@frankorama no worries, thank you for following up on our discussion. Your finding makes sense to me. Could you submit the fix as a pull request please? Here are the instructions to get you started: http://loopback.io/doc/en/contrib/code-contrib.html. Make sure to include a test that fails with the current implementation and passes with your fix in place. See the existing tests for inspiration: https://github.com/strongloop/loopback-datasource-juggler/blob/5da8170d9ea81d3aff87ba511182ba886b80edc6/test/persistence-hooks.suite.js#L240-L310
