### ISSUE TITLE
Fix use of `as` param in polymorphic relations in json model definition

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-datasource-juggler#1298]
### Linked
https://github.com/strongloop/loopback-datasource-juggler/issues/1297

### Description/Steps to reproduce

While reviewing the doc for polymorphic relations, i found quite a strange peace of code in `DataSource.prototype.defineRelations()`
as you can see in [lib/datasource.js#L486](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L486)

**what it does**:
if the **JSON** relation settings has something like
```json
"someRelation": {
  "model": "someModel",
  "polymorphic": {
    "as": "someRelationName"
  }
}
```
which is currently advised in the doc [here](https://loopback.io/doc/en/lb3/Polymorphic-relations.html#hasmany-polymorphic-relations) 

then in [lib/datasource.js#L507](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L507)
`params.model` will be replaced by `"someRelationName"` instead of using the provided model name

and obviously the [`lookUpModelTo()`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L535) method in `relation-definition.js` will throw because it looks to resolve a modelTo name `"someRelationName"`.

The keyword `as` is meant to name the relations when defining them by code.

### Expected

In my quest to review the polymorphic relations doc, i found that the keyword `as` inside the `relation.polymorphic` config object has currently multiple different conflicting applications : 
- serving as a shortcut to define the prefix for foreignKey and discriminator, 
- defining the name of the relation (same role as the top level "as")
- defining the name of the relation's modelTo
  
As a start to improve things, I propose to discuss removing the logic defined in [lib/datasource.js#L485](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L485)

**Note:** i also noted that in a general manner it has not much meaning using the `as` keyword in a model JSON definition as the relation key defines the relation's name, and `as`should be reserved when defining relations by code. Use of the `as` keyword in json model definitions can lead to non-user-friendly errors if not unpredictable results.

@ssh24 : again i made you the reviewer of this, but do not hesitate to appoint another reviewer if required

**Comment by ssh24** [comment]
@ebarault It looks like the issue is with assigning `params.model` to the polymorphic relation name instead of the target model name? The code in [lib/datasource.js#L507](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L507), should then just assign `params.model = targetModel;` and not care about the _polymorphicName_.

Also, I am wondering if this should be back-ported.

**Comment by ebarault** [comment]
@ssh24
I think it's more subtile than that, have you checked this other issue?
https://github.com/strongloop/loopback-datasource-juggler/issues/1297

I believe there is one valid case where we should assign polymorphicName rather than targetModel : if relation is hasMany,  params.model is omitted, and polymorphic=targetModelName. The code looks like such a shortcut definition was intended.

Thoughts?

I believe this should be back ported. I'm currently reviewing the polymorphic docs, it's very confusing and lots of examples don't work. We must simplify things

**Comment by ssh24** [comment]
I looked at the [other issue](https://github.com/strongloop/loopback-datasource-juggler/issues/1297) and am bit confused.

If the relation is `hasMany`, according to the [docs](https://loopback.io/doc/en/lb3/Polymorphic-relations.html#hasmany-polymorphic-relations) polymorphic relation can be defined in both ways:
```
{
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": "imageable"
    }
  }
...
```
And:
```

{
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": {
        "as": "imageable",
        ...
       } 
    }
  }
...
```
This issue is regarding the second code snippet where it assigns the `polymorphicName` to `imageable` and `params.model` also gets that value, am I correct?

Now, I understand with both #1297 and this issue the relation object will look something like in the first code snippet, where `polymorphic` could be either **polymorphicName** or the **targetModelName**. 

However, that brings up a question in my mind. How would we support other `fields` inside the `polymorphic` objects? Fields like `foreignKey, discriminator`:
```
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": {
        "as": "imageable",
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
       } 
    }
  }
...
```

**Comment by ebarault** [comment]
as said i am currently reviewing all the [polymorphic relations doc](https://loopback.io/doc/en/lb3/Polymorphic-relations.html#hasmany-polymorphic-relations) and find lots of examples that just don't work.

take this first snippet you copy-pasted:
```js
{
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": "imageable"
    }
  }
...
```

it's **incorrect** and can only lead people to confusion:
- the relation name is already defined by the relation key: `pictures``
- the modelTo is defined explicitly as `Picture`
- now there's this last param "polymorphic" of type string : 
  - according to [lib/datasource.js#L507](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L507), it should replace the relation `modelTo`, ... which is already defined here as `Picture`
  - according to [lib/relation-definition.js#L561](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L561), it's should be assigned to the `polymorphic.as` property, which stands for the name of the relation,... which is already defined as `pictures`

**what a mess !** 🤕 

To simplify, the keyword `as` should never be used for polymorphic relations in the **JSON** model definition. I'm doing a similar assessment for relations defined by code using the methods like `.hasMany()`, `.belongsTo()`, etc. and i believe it should not be used either inside the `relation.polymorphic`object, but should be only used internally. The only `as`keyword which is still valid when defining relations by code is the top level one.

for e.g. 
**correct**
`Parent.hasMany(Child, {as: 'child', polymorphic: {foreignKey: 'parentId', discriminator: 'parentType'}}`

**not correct**
~~`Parent.hasMany(Child, {polymorphic: {as: 'child', foreignKey: 'parentId', discriminator: 'parentType'}}`~~


> However, that brings up a question in my mind. How would we support other fields inside the polymorphic objects? Fields like foreignKey, discriminator

defining foreignKey, discriminator is fully supported. See in
[lib/relation-definition.js#L563](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L563) : only if the values are not provided they are replaced by default values.

**Comment by ssh24** [comment]
@ebarault This makes sense. Thank you for the clear explanation. I am reviewing the related PR #1301

**Comment by jannyHou** [comment]
@ebarault Thank you for fixing the gap between Doc and code of polymorphic relation, I am trying to review your pr https://github.com/strongloop/loopback-datasource-juggler/pull/1301, and after reading through all related issues I feel I'd better write down my understanding here and make sure we are on the same page, in case I overlook some details and give you useless& confusing reviews.

Maybe let's start from **reaching an agreement on what is our expected doc**, then implement&review code according to the correct doc. 

There are three entries that we need to clarify their meaning and usage:
Given a polymorphic relation:
```js
rName: {
  type: 'rType',
  as: 'rAs',
  model: 'rModelTo'
  polymorphic: {
    as: 'rAs',
    foreignKey: 'rAsId',
    discriminator: "rAsType"
  }
}
```

- `as`: 
  - Represents the relationName.
  - Will be overridden if `polymorphic(string)` or `polymorphic(object).as` provided
- `model`: 
  - Represents the `modelTo` in a relation.
  - On the other side, the related model will have a `belongsTo` relation defined as 
     ```js 
     relatedRName: {
       type: 'belongsTo',
       model: 'not_sure_is_it_defaultRelationModelFrom_or_rAs', 
       // I am confused with the `model` property here. 
       // My understanding is it could serve for either purpose but **NOT BOTH**,
       // 1. Represents the default modelFrom,
       //     but the actual modelFrom should be looked up dynamically by polymorphic relation
       // 2. Represents the `rAs` defined in modelFrom's relation,
       //     otherwise we have no idea which polymorphic relation it belongsTo. 
       polymorphic: {
         as: 'rAs' 
         // **`as` is NOT mentioned in doc**
         // Whether we need it depends on what's the usage of the `model` property above
         // If `model` serves the first purpose(Represents the default modelFrom), 
         //     this will be a **MUST PROVIDED** property,
         //     otherwise we have no idea which polymorphic relation it belongsTo
         // If `model` serves the second purpose(Represents the `rAs` defined in modelFrom's relation)
         //     this one will be optional, and will override `model` if provided
         foreignKey: 'rAsId',
         discriminator: 'rAsType'
         // these two properties should be the same as the ones defined in modelFrom's relationDef 
      }
    }
     ```
- `polymorphic`:
  - typeOf `polymorphic` === `String`
    - Represents the relationName
    - Will override `as`
    -  `foreignKey` will be generated by default as `as + 'Id'`,
        `discriminator` will be generated by default as `as + 'Type'`
  - typeOf `polymorphic` === `Object`
    - as: Represents the relationName
    - `foreignKey`: 
      - A property added to modelTo.
      - Represents the fk refers to modelFrom's id. 
      - Will be generated by default as `as + 'Id'`
    - `discriminator`:
      - A property added to modelTo.
      - Represents the actual modelFrom and get looked up and defined dynamically . 
      - Will be generated by default as `as + 'Id'`

**Comment by ebarault** [comment]
@jannyHou 
IMO the starting point is the following test: [`it('sets up polymorphic relations')`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/loopback-dl.test.js#L1087)

it expects one of the configurations described in the docs so let's take it as a basis:

**hasMany relation**
```
{
  "name": "Author",
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": "imageable"
    }
  }
...
}
```
**belongsTo relation** 
```
{
  "name": "Picture",
  ...
  "relations": {
    "imageable": {
      "type": "belongsTo",
      "polymorphic": true
    }
  }
...
} 
// note that in the example from the doc and in the test "imageable" is a very badly badly chosen name IMO as it's meant to reflect the concept of --belonging to Author--
```

It instructs that
- **if** `type == 'hasMany'`
- **and** `typeOf polymorphic == 'string'`
- 👉  `polymorphic` expects the name of the `belongsTo` relation name.

from the belongsTo relation name will be deduced the relation's `foreignKey` and `discriminators`.

---

Based on that your following statement is incorrect:
> - `polymorphic`:
>   - typeOf `polymorphic` === `String`
>     - ~~Represents the relationName~~
>     - ~~Will override `as`~~

it does not represent the **hasMany** relation name, but the **belongsTo** relation name, and consequently it will not override the `as` keyword

**Comment by ebarault** [comment]
putting aside the polymorphic `as` naming problem, a proper spec for the hasMany/belongsTo polymorphic relations would be:

**hasMany relation**
- `type`: **hasMany**
- `as`: **hasMany** relation name (optional)
- `model`: **modelTo**
- `polymorphic`:
  - typeOf `polymorphic` === `String`
    - matching **belongsTo** relation name
      - `foreignKey` is generated as `polymorphic + 'Id'`,
      - `discriminator` is generated as `polymorphic + 'Type'`

  - typeOf `polymorphic` === `Object`
    - `as`: matching **belongsTo** relation name
      - (required) if both foreignKey and discriminator are **NOT** provided
      - (extraneous) if both foreignKey and discriminator not provided
    - `foreignKey`:  A property of modelTo, representing the fk to modelFrom's id. 
      - generated by default as `as + 'Id'`
    - `discriminator`: A property of modelTo, representing the actual modelFrom to be looked up and defined dynamically 
      - generated by default as `as + 'Type'`

**belongsTo relation**
- `type`: **belongsTo**
- `as`: **belongsTo** relation name
- `model`: **NOT EXPECTED** (should throw an error as relation validation)
- `polymorphic`:
  - typeOf `polymorphic` === `Boolean`
      - `foreignKey` is generated as `relationName + 'Id'`,
      - `discriminator` is generated as `relationName + 'Type'`

  - typeOf `polymorphic` === `Object`
    - `as`: **NOT EXPECTED**, should throw an error at relation validation
    - `foreignKey`:  A property of modelTo, representing the fk to modelFrom's id. 
    - `discriminator`: A property of modelTo, representing the actual modelFrom to be looked up and defined dynamically .

**Comment by jannyHou** [comment]
@ebarault Your definition post in https://github.com/strongloop/loopback-datasource-juggler/issues/1298#issuecomment-298596768 looks perfect to me 👍

**Comment by ebarault** [comment]
@jannyHou excellent! i'll review the relation definition code accordingly then.

---

Regarding the naming of polymorphic `as`: 

Considering that when `typeOf polymorphic === Object`, `as` is **extraneous** when `foreignKey` and `discriminator` are provided, and that 
```
polymorphic: {
  as: 'belongsToRelName`
}
```
is fully equivalent to: 
```
polymorphic: 'belongsToRelName`
```

I suggest we **stop referencing the polymorphic `as` keyword in the doc** and favor the latter shorthand declaration. The code will keep handling the `as` keyword though for backward compatibility.

What do you think?

**Comment by jannyHou** [comment]
> I suggest we stop referencing the polymorphic as keyword in the doc

@ebarault Agree, I had same thought yesterday, I would prefer to define the relation either like 
`polymorphic: 'belongsToReName'`
OR
`polymorphic: {fk: 'fkName', discriminator: 'disName'}`,
just DO NOT combine them with `as`

**Comment by jannyHou** [comment]
@kjdelisle TBR
- repo: loopback-datasource-juggler
- version: minor release

**Comment by jannyHou** [comment]
Document PR: https://github.com/strongloop/loopback.io/pull/381
WIP, I will update hasAndBelongsToMany and hasManyThrough polymorphic docs after verify the correct definition by some example.
