### ISSUE TITLE
upsert and upsertWithWhere do not properly support MongoDB extended operators

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-datasource-juggler#1324]
# Description/Steps to reproduce
When issuing an upsert or upsertWithWhere request there is no proper support for MongoDB extended operators such as `$set`, etc...

In both cases the data is firstly converted to a model object and then tried to apply the **update** properties on it. [example](https://github.com/strongloop/loopback-datasource-juggler/blob/bb3812fbfb1709e309c4afc59986b24540aba2c2/lib/dao.js#L540) This results in an empty model with false values (update operators such as `$set` are used which produce an error)

Instead of applying this conversions, the option for allow extended operators should also be checked here and not directly create the model instance in order to get the proper update object to forward to the connector.

Finally `upsertWithWhere` is not implemented with MongoDB Connector resulting to the alternate find first, else create manual method where the same update handling takes place [Here](https://github.com/strongloop/loopback-datasource-juggler/blob/bb3812fbfb1709e309c4afc59986b24540aba2c2/lib/dao.js#L735)

For example consider **ModelA**:
```js
{
  id: 'model1'
  name: 'someName',
  address: {
    street: 'Some Street',
    number: 3
  }
}
```
Issuing an upsert command such as:
```js
ModelA.upsert({
  id: 'model1',
  $set: {
    'address.number': 5
  }
})
```
Will not be correctly executed since update object will be set to an object with undefined properties from actions in lines [733](https://github.com/strongloop/loopback-datasource-juggler/blob/bb3812fbfb1709e309c4afc59986b24540aba2c2/lib/dao.js#L733) to [737](https://github.com/strongloop/loopback-datasource-juggler/blob/bb3812fbfb1709e309c4afc59986b24540aba2c2/lib/dao.js#L737)

# Expected result

It should correctly understand the extended operators and pass them to the update query properly.

Also `upsertWithWhere` should be implemented in MongoDB connector (although it is an other repo issue)

# Additional information
`linux x64 7.8.0`
```
├── loopback@3.6.0
├── loopback-boot@2.23.0
├── loopback-connector-mongodb@1.18.1

```

**Comment by dhmlau** [comment]
@mitsos1os, would you like to submit a PR?
