### ISSUE TITLE
TypeError: modelTo.create is not a function

### ISSUE THREAD

**Issue by davidrivers93** [strongloop/loopback-datasource-juggler#1335]
Hello.

I am creating two different API's using loopback and remote connector. On first API, I have a model named Supplier with a local DB and a hasMany relationship to KmRange that is a model on the second API.

When I try to make a POST to /Suppliers/1/KmRange it throws me the next error : 

> Web server listening at: http://0.0.0.0:3006
Browse your REST API at http://0.0.0.0:3006/explorer
Error no gestionado para la solicitud POST /api/Suppliers/1/kmRange: TypeError: modelTo.create is not a function
    at HasMany.create (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1812:11)
    at ModelConstructor.method (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/loopback-datasource-juggler/lib/relation-definition.js:735:33)
    at ModelConstructor.fnCreate [as __create__kmRange] (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/loopback-datasource-juggler/lib/scope.js:320:7)
    at SharedMethod.invoke (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/shared-method.js:270:25)
    at HttpContext.invoke (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/http-context.js:297:12)
    at phaseInvoke (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/remote-objects.js:649:9)
    at runHandler (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)
    at runHandlers (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at /Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25
    at /Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at execStack (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/remote-objects.js:494:7)
    at RemoteObjects.execHooks (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/remote-objects.js:498:10)
    at phaseBeforeInvoke (/Users/david/Desktop/projects/traqui/price-hub-v1/node_modules/strong-remoting/lib/remote-objects.js:645:10)

This is the Supplier model config on API 1:

> {
  "name": "KmRange",
  "plural": "KmRanges",
  "base": "Model",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "min": {
      "type": "number",
      "required": true
    },
    "max": {
      "type": "number",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "supplier": {
      "type": "belongsTo",
      "model": "Supplier"
    }
  },
  "acls": [],
  "methods": {}
}

Any idea?

Thanks in advance.
David.

**Comment by dhmlau** [comment]
@davidrivers93, it seems to be working fine with me.  Wanna double check a few things:
- Are you using loopback 3 to create the app?  
- which version of `loopback-datasource-juggler` are you using?  
- what database are you using? 

For me, I'm using LB3, latest code in juggler with cloudant.

**Comment by davidrivers93** [comment]
Hi @dhmlau .

We are using loopback3. Our loopback-datasource-juggler is 3.4.1 and we are using a simple json as database on development.

This is the Supplier model config : 

> {
  "name": "Supplier",
  "plural": "Suppliers",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "zones": {
      "type": "hasMany",
      "model": "Zone",
      "foreignKey": ""
    },
    "rates": {
      "type": "hasMany",
      "model": "Rate",
      "foreignKey": ""
    },
    "VolumetricWeightRange": {
      "type": "hasMany",
      "model": "VolumetricWeightRange",
      "foreignKey": ""
    },
    "price": {
      "type": "belongsTo",
      "model": "price"
    },
    "kmRange": {
      "type": "hasMany",
      "model": "KmRange",
      "foreignKey": "test"
    },
    "routes": {
      "type": "hasMany",
      "model": "Route",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "*"
    }
  ],
  "methods": {}
}

This is the model-config.json file on API1 : 

> {
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "db"
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "db",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "db",
    "public": false,
    "options": {
      "strictObjectIDCoercion": true
    }
  },
  "Role": {
    "dataSource": "db",
    "public": false
  },
  "Operation": {
    "dataSource": "db",
    "public": true
  },
  "Supplier": {
    "dataSource": "suppliers",
    "public": true
  },
  "Rate": {
    "dataSource": "RangesApi",
    "public": true
  },
  "Region": {
    "dataSource": "RangesApi",
    "public": true
  },
  "Route": {
    "dataSource": "RangesApi",
    "public": true
  },
  "Zone": {
    "dataSource": "RangesApi",
    "public": true
  },
  "VolumetricWeightRange": {
    "dataSource": "RangesApi",
    "public": true
  },
  "Price": {
    "dataSource": "db",
    "public": true
  },
  "Service": {
    "dataSource": "ServicesApi",
    "public": true
  },
  "KmRange": {
    "dataSource": "ServicesApi",
    "public": false
  }
}

And this is the datasource config :  

> {
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "suppliers": {
    "name": "suppliers",
    "localStorage": "",
    "file": "suppliers.json",
    "connector": "memory"
  },
  "RangesApi": {
    "url": "http://localhost:3004/api",
    "name": "RangesApi",
    "connector": "remote"
  },
  "ServicesApi": {
    "url": "http://localhost:3001/api",
    "name": "ServicesApi",
    "connector": "remote"
  },
  "PriceRangesApi": {
    "name": "PriceRangesApi",
    "connector": "rest",
    "debug": true,
    "operations": [
      {
        "template": {
          "method": "GET",
          "url": "http://localhost:3004/api/Operations",
          "headers": {
            "accept": "application/json",
            "content-type": "application/json"
          }
        },
        "functions": {
          "call": [],
          "find": []
        }
      },
      {
        "template": {
          "method": "POST",
          "url": "http://localhost:3004/api/Operations",
          "headers": {
            "accept": "application/json",
            "content-type": "application/json"
          },
          "body": "{body}"
        },
        "functions": {
          "create": [
            "body"
          ],
          "findOrCreate": [
            "body"
          ]
        }
      }
    ]
  },
  "PriceServicesApi": {
    "name": "PriceServicesApi",
    "connector": "rest",
    "debug": true,
    "operations": [
      {
        "template": {
          "method": "GET",
          "url": "http://localhost:3001/api/Operations",
          "headers": {
            "accept": "application/json",
            "content-type": "application/json"
          }
        },
        "functions": {
          "call": [],
          "find": []
        }
      },
      {
        "template": {
          "method": "POST",
          "url": "http://localhost:3001/api/Operations",
          "headers": {
            "accept": "application/json",
            "content-type": "application/json"
          },
          "body": "{body}"
        },
        "functions": {
          "create": [
            "body"
          ],
          "findOrCreate": [
            "body"
          ]
        }
      }
    ]
  }
}


It's very rare error because I can make a POST  to /Suppliers/1/Zone without problems and Zone model is using the same connector (remote to Ranges API)

Any idea?

Thanks in advance.
David.

**Comment by dhmlau** [comment]
For the quick look, range has `public: false` where zone has `public: true`.  
I tried that using my app, it doesn't make a difference though, but i'm not using remote. 

Maybe you can give it a try (to change public to true), while I'll reproduce the problem using the additional info u provided.

**Comment by dhmlau** [comment]
@davidrivers93  actually do you have an app that can be used to reproduce this problem?

**Comment by davidrivers93** [comment]
Hi @dhmlau .

Finally, we have resolved the issue. The error comes from the model type on range model that was setted as model and not as PersistedModel.

Thanks for your support.

Best regards.

**Comment by dhmlau** [comment]
That's good to know.  Thanks!
