### ISSUE TITLE
Models cannot use "errors" as property name

### ISSUE THREAD

**Issue by joseandrespg** [strongloop/loopback-datasource-juggler#1353]
# Description/Steps to reproduce

For us this is a bug. 

We have a property called "errors" inside our model, like: 

```
"errors": {
	"type": [	
		"object"
	],
	"required": true
}
```

But every time we post a new record we got a boolean with value `false` in the database (mongo).

After debugging I found that, in the `after save` hook, the instance (`ModelConstructor`) has a property called `errors` on its root properties:
![image](https://cloud.githubusercontent.com/assets/1703342/25397245/904cbdd2-29df-11e7-8361-7a6b32a30edf.png)

And that is the value that was overwriting our input.

I would say that the internal property `errors` should be prepended with a `_` like the other internal properties.

# Expected result

The expected result will be that the our input named `errors` get stored into the `errors` property of the document in the database.

# Additional information

```
linux x64 6.9.1
├── loopback@3.6.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-mongodb@3.0.1
├── loopback-context@3.1.0
├── loopback-ds-timestamp-mixin@3.4.1
```

**Comment by ssh24** [comment]
@joseandrespg This definitely looks like an issue. The patch looks straight forward, are you willing to contribute a PR to fix this?

**Comment by joseandrespg** [comment]
@ssh24 I do: https://github.com/strongloop/loopback-datasource-juggler/pull/1357

Thanks!
