### ISSUE TITLE
{"exists":true} is not work

### ISSUE THREAD

**Issue by Sanbornzhang** [strongloop/loopback-datasource-juggler#1369]
# Description/Steps to reproduce
1.
```
git clone loopback-sandbox
```
2. change database to mongoDB
3. `node .`
4. create new user
5. query user `GET /Users`
6. filter is `{"where":{"email":{"exists":true}}}`
7. see DEBUG log
```
the filter is [object Object]
```
[cause code](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1789)

package.json
```
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^3.1.0",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.0.1"
```

[sanbox](https://github.com/Sanbornzhang/loopback-sanbox)
# Expected result
result is not null cause already register user

# Additional information

**Comment by loay** [comment]
Hi @Sanbornzhang 
Do you have already a fix that you would like to contribute?
If yes, please provide a pr https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/contrib/code-contrib.md

Thanks.

**Comment by ssh24** [comment]
@Sanbornzhang **exists** is not a valid loopback operator even though it is a mongodb operator. However, at the moment we do not support it. Look [here](https://github.com/strongloop/loopback-connector-mongodb/#additional-properties) for all the supported mongodb operators.

You could instead try something like this as your filter to get all the email of the users:
```json
{"fields": {"email": true}}
```

Closing this issue as resolved. Feel free to reopen if needed.
