### ISSUE TITLE
hasManyThrough fails

### ISSUE THREAD

**Issue by marmarosi** [strongloop/loopback-datasource-juggler#137]
In relations.js at line 134:
```
  if (params.through) {
    var fk2 = i8n.camelize(anotherClass.modelName + '_id', true);
```
should be:
```
  if (params.through) {
    var fk2 = this.dataSource.idName(anotherClass.modelName) ||
      i8n.camelize(anotherClass.modelName + '_id', true);
```
It would be even better the following definition:
```
"relations": {
      "images": {
        "type": "hasMany",
        "model": "image",
        "foreignKey": "maltKey", // malt_image.malt_key => malt.malt_key
        "through": "malt-image"
        "throughField": "imageKey", // malt_image.image_key => image.image_key
      }
    }
```
However, that does not solve the issue, later in scope.js at line 100:
```
        Object.keys(targetClass._scopeMeta).forEach(function (name) {
```
_scopeMeta is undefined. If I skip that, then in scope.js at line 74:
```
          return targetClass.find(params, function (err, data) {
```
targetClass is the through model (malt-image) instead of the target model (image). It is more interesting that find() is undefined. I abandoned at this point.

**Comment by loay** [comment]
Hi @marmarosi,
Is this issue still persisting?
Thanks.

**Comment by marmarosi** [comment]
I do not know - I do not already use strongloop modules.

**Comment by loay** [comment]
Thanks @marmarosi for getting back to me promptly. 
If you face this issue again, please leave a comment and I will re-open an issue. 
Thanks.
