### ISSUE TITLE
persist hook returning error is ignored by persistedModel.updateAttributes(data, callback)

### ISSUE THREAD

**Issue by tflowcamdev** [strongloop/loopback-datasource-juggler#1374]
# Description/Steps to reproduce

I have a model where I implemented a mixin to encrypt data in the persist hook.

However I've found that when using Model.updateAttributes(), if the persist mixin has an error, it's ignored.  In my particular case (using mongodb connector), it will proceed and write to the db.

Example mixin code to call next with an error:

```
Model.observe('persist', function(ctx, next) {
  return next('Error persist has failed!');
});
```

# Expected result

I expect the updateAttributes to call the callback with the error, and not continue to write to the DB.

```
modelInstance.updateAttributes(dataToUpdate, function(updateErr) {
   if (updateErr) {
      // log error here
   } else {
     // success
   }
});
```

With the above, updateErr will be undefined.

I believe the problem still exists in the latest code I see in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js

on line 3300:

            Model.notifyObserversOf('persist', ctx, function(err) {
              if (connector.updateAttributes.length === 5) {
                connector.updateAttributes(model, getIdValue(inst.constructor, inst),
                ....

Instead of something like:

            Model.notifyObserversOf('persist', ctx, function(err) {
              if (err) return cb(err);
              if (connector.updateAttributes.length === 5) {
                connector.updateAttributes(model, getIdValue(inst.constructor, inst),
               .....

# Additional information

Output of: node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 6.10.0

Output of: npm ls --prod --depth 0 | grep loopback

├── loopback@3.6.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
├── loopback-component-passport@3.2.0
├── loopback-connector-mongodb@3.0.1
├── loopback-context@3.1.0

**Comment by loay** [comment]
Hi @tflowcamdev 
Thanks for reporting the issue.. Can you please provide a sample repo so I can reproduce?
Also if you have already a solution, can you please submit a pr and tag me and I will review it so I can merge it. Thanks

**Comment by loay** [comment]
Actually, I did run few tests, and you can have a look in `test/manipulation.js` for example. You will see how `updateAttributes` error is being handled in the test cases. So As a matter of fact, when you try to use `updateAttributes`, the error will be printed and not undefined. 
Let's take an example:

```
      User.create({password: 'abc123'}, function(err, createdUser) {
        if (err) return done(err);
        createdUser.updateAttributes({'password':''}, function(err, updatedUser) {
          console.log( err);
          console.log('updatedUser: ', updatedUser);
          done();
        });
      });
```
You will find that the output is a stack error message, that will point out the error, as well as the `updatedUser` is undefined. 
If I misinterpret here, please let me know and please provide a sandbox repo so I can reproduce. Thanks.
