### ISSUE TITLE
Polymorphic Associations / control of relation scope

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#138]
This would be an interesting feature to support. It means that the model class/type is stored alongside the key.

Somewhat related: given that model inheritance is possible, it might make sense to at least support one level of this hierarchy for fetching:

Animal > Mammal
Animal > Reptile

Mammal.find() would find only Mammals, whereas:
Animal.find() would find both Mammals and Reptiles.

See: https://github.com/briankircho/mongoose-schema-extend for an example of this.

Essentially, being able to control the default association scopes ('where') should allow this, and other functionality, like setting the default sort order for these relations.

**Comment by violet-day** [comment]
+1

**Comment by senorcris** [comment]
This would be a great feature

**Comment by epyx25** [comment]
+1
