### ISSUE TITLE
validation with allowBlank doesn't allow empty strings

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback-datasource-juggler#1386]
Take into consideration the Gender enum scenario:
```
  user.validatesInclusionOf('gender', { in: ['male', 'female'], message: 'Gender must either be male or female', allowBlank: true, allowNull: true });
```
The reasoning is that users may not want to share their gender, so an empty value may be submitted. However, the current behavior of `allowBlank` validation does not allow it. The issue is highlighted in the code below:

```
// validations.js
function nullCheck(attr, conf, err) {
  // First determine if attribute is defined
  if (typeof this[attr] === 'undefined') {   <-- what about adding this[attr] === ''
    if (!conf.allowBlank) {
      err('blank');
    }
    return true;
  } else {
    // Now check if attribute is null
    if (this[attr] === null) {
      if (!conf.allowNull) {
        err('null');
      }
      return true;
    }
  }
  return false;
}

```

I'll gladly submit a PR if you agree.

# Additional information

Node: darwin x64 6.6.0
loopback@3.6.0
loopback-boot@2.23.0
loopback-connector@4.0.0

**Comment by dhmlau** [comment]
@simoami  you're always welcomed to submit a PR!

**Comment by simoami** [comment]
Thanks @dhmlau,

PR: [1432](https://github.com/strongloop/loopback-datasource-juggler/pull/1432)

**Comment by dhmlau** [comment]
PR has landed.  Closing this issue.

**Comment by dhmlau** [comment]
connect to strongloop/loopback-datasource-juggler/pull/1432
