### ISSUE TITLE
missing the option argument in find (scope.js)

### ISSUE THREAD

**Issue by dmellonch** [strongloop/loopback-datasource-juggler#1388]
# Description/Steps to reproduce

In have a model Azienda with a has-many-through relation, like:

`
{
  "name": "Azienda",
  "relations": {
      "mansioni": {
          "type": "hasMany",
          "model": "Mansione",
          "through": "MansioneAzienda"
        }
    }
}
`

When i perform Azienda .mansioni({}, option,  cb), the find function over related model, missing the option argument (scope.js , row 139)

`relatedModel.find(queryRelated, cb);`
      
# Additional information

win32 x64 6.10.0

loopback@3.8.0
loopback-boot@2.24.0
loopback-component-explorer@4.2.0
loopback-connector-mongodb@3.1.0

**Comment by dhmlau** [comment]
@dmellonch, thanks for catching that.  Would you like to submit a PR?

**Comment by dmellonch** [comment]
ok @dhmlau, what should I do?

**Comment by dhmlau** [comment]
@dmellonch, you can see the instructions in here to create a pull request: https://help.github.com/articles/creating-a-pull-request/

There are some more info about how to contributing to this repo: 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/CONTRIBUTING.md

**Comment by dhmlau** [comment]
@dmellonch, did you have a chance to see how you can submit the PR from the instructions I've provided above?  Thanks.

**Comment by dmellonch** [comment]
Hi @dhmlau , i have already carried out the PR.

https://github.com/strongloop/loopback-datasource-juggler/pull/1394

I hope i followed the procedures correctly.

**Comment by ssh24** [comment]
Please create a new PR since #1394 has had issues with rebasing and the tests added initially were broken. Read more [here](https://github.com/strongloop/loopback-datasource-juggler/pull/1394#issuecomment-314155237)

**Comment by dhmlau** [comment]
connected to strongloop/loopback-datasource-juggler/pull/1426
