### ISSUE TITLE
FindOrCreate does not return errors on connector error in 2.5.4LTS

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback-datasource-juggler#1397]
See  #1223 Not very good when PR doesn't end up in LTS.

**Comment by dhmlau** [comment]
@jamesjjk, as discussed in #1223 , let's use this new ticket for discussion. 
```
@jamesjjk , it's strange. The PR #1226 is for 2.x branch.
And if you look at https://github.com/strongloop/loopback-datasource-juggler/blob/2.x/lib/dao.js#L1050, your change is here.

I've created a LB2 application, and I can also see the change there too.
```

**Comment by ssh24** [comment]
Followed the discussion from a couple of stories to here. The fix is in the 2.x branch but it has never been released. The fix was landed on March 16 while last LTS release was on March 13 https://github.com/strongloop/loopback-datasource-juggler/releases/tag/v2.54.1

**Comment by ssh24** [comment]
@jamesjjk Sorry for the inconvenience.

Bumping this for a TBR on the upcoming release cycle.

**Comment by kjdelisle** [comment]
2.54.2 has been released, closing.
Please let us know if this is still unresolved.
