### ISSUE TITLE
updateAttributes does not respect strict:'filter'

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-datasource-juggler#1419]
I've made a full description here: https://github.com/strongloop/loopback/issues/3482
but I was not sure if it was the right repo. I've also made a repro in the loopback sandbox

**Comment by mrfelton** [comment]
This looks like the same issue I just described and created a patch for here: https://github.com/strongloop/loopback-datasource-juggler/issues/1422

@ernie58 can you test wether this fixes the issue for you please? Thanks.

**Comment by slorf** [comment]
On behalf of @ernie58 , we can confirm the patch solves the issue.

**Comment by ssh24** [comment]
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/1422. Fix on https://github.com/strongloop/loopback-datasource-juggler/pull/1423.

**Comment by jamesjjk** [comment]
@ssh24 This issue remains and is not fixed in Loopback-datasource-juggler 3.35.0
