### ISSUE TITLE
afterDestroy hook not called on REST remoting (deleteById)

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#142]
Shouldn't this be the case? Perhaps this is due to how removeById/deleteById/destroyById are being used? Because of this, it's easy to miss the right remote hook method invocations too.

As a workaround, I'm using `Model.on('deleted', ...)` which seems to be triggered either way.

**Comment by bajtos** [comment]
I am closing this issue, we are moving away from `beforeDestroy/afterDestroy` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `after delete` hook and open a new GH issue if you run into any problem.
