### ISSUE TITLE
Document the persistUndefinedAsNull model option

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-datasource-juggler#1421]
# Description/Steps to reproduce
Read the documnetation at https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html and note that there is no mention of the `persistUndefinedAsNull` model option

# Expected result
`persistUndefinedAsNull` should be documented.

**Comment by dhmlau** [comment]
`persistUndefinedAsNull` was introduced in this PR: 
https://github.com/strongloop/loopback-datasource-juggler/pull/542

**Comment by mrfelton** [comment]
... some activity... (keep this open, it's a valid issue)

**Comment by mrfelton** [comment]
not stale
