### ISSUE TITLE
Delete referencesMany references of one model deletes references of all models

### ISSUE THREAD

**Issue by thomaschille** [strongloop/loopback-datasource-juggler#1425]
# Description/Steps to reproduce

Repo: https://github.com/medicinisto/loopback-sandbox

Create test data 

```
POST /mods {"name":"mod1"}
POST /mods {"name":"mod2"}
POST /mods/1/refs {"name":"mod1-ref1"}
POST /mods/2/refs {"name":"mod2-ref1"}
```

Try to delete **mod1**s ref only

`DELETE /mods/1/refs`

Try to get remaining ref

`GET /refs`

# Expected result
```
[
  {
    "name": "mod2-ref1",
    "id": 2
  }
]
```
# Actual result

`[]`

# Additional information

Looks like the the `DELETE /mods/{id}/refs` not only deletes the references to this model refs, instead of it deletes all existing refs. What for me looks like a critical bug.

darwin x64 7.3.0
loopback-sandbox@1.0.0 / ... /Repos/loopback-sandbox
├── loopback@2.38.3
├── loopback-boot@2.25.0
├── loopback-component-explorer@2.7.0
├── loopback-datasource-juggler@2.55.0

**Comment by loay** [comment]
Hi @thomaschille Thanks fore reporting the issue ... I will test ur sandbox and get back to u ASAP

**Comment by loay** [comment]
@thomaschille 
I tested with both Lb2 and LB3 .. and you are right, the same behaviour happens .. I will tag it as a bug . Thanks.

**Comment by madhav8** [comment]
Any update on this issue ?
