### ISSUE TITLE
modelTo is null when polimorfic relation is called with filter is empty

### ISSUE THREAD

**Issue by emsedano** [strongloop/loopback-datasource-juggler#1429]
# Description/Steps to reproduce
![image](https://user-images.githubusercontent.com/2681144/28334452-d345afea-6bc0-11e7-9ee4-11db02ae262d.png)

![image](https://user-images.githubusercontent.com/2681144/28334881-283c6f74-6bc2-11e7-9349-58be5c22f504.png)

# Expected result
* do not run `if (scopeOnRelatedModel === true) {` if `params.include.scope` is empty (`{}`)
* get list of related objects

# Additional information
juggler version is 3.9.0

**Comment by diegobent** [comment]
I enconutered another problem here...
https://github.com/strongloop/loopback-datasource-juggler/blob/f18d3487c64ea1ed3896da4d7a5010eadbd59a0d/lib/scope.js#L136

If the query doesn't have "IdKey" in the root of "where" object, it's always returned an empty array.

More complex queries are never performed; previous juggler versions works different!

**Comment by dhmlau** [comment]
PR: https://github.com/strongloop/loopback-datasource-juggler/issues/1429

**Comment by dhmlau** [comment]
@b-admike , seems like this is in progress for a while. are you blocked?

**Comment by b-admike** [comment]
@dhmlau no, but we haven't heard from @emsedano about writing unit tests for the PR. I'll look into doing so.
