### ISSUE TITLE
Update DAO methods to catch errors in cb

### ISSUE THREAD

**Issue by loay** [strongloop/loopback-datasource-juggler#1436]
## Reference: 
https://github.com/strongloop/loopback/issues/1364
https://github.com/strongloop/loopback-datasource-juggler/pull/1433

## Description:
Some Dao methods could case Loopback app to crash as the exception error is not caught in the callback. Issue is currently fixed for the methods `create`, `updateAttribute`, `updateAttributes` => please check references above. 

## Acceptance Criteria:

- [x] test cases for each method to determine if a bug is detected. 
- [x] fix the bug accordingly. 
- [x] test with a loopback app. 
- [x] Backport if needed. 

@bajtos  thoughts?

**Comment by kjdelisle** [comment]
## Update

If `setAttributes` is only ever called in callback chains, then it should accept a callback itself and perform the try-catch there. Then we can remove all of the try-catch blocks elsewhere, and ensure that there aren't any `setAttributes` calls without protection.

If that's not the case, then we'll just need to add try-catch coverage where appropriate.

## Acceptance Criteria
- Fix setAttributes
- Create test to prove that setAttributes works

**Comment by loay** [comment]
backporting is not compatible since the function signature has changed.
