### ISSUE TITLE
order by additional feature (postgre sql)

### ISSUE THREAD

**Issue by ptrblgh** [strongloop/loopback-datasource-juggler#1448]
Issue details at the postgre sql connector page: [https://github.com/strongloop/loopback-connector-postgresql/issues/281](https://github.com/strongloop/loopback-connector-postgresql/issues/281)

In nutshell: I would like to extend the `ORDER BY` syntax. The postgre sql supports an additional option after the direction: `ORDER BY ASC|DESC NULLS FIRST|LAST`. But the following line prevents this option to code it in the connector package: [https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1531)

Is there any way to override this `_normalize` function in the connector? Or any other suggestions are welcome. :)

**Comment by loay** [comment]
Hi @ptrblgh 
You can try to use native sql, as per this documentation https://loopback.io/doc/en/lb2/Executing-native-SQL.html
Please make sure that you read the disclaimer on top.

**Comment by ptrblgh** [comment]
@loay in postgresql the following query is valid:
`SELECT name FROM user ORDER BY login_timestamp ASC NULLS FIRST`

The focus is `NULLS FIRST`. It will be "cut" by the `_normalize` function (line linked in my first post). Yes, the native sql would be one solution but I would like to solve this one in a more elegant way - if it is possible.
