### ISSUE TITLE
Best practice for querying then updating to a model with lb

### ISSUE THREAD

**Issue by seanxlliu** [strongloop/loopback-datasource-juggler#1452]
Hi guys,
Thanks for providing such amazing framework, however, I am not sure how to handle the following cases with loopback:

1. I have a 'idInjected' model, so the primary id is unknown. I have to findOne with a condition first then save or create the instance according to the finding result.
2. I know the primary Id, but I don't know the current field value, so I have to findById first then do some caculation based on the current value. e.g. `page.viewed += 1; page.save();`

However, we may face a race condition when some concurrent requests hit, due to find/update are async methods. 

Do we have locker or something for loopback to handle these cases. Any suggestions are welcome!

**Comment by loay** [comment]
Hi @seanxlliu 
Here is some documentaion that should be helpful for you. 
1) [Using Database transaction](https://loopback.io/doc/en/lb3/Using-database-transactions.html)
In this document, you will see some tips about avoiding deadlocks ..

2) Use BulkUpdate ..Here is a [documentation](https://loopback.io/doc/en/lb2/Synchronization.html#bulk-update) on how to use it

**Comment by dhmlau** [comment]
@seanxlliu , it seems like @loay has answered your question.  Closing this issue.

**Comment by seanxlliu** [comment]
Thanks @dhmlau @loay
