### ISSUE TITLE
Update/create container model does not trigger operation hooks for embedded relation model

### ISSUE THREAD

**Issue by joeybenenati** [strongloop/loopback-datasource-juggler#1456]
As the loopback docs read for embedsMany relations:
"You can define before save and after save operation hooks for an embedded model in an embedsMany relation. Then, updating or creating an instance of the container model will trigger the operation hook on the embedded model."

However,  this is not the case. Before and after save hooks are not triggered for the embedded model when creating or updating the containing model. I am able to reproduce this recreating the example taken right from the loopback docs at https://loopback.io/doc/en/lb3/Embedded-models-and-relations.html

customer.json
```
{
  "name": "Customer",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "relations": {
    "emails": {
      "type": "embedsMany",
      "model": "EmailAddress",
      "property": "emailList",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
    ...
  }
```
email.json
```
{
  "name": "EmailAddress",
  "base": "Model",
  "idInjection": true,
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "defaultFn": "uuid"
    }
  }
```

# Expected result

# Additional information
darwin x64 7.2.1
├── loopback@3.6.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.0.0
├── loopback-component-oauth2@3.0.0
├── loopback-component-passport@3.3.0
├── loopback-connector-mysql@2.4.1
├── loopback-connector-postgresql@2.7.0
├── loopback-console@1.1.0
├── loopback-datasource-juggler@3.4.1
├── loopback-ds-timestamp-mixin@3.4.1
├── loopback-softdelete-mixin4@1.0.8

**Comment by loay** [comment]
Can you please provide a sample repo to reproduce the issue?
http://loopback.io/doc/en/contrib/Reporting-issues.html

Also, if you have a solution, can you please submit a PR with your solution? 
Thanks.
