### ISSUE TITLE
Getter of hasMany returns all instances of relation when instance.id is undefined

### ISSUE THREAD

**Issue by Schubbcasten** [strongloop/loopback-datasource-juggler#1457]
# Description/Steps to reproduce

In a 'before save' hook and the to be saved instance is a new instance, the id of the instance is still undefined. When now calling `instance.relation(callback)` it returns all instances of the relation model. 
It's basically doing the same as if you would call `Model.find({ where: { realtionId: undefined } })`.
This might be expected behavior, since it's an edge case that can be handled easily, but I'm not sure.

# Expected result

[] or Array with only the related instances

**Comment by loay** [comment]
Can you please provide a project so we can reproduce the issue? Thanks. 
This should help http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
