### ISSUE TITLE
Cannot inject password before create User's instance using hook

### ISSUE THREAD

**Issue by EveX1** [strongloop/loopback-datasource-juggler#1458]
# Description/Steps to reproduce
First please forgive my poor english.

I want to generate a random password when i register a user. So i tried with a pre hook on create, but it seems validation occurs before the hook itself. I'm aware that Operation Hooks `before save` is triggered before validation, but i don't want to re-generate a password every time i save my users.

So i'm dealing with a Validation Error: 

> 'password' can't be blank (value: undefined).

I tried to delete the validation with
```javascript
delete User.validations.password;
```
but i'm afraid it will delete this validation for the whole instance. Am i wrong ? And i'm not confident with the 'I'll kick validation outta here' way of doing it.

Anyway, with validation deleted, create passes, but obviously my password wasn't injected properly.

Here is my code sample:
```javascript
User.beforeRemote('create', (ctx, user, next) => {
    const password = generate.generate({
            length: 8,
            numbers: true,
            excludeSimilarCharacters: true,
        });
        Object.assign(ctx.args, { password: password });
        next();
    });
```

(I'm not quite sure of what `user` is and why it is needed as winston.info/console.log return an empty object.)

# Expected result

 1/ Find a way to passes trough Validation or even better to execute the injection BEFORE validations occur (so Validation can still do it's job)

 2/ Find the proper way to effectively inject my password to the created instance, as i'm afraid i made myself a fool with the way i've tried.

# Additional information

Node 6.11.1 & LB 3

**Comment by loay** [comment]
You can try with `beforeSave` where you add a condition to check if there is an existing password, then to ignore the operation and to carry on with the rest of the code. 
example 

```
if (ctx.data.password)
// don't generate the password and carry on
```

Also, if you still need help, can you please provide a sample app to I can follow the scenario that you are trying to reproduce ? Thanks.

**Comment by EveX1** [comment]
Thx for the help.

I'm using LB to build an API server wich can be use by a mobile app.
The goal was to avoid users to launch their mobile browser just to confirm their email adress. So i wanted to generate the pasword and send it. But it's not needed anymore since i found that i can open an android/iOS app with a link (like the one send with `User.verify()` ). Sending passwords by email is not safe anyway. It was a poor tech choice driven by UX.

I'm sorry to say that the LB documentation can be at least inaccurate and sometimes misleading. Maybe i'm wrong but i found nothing about ctx.data in the whole doc.
ex: to get the `email` argument with a login hook, i had to use `ctx.args.credentials.email` wich is never mentionned in the doc. I was driven mad because the `console.log(ctx.args)` showed me the `email` and `password` arguments, but `credentials` was hidden. I had to stringify the object to find that nasty hidden thing. I got plenty of exemples like this one, and i can't count the hours i lost just be trying to achieve a task with a misleading/inaccurate/outdated doc.

(Right now i'm trying to understand how can i reset users' password, and the doc makes me want to kill myself: not a simple-updated-usable exemple. It's all from a 3 years repo which clearly use outdated patterns)

Sorry about that it's just LB can be a powerfull tool, but the whole "trial and error" path for using it can be utterly frustrating.

**Comment by loay** [comment]
Hi @EveX1 
I used `ctx.data` as an example .. I thought you went through `user.js` file in the `common/models` in  Loopback repo .. it could be `ctx.instance` as well..   Also, I think it is much safer to confirm via the mobile browser than to do it via a sent email :) 

Can you also direct me to the area that needs documentation improvement and I will work on it .. 

For updating the password, you can use `User.resetPassword` in the same `User.js` file ..
Also, if you do not feel comfortable using that, then you can use other various methods in juggler, such as 
`replaceOrCreate`
`updateAttribute`
`updateAtributes`
`replaceById`, where u change the password of the user with the given id .. and many more ..

Let me know if I can help further .. all the above methods are documented properly .. Thanks

**Comment by EveX1** [comment]
Thank you for your help.

Regarding the documentation, there is some enhancements I have in mind, but i don't think it's the right place. As you can see my english is not good enough to contribute directly, but is there a way I can suggest improvements ?

Oh, and you can close the issue ofc.

**Comment by loay** [comment]
Hi @EveX1 Thanks for your contribution to enhance the product. 
You can contribute to the documentation here: https://github.com/strongloop/loopback.io
Just create a PR with your enhancements in the section that you think that needs some attention. 
Don't worry about the syntax or grammatical errors.. we will try to help and fix them as much as we could, as long as the intent is clear.

**Comment by mehray61** [comment]
how can i automatically generate password after user is registered and password should be sent to user as an OTP?
