### ISSUE TITLE
Duplicate results with include relation filter in a query

### ISSUE THREAD

**Issue by BlueRoboto** [strongloop/loopback-datasource-juggler#1466]
# Description/Steps to reproduce

I generated two models A and B; **B -> hasMany -> A**.
Inside B I putted an include filter, for example :
`  "scope": {
    "include": {
      "relation": "relationA"
    }
  }`
I putted one document in A and 257 documents in B and for each B-document I added a reference of A-document.
In a find query on B-collection the scope clause generates an anomaly when resolve _relationA_. In fact in this case find result generates two related instance of A in each B-document, but there should be only one instance of A in each B-document .
This anomaly vanishes when I use a _limit_ clause at 256 (_inqLimit_) documents or if I remove one document from db (max 256 documents).
If I triple document number (768 B-documents), the find result generate three related instances of A in each B-document.

In my opinion the problem is due to the function _uniq(a)_ that does not work properly and generates wrong results in _include.js_ script.

I have done a solution in this pull request #1418.

**Please analyze my solution or even consider the reported problem and find a suitable solution.**

# Additional information

MongoDB v3.4.5 
Loopback v3.8.0
loopback-connector-mongodb v3.2.0
loopback-datasource-juggler v3.9.2

**Comment by loay** [comment]
Can you please provide a sample repo to reproduce the issue? Thank you 
[How to report a bug](http://loopback.io/doc/en/contrib/Reporting-issues.html)

**Comment by BlueRoboto** [comment]
@loay I have implemented a simple test on this repo: https://github.com/BlueRoboto/loopback-sandbox.
I have used _hasAndBelongsToMany_ instead of _hasMany_ relation.

**Comment by BlueRoboto** [comment]
@loay Have you see my test ?

**Comment by pbouda** [comment]
@loay I ran into the same issue, the given workaround works for me. Is anybody working on this?

**Comment by pbouda** [comment]
I added PR #1526 with my solution.
