### ISSUE TITLE
Filtering related models was working, now not in 3.10.0

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-datasource-juggler#1476]
@devpascoe commented on [Tue Aug 15 2017](https://github.com/strongloop/loopback/issues/3566)

Previously in 3.9.0 my endpoint /api/accounts/12345/profiles?filter[where][foo]=bar would return the filtered results correctly. However in 3.10.0 zero results return.
Additionally 
```
      foo.bars({
        where: { id: 5678 }
      }, function (err, bars) {
        ...
      });
```
^ would return filtered results but instead returns all related items with no filter applied.

I consequently downgraded from 3.10.0 to 3.9.0 and everything is functioning correctly again. Perhaps something to look into with the new release.

---

@devpascoe commented on [Tue Aug 15 2017](https://github.com/strongloop/loopback/issues/3566#issuecomment-322468262)

Note above had to set loopback to 3.9.0 AND loopback-datasource-juggler to 3.6.1 to restore functionality.

---

@dhmlau commented on [Tue Aug 15 2017](https://github.com/strongloop/loopback/issues/3566#issuecomment-322546483)

@devpascoe , what's the version of `loopback-datasource-juggler` for the non-working case?  Not sure if it's related, which connector are you using? 

---

@dhmlau commented on [Tue Aug 15 2017](https://github.com/strongloop/loopback/issues/3566#issuecomment-322547142)

To help us to get it resolved faster, can you provide a link to a test project? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

---

@devpascoe commented on [Tue Aug 15 2017](https://github.com/strongloop/loopback/issues/3566#issuecomment-322615138)

The combo of loopback-datasource-juggler 3.9.3 and loopback 3.10.0 had the issue. Reverting to juggler 3.6.1 and loopback 3.9.0 restored functionality. The reason i was sticking around on juggler 3.6.1 was this https://github.com/strongloop/loopback-datasource-juggler/issues/1381

---

@devpascoe commented on [Thu Aug 24 2017](https://github.com/strongloop/loopback/issues/3566#issuecomment-324795489)

still happening in 3.11.1

**Comment by dhmlau** [comment]
@devpascoe , after moving your issue to this repo, i couldn't set you to be the originator.  

@strongloop/sq-lb-apex , looks like it's a regression.

**Comment by jannyHou** [comment]
@dhmlau we have a story for it internally: https://github.com/strongloop-internal/scrum-apex/issues/298

**Comment by dhmlau** [comment]
Duplicate of strongloop/loopback#3487
Closing this one.
