### ISSUE TITLE
Connecting AccessToken in redis throws 500 instead of 401 when invalid

### ISSUE THREAD

**Issue by calebfroese** [strongloop/loopback-datasource-juggler#1486]
We are storing the access token in redis, using `loopback-connector-redis` as the datasource. When a request is made with an invalid access token, instead of returning a 401, it is returning 500 with the following message: 

`
{
    "error": {
        "statusCode": 500,
        "name": "TypeError",
        "message": "Cannot read property 'constructor' of null",
        "stack": ...
    }
}
`

# Description/Steps to reproduce

1. Add redis datasource using `"connector": "redis"`
2. Attach the `AccessToken` model to the redis datasource
3. Make a request to the API using an invalid access token. It will returning the above 500, instead of the expected 401. For example, a get request to `/api/Users` with headers `"Authorization": "invalid access token"`.

# Link to reproduction sandbox

https://github.com/calebfroese/loopback-redis-500-replication

# Expected result

`
{
    "error": {
        "statusCode": 401,
        "name": "Error",
        "message": "Authorization Required",
        "code": "AUTHORIZATION_REQUIRED",
        "stack": ...
    }
}
`

**Comment by paulussup** [comment]
@zbarbuto Is this something that can be looked at?

**Comment by zbarbuto** [comment]
#1492

**Comment by zbarbuto** [comment]
Issue has been resolved
