### ISSUE TITLE
Using v3.12 higher level transactions with Postgresql connector

### ISSUE THREAD

**Issue by jubilee-scott** [strongloop/loopback-datasource-juggler#1494]
I am trying to make use of the Loopback higher level transaction additions to Datasource Juggler v3.12 when utilizing the Postgresql database connector. Executing the following model remote method code throws an exception.   

```
'use strict'
const logger = require('strong-logger')
module.exports = function (BusinessFactory) {
  BusinessFactory.test1 = async function (callback) {
    try {
      let app = BusinessFactory.app
      await app.dataSources.manna_tms_ds.transaction(async models => {
        try {
          const {
            Business
          } = models;
          logger.info(await Business.count())
        } catch (err) {
          logger.error('bad1', err)
        }
      })
    } catch (err) {
      logger.error('bad2', err)
    }
  }
};

```
Exception Trace:

>     loopback:connector:transaction Starting a transaction with options: {} +2ms
>     loopback:connector:postgresql:transaction Begin a transaction with isolation level: READ COMMITTED +0ms
>     /home/scott/sw-dev/manna-tms/node_modules/loopback-datasource-juggler/lib/datasource.js:2233
>         tx.observe('timeout', function(context, next) {
>            ^
>     TypeError: tx.observe is not a function
>         at transactionCreated (/home/scott/sw-dev/manna-tms/node_modules/loopback-datasource-juggler/lib/datasource.js:2233:10)
>         at /home/scott/sw-dev/manna-tms/node_modules/loopback-datasource-juggler/node_modules/loopback-connector/lib/transaction.js:119:5
>         at Query.callback (/home/scott/sw-dev/manna-tms/node_modules/loopback-connector-postgresql/lib/transaction.js:34:11)
>         at Query.handleReadyForQuery (/home/scott/sw-dev/manna-tms/node_modules/pg/lib/query.js:126:10)
>         at Connection.<anonymous> (/home/scott/sw-dev/manna-tms/node_modules/pg/lib/client.js:163:19)
>         at emitOne (events.js:115:13)
>         at Connection.emit (events.js:210:7)
>         at Socket.<anonymous> (/home/scott/sw-dev/manna-tms/node_modules/pg/lib/connection.js:118:12)
>         at emitOne (events.js:115:13)
>         at Socket.emit (events.js:210:7)
>         at addChunk (_stream_readable.js:266:12)
>         at readableAddChunk (_stream_readable.js:253:11)
>         at Socket.Readable.push (_stream_readable.js:211:10)
>         at TCP.onread (net.js:585:20)    
> 

Environment:

> linux x64 8.4.0
> 
> ├── loopback@3.13.0
> ├── loopback-boot@2.26.2
> ├── loopback-component-explorer@5.1.0
> ├── loopback-component-storage@3.3.1
> ├── loopback-connector-postgresql@3.1.0
> ├── loopback-datasource-juggler@3.12.0
>

**Comment by dhmlau** [comment]
@zbarbuto , is it a similar problem you're running into?

**Comment by zbarbuto** [comment]
@dhmlau @jubilee-scott yes same issue. #1493 fixes. I suggest you use my fork until something is merged that works for Postgres.

**Comment by jubilee-scott** [comment]
@zbarbuto and @dhmlau thank you for your responses.  I will make use of the work around for the current time.
