### ISSUE TITLE
Move shortid to optional ID generators

### ISSUE THREAD

**Issue by ai** [strongloop/loopback-datasource-juggler#1502]
# Description/Steps to reproduce

> Perhaps a better alternative for this is to allow registering custom functions. That was people are free to register whatever ID generation they want (e.g. nanoids, hashids or some sort of slug generator function).

— @zbarbuto 

https://github.com/strongloop/loopback-datasource-juggler/pull/1501#issuecomment-335620498

**Comment by zbarbuto** [comment]
Not stale - PR just needs to be updated.
