### ISSUE TITLE
Where filter: date comparison doesn't work in nested properties

### ISSUE THREAD

**Issue by luisfavila** [strongloop/loopback-datasource-juggler#1514]
# Description

When filtering a nested property (e.g. schedule.happenedOn) which is a date, comparison operators (lt, lte, gt, gte, between) don't work and an empty array is returned instead.

# Steps to reproduce

- Create a model with a nested Date property, .eg.:
```
"properties": {
  "schedule": {
    "type": {
      "duration": {
        "type": "number",
        "required": true
      },
      "happenedOn": {
        "type": "date",
        "required": true
      }
    }
  }
}

````
- Insert record:
```
{
  "schedule": {
    "duration": 2,
    "happenedOn": "2017-10-23T11:30:00.000Z"
  }
}

````

- Query [find] with filter:
```
{
  "where": { 
    "schedule.time": {"gt": "2017-10-20T00:00:00.000Z"}
  }
}

```

# Expected result

You would expect the inserted record to be returned, but an empty array is instead.

# Additional information

win32 x64 8.3.0
+-- loopback@3.14.0
+-- loopback-boot@3.0.1
+-- loopback-component-auto-migrate@0.3.0
+-- loopback-component-explorer@5.2.0
+-- loopback-connector-mongodb@3.2.1
+-- loopback-datasource-juggler@3.12.0

**Comment by luisfavila** [comment]
I have found the bug to be located on `DataAccessObject._coerce` in `dao.js`, where nested properties are not checked and so the ISO string is not converted to DateType.

**Comment by luisfavila** [comment]
#1169 Seems to be related. I am working on the issue, but can't really write test cases for the Date ones since memory connector doesn't support them. How should I proceed @bajtos?

**Comment by bajtos** [comment]
>  I am working on the issue, but can't really write test cases for the Date operations since memory connector doesn't support them. How should I proceed?

@luisfavila sorry for the delay. To be honest, I don't know that much about juggler, could you @kjdelisle or @jannyHou help here?

My first reaction is to add support for Date operations to the memory connector, because I don't see any reason why Date should not be supported?

**Comment by luisfavila** [comment]
No problem @bajtos 

The problem was actually not the lack of support for those operations, but that nested properties were not being casted. I fixed it and also provided tests :)

**Comment by bajtos** [comment]
@luisfavila 
> I fixed it and also provided tests :)

Cool! I reviewed your pull request #1515, please see my comments there.

**Comment by luisfavila** [comment]
Thanks @bajtos! Just a quick update: I've read everything and will do the necessary changes ASAP, I'm just overloaded right now.
