### ISSUE TITLE
Memory connector: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by doowb** [strongloop/loopback-datasource-juggler#1518]
# Description/Steps to reproduce

I get the error: `TypeError: Cannot convert undefined or null to object` when trying to get all items from a newly created model. This happens in the memory connector, persisted to a file.

From the `/explorer`, I click "Try it out!" under the main `GET` route.

# Link to reproduction sandbox

I started to create a sandbox just for this issue, but sometimes I didn't receive the error when starting a fresh project. I made sure I had all of the up-to-date libraries (including `loopback` and `loopback-boot`).

# Expected result

I expect an empty array to be returned when no items are in the collection.

# Additional information

When trying to track this down in my current app, so I could submit a PR, I found that `.collection` in `lib/connectors/memory` is called at different times (which makes sense).

1. When the app is booting up and `loopback-boot` is adding defined models to the app. At this point `this.cache[model]` is `undefined`, then it's populated by calling `.initCollection`.
2. When querying the collection. At this point `this.cache[model]` was `undefined` again.

From that, it seems like there are different instances of the `memory` connector being used, but I'm not sure how I could track that down.

Then I created a new project and didn't get the errors, so I updated my dependencies in my existing project, and I'm getting the error again. If I had a better way to reproduce this, I would.

 ```
darwin x64 8.4.0
├── loopback@3.16.0
├── loopback-boot@2.27.0
├── loopback-component-explorer@5.2.0
```

**Comment by cc5tudio** [comment]
I'm having this same problem. 

"loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.0.0",
    "loopback-component-storage": "^3.3.1",

**Comment by kranthitechie** [comment]
I had the same problem.

Manually added an entry for the new model into the json file used by the memory connector and it seems to be working now.

**Comment by svashish305** [comment]
> I had the same problem.
> 
> Manually added an entry for the new model into the json file used by the memory connector and it seems to be working now.

facing same issue :D

**Comment by odykyi** [comment]
the same issue
