### ISSUE TITLE
Replace filter implementation with loopback-filters

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#1529]
Let's deliver the promise we made in our [docs] long time ago:

> We plan to convert all modules to use loopback-filter, so it will become LoopBack’s common “built-in” filtering mechanism.

Right now, loopback-filters are always behind the "real" loopback implementations and people have to port new features from loopback-datasource-juggler to loopback-filters to keep them up to date (see e.g. https://github.com/strongloop/loopback-filters/issues/13, https://github.com/strongloop/loopback-filters/issues/10, https://github.com/strongloop/loopback-filters/issues/3, https://github.com/strongloop/loopback-filters/pull/20).

Once we switch juggler to use loopback-filters, there will be only a single place where to add new filtering features.

Important note: this change should be fully backwards compatible, all existing tests in loopback-datasource-juggler and loopback should keep passing. This will most likely require improvements to be made in loopback-filters to get them feature parity with what we have in juggler right now.

**Comment by aatifhussain** [comment]
Do you have updated loopback-filters?

**Comment by bajtos** [comment]
@aatifhussain I am afraid I don't understand your question, what kind of updates do you have in mind? AFAIK, no action related to this issue has been made yet.

**Comment by aatifhussain** [comment]
@bajtos You got it right, Thank you.

**Comment by privateOmega** [comment]
@bajtos I have put in a PR 15 days ago pending review.

**Comment by bajtos** [comment]
@privateOmega thank you for pinging me, I reviewed your https://github.com/strongloop/loopback-filters/pull/26 and left some comments, PTAL.

**Comment by dhmlau** [comment]
not stale.  PR in review.
