### ISSUE TITLE
Errors not handled when raised in persist operation hook callback is invoked from updateAttributes function

### ISSUE THREAD

**Issue by nitro404** [strongloop/loopback-datasource-juggler#1530]
# Description/Steps to reproduce

When a `persist` operation hook is present in a model and `updateAttributes` is invoked and an error object is returned in the callback function, it is not handled and the instance is still written to the datasource.

# Link to reproduction sandbox

https://github.com/nitro404/persist-operation-hook-sandbox

# Expected result

An error should be output from the `test.js` boot script when running the API, but instead "No errors detected!" is printed.

# Additional information

I already have a fix in place with an additional unit test here: https://github.com/nitro404/loopback-datasource-juggler/tree/hotfix/persist-operation-hook-error-handling

**Comment by icezjy** [comment]
This is same as issue #1528. Thank you for the pull request to resolve this issue.

**Comment by aekevinscroggins** [comment]
No problem! Definitely a big issue for our project as well. Hopefully this gets merged soon!

**Comment by nitro404** [comment]
No problem! Definitely a big issue for our project as well. Hopefully this gets merged soon!
