### ISSUE TITLE
Yarn install throws error with 2.56.0 at current node LTS version

### ISSUE THREAD

**Issue by yshing** [strongloop/loopback-datasource-juggler#1544]
# Description/Steps to reproduce

When installing the latest release of using `yarn` (1.2.1 or 1.3.1)
It would throw that. (install using npm works fine.)
`error loopback-datasource-juggler@2.56.0: The engine "node" is incompatible with this module. Expected version ">= 4 <= 6".
`
Then current `engine` setting of main Loopback 2.x branch is `"node": ">=4.0.0"`.
It expected that this package would be using the same setting and should not throw Error when installing using `yarn`.
Loopback 2.x engins states     "node": ">=4.0.0"

# Link to reproduction sandbox

# Expected result
Should not get Error when installing 2.x branch using `yarn` having node in LTS version.

**Comment by ambrt** [comment]
Bumping since Git isn't removing 'stale' after thumb up.

**Comment by Extarys** [comment]
Ouch, wanted to switch from Restify to Loopback, harsh start. Any idea what I should do? The project is barely started. (Is loopback 4 will be ready soon? Maybe I could try that)

**Comment by joe-at-startupmedia** [comment]
Try this with the latest version of yarn. Place the following in your package.json file
```
  "resolutions": {
    "loopback-datasource-juggler": "2.54.1"
  },
```
This will make sure any requirement within nested dependencies resolve to this version (which doesn't enforce <= 6)
