### ISSUE TITLE
_normalize(query, options) converts the OBJECT cond for a non-loopack operator to STRING

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-datasource-juggler#1550]
### Note
please note the bug only happens when querying with a property defined in `model.json`
### Reproduce 

git clone the sandbox app from 
https://github.com/jannyHou/loopback-sandbox/tree/juggler/normalize-query

`npm i`
`node .`
open explorer, try `GET/Notes` 
  - filter: `{"where": {"title": {"some_operator": false}}}`

What happens in function `lib/dao.js/DataAccessObject.find()` is:

```js
try {
    this._normalize(query, options);
  } catch (err) {
    process.nextTick(function() {
      cb(err);
    });
    return cb.promise;
  }

  this.applyScope(query);

```

the code `this._normalize(query, options);` converts the query to `{"where": {"title": "[object Object]"}}`

But when querying with a property NOT defined in `model.json`, it preservers as an object instead of getting converted to a string.

**Comment by dhmlau** [comment]
@jannyHou , is it still an interrupt?
