### ISSUE TITLE
test connection of memory connector fails in apic designer

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-datasource-juggler#1551]
Reproduce:

- Create a memory db in apic designer
- When specify a file path, save it and run test connection, it fails.

- Problem: workspace method `DatasourceDefinition.prototype.ping` calls juggler method `DataSource.prototype.connect` first, then calls `DataSource.prototype.ping` without waiting for function connect's callback.

- Workaround: add function `Memory.prototype.ping` in memory connector:
  ```js
   Memory.prototype.ping = function(callback) {
    this.connect(callback);
  };
  ```
  but it is not the real fix.

**Comment by jannyHou** [comment]
cc @kjdelisle 
created this new issue for fix of https://github.com/strongloop-internal/scrum-apex/issues/337

**Comment by dhmlau** [comment]
@jannyHou , is this already identified as a bug?  If so, I'd like to mark it as `bug` and move to at least to `Needs Priority` column.  Thanks.

**Comment by jannyHou** [comment]
@dhmlau yep it's confirmed as a bug. Labelled and moved accordingly :)
