### ISSUE TITLE
Patients.prototype.__get__physicans() in doesnt work in a hasManyThrough relation!

### ISSUE THREAD

**Issue by alistarshady** [strongloop/loopback-datasource-juggler#1553]
hello loopback community ,
1-
make a has many through relation like the 3.0 docs. Patient, Physican and Appointment Models. 2 has many relations with through set. 2 belongs to relation from Appointment. 
 _i usually answer no to nest remoting and yes to disable incluce._
2-
from explorer one post to patients, one post to physicans. one appointment with put from /patients/{id}/patients/rel/{fk}.
3- the problem
cant get the appointment with GET to /Physicans/{id}/patients which uses the Patients.prototype.__get__physicans() internally.
## more detail: 
the problem doesnt exist with hasAndBelongsToMany as i explain below:
i wanted to make a shopping cart. first i had some products and customers. then made the cart like this: cutomers hasAndBelongsToMany products. which automatically make a customerProduct collection on the db. (i change the name of CustomerProduct table to cart with throughTable [this isnt mentioned in doc and i looked up from sourced]). i want to get each customer cart so i used the GET /customer/{id}/cart/ successfully. even i wrote a afterRemote hook to do some manipulation. at some point i thought maybe i will need the cart model itself. so i tried to use hasManyThough instead which didnt work.

**Comment by alistarshady** [comment]
i think the problem was with disableInclude.
can anyone please explain how __get__ is relation with disableInclude in this case?

**Comment by kjdelisle** [comment]
@alistarshady Thanks for opening an issue about this potential problem.

Would you be able to create a reproduction sandbox (as per the issue template) to better illustrate w hat you're encountering, and give us a link to that repository? We get _a lot_ of issues, and attempting to divine what people are running into can be very time consuming.
