### ISSUE TITLE
Model.validate does not forward attr and conf to the callback

### ISSUE THREAD

**Issue by tylkomat** [strongloop/loopback-datasource-juggler#1556]
# Description/Steps to reproduce

Since the attribute is not forwarded to the custom validator there has to be one validator for each property although the validation might be the same. Custom validators should be as flexible as the build-in validators.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by kjdelisle** [comment]
@tylkomat I think I understand what you're asking for, but just to make sure, would you be able to give us a UX sample detailing what you're hoping to see here in terms of the forwarding to the callback?

I'm asking because I want to see if what you're proposing constitutes a breaking change from the API's perspective.

**Comment by tylkomat** [comment]
This is the code directly from `validations.js`

```js
function validateCustom(attr, conf, err, options, done) {
  if (typeof options === 'function') {
    done = options;
    options = {};
  }
  conf.customValidator.call(this, err, done);
}
```

As you can see attr and conf are not forwarded to the `call`. These could be forwarded by appending to the call function like this: `conf.customValidator.call(this, err, done, attr, conf);` which would not result in any breaking changes, but would also not follow the general convention for callbacks, which is any way not followed in async case where usually the `error` should be given as first parameter to the `done` function. For example to achieve the same behaviour like the `validateLength` validator with different error messages I have to put the same configuration into the `validate` function and my custom validator function. 
For example:

```js
User.validatesLengthOf('password', {min: 7, message: {min: 'too weak'}});
```

Is something like this when one wants to achieve the same behaviour:

```js
function myLengthValidator(attr, conf) {
  return function(err) {
    ...
  };
}
const config = {min: 7, message: {min: 'too weak'}};
User.validate('password', myLengthValidator('password', config), config);
```

While it should be like this (to not break anything or another order of the parameters):

```js
function myLengthValidator(err, done, attr, conf) {
  ...
}
const config = {min: 7, message: {min: 'too weak'}};
User.validate('password', myLengthValidator, config);
```
