### ISSUE TITLE
Multiple operators on one field are skipped and only one applied

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-datasource-juggler#1559]
# Description/Steps to reproduce

When querying on a model using a composite filter on a single property *(such as **gte**, and **lte**)*, only one of the operators is applied - sent to database.
**example:**
```js
Model.find({
  where: {
    timestamp: {
      gte: '2018-02-13T08:52:30.893Z',
      lte: '2018-02-15T08:52:30.893Z'
    }
  }
})
```
end up sending to database only one of the operators on the field *(in this case the **gte** operator)*

This is a bug in the **_coerce** function

# Expected result

Both operators should be sent for the property object

# Additional information
**Related Issues:**
- https://github.com/strongloop/loopback-connector-mongodb/issues/176

linux x64 9.5.0
loopback-datasource-juggler@3.15.4 /home/mitsos/Documents/Projects/loopback-datasource-juggler
├── loopback-connector@4.4.0

**Comment by itsnotme01** [comment]
Hello, I don't know if it could help someone but one workaround is to use the 'and' operator instead, for example:

Model.find({
  where: { and: [ { timestamp : { gte: '2018-02-13T08:52:30.893Z' }},
                          { timestamp : { lte: '2018-02-15T08:52:30.893Z' }} ]
  }
})

PS: I tried it with the arangodb connector

**Comment by b-admike** [comment]
@mitsos1os as @itsnotme01 stated, I think that is the purpose of the `and` operator which enforces both the conditions specified to build a composite filter. What do you think?
