### ISSUE TITLE
Unable to filter related models by id when using a hasManyThrough relationship

### ISSUE THREAD

**Issue by frankorama** [strongloop/loopback-datasource-juggler#1569]
# Description/Steps to reproduce
BUG:

I have 2 models:  "Document" and "User", related through a model "DocumentResponsible" such that

**Document.json**
```
{
  "name": "Document",
  "base":  PersistedModel",
  ...
  "relations":[
    "responsibles":{
      "type": "hasMany",
      "model": "User",
      "foreignKey":"documentId",
      "through": "DocumentResponsible"
    },
  ],
}
```
**DocumentResponsible.json**
```
{
  "name": "DocumentResponsible",
  "base": "PersistedModel",
  "relations": {
    "document": {
      "type": "belongsTo",
      "model": "Document",
      "foreignKey": "documentId"
    },
    "user": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "userId"
    }
  }
}
```

I have a document with id = 1, and 2 users associated with the document.  Users 2, and 3

I run the following code:
```
const filter = {
  include:{
    relation: 'responsibles',
    scope:{
      where: {id: 2}
    }
  }
}
Document.findById(1, filter, (err, doc)=>{
  if(err) return callback(err);
  const responsibles = doc.responsibles();
});
```

# Expected result
I expect my `responsibles` variable to be an array with a single value:  user with id=2
```
console.log(responsibles.length) // 1
```
# Actual result
The `responsibles` array contains the 2 users associated to the document.  The filter was not executed.  Instead all the related users were returned.
```
console.log(responsibles.length) // 2
```
# Additional information

I tracked down the problem to `include.js` in the loopback-datasource-juggler.  Specifically the code in the `throughFetchHandler` function:
```
// before this code is reached
// filter.where.id = 2

var modelToIdName = idName(relation.modelTo);
filter.where[modelToIdName] = {
  inq: uniq(targetIds),
};

// after code is reached
// filter.where.id.inq:[2,3]
```

There is no verification performed to check if the `modelToIdName` property is already being used in the where clause.  If there is another way to filter by id using the include clause, please advise.

# Suggested fix
```
var modelToIdName = idName(relation.modelTo);
if(filter.where[modelToIdName]){
  filter.where.and = [
    {[modelToIdName]: {inq: uniq(targetIds)}},
    {[modelToIdName]: filter.where[modelToIdName]}
  ]
  delete filter.where[modelToIdName]
} else {
   filter.where[modelToIdName] = {
     inq: uniq(targetIds),
   };
}
```

loopback: v2.38.3
loopback-datasource-juggler: v2.54.1

**Comment by zbarbuto** [comment]
```
    scope:{
      were: {id: 2}
    }
```

You have misspelled where

**Comment by frankorama** [comment]
Good catch.  Sadly it's just a typo in the bug.  My code has "where" spelled correctly.  The bug is still relevant. :(

**Comment by zbarbuto** [comment]
As far as another way goes:  
You should be able to perform this as follows:

```
const document = await Document.findById(1);
const responsibilities = await document.responsibilities({ where: { id: 2 } });
```

Under the hood loopback does effectively the same thing.

**Comment by zbarbuto** [comment]
Having said that, I do like your suggested fix so feel free to make a PR for it.
