### ISSUE TITLE
normalize method modifies dates on between operator

### ISSUE THREAD

**Issue by victorherraiz** [strongloop/loopback-datasource-juggler#1577]
# Description/Steps to reproduce

Juggler version: 2.56.0
Loopback version:  2.39.2

When call to `Model.find` with the following where:

```js

{
  "where": {
	"createdAt": {
	      "between": [
                 new Date("2018-04-27T00:00:00.000Z"), 
                 new Date("2018-04-27T23:59:59.999Z")
               ]
	  }
    }
}
```

The dates get modified (i.e. they become current dates) before executing the query at normalize method.

# Expected result

Do not modify user parameters.

**Comment by jannyHou** [comment]
Hi @victorherraiz I am trying to reproduce your error, can you post the model definition file here? It includes the type for property `createdAt`, thanks

**Comment by jannyHou** [comment]
@victorherraiz I haven't debug the juggler's code, while when test with an local app, `Model.find` with your filter works well:

### The sample boot file

```js
'use strict';

module.exports = function sample(server, done) {
  var filter = {
    where: {
      createdAt: {
        between: [
          new Date('2018-06-06T00:00:00.000Z'),
          new Date('2018-06-06T23:59:59.999Z'),
        ],
      },
    },
  };
  var Note = server.models.Note;
  Note.create({title: 'sample', createdAt: new Date()}, function(err, n) {
    console.log(`${n.createdAt} get created`);
    Note.find(filter, function(err, r) {
      console.log(r);
    });
    done();
  });
};

```

### The model definition file

```js
{
  "name": "Note",
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "content": {
      "type": "string"
    },
    "createdAt": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

```

### printed result

```
Wed Jun 06 2018 15:53:29 GMT-0400 (EDT) get created
[ { title: 'sample', createdAt: 2018-06-06T19:53:29.586Z, id: 1 } ]
```

### dependency version

```
jannyhous-mbp:normalize jannyhou$ npm ls --depth=0
normalize@1.0.0 /Users/jannyhou/lb2/normalize
├── compression@1.7.2
├── cors@2.8.4
├── eslint@3.19.0
├── eslint-config-loopback@8.0.0
├── helmet@3.12.1
├── loopback@2.39.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@2.7.0
├── loopback-datasource-juggler@2.56.0
├── nsp@2.8.1
├── serve-favicon@2.5.0
└── strong-error-handler@2.3.2
```

**Comment by victorherraiz** [comment]
We will give you the model definition today.

In your example, you use que current date. If you use a past day, normalize method will change it to the actual date. At least in the version we use (latest of LTS)

**Comment by murcialito** [comment]
Please find below the model definition

```json
{
  "name": "Payment",
  "plural": "payments",
  "base": "Model",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "errors": [
    {
      "code": 400,
      "message": "Bad Request",
      "responseModel": "Error"
    },
    {
      "code": 422,
      "message": "Validation Error",
      "responseModel": "Error"
    },
    {
      "code": 404,
      "message": "Resource does not exist",
      "responseModel": "Error"
    },
    {
      "code": 401,
      "message": "Not Authorized",
      "responseModel": "Error"
    },
    {
      "code": 500,
      "message": "Internal Server Error",
      "responseModel": "Error"
    }
  ],
  "properties": {
    "state": {
      "type": "string",
      "required": true
    },
    "last_modified": {
      "type": "string",
      "required": true
    },
    "contract": {
      "type": "object",
      "required": true
    },
    "results": {
      "type": "object",
      "required": false
    },
    "additional_info": {
      "type": "object",
      "required": true
    },
    "createdAt": {
      "type": "date",
      "required": false
    },
    "updatedAt": {
      "type": "date",
      "required": false
    },
    "user": {
      "type": "string",
      "required": false
    },
    "fnumber": {
      "type": "string",
      "required": false
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by dhmlau** [comment]
@jannyHou , could you please follow up? Thanks.

**Comment by jannyHou** [comment]
@victorherraiz Sorry I am confused 
> In your example, you use que current date. If you use a past day, normalize method will change it to the actual date. At least in the version we use (latest of LTS)

What do you mean by "current date" and "past day"? Can you give me an example?

**Comment by jannyHou** [comment]
@victorherraiz unfortunately I still couldn't not reproduce the problem. I updated my app in https://github.com/jannyHou/loopback-sandbox/tree/normalize

- see the [sample boot file](https://github.com/jannyHou/loopback-sandbox/blob/normalize/server/boot/sample.js)
  - created an example with date `new Date('2017-03-27T10:10:00.000Z')`
  - the filter is exactly what you post [above](https://github.com/strongloop/loopback-datasource-juggler/issues/1577#issuecomment-401617316)

- added a console.log in the loopback-datasource-juggler, see [code](https://github.com/jannyHou/loopback-sandbox/blob/normalize/node_modules/loopback-datasource-juggler/lib/dao.js#L2017)

- you can run the app with `node .`, everything works fine.

Feel free to fork my example and upload the code that reproduces your error...
