### ISSUE TITLE
{include: true} or {include: 1} throws TypeError

### ISSUE THREAD

**Issue by spurreiter** [strongloop/loopback-datasource-juggler#1580]
# Description/Steps to reproduce

On `{include: true}` or `{include: 1}` the lib crashes with 
"TypeError: includes.forEach is not a function".

# Link to reproduction sandbox

# Expected result

On `{include: true}` or `{include: 1}` the lib shall not throw. In such cases an empty array shall be returned.

# Additional information

**Comment by bajtos** [comment]
Published the fix in `loopback-datasource-juggler@2.59.2` and `loopback-datasource-juggler@3.29.2`
