### ISSUE TITLE
LazyConnect MySQL Datasources Never Connect after update to v3.21.0

### ISSUE THREAD

**Issue by thirteen-eleven** [strongloop/loopback-datasource-juggler#1592]
# Description/Steps to reproduce

1. Specify "lazyConnect": true in datasources.json for the given datasource.
1. Programmatically connect to this datasource after boot using:
`app.datasources.MyDatasource.connector.connect(function(){
   console.log("Connected to MyDatasource.");
});
`
1. After connecting seems to succeed, inspect the datasource's connector.dataSource.connected field and you will see that it is false.
1. Any attempts to execute native SQL against mysql will wait indefinitely.

# Workaround

We were able to get this to work after rolling back loopback-datasource-juggler to 3.20.2.

**Comment by raymondfeng** [comment]
You should use `app.dataSources.MyDatasource.connect`

**Comment by jreeme** [comment]
This issue also breaks lazyConnect of postgres connector. I'm using the DataSource.ping() method so I can't change the way I connect. Moving back to 3.20.2 fixes my problem.

**Comment by jannyHou** [comment]
hi @thirteen-eleven @jreeme I tried @raymondfeng 's suggestion in comment, the connection establishes successfully.

My bootscript:

```js
'use strict';

module.exports = function connectToDS(server, done) {
  var mysqlDs = server.datasources.mysqlds;
  // please note you should call function `mysqlDs.connect`, NOT `mysqlDs.connector.connect`
  mysqlDs.connect(function() {
    console.log('Connected to MyDatasource.');
    console.log('connected: ', mysqlDs.connector.dataSource.connected);
    mysqlDs.automigrate(done);
  });
};
```

datasources.json

```js
"mysqlds": {
    "host": "localhost",
    "port": 3306,
    "url": "",
    "database": "dateTest",
    "password": "",
    "name": "mysqlds",
    "user": "root",
    "connector": "mysql",
    "lazyConnect": true
  }
```

dependency version

```js
├─┬ loopback-connector-mysql@2.4.1
│ ├── async@0.9.2
│ ├── debug@2.6.9 deduped
│ ├── loopback-connector@2.7.1
│ ├── mysql@2.16.0
│ └── strong-globalize@2.10.0
├─┬ loopback-datasource-juggler@3.23.0
```

**Comment by jannyHou** [comment]
I am closing this issue after verified the solution works, see comment above https://github.com/strongloop/loopback-datasource-juggler/issues/1592#issuecomment-415090642

Feel free to reopen it if you still run into the problem.
