### ISSUE TITLE
EnableGeoIndexing not working?

### ISSUE THREAD

**Issue by F3L1X79** [strongloop/loopback-datasource-juggler#1610]
Hello to all the Loopback team!
Actually I am in trouble with the **EnableGeoIndexing** attribute.
I know the problem has been discussed a lot last year, but it seems it is not resolved yet, or am I doing something wrong?

Here's my problem:
I have created an Entity Place with an attribute **geopoint** of the standard type **Loopback Geopoint**.

Here is the standard query I use to retrieve my Places:
`Place.find({where: {geopoint: {near: userGeopoint, maxDistance: maxDistance, unit: 'kilometers'}}}, function (err, places) { ... }`

All was quite fine, except the database is growing:
Recently it has grown from 20.000 entries to 80.000 entries... and the query is now approximately **9 sec** to finish!

So I tried to add the attribute 
`"enableGeoIndexing": true`
in **datasource.json** of my **mongo Ds** connector.

Then I ran in two major problems:
+ First one, is that I get this error: 
```
/Users/ovianet_devweb/bandstiger_loopback/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^
TypeError: Cannot read property '1' of undefined
    at MongoDB.fromDatabase (/Users/ovianet_devweb/bandstiger_loopback/node_modules/loopback-connector-mongodb/lib/mongodb.js:301:33)
```
when I run a non-geolocated query...

+ Second is that I get this error:
```
MongoError: error processing query: ns=bandtiger_prod.PlaceTree: GEONEAR  field=geopoint maxdist=10000 isNearSphere=0
Sort: {}
Proj: {}
 planner returned error: unable to find index for $geoNear query
    at queryCallback (/Users/ovianet_devweb/bandstiger_loopback/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/cursor.js:247:25)
```
when I run the geolocated query.

So I tried to add **2dsphere indexes** in my **place.json** file:
```
 "indexes": {
    "geopoint_2dsphere": {
      "geopoint": "2dsphere"
    }
  },
```
Then, I run an autoupgrade script in my **boot folder**:
```
'use strict';
var Promise = require('bluebird');

module.exports = function (server) {

    Promise.each(server.models(), function (model) {

        if (model.dataSource) {
            var autoupdate = Promise.promisify(model.dataSource.autoupdate);
            if (autoupdate) {
                return autoupdate.call(model.dataSource, model.modelName);
            }
        }
    });
};
```
but the error persists...

For debug help, here is what I can see in my mongodb log after Loopback restart:
`I INDEX    [conn17] build index on: bandtiger_prod.Place properties: { v: 1, key: { geopoint: "2dsphere" }, name: "geopoint_2dsphere", ns: "bandtiger_prod.Place", 2dsphereIndexVersion: 3 }`

but it's strange because in the mongo shell when I run:
```
 db.Place.getIndexes();
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "bandtiger_prod.Place"
	}
]
> 
```
I can't see the indexes created.

I'm sorry, I know it's a too long post, but I think I really need a hand on what's need to be done. I've been strugling on this for days...

**Comment by F3L1X79** [comment]
Hello,

Here is some feedback about theses issues!

The first error is due to a forgotten part of code I think:
```
/Users/ovianet_devweb/bandstiger_loopback/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^
TypeError: Cannot read property '1' of undefined
    at MongoDB.fromDatabase (/Users/ovianet_devweb/bandstiger_loopback/node_modules/loopback-connector-mongodb/lib/mongodb.js:301:33
```
Because after adding  `&& data[p].coordinates` in loopback-connector-mongodb/lib/mongodb.js everything is working fine:
```
} else if (data[p] && prop && prop.type && prop.type.name === 'GeoPoint' &&
        this.settings.enableGeoIndexing === true && data[p].coordinates) {
      data[p] = {
        lat: data[p].coordinates[1],
        lng: data[p].coordinates[0]
      };
    }
```

For the second error, I realised that the indexes weren't created because mongo needs to get an object with { 'lng' : xxx, 'lat': yyy } whereas loopback have the GeoPoint attributes like { 'lat' : xxx, 'lng': yyy } and only this!!!
Here is an example of the error I was getting:
```
"errmsg" : "Can't extract geo keys: { _id: ObjectId('59c27a7d2128388ce9d4cd8b'), created: 1505917563, name: \"white restaurant tahiti\", geopoint: { lat: -17.527158, lng: -149.546147 },  id: ObjectId('59c27a7d2128388ce9d4cd8b')}  can't project geometry into spherical CRS: { lat: -17.527158, lng: -149.546147 }",
	"code" : 16755
```

My workaround was to add a Loopback's remote method to create a new attribute with the lng before the lat...:
```
Place.createMongoGeoloc = function (cb) {
        Place.find(function (err, places) {
            var count = 0;
            places.forEach(function (place) {
                var placeJSON = place.toJSON();
                if (!placeJSON.location && placeJSON.geopoint && placeJSON.geopoint.lat && placeJSON.geopoint.lng) {
                    count++;
                    place.updateAttributes({
                        geomongo: {
                            lng: placeJSON.geopoint.lng,
                            lat: placeJSON.geopoint.lat
                        }
                    });
                }
            });
            cb(err, count);
        });
    };

    Place.remoteMethod('createMongoGeoloc', {
        description: 'Update the Geolocation field',
        returns: {arg: 'count', type: 'number'},
        http: {verb: 'put'}
    });
```

After that I added new indexes in my Place.json:
```
 "indexes": {
    "geomongo_2dsphere": {
      "geomongo": "2dsphere"
    }
  }
```

And everything was working fine for:
`Place.find({where: {geomongo: {near: userGeopoint, maxDistance: maxDistance, unit: 'kilometers'}}}, function (err, places) { ... }`
in 0.02s instead of 9 sec!

**Comment by dhmlau** [comment]
@b-admike , I know you were looking at Geopoint a while back.  Could you please help?  There's another ticket in the mongodb connector as well.  Thanks!

**Comment by b-admike** [comment]
@F3L1X79 This issue should have been addressed by https://github.com/strongloop/loopback-connector-mongodb/pull/522. Can you please get the latest version of the connector and try again?

**Comment by jamesjjk** [comment]
@b-admike strongloop/loopback-connector-mongodb#522 does not address the issue described.  

When you persist a { lat, lng } object, MongoDB is very specific about the order of the properties in the object being:
```
If specifying latitude and longitude coordinates, the first field, regardless of the field name, must contains the longitude value and the second field, the latitude value ; i.e.
```
https://docs.mongodb.com/manual/geospatial-queries/

The current version is not dealing with this issue, in fact it would be better to transform to a JsonGeo Point or even an array [lng, lat]

In particular when enabling indexing using EnableGeoIndexing the order must be long lat. Ergo MongoDb will throw errors.
