### ISSUE TITLE
include filter does not work if foreignKey in hasManyThrough relation is hidden

### ISSUE THREAD

**Issue by ketansp** [strongloop/loopback-datasource-juggler#1648]
# Description
After 3.25.1 / 3.25.0 update, the include filter on hasManyThrough relations has stopped working. The point to note here is that all foreign keys in my project are hidden. I have started getting this warning in logs. `Potential security alert: hidden/protected properties ["somefields"] are used in query.`

# Expected result
The relation should work even if the foreign key hidden

# Steps to reproduce
Consider three models `AppUser`,` AppRole` and `AppUserRoleMapping` with below definitions.
app-user.json
```
{
  "name": "AppUser",
  "plural": "AppUsers",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "String",
      "required": true
    },
    "email": {
      "type": "String",
      "required": false
    }
  },
  "validations": [],
  "relations": {
    "appRoles": {
      "type": "hasMany",
      "model": "AppRole",
      "through": "AppUserRoleMapping",
      "foreignKey": "fk_id_user",
      "keyThrough": "fk_id_role"
    }
  },
  "acls": [],
  "methods": {},
  "hidden": []
}
```
app-role.json
```
{
  "name": "AppRole",
  "plural": "AppRoles",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "String",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
app-user-role-mapping.json
```
{
  "name": "AppUserRoleMapping",
  "plural": "AppUserRoleMappings",
  "base": "PersistedModel",
  "indexes": {},
  "properties": {},
  "validations": [],
  "relations": {
    "appUser": {
      "type": "belongsTo",
      "model": "AppUser",
      "foreignKey": "fk_id_user"
    },
    "appRole": {
      "type": "belongsTo",
      "model": "AppRole",
      "foreignKey": "fk_id_role"
    }
  },
  "acls": [],
  "methods": {},
  "hidden": [
    "fk_id_user",
    "fk_id_role"
  ]
}
```
Now, the data is present in all three tables. Before 3.25.0 / 3.25.1, when I executed `AppUser.find({include : 'appRoles'})`, it used to give me `appRoles` array populated with proper values.
After the update, I see this warning ```Potential security alert: hidden/protected properties ["fk_id_user"] are used in query.``` and the query returns empty `appRoles` list.

**Comment by ketansp** [comment]
PS. I figured this is an issue with 3.25.0 / 3.25.1 update because the code started working as expected once I rolled it back to previous version.

**Comment by raymondfeng** [comment]
See #1649
