### ISSUE TITLE
Saving password as blank to mysql database 

### ISSUE THREAD

**Issue by evanzombie** [strongloop/loopback-datasource-juggler#1650]
# Description/Steps to reproduce

I'm using version 3.25.0 and when I register for a new user in Loopback Explorer the password is saved as blank. I reinstalled to loopback-datasource-juggler@3.24.0 and it's working correctly.
# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by raymondfeng** [comment]
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/1645
