### ISSUE TITLE
Regression in multi-level related queries

### ISSUE THREAD

**Issue by ashearer** [strongloop/loopback-datasource-juggler#1651]
The recent commit to prevent "deeply nested or circular" queries breaks existing well-behaved apps that chain more than 3 relationships in a programmatic query.

The new code, in addition to checking whether the traverse package marks the query `circular`, also checks the number of levels used to represent the query against an arbitrary limit of 10. Each chained relationship in the query consumes 2 or 3 levels in the object representation, so the 4th relationship can fail.

There's a new field in the "options" parameter to change the maximum depth to something other than 10, but it's not clear how to set it or whether it's possible to set, since the existing callers don't appear to pass it through.

At a minimum, the limit should be raised (for example, to allow at least 10 chained relationships instead of 3). Even better, the arbitrary depth limit should be removed entirely, since circularity is the important criterion.

The regression occurred in commit 0ce3f4ead9914951aec275c1a4829d2bf5afb56d

# Description/Steps to reproduce

Made-up example:

```
const storeReport = models.Store.findById(id, {
  include: [
    {relation: "retailChain"},
    {relation: "receivables",
     scope: {
       include: [
         {relation: "brand"},
         {
           relation: "sender",
           scope: {
             include: {
               relation: "region",
               scope: [
                 {
                   include: {relation: "country"}
                 }
               ]
             }
           }
         }
       ]
     }
   }
 ]
});
```
# Expected result
Success

# Actual result
exception `The query object is too deep or circular`

# Additional information

darwin x64 8.11.3
```
├── loopback@3.23.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.3.1
├── loopback-connector-mysql@5.3.1
├── loopback-console@1.1.0
```

**Comment by dhmlau** [comment]
@raymondfeng, could you PTAL? Thanks.

**Comment by raymondfeng** [comment]
@ashearer What do you think about https://github.com/strongloop/loopback-datasource-juggler/commit/0d84b55f908e46f21eb921fd00667fecd8020ff0?

**Comment by raymondfeng** [comment]
Please use 3.26.0/4.2.0 and follow instructions at https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Querying-data.md#sanitizing-filter-objects.

**Comment by ashearer** [comment]
Thanks for the commit! This makes it possible to work around the problem.

I'm concerned that it doesn't go far enough to fix the root of the issue, though. Loopback performs well when chaining many relationships, but existing queries that do so have been broken by a point release, and remain broken until library users hunt down an esoteric setting. From now on, they need to keep that setting in mind when writing queries in case they chain one too many.

This might be a justifiable change in a major-version release if there was a compelling benefit, but even though the documentation put this setting at the end of a section on security, it doesn't explain how there's a security benefit to putting this limit on programmatic ORM queries (no end-user input is even involved). It just says that a deep query might be too slow. If there has to be a limit, it should be grounded in some evidence-based tipping point for “too slow”. (The limit started out at 10, corresponding to about 3 chained relationships, but was changed to 12 in response to this ticket, perhaps to make my example of 10 levels pass.) If the limit is so low that valid queries are in danger of tripping it, it should also be based on a more meaningful property of the query than the maximum depth of the JSON used to represent it, like the number of chained relationships, or the number of conditions. Relationship lookups could be represented with either 2 or 3 levels of JSON, and the choice doesn't affect the speed of the query, but one could be blocked and not the other. There could also be many relationships on the same level, or many conditions, each of which could make the query much slower than one more chained relationship, but those aren't limited.

If denial of service from queries over the REST interface is a concern, ideally a separate function would be available applying only to those queries, not affecting ORM queries that are embedded in the source code. Servers that don't rely on or allow arbitrary queries over the REST interface therefore wouldn't have to worry about the new setting.

Failing that, it would be preferable to have an "unlimited" setting available (perhaps represented by null or 0), and use it as the default, restoring the original behavior. Then a maximum depth could optionally be set by the library user, and starter files for new projects could include a finite default, which would at least put the setting explicitly in front of new library users without affecting existing projects.
