### ISSUE TITLE
MaxDepth

### ISSUE THREAD

**Issue by sandeepjain98** [strongloop/loopback-datasource-juggler#1653]
https://github.com/strongloop/loopback-datasource-juggler/blob/d3efc40a370c2ff2a83c6458c962f2a66ffabe28/lib/utils.js#L326

1. How do we configure maxDepth 
2. The below query is failing as it shows level=11. Is the level number correct for below query. Please note we are using MySql & Mongo.
Query : 
{
  "where": {
    "name": "name1",
    "country": "country1"
  },
  "fields": [
    "id"
  ],
  "include": {
    "relation": "levels",
    "scope": {
      "fields": [
        "id",
        "name"
      ],
      "where": {
        "name": "Root"
      },
      "include": {
        "relation": "nodes",
        "scope": {
          "fields": [
            "id",
            "guid",
            "name",
            "parentId",
            "code",
            "number"
          ],
          "where": {
            "number": 0
          },
          "include": [
            {
              "relation": "child",
              "scope": {
                "fields": [
                  "guid",
                  "name",
                  "id",
                  "levelId",
                  "code",
                  "number"
                ],
                "order": "id ASC",
                "skip": 0,
                "limit": 30,
                "include": {
                  "relation": "level",
                  "scope": {
                    "fields": [
                      "name"
                    ]
                  }
                }
              }
            },
            {
              "relation": "parent",
              "scope": {
                "fields": [
                  "guid",
                  "name",
                  "id",
                  "levelId",
                  "code",
                  "number"
                ],
                "include": {
                  "relation": "level",
                  "scope": {
                    "fields": [
                      "name"
                    ]
                  }
                }
              }
            }
          ]
        }
      }
    }
  },
  "limit": 1,
  "offset": 0,
  "skip": 0
}

**Comment by raymondfeng** [comment]
Please use 3.26.0/4.2.0 and follow instructions at https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Querying-data.md#sanitizing-filter-objects

**Comment by sandeepjain98** [comment]
Thanks will try the latest one with maxDepthConfigurations
