### ISSUE TITLE
In 3.28 version prohibitHiddenPropertiesInQuery is ignored if set in a model

### ISSUE THREAD

**Issue by FedericoMassaioli** [strongloop/loopback-datasource-juggler#1686]
# Description/Steps to reproduce

I have a relation that is set up like this:

```
      myMainModel.hasOne(myTargetModel, {
        as: 'myRelation',
        foreignKey: 'protectedForeignKey',
        primaryKey: 'hiddenPrimaryKey'
      });
```
`hiddenPrimaryKey` property is hidden in `myMainModel`.
`protectedForeignKey` is listed among protected properties in `myTargetModel`.
The option `prohibitHiddenPropertiesInQuery` is set to `false` in `myTargetModel`. This is the only place in all the code where the `prohibitHiddenPropertiesInQuery` option is explicitly referred to.

# Expected result

With `loopback@3.23.2` and `loopback-datasource-juggler@3.26.0` everything works, the relation can be included without problems when the main model is queried.

With `loopback@3.24.0` and `loopback-datasource-juggler@3.28.0` every attempt to include the relation is ignored, and the alert:
```
Potential security alert: hidden/protected properties ["protectedForeignKey"] are used in query.
```
is emitted on the Node console, as if the ` "prohibitHiddenPropertiesInQuery": false` setting where absent from `myTargetModel` definition.

The relation can also be queried and included correctly if the ` "prohibitHiddenPropertiesInQuery": false` setting is moved to datasource definition, but this is not what you usually want.

# Additional information

See above for the affected version, the issue manifest itself on all tested hardware/OSes.

**Comment by raymondfeng** [comment]
@FedericoMassaioli How did you configure `prohibitHiddenPropertiesInQuery` for your model?

The feature is covered by the following test:
https://github.com/strongloop/loopback-datasource-juggler/blob/bd5fd07d270084f8cc3d0cce1470431708f9b72a/test/model-definition.test.js#L413

**Comment by FedericoMassaioli** [comment]
@raymondfeng In the model definition, at the same level of `properties` and `protected`, where it used to work until 3.28.

Where am I supposed to configure it?

**Comment by raymondfeng** [comment]
Something like the following in your model json file should do it:
```json
{
  "name": "Note",
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "content": {
      "type": "string"
    }
  },  
  "prohibitHiddenPropertiesInQuery": false
}

```

**Comment by raymondfeng** [comment]
Can you try `loopback@3.24.2`?

**Comment by FedericoMassaioli** [comment]
> Something like the following in your model json file should do it:
> 
> ```json
> {
>   "name": "Note",
>   "properties": {
>     "title": {
>       "type": "string",
>       "required": true
>     },
>     "content": {
>       "type": "string"
>     }
>   },  
>   "prohibitHiddenPropertiesInQuery": false
> }
> ```

This is exactly the configuration that I used to have and doesn't work anymore.

**Comment by FedericoMassaioli** [comment]
> Can you try `loopback@3.24.2`?

Yes, I hope to find some time tomorrow for that, I'll let you know ASAP.
Warmly thanks for your help.

**Comment by FedericoMassaioli** [comment]
> Can you try `loopback@3.24.2`?

I tried, but the problem persists, with `loopback-datasource-explorer@3.28.1` too.

I forgot to mention that `myTargetModel` is persistent but it's not public.

**Comment by rcmgleite-tweak** [comment]
Any updates on this?
