### ISSUE TITLE
mongodb aggregation

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback-datasource-juggler#1688]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@techaks , could you please provide some information on the question / issue that you have? Thanks.

**Comment by dhmlau** [comment]
Looks like you've created another issue.  Closing as duplicate of https://github.com/strongloop/loopback-connector-mongodb/issues/494.
