### ISSUE TITLE
URGENT - latest npm releases include .git files

### ISSUE THREAD

**Issue by regevbr** [strongloop/loopback-datasource-juggler#1708]
Latest npm releases (e.g. 2.59.0) includes .git files which causes npm install to fail with 
```bash
npm ERR! git ./node_modules/loopback-datasource-juggler: Appears to be a git repo or submodule.
npm ERR! git    ./node_modules/loopback-datasource-juggler
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```
When running `npm install` after the module was already installed...

**Comment by regevbr** [comment]
@bajtos can you please check this out? all my CI pipelines are failing due to this issue...
Thanks!

**Comment by jannyHou** [comment]
@regevbr looking.
> includes .git files

You mean the hidden `.git` folder? Could you post the full name of the file(s)?

**Comment by regevbr** [comment]
@jannyHou sure here it is:
```bash
regevbr@regevbr-virtual-machine:/tmp/a$ ll node_modules/loopback-datasource-juggler/.git
total 16
drwxr-xr-x 4 regevbr regevbr 4096 Apr  9 19:46 ./
drwxr-xr-x 9 regevbr regevbr 4096 Apr  9 19:46 ../
drwxr-xr-x 3 regevbr regevbr 4096 Apr  9 19:46 logs/
drwxr-xr-x 3 regevbr regevbr 4096 Apr  9 19:46 refs/
```

**Comment by foxindabox** [comment]
Experiencing the same issue.

**Comment by jannyHou** [comment]
Weird, the `/.git` folder is not on the 2.x branch, see https://github.com/strongloop/loopback-datasource-juggler/tree/2.x

**Comment by regevbr** [comment]
It doesn't matter. What matters is the contents of the directory where you
ran the npm publish command

**Comment by rajanmishra** [comment]
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by jannyHou** [comment]
released a new version 2.59.1 https://github.com/strongloop/loopback-datasource-juggler/commits/2.x

@regevbr @rajanmishra Could you try?

**Comment by jannyHou** [comment]
Make sure you remove or uninstall `loopback-datasouce-juggler` from `node_modules` then install the module again. Should be fixed. Feel free to reopen this issue if you still get the error.

**Comment by regevbr** [comment]
@jannyHou it is fixed! Thanks for the quick response!

**Comment by foxindabox** [comment]
@jannyHou The same changes are needed in 4.6.0
