### ISSUE TITLE
loopback-datasource-juggler EISGIT error when sync with package-lock.json

### ISSUE THREAD

**Issue by wayahead** [strongloop/loopback-datasource-juggler#1711]
After upgraded @loopback/repository to the latest version 1.4.0, the ESGIT error came out when sync with package-lock.json.

# Description/Steps to reproduce

Run the below steps:
1. npm update
2. npm i --package-lock

then:

npm ERR! path /home/wayahead/workspace/loopback/pinwheel/pinwheel/node_modules/loopback-datasource-juggler
npm ERR! code EISGIT
npm ERR! git /home/wayahead/workspace/loopback/pinwheel/pinwheel/node_modules/loopback-datasource-juggler: Appears to be a git repo or submodule.
npm ERR! git     /home/wayahead/workspace/loopback/pinwheel/pinwheel/node_modules/loopback-datasource-juggler
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wayahead/.npm/_logs/2019-04-09T23_57_40_760Z-debug.log
[2019-04-09T23_57_40_760Z-debug.log](https://github.com/strongloop/loopback-datasource-juggler/files/3061530/2019-04-09T23_57_40_760Z-debug.log)

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@wayahead, it has been fixed in the latest version of `loopback-datasource-juggler` (`loopback-datasource-juggler@2.59.1`).  Could you please update and try again?  Thanks! 

cc @jannyHou

**Comment by wayahead** [comment]
@dhmlau, I used the @loopback/repository1.4.0 with loopback-datasource-juggler 4.6.1. And I reproduced this issue after I got your feedback. Thanks.

**Comment by wayahead** [comment]
> 
> 
> @wayahead, it has been fixed in the latest version of `loopback-datasource-juggler` (`loopback-datasource-juggler@2.59.1`). Could you please update and try again? Thanks!
> 
> cc @jannyHou

@dhmlau, I used the @loopback/repository1.4.0 with loopback-datasource-juggler 4.6.1. And I reproduced this issue after I got your feedback. Thanks.

**Comment by foxindabox** [comment]
Experiencing the same issue

**Comment by foxindabox** [comment]
@jannyHou  Please put fixes in version 4.6.1 as well. This is breaking the builds.
