### ISSUE TITLE
[BUG] after running npm prune: code EISGIT

### ISSUE THREAD

**Issue by rachedanis** [strongloop/loopback-datasource-juggler#1715]
# Steps to reproduce

```
npm init 
npm i --save loopback-datasource-juggler@^3.0.0
npm prune
```
# Result

```
npm ERR! path node_modules/loopback-datasource-juggler
npm ERR! code EISGIT
npm ERR! git node_modules/loopback-datasource-juggler: Appears to be a git repo or submodule.
npm ERR! git     node_modules/loopback-datasource-juggler
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by dhmlau** [comment]
@rachedanis, we've released a new version of juggler `loopback-datasource-juggler@3.29.1` that fixes this issue.  Please update your dependencies.  Thanks!

**Comment by rachedanis** [comment]
Hi @dhmlau, Actually I started having this issue since the 3.29.1

**Comment by rachedanis** [comment]
PS : I'm not directely using this dependency ; I'm using loopback-connector-postresql@3.5.1 which supports 3.x.
