### ISSUE TITLE
Coerce deeply nested model properties with primitive data types

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-datasource-juggler#1716]
# Description/Steps to reproduce

As a follow up to #1702, we need to handle the use cases described in https://github.com/strongloop/loopback-datasource-juggler/pull/1702#discussion_r268159610 for coercing deeply nested primitive types on model properties during instantiation.

**Comment by dhmlau** [comment]
@b-admike , With PR #1702 has landed, is this issue done?
