### ISSUE TITLE
EmbedsMany delete methods fail to pass options

### ISSUE THREAD

**Issue by bmatson** [strongloop/loopback-datasource-juggler#1724]
# Description/Steps to reproduce

We use the options inside of our loopback app to enforce client tenancy.  Since this is a security feature we require the options and the associated security token to be passed through to all methods, and fail if it is not passed.  Since the options also contain transaction information, this can cause concurrency problems as well for people who are doing transactions.

In the EmbedsMany.prototype.destroyById and destroyAll, the calls to modelInstance.updateAttribute or modelInstance.setAttribute fail to pass through the incoming options.

We're using the 3.x version of the loopback-datasource-juggler, however the problem exists in master as well.  

PR coming shortly against master with fix.

**Comment by dhmlau** [comment]
PRs for both master and 3.x have landed. Closing as resolved. @bmatson, thanks again for your contribution!
