### ISSUE TITLE
Using dot notation / mongo extended operators return unexpected result for update operations

### ISSUE THREAD

**Issue by Boxonical** [strongloop/loopback-datasource-juggler#1731]
# Description

Update operations will return outdated & polluted result when dot notation / mongo extended operators is used.

Tested: `updateAttributes` & `upsertWithWhere`

Not Tested: `updateAll` & `upsert`

Findings:
1. `updateAttributes` [returned instance is not rebuilt by default](https://github.com/strongloop/loopback-datasource-juggler/blob/df4366eb3114a7e16673ce1b4d29044ab33bf094/lib/dao.js#L2916) using response from MongoDB findOneAndUpdate operation
2. `.setAttributes` / `.toObject` #1723 does not take into account for updates using dot notation or mongo extended operators

# Link to reproduction sandbox

https://github.com/Boxonical/loopback-sandbox

# Actual & Expected result

Car.json
```json
{
  "name": "Car",
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "fuel": {
      "type": "number",
      "default": 0
    },
    "interior": {
      "type": "object",
      "default": {}
    }
  }
}
```

**CASE 1**: Update with dot notation
``` js
car.updateAttributes({'interior.seats': 5});
```
Actual:
```json
{
  "id": "5cc826d2f4af18f6f0932628",
  "name": "My Car",
  "fuel": 0,
  "interior": {},
  "interior.seats": 5
}
```
Expected:
```json
{
  "id": "5cc826d2f4af18f6f0932628",
  "name": "My Car",
  "fuel": 0,
  "interior": {
    "seats": 5
  }
}
```
**CASE 2**: Update with mongo extended operators
```js 
self.updateAttributes({$inc: {'fuel': 10}});
```
Actual:
```json
{
  "id": "5cc826d2f4af18f6f0932628",
  "name": "My Car",
  "fuel": 0,
  "interior": {},
  "$inc": {"fuel": 10}
}
```
Expected:
```json
{
  "id": "5cc826d2f4af18f6f0932628",
  "name": "My Car",
  "fuel": 10,
  "interior": {}
}
```

# Additional information
- darwin x64 10.15.3
- loopback@3.25.1
- loopback-boot@2.28.0
- loopback-component-explorer@6.3.1
- loopback-connector-mongodb@4.1.0

**Comment by dhmlau** [comment]
@b-admike @hacksparrow, could you please take a look? Thanks.

**Comment by bajtos** [comment]
I am not sure how easy it is to rebuild the object. IIRC, in LB4, we are avoiding this problem by returning `{count: 1}` from update/patch operations instead of trying to return the updated object. I suspect the problem reported by @Boxonical is specific to LB3 only.

Let's timebox the investigation to 1-2 days.

We must be careful to not break existing applications that may expect the current behavior, regardless of how good or bad it is.
