### ISSUE TITLE
Where filter not working on count endpoint with HasManyThrough

### ISSUE THREAD

**Issue by lriggle-strib** [strongloop/loopback-datasource-juggler#1743]
# Description/Steps to reproduce
This is only related to the `/{id}/relation/count` endpoint, though other endpoints may have this issue as well. When I try and get a count of how many related records match the "where" query included, the count of the full relation set is always returned. It doesn't matter what the where filter is, or even if it is included.

# Expected result
For example: I have a HasManyThrough relationship between roles and users.
- There are 400 users associated with the specified role, `/roles/{2}`
- I want to query all the users that have `abc` in their email address.
    - `{"where": {"email": {"like": "%abc%"}}}`
- `/roles/{2}/users` with the above where filter returns 3 users.
    - This endpoint works just fine with 3.6.1, but I also tried it with 4.7.0
- `/roles/{2}/users/count` with the where filter `{"email": {"like": "%abc%"}}` (because it's just a where field, not a filter field) returns 400 users
   - The endpoint should return a value of 3

# Additional information
- Using MySQL as the datasource for my API, since most of the data in the other endpoints makes more sense in a relational model
- node -e 'console.log(process.platform, process.arch, process.versions.node)'
    - linux x64 8.16.0
- npm ls --prod --depth 0 | grep loopback
```
├── loopback@3.25.1
├── loopback-boot@2.28.0
├── loopback-component-explorer@6.3.1
├── loopback-component-storage@3.6.0
├── loopback-connector-mysql@5.4.0
├── loopback-datasource-juggler@3.31.0
npm ERR! peer dep missing: elasticsearch@^13.2.0, required by http-aws-es@3.1.3
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
```

**Comment by lriggle-strib** [comment]
My workaround is to recreate the endpoint by calling `/roles/{id}/users` and returning the number of records found. This isn't ideal, especially with large datasets, but it will work for the time being.

**Comment by bajtos** [comment]
Hi @lriggle-strib, thank you for reporting the issue. Are you able to reproduce the problem using `memory` connector too? It would help us a lot if you could create a small application reproducing the issue, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs

Here is the code where HasManyThrough methods are defined:

https://github.com/strongloop/loopback-datasource-juggler/blob/a5ba7408ffe70de988c34e8e3f473747a936ae93/lib/relation-definition.js#L1001-L1279

I see that e.g. `exists` method has its own implementation, but `count` does not. I think this means LoopBack uses the generic `count` method that available for model scopes, see here: https://github.com/strongloop/loopback-datasource-juggler/blob/a5ba7408ffe70de988c34e8e3f473747a936ae93/lib/scope.js#L509-L525

I cannot tell why this `count` implementation does not work correctly for HasManyThrough relation and unfortunately don't have time to debug this myself now.
