### ISSUE TITLE
coerceArray coerces empty object into array - MAJOR BUG

### ISSUE THREAD

**Issue by regevbr** [strongloop/loopback-datasource-juggler#1745]
# Description

In the v2 of the library when perfroming a static update (update with where clause) empy objects are being coerced into empty arrays which is a major bug and causes lots of issues down the line...

# Steps to reproduce

Perform an updateAll on a model (static update not model specific update attributes) and send in the request a property set to be an empty object (i.e. {})
The dao.js code coerces that object into an empty array.

# Expected result
keep the updated value as an empty object

# Additional information

This issue is fixed in the latest code - https://github.com/strongloop/loopback-datasource-juggler/blob/de4718d5b81d29ac23597172d8ee591617924fe0/lib/model-utils.js#L226-L228

But is still wrong in the v2 trees

https://github.com/strongloop/loopback-datasource-juggler/blob/c7535ff67cf1f6b37e7fae9865e679f4a3fcf510/lib/dao.js#L1552

The issue that got the fix rolling in the latest versions - #1230

**Comment by bajtos** [comment]
Sorry, version 2.x is no longer supported - see https://github.com/strongloop/loopback-datasource-juggler#supported-versions
