### ISSUE TITLE
"Autoupdate" actually drops tables instead of altering them

### ISSUE THREAD

**Issue by ricky92** [strongloop/loopback-datasource-juggler#1761]
I tried digging into the source code and found the cause to this issue:
https://github.com/strongloop/loopback-datasource-juggler/blob/6b83b6f4d1a4941917ffbaf8cebf476e40a53f83/lib/datasource.js#L1141

Apparently, the `autoupdate` function waits for the connection to be established before proceeding with its execution, but instead of queuing itself it queues the `automigrate` function. This causes tables to be dropped instead of altered.

**Comment by dhmlau** [comment]
@ricky92, would you be interested in submitting a patch? Thanks.
