### ISSUE TITLE
Cannot create data source "shop": Cannot initialize connector "mysql": time is not defined

### ISSUE THREAD

**Issue by MAHOSSAN** [strongloop/loopback-datasource-juggler#1765]
Questions:
 Cannot create data source "shop": Cannot initialize connector "mysql": time is not defined

I am new to loopback . I am trying to connect my loopback with mysql database but when i run the applications form command prompt i am getting following errors .   

Microsoft Windows [Version 10.0.17134.885]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Khundokar Nirjor\Desktop\loop\cart> node .
C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:280
    throw err;
    ^

ReferenceError: Cannot create data source "shop": Cannot initialize connector "mysql": time is not defined
    at Handshake.Sequence (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\sequences\Sequence.js:28:3)
    at new Handshake (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\sequences\Handshake.js:10:12)
    at Protocol.handshake (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\Protocol.js:51:32)
    at PoolConnection.connect (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\Connection.js:119:18)
    at Pool.getConnection (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\Pool.js:48:16)
    at MySQL.connect (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-connector-mysql\lib\mysql.js:90:17)
    at Object.initializeDataSource [as initialize] (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-connector-mysql\lib\mysql.js:44:28)
    at DataSource.setup (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-datasource-juggler\lib\datasource.js:493:19)
    at new DataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-datasource-juggler\lib\datasource.js:138:8)
    at Registry.createDataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\registry.js:364:12)
    at dataSourcesFromConfig (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:570:19)
    at Function.app.dataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:269:14)
    at C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:191:9
    at C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:282:5
    at Array.forEach (<anonymous>)
    at forEachKeyedObject (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:281:20)

I am expecting that my loopback applications will be connected with mysql database through loopback server .

Here is my datasource.json file .
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "shop": {
    "host": "localhost",
    "port": 8081,
    "url": "",
    "database": "shoppingdatabase",
    "password": "",
    "name": "shop",
    "user": "root",
    "connector": "mysql",
    "connectTimeout": 1000000
  }
}
Here is carts.js code .

'use strict';

module.exports = function(Carts) {

};

Here is my carts. jason code .

{
  "name": "carts",
  "plural": "Carts",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "productId": {
      "type": "number",
      "required": true
    },
    "quantity": {
      "type": "number",
      "required": true
    },
    "createdAt": {
      "type": "date",
      "required": true
    },
    "updatedAt": {
      "type": "date",
      "required": true
    },
    "userId": {
      "type": "number",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
here is code for model-config.json code 

{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "db"
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "db",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "db",
    "public": false,
    "options": {
      "strictObjectIDCoercion": true
    }
  },
  "Role": {
    "dataSource": "db",
    "public": false
  },
  "carts": {
    "dataSource": "shop",
    "public": true
  },
  "products": {
    "dataSource": "shop",
    "public": true
  },
  "users": {
    "dataSource": "shop",
    "public": true
  },
  "vendors": {
    "dataSource": "shop",
    "public": true
  }
}
here is code for Sequence.js code .

function Sequence(options, callback) {
  if (typeof options === 'function') {
    callback = options;
    options = {};
  }

  EventEmitter.call(this);

  options = options || {};

  this._callback = callback;
  this._callSite = null;
  this._ended = false;
  time._timeout = 1000000;
  this._timer    = new Timer(this);
}

**Comment by MAHOSSAN** [comment]
Here is my datasource.json file .
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "shop": {
    "host": "localhost",
    "port": 8081,
    "url": "",
    "database": "shoppingdatabase",
    "password": "",
    "name": "shop",
    "user": "root",
    "connector": "mysql",
    "connectTimeout": 1000000
  }
}

**Comment by dhmlau** [comment]
@MAHOSSAN, looking at the error:
> time is not defined

do you have a `time` property or type in the model?  If it's ok, could you please share what's the model looks like that uses this datasource? 

Also, since you're new to LoopBack, have you considered using [LoopBack 4](https://loopback.io/doc/en/lb4/Getting-started.html) instead?  LoopBack 3 will go EOL in Dec 2020.  You might want to consider LoopBack 4 too. Thanks!

**Comment by MAHOSSAN** [comment]
I do have any time property in model. As you can see i mentioned time 30000 in datasoursec.json file. How can I solve this problem? Please leave your suggestion and code. Thanks

**Comment by dhmlau** [comment]
@MAHOSSAN, I don't see any `time` or `30000` in your datasources.json.  Could you please point out the part that has that property? 

Here are the valid properties in datasources.json for mysql: https://github.com/strongloop/loopback-connector-mysql#properties.

**Comment by MAHOSSAN** [comment]
Please recheck my questions i updated the the questions with all the codes .. Please tell me what will the solutions of this error.

**Comment by dhmlau** [comment]
@hacksparrow @raymondfeng , I'm not very familiar with sequence in LB3.  From the above code snippets, I didn't see anywhere `time` is defined.  Is there such variable supposedly to be accessible within a LoopBack application? Thanks.

**Comment by hacksparrow** [comment]
@MAHOSSAN please share a bare minimum app which reproduces this problem, we will then be able to help you troubleshoot and fix the problem.

**Comment by raymondfeng** [comment]
@MAHOSSAN Can you run `npm ls mysql` to find the version?

**Comment by raymondfeng** [comment]
BTW, I don't usage of `time` at https://github.com/mysqljs/mysql/blob/master/lib/protocol/sequences/Sequence.js#L28.
