### ISSUE TITLE
Feature: validatesForeignIntegrity or similar name

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback-datasource-juggler#178]
Validator that would check if related objects exist in database. This is usefull for mongodb. Is this a way to go?

**Comment by loay** [comment]
@offlinehacker @nasplachkov 
Thanks for reporting the issue. I am having a look.

**Comment by loay** [comment]
There is that validator: `Post.validatesPresenceOf('');` 
Does that work for you?
