### ISSUE TITLE
[Major] Create or update a property defined as an array gives an error

### ISSUE THREAD

**Issue by MaximeTroiano** [strongloop/loopback-datasource-juggler#1780]
## Steps to reproduce

Create a property of type "array" on your property.
Model definition:
```
{...
    "properties": {
        ...,
        "type": {
            "type": "array"
        },
        ...
    },
...}
```

Same happens for

```
{...
    "properties": {
        ...,
        "type": {
            "type": ["any"]
        },
        ...
    },
...}
```

Then try to create by sending a POST request to the model
`POST http://localhost:3000/myModel`

Example data: 
```
{
    "type": ["customer", "partner"]
}
```

## Current Behavior

The server saves the values as `{'customer','partner'}`, which then gives an error:

> Error: could not create List from JSON string: "{\"customers\",\"partners\"}"

## Expected Behavior

It should save the data as I sent it `['customer','partner']`

## Link to reproduction sandbox

[![Edit loopback-sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loopback-sandbox-vtole?fontsize=14)

**Comment by dhmlau** [comment]
@MaximeTroiano, in your sandbox, you're using in-memory connector.  Do you see problems in the in-memory database or other database? Thanks.

**Comment by MaximeTroiano** [comment]
@dhmlau I'm using the postgres connector on the real project

**Comment by MaximeTroiano** [comment]
@dhmlau I'm using the postgres-connector on the project

**Comment by MaximeTroiano** [comment]
@dhmlau can we have some visibility on this?

**Comment by bajtos** [comment]
@MaximeTroiano I am afraid I am not able to reproduce the problem. I don't know how to run your sandbox app & send requests, so I created the following standalone script:

```js
'use strict';

const loopback = require('loopback');
const {promisify} = require('util');
const fetch = require('node-fetch');

const app = loopback();
app.use(loopback.rest());

app.dataSource('db', {connector: 'memory'});

const MyModel = app.registry.createModel({
  "name": "myModel",
  "properties": {
    "type": {
      "type": "array"
    }
  },
});
app.model(MyModel, {dataSource: 'db'});


const start = promisify(function startCb(cb) {
  app.listen(3000, cb);
});

main().catch(err => {
  console.error(err);
  process.exit(1);
});

async function main() {
  await start();

  const resultDirect = await MyModel.create({types: ['customer', 'partner']});
  console.log('Instance created via JS API', resultDirect);

  const response = await fetch('http://localhost:3000/myModels', {
    method: 'post',
    body: JSON.stringify({types: ['customer', 'partner']}),
    headers: { 'Content-Type': 'application/json' },
  });
  const resultHttp = await response.json();
  console.log('Instance created via HTTP:', resultHttp);
}
```

When I run this scripts, both paths succeed - one model is created via JS API, another via REST API.

We need more help and information from you to be able to reproduce the issue. Can you perhaps take my script above and tweak it until it demonstrates the error you are facing?
