### ISSUE TITLE
Discover table indexes

### ISSUE THREAD

**Issue by deepakrkris** [strongloop/loopback-datasource-juggler#1786]
## Current Behavior

model discovery with ds.discoverSchemas() returns model definition without any index configurations for all db connectors. Not sure if this is a known issue already. If this is a known limitation this has to be documented with explanations.

Description/Steps to reproduce

```
ds.discoverSchemas('todo', {relations: true}, function(err, models) {
    console.log(models);
});
```

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback-next/issues/2331 and https://github.com/strongloop/loopback-next/issues/2606
