### ISSUE TITLE
Loopback app is failing to connect to MongoDB if the MongoDB password contains special character `@` 

### ISSUE THREAD

**Issue by rranjann** [strongloop/loopback-datasource-juggler#1788]
The Loopback based `Microservices` is failing to connect to `MongoDB` if the `MongoDB` password contains special character `@`. It’s working fine if the password contains other special character. But if the MongoDB password contains `@` , following exception occurred.

```
{"log":"Unhandled rejection MongoError: authentication fail\n","stream":"stderr","time":"2019-10-30T08:58:03.990065653Z"}
{"log":"    at /node_modules/mongodb-core/lib/topologies/replset.js:1456:15\n","stream":"stderr","time":"2019-10-30T08:58:03.990078603Z"}
{"log":"    at /node_modules/mongodb-core/lib/auth/scram.js:352:15\n","stream":"stderr","time":"2019-10-30T08:58:03.990102783Z"}
{"log":"    at  /node_modules/mongodb-core/lib/connection/pool.js:532:18\n","stream":"stderr","time":"2019-10-30T08:58:03.990106763Z"}
```

# Additional information

```
- node -e 'console.log(process.platform, process.arch, process.versions.node)'
$ darwin x64 6.11.1

- npm ls --prod --depth 0 | grep loopback
├── loopback@3.22.3
├── loopback-boot@2.27.1
├── loopback-cascade-delete-mixin@1.3.1
├── loopback-component-explorer@6.3.0
├── loopback-connector-mongodb@3.8.0
├── loopback-context@3.3.0
├── loopback-datasource-juggler@3.24.0
```

Please let me know if any further details are required.

**Comment by dhmlau** [comment]
could you please try to encode the whole password?

**Comment by rranjann** [comment]
@dhmlau The encoded `MongoDB`password we had used is `p@ssw0rd`.

**Comment by dhmlau** [comment]
Have you tried to encode the password?  Please see https://github.com/strongloop/loopback-connector-mongodb#creating-a-mongodb-data-source

> If your username or password contains special characters like @, $ etc, encode the whole username or password using encodeURIComponent.
> Eg: pa$$wd would become pa%24%24wd.

**Comment by rranjann** [comment]
Yes ... In our product we are using the `encodeURIComponent` while retrieving the username and password from environment variable since long. We had observed the above failure even with `encodeURIComponent`. 

Please let me know if you need any further details.

> const mongoUser = encodeURIComponent(process.env.MONGO_USERNAME || 'admin');
> const mongoPw = encodeURIComponent(process.env.MONGO_PASSWORD || 'Welcome2ibm');
> const authMechanism = encodeURIComponent(process.env.MONGO_AUTHMECHANISM || 'DEFAULT');
> const mongoHost = encodeURIComponent(process.env.MONGO_HOST || 'mongo-readsvc');
>

**Comment by hacksparrow** [comment]
@rranjann use this function to generate [percent-encoded](https://tools.ietf.org/html/rfc3986#section-2.1) passwords:

```js
function percentEncode(string) {
  let encoded = '';
  string.split('').forEach(function(char) {
    encoded += '%' + char.charCodeAt(0).toString(16).toUpperCase();
  });
  return encoded;
}
```

From https://github.com/strongloop/loopback-connector-mongodb/issues/499#issuecomment-503435737.

**Comment by rranjann** [comment]
@hacksparrow Following `loopback libraries` used in our Microservices. Do we need to upgrade any of below libraries apart from the function `percentEncode` which you had recommended.

```
- npm ls --prod --depth 0 | grep loopback
├── loopback@3.22.3
├── loopback-boot@2.27.1
├── loopback-cascade-delete-mixin@1.3.1
├── loopback-component-explorer@6.3.0
├── loopback-connector-mongodb@3.8.0
├── loopback-context@3.3.0
├── loopback-datasource-juggler@3.24.0
```

**Comment by dhmlau** [comment]
@hacksparrow, looks like you're looking into it.  Assigning it to you now. Thanks.

**Comment by hacksparrow** [comment]
@rranjann it is an implementation problem in the official MongoDB driver. They require special characters to be URL encoded, but they don't decode them back to plain text before passing the values to the database - https://github.com/mongodb/node-mongodb-native/blob/master/lib/core/uri_parser.js#L569-L578.

Calling `decodeURIComponent` on those values will fix the problem, but I am not sure if it introduces any new problems.

**Comment by dhmlau** [comment]
@hacksparrow @rranjann, is this issue good to close? I think you two had a separate discussion on this. Thanks.

**Comment by hacksparrow** [comment]
Let's close this, it is MongoDB's Node.js driver problem.
