### ISSUE TITLE
loopback-connector-ibmi needs modifications to some query tests

### ISSUE THREAD

**Issue by markdirish** [strongloop/loopback-datasource-juggler#1809]
## Steps to reproduce

Run datasource tests on [loopback-connector-ibmi](https://github.com/strongloop/loopback-connector-ibmi)

## Current Behavior

There are 2 issues with the tests found in `test/basic-querying.test.js`:

1. The test `should support string "gt" that is not satisfied` assumes that the table is encoded in ASCII or a related encoding (lowercase letters come after capital letters). IBM i tables are by default encoded in EBCDIC (lowercase letters come before capital letters). The test as written doesn't pass on IBM i, so need to check the db adapter and adjust the test accordingly.

2. Like many connectors (including `db2`), the IBM i connector does not have GeoPoint support. Currently, GeoPoint tests in the file fail when using `loopback-connector-ibmi`. Need to add `ibmi` to the list of adapters that do not support GeoPoint.

3. When checking for explicit error messages, be sure to check `error.odbcErrors[0].message` instead of `error.message`. The underlying ODBC connection used by this connector can return multiple errors, so `error.message` is usually a generic message saying where the error happened, while the `error.odbcErrors[x].message` is an error directly from the database.

## Expected Behavior

There is nothing wrong with the connector in regards to these tests, just have to make sure the juggler tests are aware of IBM i's limitations. Need to adjust tests to ensure they pass.

## Additional information

These changes are needed for the `loopback-connector-ibmi` to pass all tests. Will make PRs for both v3 (lts) and v4 (current)

## Related Issues

**Comment by dhmlau** [comment]
@markdirish, assigning this to you since you have a PR in progress #1810 .

**Comment by dhmlau** [comment]
@markdirish, are you still pursuing this? Thanks.
