### ISSUE TITLE
[CI] Postgresql downstream tests failed

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-datasource-juggler#1816]
Originated from https://github.com/strongloop/loopback-datasource-juggler/pull/1813. Looking at the logs, there's no specific error, only:
```
No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
```

## Acceptance Criteria
- [ ] investigate why the postgresql downstream CI failed and fix it.

**Comment by agnes512** [comment]
Discussion during estimation meeting: Maybe we can create DB names dynamically. Using different db names to run v3 and v4 separately.

**Comment by agnes512** [comment]
closing as done
