### ISSUE TITLE
"property cannot be changed" message when attempting to PUT (replaceById)

### ISSUE THREAD

**Issue by frankorama** [strongloop/loopback-datasource-juggler#1836]
## Version

Loopback v3.27.0

## Steps to reproduce

1. Create a Model called "Student" with an auto-created id and a name (string) property
2. Created a new student with {name: "John Doe"}
3. Retrieve new instance ID (example: 1)
3. Modify the student name by calling endpoint PUT 

URL: /api/students/1
Data: 
`{name: 'Jane Doe'}`

## Current Behavior

Instance is updated in the database
Console displays messages:
```
WARNING: id property cannot be changed from 1 to 1 for model:Student in 'before save' operation hook
WARNING: id property cannot be changed from 1 to 1 for model:Student in 'loaded' operation hook
```

## Expected Behavior

- Database updates
- No warning messages in the console

## Link to reproduction sandbox

No sandbox yet.  Can provide if needed

## Additional information

Debugging the issue I see the problem is with the following code:
```
// dao.js  line 2735 && 2671
if (ctx.data[pkName] !== id && !Model._warned.cannotOverwritePKInLoadedHook) {
```
`ctx.data[pkName]` is an object (BSON) while the `id` property is a string.

## Related Issues

N/A

**Comment by bajtos** [comment]
Thank you @frankorama for reporting the issue. Could you please create a small application we can use to quickly reproduce it locally? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.

**Comment by frankorama** [comment]
@bajtos [Fork](https://github.com/JITbase/loopback-sandbox-1836) created with a test case illustrating the problem.
to run:
```
npm install
npm unit-test
```

**Comment by lrpinto** [comment]
Hi, anyone got to the bottom of this?

I ma having similar issue.

**Comment by frankorama** [comment]
> Hi, anyone got to the bottom of this?
> 
> I ma having similar issue.

Looks like I'll have to do a pull request.  As mentioned in the comments, the error is written to the console, but the object is still updated, so there doesn't seem to be a show-stopping bug.

**Comment by lrpinto** [comment]
I am with you. It is just a warning. It just a little annoying.

But perhaps a pull request allowing to declare a Mongo ID as [ObjectId ](https://docs.mongodb.com/manual/reference/method/ObjectId/) would be good (mongoose already has this type)... Truth to be said I have not done any effort to find how to do it, but maybe in Xmas I have time...
