### ISSUE TITLE
Dynamically connect to the data source in middleware

### ISSUE THREAD

**Issue by prateek9958** [strongloop/loopback-datasource-juggler#1854]
I have a use case that needs to `dynamically connect to the data source` in the `middleware`. If this possible then how???

**USE CASE**
`Based on URL - GET the database name and refresh the connection of the` **MongoDB**

I have been doing this in `auth` middleware. 
![image](https://user-images.githubusercontent.com/41443599/88481311-3cb8f180-cf78-11ea-9226-b5b3c86cb9c9.png)

my datasource.json
![image](https://user-images.githubusercontent.com/41443599/88481353-9b7e6b00-cf78-11ea-84c3-fdfdc3f598e8.png)

And I have mapped my data source to the models also

But in auth, I am getting data source as connected and it is connecting to default ip and port! 
Need to know to which middleware state I have to push

`LOOPBACK VERSION: 3`

**Comment by kaonashi164** [comment]
the same +1

**Comment by prateek9958** [comment]
### Solution:
My auth or db checking middleware define in `initial:before` key in `middleware.json`
![image](https://user-images.githubusercontent.com/41443599/88584190-e8446d80-d06e-11ea-8980-57b15d6e18cb.png)

My db disconnection middleware define in `final` key in `middleware.json`
![image](https://user-images.githubusercontent.com/41443599/88584238-f8f4e380-d06e-11ea-948d-a3102046ea1e.png)
