### ISSUE TITLE
A better way to handle relation inheritances 

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#192]
See https://groups.google.com/forum/#!topic/loopbackjs/72NtR9vdb_o

This is one of the tricky issues around the fk/pk typing with relations and inheritance.

Here is the problem:
1. role extends Role and roleMapping extends RoleMapping
2. role hasMany roleMappings and roleMapping belongsTo role

Since you don’t have explicit belongsTo relation defined in the roleMapping model, it inherits one from the base RoleMapping model which points to Role instead of role. As a side effect, the ‘roleId’ property is typed by Role.id (which defaults to Number).

**Comment by mike-aungsan** [comment]
I have similar issues with extending roleMapping and accessToken.
