### ISSUE TITLE
beforeDestroy and afterDestroy hooks not trigered if called with destroyById

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback-datasource-juggler#202]
I guess some kind of triggers are needed for class methods and not only for class instance methods.

**Comment by bajtos** [comment]
I am closing this issue, we are moving away from `beforeDestroy/afterDestroy` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `before delete` and/or `after delete` hooks and open a new GH issue if you run into any problem.
