### ISSUE TITLE
How to sync query method with other method

### ISSUE THREAD

**Issue by nitinshinde42** [strongloop/loopback-datasource-juggler#207]
dataSource.connector.query() executes asynchronously w.r.t calling function getStateDBName(). Because of this, there is a race condition between caller of getStateDBName() and dataSource.connector.query(). Is there any way to synchronize?

getStateDBName = function(city) {

    console.log("city in getStateDBName "+city);
    var dbname = null;

    var dataSource = new DataSource('mysql', {
        host: 'localhost',
        port: 3306,
        database: 'xxxxxl',
        username : 'root',
        password : 'yyyyyy'

    }); 

    var sql = "select state from kp_city_state where city = '"+city+"'";

    dataSource.connector.query(sql, function(err, queryResult){
       ....
      }
}

**Comment by raymondfeng** [comment]
Use a module like https://github.com/caolan/async
