### ISSUE TITLE
Custom Table Names on hasAndBelongsToMany Relationships

### ISSUE THREAD

**Issue by jcq** [strongloop/loopback-datasource-juggler#230]
I've searched through the docs and various repos, but it's possible that I've just missed this.

Is it possible to specify the name of the junction table on a hasAndBelongsToMany relationship? I have an existing database with the following tables: 
- contacts
- addresses
- contacts_addresses (contains foreign keys contact_id and addresses_id)

If I understand things correctly, the default schema that hasAndBelongsToMany would expect for this would be contactsaddresses, but I'd obviously prefer not to have to redo my existing table schema (and all other non-Loopback code that refers to it.

Thanks in advance...

**Comment by Sopamo** [comment]
I also think that would be way easier then using a hasManyThrough.

**Comment by flyswatter** [comment]
I was just playing with building a loopback application that could talk to a legacy database, and customizing table names for models at all levels would be a requirement for that.

**Comment by mghaderyan-nisum-com** [comment]
So this issue being "closed" means it is fixed or it got ignored?!

**Comment by superkhau** [comment]
I

**Comment by schankam** [comment]
Just read all of this... So there is still no way to choose a custom name for junction table with HABTM ? This feature become useless for a lot of people working with legacy DB.. I guess for now I will stick with defining the model for the junction table with "belongsTo"... But this is really not the way I was expecting it to work...

**Comment by quorak** [comment]
+1

**Comment by smumu** [comment]
Any news about this feature (planned, milestone, abandoned ...) ?

**Comment by yagobski** [comment]
the hasAndBelongsToMany has no interest to be used if we can't customize the name of the table junction. Please take this request. Junctions tables are not models and adding them to modeles folder have no sense.

**Comment by waldemarzahn** [comment]
https://github.com/strongloop/loopback-datasource-juggler/pull/1303

**Comment by ssh24** [comment]
Closing this as https://github.com/strongloop/loopback-datasource-juggler/pull/1303 landed. Thank you @waldemarzahn for the contribution.
