### ISSUE TITLE
Assigning default values: null vs. undefined

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#234]
Currently any default value (default: ... in LDL) will be assigned as long as the value is undefined. If the value has been set to null, the default won't be assigned.

This introduces the following side-effect: due to the `removeUndefined()` calls during `save()`, you cannot actually persist 'undefined' to the data store. AFAIK most databases will represent missing data as null anyway. As such, you cannot ever get back to a state where the default value will be applied - it will remain null.

**Comment by superkhau** [comment]
@fabien Has the issue been resolved? Can I close it?
