### ISSUE TITLE
deleteAll does not work for embedsMany relations

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback-datasource-juggler#251]

**Comment by jannyHou** [comment]
I am closing it since it's a duplidate of https://github.com/strongloop/loopback-datasource-juggler/issues/258
To keep it easy to track, let's keep updating fix and discussion under that one. Thanks for understanding!

**Comment by jannyHou** [comment]
I am closing it since duplicate bug already reported here: https://github.com/strongloop/loopback-datasource-juggler/issues/258

To keep it easy to track let's keep updating fix and discussion under that one. Thanks for understanding :)
