### ISSUE TITLE
Validators are not triggered on updateOrCreate

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback-datasource-juggler#262]
inst.save() should be called in updateOrCreate

**Comment by bajtos** [comment]
Ad "before/after(save) hooks not triggeted": we are working on a new hook infrastructure that will not have this problem, see #403.

The scope of this issue is to add the missing model validation.

**Comment by bajtos** [comment]
When we release the fix, we should post a note to LoopBack mailing list explaining the change, as it may break incorrectly written applications that were relying on the fact that `updateOrCreate` with invalid model does not return an error.

**Comment by aarnaud** [comment]
+1

**Comment by jcsmesquita** [comment]
+1. I'm still having issues with the latest version 2.21.0.

**Comment by bajtos** [comment]
That's expected, see https://github.com/strongloop/loopback-datasource-juggler/blob/e13c0cdc12467aff5f347fa1112c03ba1dcdbb8b/lib/dao.js#L396-L398

**Comment by bajtos** [comment]
We can implement this now behind a flag which can be removed in 3.x, that way it's not a breaking change.

**Comment by fabien** [comment]
+1

**Comment by bajtos** [comment]
The feature is available in `loopback-datasource-juggler@2.25.1`. By default, validation errors are printed via `console.warn`. Use the new model option `validateUpsert` to trigger a regular error instead.

**Comment by jcsmesquita** [comment]
I'm migrating to the latest version of loopback because of this! It's awesome it works! Thanks a lot!
