### ISSUE TITLE
Documentation of supported events

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#269]
This information has been collected by Partap Davis

See: https://groups.google.com/forum/#!topic/loopbackjs/61qd--Xkowo

Event: 'deleted'
Args: id

Emitted by:
- Model.removeById()
- Model.destroyById()
- Model.deleteById()
- Model.prototype.remove()
- Model.prototype.delete()
- Model.prototype.destroy()

Event: 'deletedAll'
Args: where (optional)

Emitted By:
- Model.remove()
- Model.deleteAll()
- Model.destroyAll()

Event: 'changed'
Args: instance

Emitted by:
- Model.create()
- Model.updateOrCreate()
  -Model.upsert()
  -Model.prototype.save()
- Model.prototype.updateAttributes()

Event: 'set'
Args: instance

Emitted by:
- Model.prototype.setAttributes()

Note that the event is _not_ emitted on Model.prototype.setAttribute(), so the docs describing setAttribute() as equivalent to setAttributes({name:value}, cb) is inaccurate...

**Comment by crandmck** [comment]
I believe the model events are documented fully and this can be closed.

If you have a moment, please confirm:
- https://loopback.io/doc/en/lb3/Events.html#model-events
- http://loopback.io/doc/en/lb3/Basic-model-object.html
