### ISSUE TITLE
Expose/extract utility or helper functions

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#274]
I find myself using these useful helper methods:

``` javascript
var defineScope = require('loopback-datasource-juggler/lib/scope').defineScope;
if (!defineScope) throw new Error('defineScope helper function is missing');

var mergeQuery = require('loopback-datasource-juggler/lib/scope.js').mergeQuery;
if (!mergeQuery) throw new Error('mergeQuery helper function is missing');

var applyFilter = require('loopback-datasource-juggler/lib/connectors/memory').applyFilter;
if (!applyFilter) throw new Error('applyFilter helper function is missing');
```

I'm asserting their existence, in case they ever disappear. I think these are good candidates to refactor out into `utils` and/or expose through `loopback-datasource-juggler` (index.js).

**Comment by raymondfeng** [comment]
@fabien Have you created a PR for your commits?

**Comment by fabien** [comment]
@raymondfeng hasn't this been merged yet as part of the scope work?

**Comment by raymondfeng** [comment]
Cool. I'm closing this issue then.

**Comment by fabien** [comment]
@raymondfeng apparently only mergeQuery has been extracted. `defineScope` and `applyFilter` have not been moved into `utils`. Reopen?

**Comment by raymondfeng** [comment]
Sure.

**Comment by mrbatista** [comment]
+1
