### ISSUE TITLE
Map nested models to embedded relations

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#299]
Should we map the following to actual embedded relations, now that they are available?

```
address: {type: Address} // embedsOne
addresses: {type: [Address]} // embedsMany
```

**Comment by raymondfeng** [comment]
We could. What's the implication?

**Comment by clarkorz** [comment]
Currently I only use embedded relations when the the logic between host model and embedded model  is  complex, so I have to handle it myself. 

If the only matter thing is the document structure, I prefer to embed model as simple property. The CONS is:
1. have to define a validation for the embed property
2. I don't like anonymous model, hence the embedded models have to be defined as top level models

Thoughts?

**Comment by jmls** [comment]
are you talking about mapping a property directly to an embedded model  - rather than defining a relationship ? Also, what's an "anonymous model" ?
