### ISSUE TITLE
upsert to postgressql causes TypeError: Object.keys called on non-object in lib/model.js:124

### ISSUE THREAD

**Issue by aljo666** [strongloop/loopback-datasource-juggler#302]
```
loopback-datasource-juggler/lib/model.js:54
  if (typeof data != object)
                     ^
ReferenceError: object is not defined
```

I think that data sould be checked if is typeof object otherwise the function crashes if you try to upsert data to postgresql database because of the RETURNING clause.

should be something like

``` js
ModelBaseClass.prototype._initProperties = function (data, options) {
  if (typeof data != 'object')
    return;
```

**Comment by Morriz** [comment]
Hi. This is still an issue, and the cause lies in the fact that  /{id} and ?id={id} do totally different things.

I created a related bug some days ago: https://github.com/strongloop/loopback-sdk-angular/issues/125
