### ISSUE TITLE
How to use defineValueType()

### ISSUE THREAD

**Issue by projectxmaker** [strongloop/loopback-datasource-juggler#307]
Hi,

Found in document about [ModelBuilder class](http://docs.strongloop.com/display/LB/ModelBuilder+class#modelbuilderdefinevaluetypetype-aliases), there's a function called defineValueType which is described to create new property type, but I don't know how to use it to create a new property type, which  is similar to /lib/geo.js (the reason why I don't use the existing GeoPoint type is because it stops the system from working if any validation implemented inside it failed, for example: input data is not valid).

Any help is greatly appreciated.

**Comment by raymondfeng** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs.
