### ISSUE TITLE
no control over link tables in HasAndBelongsToMany

### ISSUE THREAD

**Issue by punund** [strongloop/loopback-datasource-juggler#317]
There is no way to customize the name of the link table in HasAndBelongsToMany relations.  Also, the code insists that this table should have the `id` column, which is, strictly speaking, not needed, as primary key is composed from the ids of tables being joint.

This makes it difficult to reuse existing database structure.

**Comment by raymondfeng** [comment]
You need to run `automigrate` or `autoupdate` to create tables in your DB. See http://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models

**Comment by punund** [comment]
I would if I could, but the whole issue was about inability to use existing tables.

**Comment by raymondfeng** [comment]
You have a typo in the Book relations, the key should be `homme` instead of `Homme`.
