### ISSUE TITLE
Auto increment not working with embedsMany

### ISSUE THREAD

**Issue by janober** [strongloop/loopback-datasource-juggler#336]
Somehow I can not get the auto increment to work with "embedsmany". Always when I create a Picture (no matter if directly WITH the party or adding it later TO the party ) it complains that I did not supply an id. Also tried having the "id" set as optional "number" property. Does anybody know what I am doing wrong?

Do I also have to define the relationship in Picture somewhere?

Thanks!

Party:

```
{
  "name": "Party",
  "plural": "Parties",
  "base": "PersistedModel",
  "mixins": {
  "ObjectId": true
},
  "properties": {
  "name": {
    "type": "string",
      "required": true
  },
  "date": {
    "type": "date",
      "required": true
  }
},
  "validations": [],
  "relations": {
  "pictures": {
    "type": "embedsMany",
      "model": "Picture",
      "options": {
      "forceId": true,
        "validate": true,
        "autoId": true
    }
  }
},
  "acls": [],
  "methods": []
}
```

Picture:

```
{
  "name": "Picture",
  "plural": "Pictures",
  "base": "PersistedModel",
  "properties": {
  "filename": {
    "type": "string",
      "required": true
  },
  "date": {
    "type": "date",
      "required": true
  }
},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

**Comment by brunocascio** [comment]
Not work for me.

```
"steps": {
      "type": "embedsMany",
      "model": "Step",
      "options": {
        "persistent": true
      }
    },
```

Step model:

```
{
  "name": "Step",
  "base": "PersistedModel",
  "properties": {
    "pos": {
      "type": "number",
      "required": true
    },
    "text": {
      "type": "string",
      "required": true
    },
    "image": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

**Comment by fabien** [comment]
@brunocascio check the additional options on the embedsMany above (forceId, validate, autoId).

**Comment by brunocascio** [comment]
Well, i added that properties. But not work.

````
"steps": {
      "type": "embedsMany",
      "model": "Step",
      "options": {
        "persistent": true,
        "forceId": true,
        "validate": true,
        "autoId": true
      }
```

**Comment by brunocascio** [comment]
Actually it's a bug?

**Comment by jmls** [comment]
I can't get this working either. Same error, same options

**Comment by markleusink** [comment]
I got this to work in my setup. I'm using MongoDb as my data store and have a `Page` model that should have embedded comments:

- define a 'transient' datasource in `datasource.json`

```json
"transient": {
  "name": "transient",
  "connector": "transient"
},
```

- use that for the model that you want to embed (in `model-config.json`):

```json
"Comment" : {
 "dataSource" : "transient",
 "public" : false
}
```

- setup the relation:

```json
  "relations": {
    "comments": {
      "type": "embedsMany",
      "model": "Comment",
      "property": "comments",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  },
```

(even with `forceId : false` it automatically inserts an id for the embedded document)

You can then do a `POST` to `/api/Pages/:parentId/comments`: that will create/ append to an array in the parent model (named after the property and prefixed by an underscore: `_comments`). Note that the parent model (Page) is set up with a MongoDB data source.

**Comment by mailuser41** [comment]
@markleusink : this works only for transient datasource. How abt making it to persistent model as informed by @brunocascio. Well.. we want to query the comment based on the generated id..

**Comment by markleusink** [comment]
Although the model ('Comment') uses a transient datasource in this setup, the data is actually stored as an embedded document array in the parent ('Page'). You can query Comments, but (AFAIK) only for a specific Page.

**Comment by mailuser41** [comment]
Thanks for the reply Mark. There is slight variation in my scenario. I want the same address (comment in your case) to linked with another entity. Hence I used the persistent datasource and not transient. Also the the unique primary key is not generated.

I still think this is a bug.

Thanks

**Comment by cesarizu** [comment]
The solution by @markleusink works for me except for id generation, it is not generated.

Is there a way to make it use "comments" instead of "_comments" as the database property?

**Comment by markleusink** [comment]
The property name is prefixed with an underscore, because the relation name is the same as the property name. If you change it to (e.g.) this, it will use `comments` as the property name:

     "relations": {
      "commentsRel": {
        "type": "embedsMany",
        "model": "Comment",
        "property": "comments",
        "options": {
          "validate": true,
          "forceId": false
        }
      }
     },

**Comment by cesarizu** [comment]
Thanks @markleusink that worked!

**Comment by vasumahesh1** [comment]
Hey @markleusink  This was working perfectly, until I had two embedsMany (One embedsMany within another embedsMany).... Once I got that It said theres a duplicate Index. :/ any thoughts on that?


```js
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The `Quiz` instance is not valid. Details: `quizQuestions` contains invalid item at index `0` (`questionOptions` contains duplicate `id`) (value: [ { id: undefined,\n    qu...} ]).",
    "statusCode": 422,
    "details": {
      "context": "Quiz",
      "codes": {
        "quizQuestions": [
          "invalid"
        ]
      },
      "messages": {
        "quizQuestions": [
          "contains invalid item at index `0` (`questionOptions` contains duplicate `id`)"
        ]
      }
    },
    "stack": "ValidationError: The `Quiz` instance is not valid. Details: `quizQuestions` contains invalid item at index `0` (`questionOptions` contains duplicate `id`) (value: [ { id: undefined,\n    qu...} ]).\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:264:12\n    at ModelConstructor.<anonymous> (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:472:11)\n    at ModelConstructor.next (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:75:12)\n    at ModelConstructor.<anonymous> (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:469:23)\n    at ModelConstructor.trigger (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:65:12)\n    at ModelConstructor.Validatable.isValid (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:435:8)\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:260:9\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:106:23\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:189:25\n    at event (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-ds-timestamp-mixin\\index.js:29:5)"
  }
}
```



Data that was sent...
```
{
  "title": "This is a Quiz",
  "description": "Hello, Quiz",
  "isClosed": true,
  "duration": 10,
  "quizQuestions": [
    {
      "questionContent": {
        "data": "What is the Capital of India?",
        "type": "text"
      },
      "questionOptions": [
        {
          "isAnswer": false,
          "optionContent": {
            "data": "Mumbai",
            "type": "text"
          }
        },
        {
          "isAnswer": true,
          "optionContent": {
            "data": "New Delhi",
            "type": "text"
          }
        }
      ]
    }
  ]
}
```
so as long as "questionOptions" has one value it inserts by using the transient trick.... Once I put two values in that I get this error! 


Bit of a noob here.... But I did as you followed and as I grew my Models I tested Question, Option & Content manually and all were working by the method you specified... But it seems to fail for this...

**Comment by vasumahesh1** [comment]
Infact its with any embedsMany: If the Inner array was 2 I get the above error. If the quizQuestions was of count two, I get:

```js
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The `Quiz` instance is not valid. Details: `quizQuestions` contains duplicate `id` (value: [ { id: undefined,\n    qu...} ]).",
    "statusCode": 422,
    "details": {
      "context": "Quiz",
      "codes": {
        "quizQuestions": [
          "uniqueness"
        ]
      },
      "messages": {
        "quizQuestions": [
          "contains duplicate `id`"
        ]
      }
    },
    "stack": "ValidationError: The `Quiz` instance is not valid. Details: `quizQuestions` contains duplicate `id` (value: [ { id: undefined,\n    qu...} ]).\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:264:12\n    at ModelConstructor.<anonymous> (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:472:11)\n    at ModelConstructor.next (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:75:12)\n    at ModelConstructor.<anonymous> (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:469:23)\n    at ModelConstructor.trigger (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:65:12)\n    at ModelConstructor.Validatable.isValid (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:435:8)\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:260:9\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:106:23\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:189:25\n    at event (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback-ds-timestamp-mixin\\index.js:29:5)"
  }
}
```

**Comment by sebastianhaas** [comment]
+1 for @vasumahesh1's issue described above

**Comment by sebastianhaas** [comment]
To me it seems like id generation for multiple inserts at once is broken. If I insert just one embedded Model at a time, everything works like expected. As soon as try to add more than one objects at once- I get the same error message as @vasumahesh1.

I tried all possible combinations of the options stated above.

**Comment by vasumahesh1** [comment]
@sebastianhaas Yeah Same ... This is actually blocking my work at the moment :( ... To solve around this issue i ll need to make a custom remote head accepting these values and change the embedsMany to hasMany and manually add the values in each case using `add()` of hasMany ... That way I can do an Embedded Insert ...

**Comment by FELS-Rohit** [comment]
@vasumahesh1  @sebastianhaas  
Found a Solution for this Problem
in Answer.json File add Id Properties with following setting 

   "id": {
      "type": "string",
      "id": true,
      "defaultFn": "uuid"
    }
Rest all setting Same as @markleusink described Above

**Comment by sebastianhaas** [comment]
Wow, thanks a lot @FELS-Rohit. Works for me.

**Comment by dylandechant** [comment]
yes thanks @FELS-Rohit this blocked me for a couple of days 👍

**Comment by pushkrajd** [comment]
Setting "of defaultFn": "uuid" is this available  on Loopback documentation "https://loopback.io/doc"
