### ISSUE TITLE
unexpected root element of wsdl or include

### ISSUE THREAD

**Issue by NgaNguyenDuy** [strongloop/loopback-datasource-juggler#343]
hi,
I have a problem with datasource when i try connecting to soap connector. My root element  is not wsdl, it same as: <definitions targetNamespace="..."></definitions>.
I get an error similar to the title: "unexpected root element of wsdl or include".

And my question is how to fix it?

Thank,

**Comment by raymondfeng** [comment]
Closing the issue. For questions, please post to https://groups.google.com/forum/#!forum/loopbackjs
