### ISSUE TITLE
I can't hook into beforeDestroy in request DELETE /Books/{id}

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback-datasource-juggler#345]
I can't hook into beforeDestroy in request DELETE /Books/{id}
Book.beforeDestroy = function () {
    console.log(arguments);
}
But i doesn't work and don't show anything.

**Comment by raymondfeng** [comment]
We're deprecating `beforeDestroy` to favor http://docs.strongloop.com/display/LB/Operation+hooks.
