### ISSUE TITLE
DataSource discoverSchema doesn't fire callback if table was not found 

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback-datasource-juggler#353]
Using the mssql connector:

``` javascript
this.discoverSchemas(modelName, options, function (err, schemas) {
    if (err) {
      cb && cb(err, schemas);
      return;
    }
    for (var s in schemas) {
      cb && cb(null, schemas[s]);
      return;
    }
  });
```

If both *err* and *schemas* are undefined, *cb* will never be called nor does the function return anything.

[Code can be found here.](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L1166-1169)

(This issue was originally put in the wrong repo)

**Comment by ccampbellsoln** [comment]
Was this resolved for `discoverSchema()`?
