### ISSUE TITLE
Include __cachedRelations in toObject() and toJSON()

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback-datasource-juggler#366]
When I use findOne().include('related-model') I get back a model that has the __data and __cachedRelationships properties.  Currently I am using lodash to merge these into the complete fieldset.  It seems weird to always have to doctor up the query results though.

Should __cachedRelations be included in toObject() and toJSON()?  I don't know if this would go against current expectations, but it seems to make sense to me.  I think it would make the API more convenient.

If not, then we should document how the application programmer is supposed to obtain that information.  The [current examples](http://docs.strongloop.com/display/public/LB/Include+filter) don't mention what you should do with the result set, and it's really not obvious from the implementation.

**Comment by mattwilliams** [comment]
BTW, what is the proper way to get the embedded records?  I am using __cachedRelations which seems to work.  It returns an object with an array of related records.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/include.test.js

**Comment by raymondfeng** [comment]
Use `toJSON()`

**Comment by bitmage** [comment]
toJSON isn't working for me...  The relationship data is present in __cachedRelationships but does not get included in toJSON().  @raymondfeng I'm not sure how [this code](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-definition.js#L264) could be including the relationships, since it doesn't make any mention of them.

**Comment by TimPerry** [comment]
+1 this still doesn't appear to work. @bitmage I agree with you there is no mention of __cachedRelationships.

**Comment by JoshElias** [comment]
+1 toJSON is not a function on the model returned from an Model.findById

**Comment by gbhipolitoglyph** [comment]
thanks!
Include filter https://loopback.io/doc/en/lb3/Include-filter.html + `toJSON()` worked for me
