### ISSUE TITLE
validatesInclusionOf should not enforce null check

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback-datasource-juggler#372]
Currently there is no way to enforce an enumeration, but allow undefined/null.  Even putting them in the list of allowed options does nothing because a nullCheck() short circuits this:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/validations.js#L289

My suggestion is to simply return from the inclusion validator without doing any checks if the value is null or undefined.  This decouples the inclusion/required validations and allows the app programmer to select which properties he wants.

Thoughts on whether this is the right way to go?  Concerns for backwards compatibility?  I'm happy to create a pull request if there's consensus about the approach.

Thanks!

**Comment by mrfelton** [comment]
+1

**Comment by raymondfeng** [comment]
Isn't it fixed at https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/validations.js#L289?

**Comment by bitmage** [comment]
No.  That's precisely the logic that I pointed out as being the problem.

For an enumeration, it *always* checks to see if the record is null.  I'm saying that it should not do this.

**Comment by mrfelton** [comment]
Pretty sure this issue shouldn't be closed. This is a real problem and makes most of the built in validators useless for non-required fields.

**Comment by jamesreimer** [comment]
This issue really should be reopened. I agree with mrfelton on this making validators useless for non-required fields. Obviously you can do your own validation to get around it, but you really shouldn't have to if the validators exist.

**Comment by wprater** [comment]
you can just pass in `allowNull` to allow them in addition to your exclusion list https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/validations.js#L608

**Comment by beeman** [comment]
Thanks @wprater, this works in the case where I want to validate an option zip code:

```
  // Ensure that the zipCode is either 5 or 5-4 chars long
  Person.validatesFormatOf('zip', {
    with: /(^\d{5}$)|(^\d{5}-\d{4}$)/,
    allowNull: true
  });
```

**Comment by jamesobd** [comment]
WHY is allowNull not documented?  Can someone add it to the documentation for the validatesInclusionOf options here: https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validatesinclusionof

**Comment by blackvirus18** [comment]
allowNull really should be added to the doc.

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Added to http://loopback.io/doc/en/lb2/Validating-model-data.html#options-object and also added to the API docs.

**Comment by sabliao** [comment]
Even after I use allowNull: true, I still get an error about an optional field (that, if included, needs to be from a short list of valid values) if I don't have it as part of the payload, and the error that comes back is ["inclusion.blank"]. Is this because undefined isn't the same as null? If so, could we have allowNull also allow undefined?

**Comment by brawaga** [comment]
@sabliao, you can also use allowBlank: true, as I see in the code of loopback validations.js file.

**Comment by Caperious** [comment]
@sabliao thank you, your suggestion was the one i was looking for!
