### ISSUE TITLE
Auto increment field

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-datasource-juggler#377]
Is there any option for the model to have auto increment field?

like:

```
{
 "uniqueNumber": {
    "type": "Number"
    "autoIncrement": 10000,  // Where 10000 is default initial value
 }
```

Thanks

**Comment by raymondfeng** [comment]
Not at the moment. We plan to enrich the id property options in the future to support more flavors, such as uuid, autoIncrement, etc.

**Comment by nosensezzz** [comment]
Can you update this post after implemented the auto increment?

**Comment by berill** [comment]
hi @raymondfeng, any update around the uuid and autoIncrement support?

**Comment by superkhau** [comment]
@berill There are no set dates for any features. We take them on as they are prioritized in sprint planning. However, we do accept patches if you want to submit a PR. ;)

**Comment by berill** [comment]
eheheh @superkhau, didn't mean to sound like I was expecting it to be just done, sorry! ;-)

Was more wondering whether there was any road map around this particular issue.
At the moment, I'm still trying to find my feet with Node and loopback, but won't say not to contribute something back if possible!

**Comment by superkhau** [comment]
@berill No offense taken, I just wanted to give you a direct answer to make sure there is no confusion. Our public road map is here: https://waffle.io/strongloop/loopback. Feel free to contribute at your own pace, good luck with the learning. If you need any pointers, feel free to get help on one of our supported channels: https://github.com/strongloop/loopback/wiki/Questions. A lot of people there willing to help you out.
