### ISSUE TITLE
Rest Api taking long time i.e greater than 10 sec to serve google gecode api request

### ISSUE THREAD

**Issue by nitinshinde42** [strongloop/loopback-datasource-juggler#381]
I am using Rest connector to serve google geocode api, for this I defined
custom method template. But to serve the google geocode api, it takes more
than 10 secs. 
If request is made without rest connector, hardly it takes 256  millisecs. 
Here is code snippet. Can someone suggest what could be going wrong?

//define custom function template
module.exports = loopback.createDataSource({
    connector: require('loopback-connector-rest'),
    debug: false,
    operations: [
        {   
            template: {
                'method': 'GET',
                'url': 'http://maps.googleapis.com/maps/api/geocode/{format=json}',
                'headers': {
                    'accepts': 'application/json',
                    'content-type': 'application/json'
                },  
                'query': {
                    'latlng': '{latitude},{longitude}',
                    'sensor': '{sensor=false}'
                },  
                'responsePath': '$.results[0].address_components'
            },  
            functions: {
               'geocity': ['latitude', 'longitude']
            }   
        }   
    ]});

//function call
rest.geocity(loc[0], loc[1], function(err, result, res){
        
    if (result && result[0]) {
        ....
    }
});

**Comment by raymondfeng** [comment]
It's weird. The REST connector uses `request` too. I don't see how our code will add 12 seconds. Could be a Google throttling issue?

**Comment by raymondfeng** [comment]
Please provide a test case from a github repo to reproduce the problem and reopen this issue.
