### ISSUE TITLE
[like] and [nlike] filters wont search for numeric sequences in a string

### ISSUE THREAD

**Issue by daankets** [strongloop/loopback-datasource-juggler#385]
Passing a **numerical-only** LIKE filter value via a REST query will result into the sequence being parsed as a **Number**. This will result in an error during the **_coerce** function (dao.js). The numeric sequence should however be interpreted as text. For example, when looking through IBAN numbers using like, it's not possible to search using numbers only...

Further, it remains a very annoying fact that the like filter can't handle case insensitive queries. I propose an '**ilike**' operator for 'case insensitive like' operations...

**Comment by raymondfeng** [comment]
The plan is to add `regexp` operator.

**Comment by jdhiro** [comment]
I was surprised to see loopback doesn't support regex queries, but glad to hear they are on the way.

**Comment by superkhau** [comment]
Fixed at strongloop/loopback#963

**Comment by shubham201** [comment]
### Having problem for number and date types while using `regexp` operator.

@raymondfeng I am having one issue here related to `regexp` operator : 

> Tried querying 
- `{"where": {"string": RegExp(/^s/) } }` , 
- `{"where": {"string": {"regexp": RegExp(/^s/)}}}` & 
- `{"where": {"string": {"regexp": "^s"}}}` 
and These works fine.

> But, 
- `{"where": {"number": RegExp(/^1/) } }` , 
- `{"where": {"number": {"regexp": RegExp(/^1/)}}}` & 
- `{"where": {"number": {"regexp": "^1"}}}`
don't work. 
**And same is the case with date type properties. And also observed for strings having digits.**
Consider i have the appropriate data for querying them.

Is there any other way of querying for numbers, dates and strings having digits?
