### ISSUE TITLE
Discovery changes properties to lowercase

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-datasource-juggler#386]
`discoverSchema` changes property names as lowercase even when defined as camelcase. ie) `createdAt` is discovered as `createdat`. See https://github.com/strongloop/loopback-example-mysql#6-add-a-script-to-discover-a-schema-from-existing-data for a working example.

**Comment by f0ysal** [comment]
@superkhau @raymondfeng is there any update on this? I am also facing the same issue.

**Comment by conradj** [comment]
@superkhau @raymondfeng @f0ysal I seeing this as well, using PostgreSQL

**Comment by conradj** [comment]
@superkhau @raymondfeng @f0ysal This is my workaround: https://github.com/conradj/iotserver/blob/479d2beb469bc47c3644c9c63f79aac4dc0f7301/server/bin/discover-db-schema.js

**Comment by JacopKane** [comment]
Same here, when migrating builtin models like user are camel-case, but discovery reads  my tables as small-cased if it doesn't have underscores in it
