### ISSUE TITLE
Guids

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-datasource-juggler#388]
We should add a new type (or option) for automatically generating guids. Something like this:

```js
{myCustomId: {type: 'guid'}}
```

 - [x] implementation
 - [ ] docs

**Comment by kraman** [comment]
@ritch How do i set if this should be generated automatically or not

**Comment by fabien** [comment]
+1

**Comment by bajtos** [comment]
Based on our discussion in #453, we decided to go with a simpler approach - see #458.

**Comment by bajtos** [comment]
@crandmck I have described the new option `defaultFn` in a new row of the table of all property options in http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties. Please review and let me know if there is any other place where to mention this new option.

**Comment by crandmck** [comment]
@bajtos I reviewed your addition, and made some minor edits.  Added xref in http://docs.strongloop.com/display/LB/Using+the+model+generator#Usingthemodelgenerator-Addingdefaultvalues.  That's the only place I found that seems appropriate.

**Comment by bajtos** [comment]
@crandmck looks good, thank you :+1:
