### ISSUE TITLE
Handle invalid date

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#393]
new Date('foo') returns an instance of Date but it's invalid. We should test it as follows before passing to the DB:

```js
if ( isNaN( d.getTime() ) ) {  
    // date is not valid
 }
```

**Comment by kidwm** [comment]
I use `<input type="date">`, and the default value is empty string, that would make the API call fail.
And it seem no chance to correct this case in `observe('before save')` ?

**Comment by raymondfeng** [comment]
Maybe we should default the empty string to a `null` date.

**Comment by raymondfeng** [comment]
Do you want to create a patch around https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L483-L490?

**Comment by kidwm** [comment]
`if (!arg) return null;`
How about adding this line?
BTW, why not use `Date.parse()` here?
```js
// DataType for Date
function DateType(arg) {
if (!arg) return null;
var d = new Date(arg);
if (isNaN(d.getTime())) {
throw new Error('Invalid date: ' + arg);
}
return d;
}
```

**Comment by raymondfeng** [comment]
It should have been fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/470

**Comment by shaheero** [comment]
Using loopback 3.8 and linux x64 8.0.0, when the `date` field is equal `null`, a validation error is returned:
`ValidationError: The `myModel` instance is not valid. Details: `date` is not a valid date (value: Invalid Date).`

The property is defined as follows:
```
"date": {
      "type": "Date",
      "default": null,
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "date",
        "dataType": "datetime",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "Y"
      }
    }
```

It's worth mentioning that when I console.log the request data, it shows the date property with an empty string (not null as provided in the input)
`date: '',`

@raymondfeng

**Comment by jgwinner** [comment]
@shaheero I don't see anyone commented. I guess it's a closed item.
I'm running into this as well.

If a Date value is allowed to be null, I'd expect an invalid date to simply become 'null'. I guess this is debatable. Some libraries, for example the PyMySQL turn null dates into empty strings though.

I've already forked juggler due to issues with binary GUID's so maybe I just incorporate the same fix here ...

        == John ==
