### ISSUE TITLE
Per-method hooks

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#397]
A follow-up for #367.

As a LoopBack user, I want to execute my custom piece of code before/after a particular method is executed.
- the handler is async
- the handler can change input arguments and/or result (arguments passed to the callback)
- both static and prototype (instance) method can be overriden
- handlers are inherited by subclassed models

@raymondfeng suggested using a `ctx` object instead of a list of arguments in the handler

**Comment by ritch** [comment]
@bajtos - reopen if this shouldn't be closed.

**Comment by bajtos** [comment]
For anybody coming to this issue: we don't support per-method hooks, at least not at the level provided by `Model` class from loopback-datasource-juggler. There are other ways how to achieve this functionality, for example by using strong-remoting's before/after hooks, or by using a 3rd party library that can wrap model methods contributed by connectors into proxies allowing injections of custom code.
