### ISSUE TITLE
Shouldn't the data passed into beforeUpdate be the data before it's updated?

### ISSUE THREAD

**Issue by onyxrev** [strongloop/loopback-datasource-juggler#401]
I want to compare the data of a model before it's updated to the state after it's updated but the data in the beforeUpdate hook (and indeed in the beforeValidate hook) is already updated.  This seems counterintuitive to me.

See test: https://github.com/strongloop/loopback-datasource-juggler/blob/1b001eedd37f78eb76107ca3b2579f0f4ca700ea/test/hooks.test.js#L244

**Comment by onyxrev** [comment]
In general some way to get at the deltas in the hooks would be very helpful.  I could add the feature if others agree.

**Comment by raymondfeng** [comment]
We're deprecating `beforeUpdate` to favor http://docs.strongloop.com/display/LB/Operation+hooks. Can you try the new hooks? I'm closing the issue. Please feel free to reopen it if the new hooks don't support your use case.

**Comment by onyxrev** [comment]
At the moment, since the delta data is only populated in the updateAll case, it's not super helpful.  But I think the hooks are the right direction.
