### ISSUE TITLE
destroyAll with where break compatibility with loopback-connector-rest

### ISSUE THREAD

**Issue by tario** [strongloop/loopback-datasource-juggler#404]
I am using REST datasource and I am trying to make a simple delete from strongloop API explorer, it fails crashing the server with exception "TypeError: object is not a function"
It was reported on lookback-connector-rest, but maybe should be fixed on loopback-datasource-juggler
https://github.com/strongloop/loopback-connector-rest/issues/21

Stacktrace:
https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-connector.js#L271
https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-model.js#L53
...

The callback object used on rest-connector.js:L271 is defined here (Stacktrace): 
https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-connector.js#L268
https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-connector.js#L353
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L909

Note this line of code on dao.js
```javascript
    this.getDataSource().connector.destroyAll(this.modelName, where, function (err, data) {
```

It passes the "query object" as second argument to destroyAll function, destroyAll only forward the arguments in order and the second argument arriving on RestConnector.prototype.responseHandler is the same queryobject, later this object is used as "function" and then it fails with the error "Object is not a function"

Maybe I can fix this on my own fork, but I don't know what would be the best solution according your project to share it with you.

PD: beside this, the design ideas and the implementation of strongloop is pretty AWESOME

Edit: additional data, I found the change on b136a8fc, after version 2.9.0, maybe downgrading to that version of the npm would work fine for me

**Comment by raymondfeng** [comment]
@tario Thank you for reporting the inconsistency. IIRC, the `where` argument was added after the REST connector was built. Can you try to submit a patch to fix it in https://github.com/strongloop/loopback-connector-rest/issues/21?

**Comment by tario** [comment]
I will send a Pull Request, in what branch you need the fix ?

**Comment by tario** [comment]
I have yet another thing that seems like a wrong behavior related to delete, I have a strongloop "client" consumming another strongloop "server" using REST datasource, each time I delete an item requesting delete to client, server returns status code 204 No Content (According to this, it is ok http://www.restapitutorial.com/lessons/httpmethods.html), but client strongloop interprets it like an error and returns 500 Internal Server Error on the first request.

Since this bug(?) is not directly related to #404, I will create a separated issue for it

**Comment by raymondfeng** [comment]
Closing this issue to favor https://github.com/strongloop/loopback-datasource-juggler/issues/406
