### ISSUE TITLE
How to use Custom Model.find method Synchronously?

### ISSUE THREAD

**Issue by inawlaljar** [strongloop/loopback-datasource-juggler#410]
Hi, 

I am using a custom model and trying to filter it in a loop using find method. e.g. given below 

for i = 0 to n
{
  var u = User.find( where { name: 'john'});
}

It doesn't work. 

Also, if I use the following
for i = 0 to n
{
  User.find( where { name: 'john'}, function(u) {... <callback?>} );

  // How do I call the code for further processing? 
}

Is there a way to call find method synchronously ? Please help. 

Thanks,
Raj

**Comment by raymondfeng** [comment]
Try https://github.com/caolan/async <https://github.com/caolan/async>. In Node, most of apis are asynchronous. For better flow control, check out http://strongloop.com/strongblog/node-js-callback-hell-promises-generators/ <http://strongloop.com/strongblog/node-js-callback-hell-promises-generators/>.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by raymondfeng** [comment]
Please post further questions to https://groups.google.com/forum/#!forum/loopbackjs
