### ISSUE TITLE
dao.js in loopback-datasource-juggler giving error.

### ISSUE THREAD

**Issue by siddhant-mohan** [strongloop/loopback-datasource-juggler#425]
if (err) return cb(er);
                         ^
ReferenceError: er is not defined
    at done (/node_modules/loopback-datasource-juggler/lib/dao.js:1025:26)

callback is called with er object instead of err object.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-datasource-juggler/commit/79eabf3cf97b5db3aaf257986f3258a984fcb4cc
