### ISSUE TITLE
Multiple Models can't mixin same class after attached to a same data source

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback-datasource-juggler#429]
```js
Expert.on('dataSourceAttached', function (Expert) {
    Expert.mixin(Countable);
    Expert._mixins; //  [ Inclusion(), RelationMixin(), Countable() ]
    Expert.dataSource.DataAccessObject._mixins; // [ Inclusion(), RelationMixin(), Countable() ]
  });
```
After *mixin* a class to Model, the `DataAccessObject` of the *dataSource* that attached to that Model will also be altered. And all other Models that also attach to the same *dataSource* can't mixin `Countable`.

I think it's because that  all the Models are sharing(referencing) a same `_mixins` array with the `DataAccessObject` of *dataSource* which they all attached to. The `_mixins` property is defined in `jutil.mixin()` ([code](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L83)).

I'm thinking of two solutions:
1. **deep clone `sourceProperty` and/or merge into `targetProperty`**
2. **simply create a new array when pushing new value** at [line](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L37)
```js
newClass._mixins = [mixinClass].concat(newClass._mixins);
```

What do you think?

**Comment by raymondfeng** [comment]
I think here is what's happening:

1. The DataAccessObject class has a static property _mixins, which contains [Inclusion, RelationMixin].
2. The DataAccessObject class is then mixed into the model class, but we didn't create a new array of _mixins and merge the ones from the source class.

The fix could be:
1. In https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L68, we checks the presence of _mixins on both source and target and merge the ones from source into the target class.

**Comment by clarkorz** [comment]
@raymondfeng maybe not related, but what this line does? why self assigning?
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L80
> sourceProperty.value = sourceProperty.value;

**Comment by raymondfeng** [comment]
> @raymondfeng maybe not related, but what this line does? why self assigning?
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L80

> sourceProperty.value = sourceProperty.value;

@ritch Can you comment?

**Comment by ritch** [comment]
That Line has no purpose it should be removed

**Comment by raymondfeng** [comment]
@clarkorz Are you working on a PR?
