### ISSUE TITLE
Support persistent and serializable flags

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-datasource-juggler#432]
``` js
{
  type: 'string',
  persistent: true, // default true (persisted into db)
  serializable: true // default true (serialized into json)
}
```

**persisted** - only stored using the connector if `true` or `undefined`

**serializable** - if `false` the value will not be included in `.toJSON()` result

@raymondfeng @bajtos @fabien

**Comment by bajtos** [comment]
:+1: 

IIRC there are quite few older issues and mailing list threads that will be resolved once this is implemented. It would be nice to find them and link them to this story.

**Comment by clarkorz** [comment]
https://github.com/strongloop/loopback/issues/768

check @raymondfeng 's comment

**Comment by raymondfeng** [comment]
I would like to make the property configuration more flexible as follows:

For JSON mapping:
```json
"myProp": {
  "type": "string",
  "json": {
    "in": true,
    "out": true,
    "name": "my-prop"
  }
}
```
Please note that "json" is consistent with DB specific mappings such as "mysql".

* in - The property can be deserialized from the JSON object (I'm open to `deserializable` too)
* out - The property can be serialized into the JSON object (I'm open to `serializable` too)
* name - The custom name for the property in JSON. (I see the need to map `myProp` to `my-prop` in some cases).

A few shortcuts:
1. `"json": false === "json": {"in": false, "out": false, "name": "myProp"}`
2. `"json": "my-prop" === "json": {"in": true, "out": true, "name": "my-prop"}`
3. `undefined === "json": {"in": true, "out": true, "name": "myProp"}`

For persistence mapping:
```json
"myProp": {
  "type": "string",
  "persistence": {
    "in": true,
    "out": true,
    "name": "my-prop"
  }
}
```

* in - The property can be loaded from DB (I'm open to `deserializable` too)
* out - The property can be saved into DB (I'm open to `serializable` too)
* name - The custom name for the property in DB. (I see the need to map `myProp` to `my-prop` in some cases).

Please note "persistence" can be used to define common DB mappings for all DB types. Similar shortcuts are supported as for JSON.

**Comment by bajtos** [comment]
Sounds good :+1: 

An alternative naming: `json -> transport`, `persistence -> storage`. Just an idea to consider, the current proposal is ok.

**Comment by seriousben** [comment]
This is great! Thanks

**Comment by anjorinjnr** [comment]
Was this ever implemented?

**Comment by budasnorbi** [comment]
> Was this ever implemented?

This is a good question, also looking for the solution, but so far did't find any.
