### ISSUE TITLE
Question about accessing nested properties in query result object

### ISSUE THREAD

**Issue by aol-nnov** [strongloop/loopback-datasource-juggler#434]
Hi!
I have the following models:
```
{
    "name": "item",
    "base": "PersistedModel",
    "properties": {
        "name": {
            "type": "String"
        }
    },
    "relations": {
        "vendor": {
            "type": "belongsTo",
            "model": "vendor"
        }
   }
}
```
and
```
{
    "name": "vendor",
    "base": "PersistedModel",
    "properties": {
        "name": {
            "type": "string",
            "required": true
        }
    }
}
```

Here is the code snippet in question:
```
app.models.item.find({include: ['vendor']}, function(err, data){
                console.dir(data);
                console.log('typeof data[0] is', typeof data[0]);
                console.log('typeof data[0].vendor is', typeof data[0].vendor);
            });
```
it yeilds the following debug output:
```
[ { item_id: '1eb3b92b-78ee-4fa2-bdaf-bd4a012b6113',
    name: 'item 1',
    commonProps: { prop1: 'val1', prop2: 2 },
    vendorId: '3e9dc3f9-7c55-4d34-94e5-b899f9f8f30b',
    vendor: 
     { vendorId: '3e9dc3f9-7c55-4d34-94e5-b899f9f8f30b',
       name: 'ven 1',
       slug: 'ven-1' } },
  { item_id: '70e4052f-ed5d-41bf-9e4e-e9a8d83821a4',
    name: 'item 2',
    commonProps: { prop2: 22, prop3: 'val3' },
    vendorId: '3e9dc3f9-7c55-4d34-94e5-b899f9f8f30b',
    vendor: 
     { vendorId: '3e9dc3f9-7c55-4d34-94e5-b899f9f8f30b',
       name: 'ven 1',
       slug: 'ven-1' } } ]
typeof data[0] is object
typeof data[0].vendor is function
```
I'd like to pass ```data``` variable straight to templating engingine, but nested properties of a ```vendor``` field are not accessible inside of templating engine (due to it is not an object, but a function, I suppose).

Dirty workaround ```JSON.parse(JSON.stringify(data))``` before passing result to templating engine solved this issue, but I'm looking for more clear solution.

Please advice!

P.S.: the templating engine is handlebars, if it matters.

**Comment by clarkorz** [comment]
The `data` variable is an array of Model instance, you shouldn't pass it to template engine directly. You should call `toObject()` on each items, which will transform a model instance to plain object:
```js
data = data.map(function (item) { return item.toObject() });
```

**Comment by aol-nnov** [comment]
@clarkorz thanks for the response! I was thinking of ```toObject()``` too, but was (unsuccessfully) trying to call it against the whole ```data``` object.
So, I have to iterate over the returned ```data``` instance...

Well, just thought of something: what if it happen so, that there would be more levels of property nesting? Is there an elegant way around such situation too?

**Comment by aol-nnov** [comment]
I guess, I could borrow some bits of strong-remoting, but not yet found the place where the dataset is translated to the resulting JSON response.

**Comment by clarkorz** [comment]
@aol-nnov 
> that there would be more levels of property nesting

That's what `toObject()` will do :)

**Comment by aol-nnov** [comment]
> That's what toObject() will do :)

Do I get you right, that single ```toObject()``` call will walk through all levels of nesting for the object it was called against?

**Comment by clarkorz** [comment]
That's right

**Comment by aol-nnov** [comment]
perfect!
Thank you very much!
