### ISSUE TITLE
Adding additional data on save & create

### ISSUE THREAD

**Issue by janober** [strongloop/loopback-datasource-juggler#442]
Hello,

I would like to add the CAS value to the data as "_cas" for the Couchbase-Connector (to be able on save to check if the data changed). That works fine when data gets queried. However it seems like that is not possible for "create" and "save".

On "create" the data I can give the callback gets simply set as "id". So it is impossible for me to set data on the object that gets returned.

On "save" it seems even worst. There I can give no data at all to the callback.

So is there any way for me to achieve what I want to do?

Thanks!

**Comment by janober** [comment]
Anybody anything?

**Comment by superkhau** [comment]
Would you like to submit a patch?

**Comment by janober** [comment]
Actually first wanted to know if there is already a way because it seems like something that should be possible already. Want to avoid to "fix" something that does not need "fixing". 

If there is definitely no way (what I guess your comment means) then yes I can obviously look into it and submit a patch once done. Because of a deadline will not happen within the next month but afterwards I will. Added it to my to-do-list.

**Comment by loay** [comment]
Hi @janober 
Did you submit a patch? is this issue still persisting?
Thanks

**Comment by janober** [comment]
Sorry never got to it and considering my current to-do-list that will probably not change any time soon. So is still pending.

Ah yes thanks. I used the connector which is listed there. Tried to extend it and fix some issues that is when I came across this problem.

**Comment by loay** [comment]
@janober 
Thanks for your reply. We will close the issue for now. If you ever do a Pull request, please leave a comment here. Thanks.

**Comment by janober** [comment]
Had now another look and made the following change:
https://github.com/janober/loopback-datasource-juggler/commit/459988695d4ed657f062c024e538e4368f27f36e

Did not create tests yet because wanted to see first if the change would be ok and accepted like that.

**Comment by janober** [comment]
ping

**Comment by janober** [comment]
ping pong

**Comment by loay** [comment]
@janober 
Having a look. Thanks

**Comment by janober** [comment]
Great thanks! 

Is simply an additional parameter that can be used for the create-callback and an additional property for the already existing result for the save. Do not like that it would be inconsistent but they are already anyway. To not break any existing code something like that would probably be the best & easiest.

**Comment by loay** [comment]
The code is to add to the function the way to get the property for the existing results. I don't see code for save or create, unless there is something I am missing here. 
Also, to give you the bigger picture, the whole thing has to be there, because I can tell you that this function modification are acceptable, but when we try to implement the whole thing, it may fail our tests then we cannot implement it.

**Comment by janober** [comment]
Hi,

tried to write a test but to be honest really have no clue where it is supposed to go.

Ah yes did run the tests after making my changes and everything still worked fine. It got implemented in a way that nothing should break.

The changes make something like the following possible:

```javascript

MyConnector.prototype.create = function (model, data, callback) {
  // Create the entry in the database
  MyDatabase.create(data, function(err, createdEntry) {
    // "newData" has now a value set as "cas". This one we want to save on the
    // new instance as "_cas"
    callback(err,createdEntry && createdEntry.id, undefined, {"data": {"_cas": createdEntry.cas}});
  });
};


MyConnector.prototype.save = function (model, data, callback) {
  
  // Copy the data so that we do not change any outside values
  var dataCopy = extend({}, data);
  
  // Remove the cas because we do not actually want to save it in the database
  // and give it to the save-method as option
  var options = {};
  if (dataCopy.hasOwnProperty("_cas") ) {
    options.cas = dataCopy._cas;
    delete dataCopy._cas;
  }
  
  // Save the data in the database
  MyDatabase.save(dataCopy, options, function(err, newData) {
    // "newData" has an updated "cas" value which we want to save on the
    // new instance as "_cas"
    callback(err,undefined, {"data": {"_cas": newData.cas}});
  });
  
};
```

The changes in "create" L332 & L355 simply make sure that any data returned as forth parameter in the property "data" will get set additionally on the instance. In the above example it would be "_cas".

The changes in "save" L2219 do the same but on save. Checks simply if in the already existing third parameter anything is set as property "data" and if so sets it on the instance.

This changes allow now any datasource to add any kind of additional property on create & save. This is for example very important with Couchbase to be able to check if the data got changed in the meantime: http://developer.couchbase.com/documentation/server/current/sdks/dotnet-2.2/check-and-swap.html

**Comment by loay** [comment]
Thanks @janober 
I will give it a deeper look. I will ping you here again as soon as I am done.

**Comment by janober** [comment]
Any updates?

**Comment by loay** [comment]
Hi @janober 
Not yet. I will get back to you ASAP. Thanks.

**Comment by janober** [comment]
@loay Thanks have a nice week!

**Comment by janober** [comment]
Hi, wanted to check back again because I really need it. Any chance that it get merged? Thanks!

**Comment by janober** [comment]
Hi, has now almost been 6 months. Can I expected that to get merged? Thanks!

**Comment by janober** [comment]
Hello...

**Comment by smith64fx** [comment]
This is really important! Why does nobody care about it? =/

I have the same issue. When my ArangoDB Connector creates a model, i want to add an "_id" attribute aswell. But it doesn't work =(

@janober I like your solution. Gotta take it :) Thank you

And @loay We should really implement it cause it won't break any tests and is just *better* for any current and future connectors! Must have!!

**Comment by janober** [comment]
@smith64fx great to see that I am not the only one in the big wide world who did run into this issue ;-) Would also love if that would finally get merged. Is a very small and simple change which has a big impact.

**Comment by smith64fx** [comment]
@janober This issue can be closed.

Just use add this to your model
```
"updateOnLoad"
```
and the data will be saved:

This is from the dao.js
![image](https://cloud.githubusercontent.com/assets/3246782/21222020/21ff5654-c2c0-11e6-9102-43a827152bd4.png)

Example
```
{
  "name": "Client",
  "plural": "Clients",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "updateOnLoad": true
```

Very funny that nobody of us saw it :D
@loay this issue can be closed!

**Comment by janober** [comment]
Ehm stop. I wait since 6.5 months for it to get merged and did not get an answer since over 4 and then another person says it can be closed and within a few hours (without waiting for any confirmation or thought if it even makes any sense) it gets closed.

Sorry but I dont think it can get closed. I can not believe that setting "updateOnLoad" on the model will allow the datasource-juggler to set data it does not have. Like written above the callbacks for save & create do not allow that any data is given. The one for create only takes the id and the one for save nothing. So how would it get this value to set? Again this value was not there before (or was different). The database did create/update it and the datasource-juggler came never in contact with it.

The only way it could work with "updateOnLoad" is:
1. it would query it again form the database -> very waistful, so do not think so
2. there are some callbacks/hooks/... in the connectors I am not aware of which would get the data later -> can not imagine so and would be a very questionable design choice
3. magic -> who knows

Because I kind of believe in magic I gave it a try anyway and it did like expected not work. So I guess there is no Santa either...

So can any of you please either explain me if I overlook something very obvious and really should sleep more and tell me how I can make that work or please merge my PR.

Thanks a lot!

**Comment by superkhau** [comment]
@janober Sorry for the quick close, we can always reopen quickly though. ;) Thanks for chiming in again and clarifying. To be more clear -- we reserve issues for bugs/feature requests. You'll probably have better luck in determining whether your use case fits on our [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs) or [Gitter](https://gitter.im/strongloop/loopback) since it's more of a question. That said, are operation hooks not working for your use case? http://loopback.io/doc/en/lb3/Operation-hooks.html

**Comment by janober** [comment]
@superkhau Thanks for the fast answer. I would say this issue is something between a bug(its something what really has to work) and a feature (which is currently not possible). Some databases like Couchbase add additional properties to easily determine if the document changed in the meantime. Like you can imagine this is a very important piece of information (if you do not simply want to overwrite your data all the time) and currently there is no way to get that information on the model when it gets saved or created.
The hooks you are talking about are very hight level and are therefor not right for the this issue.
The solution is also incredible simple (if you look at my PR above) and does not break anything. So merging it should be no problem.

**Comment by superkhau** [comment]
@janober Can you submit a PR against this repo and link to it here? There is too much noise above. Let's continue this conversation in the actual PR review (the changes above LGTM, but I want to make sure via our CI and you'll need to add some tests to prevent regressions).
