### ISSUE TITLE
Question:Query filter comparison between fields.

### ISSUE THREAD

**Issue by violet-day** [strongloop/loopback-datasource-juggler#444]
Is any way to query like 

``` sql
select * from country where GNP>GNPOld
```

``` js
MaterielShippingPlan.find({
  $where:'this.quantity>this.shipped'
})
```

In some condition,it would need comparison between fields.

**Comment by raymondfeng** [comment]
We don't support it at the moment. It seems like a useful feature. 

AFAIK, $where in mongodb is not very performed.

**Comment by violet-day** [comment]
@raymondfeng I have made [PR](https://github.com/strongloop/loopback-connector-mysql/pull/77) to implement mysql.Please check

**Comment by loay** [comment]
Hi @violet-day
Concerning the PR, there were few comments to fix. Also, you need to accept the agreement, otherwise the tests will fail. 
Thanks.
