### ISSUE TITLE
Add where filter support for string lengths.

### ISSUE THREAD

**Issue by bradplank** [strongloop/loopback-datasource-juggler#448]
I would like the ability to use a where filter based upon the string length of a table column.  The where filter would then do the following based upon the DB connector type:

Sample SQL [loopback-connector-mssql]:
`SELECT * FROM dbo.User WHERE LEN(name) > 0`

Sample MongoDB [loopback-connector-mongodb]:
`User.where("this.name.length > 0")`

If the `loopback-datasource-juggler` is not the correct place for this feature request, please help me find the right place for this request.

Thank you!

**Comment by loay** [comment]
Hi @bradplank 
Yes, this is the right place.  Thanks

**Comment by loay** [comment]
Thanks @bradplank, we look into that. 
As a workaround: 
Did you try the following for Mongo: 
```
dbo.User.find( { $where: "this.name.length > 1" } );
```
In general, you can use the `length` but as in a function. For example, you use `User.find` to find all the users that fit your search criteria, then 
```
if (u.name.length >0) {console.log(u.name)}
```
I will make a request to add it as a feature.

**Comment by loay** [comment]
@bradplank 
Also, you can use native SQL:
https://docs.strongloop.com/display/LB/Executing+native+SQL

**Comment by dhmlau** [comment]
@loay has provided some ways to filter by string length.
It's been more than a year since we've replied, I'm closing it due to inactivity. 
Feel free to reopen if you are still running into this issue.  Thanks.
