### ISSUE TITLE
Refactor model/model-definition/model-buidler to strong-model module

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#450]
We should refactor the model definition code into its own module, such as `strong-model`.

Similar efforts:
- https://github.com/LearnBoost/mongoose/tree/master/lib/schema
- https://github.com/hapijs/joi
- https://github.com/bluefeet/o-js

**Comment by bosco-li** [comment]
Assigning to Apex since the team will be owning the FA in 2017

/cc @0candy @kjdelisle @pthieu
