### ISSUE TITLE
updateAll not working as expected when using the memory connector

### ISSUE THREAD

**Issue by steirico** [strongloop/loopback-datasource-juggler#455]
Accordingly to the docs at http://apidocs.strongloop.com/loopback/#persistedmodel-updateall, the callback of `updateall`  should pass the number of updated data sets by the parameter `count`.

Using the Memory connector, the result for `count` is always `null`. Furthermore, `err` is always equal to `null`, even if no data set was updated. Consequently, there is no way to test if the update was successful or not.

**Comment by raymondfeng** [comment]
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/pull/321
