### ISSUE TITLE
Support lazy connection for data sources

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#463]
At the moment most connectors eagerly create a connection pool or connections to the backend before any request to the connector is received. We should establish a way for connectors to lazily initialize or connect.

**Comment by bajtos** [comment]
Cross-posting conversation from SlackChat.

@raymondfeng 
> Connectors use this pattern at the moment
> 1. The top level is a factory
> 2. It has connect/disconnect on the instance

@bajtos
>  I think we need two things:
>  1) a way how to specify that the application should not connect to datasources - because now we do `require('path/to/app')`, which does not allow to pass any options
> 2) in connectors and/or the juggler, honour this new option

> > 1 can be controlled via env var
> This is a bit concerning to me, what if somebody happen to have the env var set up by accident? I think a global javascript variable may be safer, or perhaps a new custom property on `process` object. Not a big deal though.

**Comment by bajtos** [comment]
AFAICT, at least the MySQL connector does not provide `connect` method and connects immediately from `initialize`. I think in order to implement this issue, we will have to fix all connectors to correctly implement `connect` method.

While we are at changing this, it would be nice to document the new expectation in https://docs.strongloop.com/display/APIC/Building+a+connector

**Comment by bajtos** [comment]
@jannyHou what modules are remaining to release to make this feature widely available?

**Comment by jannyHou** [comment]
**CHECKLIST**

- [ ] (Released 2.0.0) Add flag in apiconnect-cli-loopback https://github.ibm.com/apimesh/apiconnect-cli-loopback/pull/60
- [x] Read flag in loopback-boot https://github.com/strongloop/loopback-boot/pull/185

Only trigger connect phase in connectors
- [ ] (Released 1.0.16) db2 https://github.com/strongloop/loopback-connector-db2/pull/31
- [ ] (Released 1.0.10) cloudant https://github.com/strongloop/loopback-connector-cloudant/pull/16
- [x] mysql https://github.com/strongloop/loopback-connector-mysql/pull/166
- [ ] (Released 1.15.0) mongodb https://github.com/strongloop/loopback-connector-mongodb/pull/241
- [x] mssql https://github.com/strongloop/loopback-connector-mssql/pull/80
- [x] postgresql https://github.com/strongloop/loopback-connector-postgresql/pull/140
- [x] oracle https://github.com/strongloop/loopback-connector-oracle/pull/64

**Comment by bajtos** [comment]
Released loopback-boot@2.19.0

**Comment by bajtos** [comment]
@jannyHou could you please work with @raymondfeng and/or @superkhau to get the remaining connectors released?
