### ISSUE TITLE
Add before/after hooks for connector native operations

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#464]
The connector translates model methods into native operations implemented using a driver to its backend. It's often desirable to inject some logic before/after a native operation is invoked. For example, connectors for databases should allow hooks to intercept DB commands. REST/SOAP/REMOTE connectors should allow hooks to access HTTP req/res objects.

- [x] REST connector
- [x] SOAP connector
- [x] SQL connectors
- [x] MongoDB connector

**Comment by chandadharap** [comment]
PRs are not done with review, moving it back to review.

**Comment by fabien** [comment]
@raymondfeng interesting stuff +1
