### ISSUE TITLE
Refactor common logic for relational DBs into the base SQL connector

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#468]
* Build query from the filter object (Query Builder)
  - buildWhere
  - buildSelect
  - buildOrderBy
  - buildPagination
* Map between model/property and table/column (Metadata Mapper and Value Converter)
  - Convert values between JSON and DB for DMLs
  - Map between model definitions and DB schemas for DDLs
  - ID/Key types/values
  - Escape identifiers and values
    - escapeIdentifier
    - escapeValue
* Generate SQL statements and parameters (SQL Builder)
  - DMLs for CRUD operations (create, find, update, delete, count)
  - DDLs for schema discovery and schema definitions (create/alter/drop)

**Comment by raymondfeng** [comment]
The following has been achieved:

1. Refactor most of the common logic for SQL based connectors into the base Connector and SqlConnector. 

2. Rebase loopback-connector-mysql and loopback-connector-postgresql to use the new base classes

3. Refactor out migration and discovery logic into their own JS files.

See:

- https://github.com/strongloop/loopback-connector/tree/feature/connector-refactor
- https://github.com/strongloop/loopback-connector-mysql/tree/feature/connector-refactor
- https://github.com/strongloop/loopback-connector-postgresql/tree/feature/connector-refactor
- https://github.com/strongloop/loopback-datasource-juggler/tree/feature/connector-refactor

**Comment by raymondfeng** [comment]
Todos:

1. Rebase loopback-connector-mssql
2. Rebase loopback-connector-oracle
3. Test loopback-connector-mongodb
4. Refactor the common migration/discovery logic into base SqlConnector
5. Rebase the connectors to use the common migration/discovery logic

**Comment by chandadharap** [comment]
Please break up into individual stories as applicable. I suggest a Rebase story for 1, 2, 3. a Refactor story for 4. and one for 5 and one for 6. Does that make sense?

**Comment by raymondfeng** [comment]
See:
1. https://github.com/strongloop/loopback-connector/issues/14
2. https://github.com/strongloop/loopback-connector/issues/15
3. https://github.com/strongloop/loopback-connector/issues/16

**Comment by chandadharap** [comment]
Foundation work is done. Rest is broken up and captured.
