### ISSUE TITLE
Performance: Extended User model relations take 20 times longer to fetch

### ISSUE THREAD

**Issue by smstromb** [strongloop/loopback-datasource-juggler#471]
I've been noticing lately that all the relations I have on user model that I extended from Loopback's base User model take an insane amount of time to load. At first I blamed a slow mongoDB connection but just recently I recreated the issue using a fresh loopback app and an in-memory database to negate any latency from my DB and I'm still getting response times that average ~250ms for a single join. 

Note: This is only an issue if extending 'User'. If I modify my user model to extend from PersistedModel instead, the return times are ~10ms.

Recreation steps:

1. Create new loopback app
2. Use cli to create following models and relationships

user.json
```
{
    "name": "user",
    "base": "User",
    "idInjection": true,
    "scope": {
        "include": "foo"
    },
    "properties": {},
    "validations": [],
    "relations": {
        "foo": {
            "type": "hasOne",
            "model": "foo",
            "foreignKey": "userId"
        }
    },
    "acls": [],
    "methods": []
}
```
foo.json
```
{
  "name": "foo",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": []
}
```

3. Set LB's default User model to 'public:false'

model-config.json
```
  "User": {
    "dataSource": "db",
    "public": false
  },
```
via /explorer:
4. Create test user
5. Authenticate with api/users/login
6. Create foo object for user
7. GET /api/users/1

result: 257ms
```
{
  "email": "my@email.com",
  "id": 1,
  "foo": {
    "name": "bar",
    "id": 1,
    "userId": 1
  }
}
```

If I query for just the user without automatically including 'foo', the response time is ~10ms. If I query just for 'foo', it again responds in only ~10ms. 

Why is the sum of these two calls over 20 times slower?

**Comment by raymondfeng** [comment]
I found the culprit in User.setter.password which uses `bcrypt` to hash the password. The setter is triggered when a record is loaded from the database too even the password is already hashed. I'll add a fix soon.

**Comment by smstromb** [comment]
Is this a safe fix? Hypothetically, if a user entered a hash as their password during user creation (if they use a password manager that uses the blowfish cypher for example), that password would never be hashed and they would never be able to login.

**Comment by raymondfeng** [comment]
I think the chance is rare for two reasons:

1. Using a 64 bytes hashed string is rare.
2. It's the user's choice to supply such password, not forced by others.

**Comment by dakotahNorth** [comment]
Using User with bcrypt (0.8.5) still results in unusually long times. I have 60 unit tests that normally takes a little less then 4 seconds to run. When I switched to inheriting to User, resulted in unusually long times ... 12 seconds.

That is a huge increase in test run times from just inheriting from the User model. Do I need to do anything else besides for including bcrypt as a dependency?
