### ISSUE TITLE
removeUndefined in doDelete() will cause destroyAll items in table.

### ISSUE THREAD

**Issue by TonnyTao** [strongloop/loopback-datasource-juggler#479]
This is a great disaster!

```javascript
Tag.destroyAll({userId: undefined})   //this will remove all tags in Tag table.
```

**Comment by raymondfeng** [comment]
Should we report it as an error if `undefined` values are seen in the `where` statement?

**Comment by fabien** [comment]
Yes, we should throw in this case. Unlike `null`, `undefined` is really tricky.

**Comment by raymondfeng** [comment]
PR is welcome!

**Comment by loay** [comment]
Hi @TonnyTao 
The issue is reported as a bug: https://github.com/strongloop/loopback-datasource-juggler/issues/492
We will try to fix it as soon as we can. 
Thanks.

**Comment by loay** [comment]
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/492
