### ISSUE TITLE
Shared state for hooks invoked for a single operation

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#484]
Add a context property that will be preserved across all hooks invoked for a single operation.

For example, both "access", "before save" and "after save" invoked for `Model.create()` should have the same object passed in `ctx.hookState`.

This way the hooks can pass state date between "before" and "after" hook.

/cc @fabien

**Comment by fabien** [comment]
@bajtos I would like to give this - and `targetData` a shot - unless you have time to do this now?

**Comment by bajtos** [comment]
@fabien I don't have time for that now, I'll reassign to you. Can you please send `targetState` in a standalone pull request? I think this part will pretty much unopinionated, thus the pull request can be merged sooner.

What is the idea behind `targetData`? If you are referring to our discussion in #483, then let's keep the comments there and don't spread them across multiple issues.

**Comment by fabien** [comment]
@bajtos yes, let's keep `targetData` at #483

**Comment by bajtos** [comment]
Implemented by #485.
