### ISSUE TITLE
Caution: prototype.destroy - verify that id is defined

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#492]
At the moment, when you call `destroy` on an instance that has no `id` (as deduced by `getIdValue`), the delete is still performed. This wasn't an obvious issue before, but the problem is that the following is passed to the `before delete` and `after delete` operation hooks:

```
where: { id: undefined }
```

Which is an invalid condition that might have disastrous results when using it in such a hook.

**Comment by fabien** [comment]
I can confirm that it does wipe out all instances in this case (the condition is effectively reduced to `where: {}`) - which means this is somewhat critical.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-datasource-juggler/issues/479. I'm proposing to report `undefined` values in `where` as errors.

**Comment by fabien** [comment]
I think in this case it wouldn't hurt bailing out early and throwing an error before even attempting to run any `delete` hooks.
