### ISSUE TITLE
Arbitrary client side id injection possible over POST Model API

### ISSUE THREAD

**Issue by craigcabrey** [strongloop/loopback-datasource-juggler#496]
Using a generated API for a `PersistedModel` (such as the builtin `User` model), it is possible to create the resource with any id.

For example, `POST /api/Users` with:

```js
{
  "id": 10000,
  "email": "test@abc.com",
  "password": "password"
}
```

The system accepts this request and creates a new `User` with an id of 10000. Is this intended behavior? If so, is there a proper way to disable this client side injection ability?

**Comment by craigcabrey** [comment]
Our current workaround:

```js
module.exports = function(app) {
  app.models().forEach(function(model) {
    model.beforeRemote(
      'create',
      function(ctx, modelInstance, next) {
        delete ctx.args.data.id;
        next();
      }
    );
  });
};
```

**Comment by raymondfeng** [comment]
What connector do you use?

**Comment by loay** [comment]
Hi @craigcabrey 
Is this issue still persisting?
Thanks.

**Comment by loay** [comment]
Closing this issue. Also, this issue is currently being fixed: https://github.com/strongloop/loopback-datasource-juggler/issues/849
If you are still running into similar problems after the fix is being landed, please feel free to leave a comment and I will re-open the issue. Thanks.
