### ISSUE TITLE
Embedded relations vs. operation hooks

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#497]
With `beforeValidate` being deprecated and because embedded instances are not persisted directly, `before save` is never called. See for example:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2016

Any `beforeValidate` hooks on 'transient' models cannot be implemented anymore. Either we fake such a notification of `before save`, or we reintroduce a `validate` hook event across the board. The latter makes most sense, despite the team's effort to minimize the new hooks API.

**Comment by bajtos** [comment]
Hello everybody, #904 and #911 added basic support for operation hooks in the scope proposed by this pull request. You can `npm install strongloop/loopback-datasource-juggler#2.x` to try it out before we publish a new version to npmjs.org.

create() triggers
 - before save
 - after save

updateById() triggers
 - before save
 - after save

destroy() triggers
 - before delete
 - after delete

**Limitations**

 - `before save` & `after save` hooks don't provide `ctx.isNewInstance`
 - async validations are not supported yet
 - `persist` and `loaded` hooks are not triggered at all

 - `before delete` hook does not provide `ctx.where` property and
    it's not possible to change the outcome of `destroy()` using this
    hook. Note that regular DAO does support this.

 - updating embedded instances triggers update of the parent (owning)
   model, which is correct and expected. However, the context provided
   by `before save` and `after save` hooks on the parent model is sort of
   arbitrary and may include wrong/extra data. The same probably applies
   to the scenario when deleting embedded instances triggers update of
   the parent model.

I am closing this issue as done, please open a new issue for anything you are missing in the current implementation.
