### ISSUE TITLE
Bug or edge case in list.js

### ISSUE THREAD

**Issue by jrschumacher** [strongloop/loopback-datasource-juggler#505]
I was debugging my application and I think I found a bug or edge case: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/list.js#L74

In the reference above we are checking for `this.itemType && (obj instanceof this.itemType)` if `this.itemType` were to be undefined or false then it would make the condition false and run `this.itemType(obj)` which would then throw an error in reference to it *not* being a function.

**Comment by raymondfeng** [comment]
@jrschumacher Can you provide a model definition that can be used to reproduce the problem?

**Comment by jrschumacher** [comment]
@raymondfeng I don't have one. I was tracing the code and just saw it in my mind. I'll see if I can throw something together to see if it truly is.

**Comment by loay** [comment]
Hi @jrschumacher 
Is this issue still presisting? 
Also, there is a reported bug, where if it the item is `undefined`, then it will throw an error. 
https://github.com/strongloop/loopback-datasource-juggler/issues/492
Is it related to your case? if not, can you please provide more info or a repo to reproduce? Thanks.

**Comment by jrschumacher** [comment]
@loay no I'm going to close this. My issue was resolved a long time ago and I read through the code again and I don't believe this is an edge case as I originally thought.
