### ISSUE TITLE
Add Retry Logic

### ISSUE THREAD

**Issue by idosh** [strongloop/loopback-datasource-juggler#506]
Cloud providers encourage to add retry logic to database queries to overcome transient failures.
[Article about retry logic in Azure](http://social.technet.microsoft.com/wiki/contents/articles/4235.retry-logic-for-transient-failures-in-windows-azure-sql-database.aspx)

**Comment by raymondfeng** [comment]
We plan to add `connector` level hooks. They can be used for retry.

**Comment by loay** [comment]
Hi @idosh 
Does raymondfeng's  comment answer your concern? Thanks.

**Comment by idosh** [comment]
Yes, thanks
