### ISSUE TITLE
modelBuilder oddness

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-datasource-juggler#512]
so, I am trying to build a model. This is the program :

```javascript
var boot = require('loopback-boot');
var app = require('../server/server.js')

var db = app.dataSources['mem']

var schema = {
 "name": "Invoiceline",
 "properties": {
  "invoicelineid": {
   "type": "Number",
   "required": true,
   "length": null,
   "precision": 32,
   "scale": 0,
   "id": 1
  }
 }
}
db.modelBuilder.buildModels(schema)
```
this falls over with the following error :

**/usr/local/lib/node_modules/loopback-datasource-juggler/lib/model-builder.js:122
    throw new Error('Class name required');
          ^
Error: Class name required**

I modified modelBuilder.js to read as follows

```javascript
for (var s in schemas) {
    console.log("working on",schemas[s])
    var name = this.getSchemaName(schemas[s].name);
    schemas[s].name = name;
    var model;
    if(typeof createModel === 'function') {
      model = createModel(schemas[s].name, schemas[s].properties, schemas[s].options);
    } else {
      model = this.define(schemas[s].name, schemas[s].properties, schemas[s].options);
    }
    models[name] = model;
    relations = relations.concat(model.definition.relations);
  }
```
this gives the console output
```javascript
working on { name: 'Invoiceline',
  properties: 
   { invoicelineid: 
      { type: 'Number',
        required: true,
        length: null,
        precision: 32,
        scale: 0,
        id: 1 } } }
working on function (predicate) {
    if (this == null) {
      throw new TypeError('Array.prototype.findIndex called on null or undefined');
    }
    if (typeof predicate !== 'function') {
      throw new TypeError('predicate must be a function');
    }
    var list = Object(this);
    var length = list.length >>> 0;
    var thisArg = arguments[1];
    var value;

    for (var i = 0; i < length; i++) {
      value = list[i];
      if (predicate.call(thisArg, value, i, list)) {
        return i;
      }
    }
    return -1;
  }
/usr/local/lib/node_modules/loopback-datasource-juggler/lib/model-builder.js:122
    throw new Error('Class name required');
```
this is odd, because there is only 1 item in the supplied schema (so where does the second **working on** come from ? )

after some digging, it seems as if the offending code is at line 730 of modelBuilder.js 
``` model = this.define(schemas[s].name, schemas[s].properties, schemas[s].options);```

if I comment this line out, I only get 1 **working on** entry in the console.

Also, if I change 
```javascript
for (var s in schemas) {
```
to
```javascript
schemas.forEach(function(schema) {
```
(and replace all schemas[s] with schema)

it doesn't crash

**Comment by fabien** [comment]
`buildModels` takes an array of schema definition objects and it looks like you're passing in a single object instead.

**Comment by jmls** [comment]
nope, if you look in the lines above there is this code

``javascript
// Normalize the schemas to be an array of the schema objects {name: <name>, properties: {}, options: {}}
  if (!Array.isArray(schemas)) {
    if (schemas.properties && schemas.name) {
      // Only one item
      schemas = [schemas];
    } else {
      // Anonymous schema
      schemas = [
        {
          name: this.getSchemaName(),
          properties: schemas,
          options: {anonymous: true}
        }
      ];
    }
  }
```

**Comment by fabien** [comment]
Yes, I just spotted that too, strange...

**Comment by jmls** [comment]
and just for the purposes of completeness,
```javascript
var schema = [{
 "name": "Invoiceline",
 "properties": {
  "invoicelineid": {
   "type": "Number",
   "required": true,
   "length": null,
   "precision": 32,
   "scale": 0,
   "id": 1
  }
 }
}]
```
(ie passing in an array)
fails with the same error

**Comment by fabien** [comment]
I think you should investigate where `Array.prototype.findIndex` comes from - it looks like a polyfill for ES6: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

**Comment by raymondfeng** [comment]
That's the danger to use `for(var s in schemas)` to iterate over an array. I'll fix that code.

**Comment by jmls** [comment]
@fabien : spot on, I just found that &*^&%*%&^%^ polyfill in one of my libraries. stripped it out, working now .. thanks.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/513

**Comment by loay** [comment]
Issue is fixed as per PR 513. Closing
