### ISSUE TITLE
Document polymorphic.idType

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#517]
See #507.

**Comment by davidcheung** [comment]
Hi @fabien, @raymondfeng 
I'm trying to document the [`polymorphic.idType`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1237-L1241) property, 
- Was wondering if this is the correct understanding of it?
- and if so any thoughts on whether it clarifies the property?
- and are there other properties from polymorphic relationship that we should add to the docs as well? 

```
//For example, a polymorphism "hasMany" relationship exists between School and (Student, Teachers, Staff) through `Person`
//the idType of polymorphic models will default as the modelFrom ID
[ //Collection of `Person`
  {/*Person-Object(From student)*/
    id: 1,
    personId : 1, //PersonId.type inherits from student
    studentName : "foo"
  },
  {/*Person-Object(From Staff)*/
    id: 2,
    personId : 2, //PersonId.type inherits from staff
    staffRank : "rank"
  },
  {/*Person-Object(From Professor)*/
    id : 3,
    personId : 3, //PersonId.type inherits from professor
    faculty : "science"
  }
]
//You may explicitly specify idType of Person by 
Student.belongsTo('Person',{
  polymorphic : {
    foreignKey: 'personId',
    discriminator: 'personType',
    idType: {Explicit-Model-IdType}
  }
});
```

**Comment by raymondfeng** [comment]
@davidcheung What does the Student belongsTo Person relation for?

**Comment by davidcheung** [comment]
@raymondfeng 
It would be for scenario such as 
``` 
School.hasMany("person", {
  model: "Student",
  polymorphic: "person"
});
```

**Comment by raymondfeng** [comment]
Sure, but for belongsTo, you just say `Student` belongsTo `School` right? I don't see the ploymorphic coming in play for `belongsTo`

**Comment by raymondfeng** [comment]
This test makes more sense - https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L1721-L1746

**Comment by davidcheung** [comment]
@raymondfeng 
if School wants to treat multiple different type of models (student/teacher/professor), is that how an example could work?
```
School.hasMany("person", {
  model: "Student",
  polymorphic: "person"
});
School.hasMany("person", {
  model: "Teacher",
  polymorphic: "person"
});
School.hasMany("person", {
  model: "Professor",
  polymorphic: "person"
});
```

**Comment by davidcheung** [comment]
@raymondfeng thanks, I will use that example instead.
> This test makes more sense - https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L1721-L1746

**Comment by raymondfeng** [comment]
In the example above, you should see instances like:

Author: 
- {id: 1, name: 'John'}

Reader: 
- {id: 1, name: 'Marry'}

Pictures:
- {oid: 1, type: 'Author', ...} // pic for John
- {oid: 1, type: 'Reader', ...} // pic for Mary

**Comment by davidcheung** [comment]
@raymondfeng Thanks! 
@crandmck I have added a [temp restricted page](https://docs.strongloop.com/display/LB/Copy+of+Polymorphic+relations) in the docs, please take a look, thanks!

**Comment by crandmck** [comment]
Changes by @davidcheung LGTM.  I copied them into https://docs.strongloop.com/display/LB/Polymorphic+relations.  

This issue can be closed now, but if possible, I would really like to address the comments at the top of the document, although strictly speaking they are outside the scope of this issue... but while we're working on it...

**Comment by davidcheung** [comment]
Closing this issue, opened another issue to address the community comments regarding the current examples.
