### ISSUE TITLE
Premature merge of PR #515 - connectors not ready for changed API

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#523]
@bajtos The merge of #515 introduces an unexpected API change - the connector should return the updated data, as part of 3 instead of 2 arguments. While the memory connector has been (silently) updated, the MongoDB connector (for example) has not been updated, nor is there a branch/PR with these changes pending.

https://github.com/strongloop/loopback-datasource-juggler/commit/84d538c1cac9eab7f2faa1029f74aead4fa3ddc9#diff-d717a01e40d8164976e4468af1bce663R1590

/cc @raymondfeng

**Comment by bajtos** [comment]
As I commented in the commit, this change was not intentional, I'll fix it on Monday.

**Comment by bajtos** [comment]
I find surprising that our CI build did not detect this problem for us. @rmg could you please check why the recent changes in the master branch of loopback-datasource-juggler did not trigger CI build of loopback-connector-mysql (and all other connectors)?

**Comment by rmg** [comment]
@bajtos only some of the connectors depend on loopback-datasource-juggler, and CI wasn't using devDependencies for generating these particular build triggers. I'm changing that now.
