### ISSUE TITLE
updateOrCreate fails to update a model with id 0

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-datasource-juggler#547]
This is a corner-case: `updateOrCreate` fails to update an existing model with a numeric ID that has a value of zero because the following lines of code evaluate zero as false, even though a valid `id` exists.

```
  if (!id) {
    return this.create(data, options, cb);
  }
```

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L363-L366

**Comment by raymondfeng** [comment]
Good catch. We should fix it. Do you want to submit a patch?
