### ISSUE TITLE
Support regular expressions in SQL connectors.

### ISSUE THREAD

**Issue by carragom** [strongloop/loopback-datasource-juggler#552]
Hello,

I would like to start a discussion about adding a new filter for regular expressions in where clauses. AFAIK the only supported database without native regex support is MSSQL. All others have the feature. Here are some links:

https://dev.mysql.com/doc/refman/5.5/en/regexp.html
http://www.postgresql.org/docs/9.0/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP
http://docs.oracle.com/cd/B19306_01/server.102/b14200/conditions007.htm

I have a working patch for the postgresql connector. I would like to submit it for review but first some questions:

* What would be an acceptable keyword for this ?. rlike, regex ?.
* What would be the correct way to handle this in a connector where this functionality is not available?. Throw and error?.
* Should it be case insensitive by default?.

Thanks.

**Comment by superkhau** [comment]
Bumping up to 3 points because its taking longer than the expected 2 points.

/cc @chandadharap

**Comment by superkhau** [comment]
Bumping up to a 5 as it's taken 2 days now.

//cc @chandadharap
