### ISSUE TITLE
Embedded relations + includes + toJSON

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#555]
Currently, when including embedded relations, you'll end up with 'duplicate' attributes (and data), for example: `addresses` (the included relation) and `_addresses` (the actual attribute ~ keyFrom). I'd say, for consistency we should purge the `_addresses` when calling toJSON in this situation, and only keep `addresses` to reflect the relation name. Thoughts?

@raymondfeng @bajtos

**Comment by bajtos** [comment]
> I'd say, for consistency we should purge the `_addresses` when calling toJSON in this situation, and only keep `addresses`  to reflect the relation name. Thoughts?

Makes sense to me.

Perhaps the field `addresses` should be populated always, even when the embedded relation is not listed in `includes`, because that's the point of embedded relations, isn't it?

**Comment by clarkorz** [comment]
Is there a way to use same name (`addresses`) for both relation and property?
