### ISSUE TITLE
idName should be resolved and passed to connector

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-datasource-juggler#556]
If a model is defined with a field such as: 

```
seq: {type: Number, index: true, id: true} 
```

Then for: 

```
MyModel.findOne({where: {id: xxx}} ... 
MyModel.all({order: 'id'} ... 
```

I think that it is reasonable to expect the core code to map `id` to the actual field name (like `seq` in this case) before calling the connector implementation ... but right now that doesn't happen

Right now I see the following logs when the connector receives a call from the juggler: 

```
{"where":{"id":0},"limit":1,"offset":0,"skip":0} 
```

being passed to the connector as an argument ... instead of the actual identifier which in this case is `seq` ... so ideally something like the following should reach the connector instead: 

```
{"where":{"seq":0},"limit":1,"offset":0,"skip":0}
```

**Comment by pulkitsinghal** [comment]
For the original support thread, strongloop folks can refer to: https://support.strongloop.com/requests/669

**Comment by bajtos** [comment]
I'm cross posting @raymondfeng's answer from the support thread:

>
The `find` or `findOne` method on the model passes the query that uses the model property names, even for id properties. In your case, `seq` should be be used instead of `id`. The name(s) of id properties are completely controlled by the model definition. Please note the PK can be a composite key that consists of multiple properties. 

> For a model like:
```
User = db.define('User', { 
id: {type: Number}, 
seq: {type: Number, id: true}, 
name: {type: String, sort: true}, 
});
```
> Only the `seq` is an id property.

> In the connector, the id name(s) can be found as idName() or idNames() from the base connector class. 

@pulkitsinghal I can see the support ticket was closed, can we consider this issue as resolved? If not, then what change would you like to see?

Loosely related: https://github.com/strongloop/loopback/issues/126

**Comment by pulkitsinghal** [comment]
I went to the support ticket:
https://support.strongloop.com/hc/en-us/requests/669

But I didn't see the quoted feedback there ... Maybe I went to the wrong place now or maybe I placed an incorrect URL in my previous comments ... I'm unsure.

@bajtos - Based on the comment you posted, here's my takeaway:
> It is the connector's job to match the string literal `id` and then use `idName()` or `idNames()` to substitute it as needed.

  * Correct?
  * So it becomes my task to fix/enhance the elasticsearch connector to do this and make sure the unit tests cover it ... Correct?

I hope you answer yes and yes, in which case, go ahead and close this out.

Otherwise, maybe explain it to me again why or how my expectations here are incorrect.

**Comment by raymondfeng** [comment]
@pulkitsinghal I think you are proposing a virtual `id` property that will be mapped to the physical primary key by LoopBack. It's probably a nice to have feature. But I would prefer to name it differently such as `$id` to avoid conflicts.
