### ISSUE TITLE
Check for availability of Connector.exists()

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-datasource-juggler#557]
Juggler doesn't check the presence of Connector.exists() today

**Comment by pulkitsinghal** [comment]
Can you point me to a sample line of code elsewhere in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js that shows any other such method whose `Connector.myMethod()` presence is being checked so I may mimic. I'm very new to JS. Then I can submit PR.

**Comment by 0candy** [comment]
We do check whether the connector exist.
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L235-L248

Could you give more info on what are you trying to do?

**Comment by pulkitsinghal** [comment]
Thanks @0candy cannot remember what I was doing back then.

**Comment by 0candy** [comment]
Thanks for the follow up. Sorry for the delay.
