### ISSUE TITLE
Notification on client when change event happens on server

### ISSUE THREAD

**Issue by chandadharap** [strongloop/loopback-datasource-juggler#563]
Would like a feature to be notified on the client when a change event happens on the server. 

Refer previous cs issue for context:
https://github.com/strongloop-internal/scrum-cs/issues/79

**Comment by bajtos** [comment]
> Would like a feature to be notified on the client when a change event happens on the server.

I believe this request should have been addressed by the new liveset feature as described in https://strongloop.com/strongblog/build-real-time-apps-with-angular-liveset-and-loopback/.

I am closing this feature as done. @sumitha could you please check with the customer whether the liveset feature addresses their needs and reopen the issue if necessary?
