### ISSUE TITLE
Throw an error when model uses unknown mixin

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#566]
At the moment, when a model wants to apply a mixin that does not exist, LoopBack silently ignores this instructions with a log message printed via `debug`. This behaviour makes it difficult to spot and troubleshoot such issue. 

I am proposing to throw an error when the mixin is not found.

/cc @raymondfeng @fabien

**Comment by listepo** [comment]
+1

**Comment by davidcheung** [comment]
Info placeholder : 
https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/mixins.js#L42

**Comment by alexpit** [comment]
issue solved via #944, closing

**Comment by alexpit** [comment]
reopen to include in test

**Comment by bajtos** [comment]
We usually don't verify stories that affect code API only.
