### ISSUE TITLE
unsetAttributes & save() vs. updateAttributes()

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#567]
It appears that the following does not work as expected:

```javascript
inst.unsetAttribute('foo'); // used to be: 'bar'
inst.updateAttributes({ other: 'thing' }, next);

// result when re-fetched from db:

inst.foo === 'bar';
inst.other === 'thing';

// expected:

inst.foo === undefined;
inst.other === 'thing';

```

However, the following DOES work:

```javascript
inst.unsetAttribute('foo'); // used to be: 'bar'
inst.other = 'thing';
inst.save(next);
```

Which indeed confirms that `updateAttributes` is a partial update. This begs the question: how can one completely 'replace' an object's attributes using a REST Api call - which only uses `updateAttributes`, not `save`. Should this be supported? Using a flag perhaps? 

Think about the case where the schema is completely free (MongoDB), and you wouldn't want to keep around all those 'sparse' attributes (as null or worse, as their now-obsolete values).

**Comment by loay** [comment]
@Amir-61 
Isn't that part of the task you are working on? Is it implemented ?
Thanks.

**Comment by Amir-61** [comment]
@loay 

We implemented replaceById and replaceOrCreate which do what Fabien is looking for. This issue was reported long time ago. I believe if it still happens for `updateAttributes` it can be considered to be a bug, although newly implemented `replace*` methods can be used to achieve what Fabien is looking for.

Thanks!

**Comment by loay** [comment]
Thanks @Amir-61 
@fabien I will close that issue for now. If you have any concerns about the implemented methods, please leave a comment and I will re-open the issue. Thanks.
