### ISSUE TITLE
Model scopes should not cache results

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#575]
The current behavior has a bug because `__cachedRelations` is set on the Class-level (static) as well, which should never happen. Caching is only allowed on the instance (relations) level.

To reproduce:

```
Thing.scope('active', { where: { active: true } });

var widget;

Thing.create({ name: 'Widget', active: true }, function(err, inst) {
   widget = inst;
});

Model.active(function(err, instances) { ... }); // will include 'Widget', as expected

widget.updateAttribute('active', false);

Model.active(function(err, instances) { ... }); // should NOT include 'Widget', but does anyway

Model.__cachedRelations // has been set, but should be undefined!
```

/cc @raymondfeng @bajtos

**Comment by fabien** [comment]
This is also a source of memory leaks, of course, which makes it rather critical.

**Comment by bajtos** [comment]
@fabien so what do you propose? We cannot remove `__cachedRelations` entirely, because they are used by "filter[include]" and it would be a breaking change too. Perhaps we can add a new option to the `scope` method that will allow developers to disable caching?

```js
Thing.scope('active', { where: { active: true }, cached: false });
```

**Comment by fabien** [comment]
@bajtos it is wrong to cache the results of such a static method - `__cachedRelations` is never reset in this case. Can you point me to the code where it is being used? I cannot see a reason to support this.

I think you got it the wrong way around - if we were to add an option for it, it should explicitly set `cached: true` instead - again, because there should be never be a reason to rely on this behavior.

When was the last time you hit `GET /api/tickets/active` and expect the exact same (cached) results that you got the first time after you started your app? ...

/cc @raymondfeng thoughts?

**Comment by bajtos** [comment]
> @bajtos it is wrong to cache the results of such a static method - __cachedRelations is never reset in this case. Can you point me to the code where it is being used? I cannot see a reason to support this.

> I think you got it the wrong way around - if we were to add an option for it, it should explicitly set cached: true instead - again, because there should be never be a reason to rely on this behavior.

> When was the last time you hit GET /api/tickets/active and expect the exact same (cached) results that you got the first time after you started your app? ...

I agree with you that `__cachedRelations` should not have been implemented at all, I have been bitten by this myself in the past.

However, backwards compatibility matters. Can you prove that there is no application out there that includes a piece of code similar to what you have described in the issue description and depending on the values being cached, even if such expectation is silly? In other words, can you prove that by disabling the cache, we will not break any existing application out there?

I proposed `cached` defaulting to `false` in order to preserve backwards compatibility. We can add a deprecation warning telling people to disable caching and then change the default to `true` in v3.0.

**Comment by fabien** [comment]
@bajtos I don't think you get it. `Model.scope` has nothing to do with `__cachedRelations` at all - `scope !== relations`. No one should ever rely on this, it is not only a bug, but it is a conceptually false statement. 

It's an overlooked implementation detail from `include` and `relations` that has leaked into the general notion of `scopes`.

It would be silly to try to ensure backwards compatibility for an assumption so flawed. Instead of encouraging this (a memory leak, and source of a lot of confusion, mind you), we should deprecate it firmly. No options or anything to condone such behavior.

Where's your unit tests to affirm this flawed behavior? If it's not in the core tests, we have no obligation to keep BC IMHO.

**Comment by bajtos** [comment]
> Where's your unit tests to affirm this flawed behavior? If it's not in the core tests, we have no obligation to keep BC IMHO.

Our test coverage is not good enough to allow us to make such bold statements. No offence, but even your contributions (pull request) don't provide tests for all important use-cases/configuration options.

> I don't think you get it. Model.scope has nothing to do with __cachedRelations at all - scope !== relations. No one should ever rely on this, it is not only a bug, but it is a conceptually false statement.

> It's an overlooked implementation detail from include and relations that has leaked into the general notion of scopes.

It's possible that I am misunderstanding the underlying problem and its impact on things like relations.

The important part is that we should strive to preserve backwards compatibility and fix this in such way that minimises the number of people that may discover that their application no longer works after a fresh `npm install`.

If we can't preserve backwards compatibility, then the change should wait until the next major release (v3.0).

**Comment by jsheely** [comment]
I believe this is a related issue. Randomly this query of related models + sub related model will not return the sub related model populated.

```
Schedule.findOne({
	where: {id: id},
	include: ['media', 'events', {events: ['media']}]
}).then(function(fullSchedule){
	//Randomly fullSchedule.events[0].media will be null
	//When value is null _cachedRelations will be empty.
});
```

Setting: var saveOnCache = false; in the scope.js appears to have fixed it.
