### ISSUE TITLE
Mongo Object Ids get converted to Strings

### ISSUE THREAD

**Issue by arlaneenalra** [strongloop/loopback-datasource-juggler#58]
I ran across this issue when dealing with related documents with a Mongo DB backend.  I have a models.json file that looks contains something similar to:

```
{
  "service": {
    "properties": {
      "slug": {
        "type": "String"
      },
      "title": {
        "type": "String"
      },
      "link": {
        "type": "String"
      },
      "subtitle": {
        "type": "String"
      },
      "intro": {
        "type": "String"
      },
      "content": {
        "type": "String"
      },
      "icon": {
        "type": "Object"
      },
      "image": {
        "type": "Object"
      }
    },
    "public": true,
    "dataSource": "db"
  },
  "serviceCategory": {
    "options": {
      "relations":{
        "services": {
          "model": "service",
          "type": "hasMany"
        }
      }
    },
    "properties": {
      "title": {
        "type": "String"
      },
      "tagline": {
        "type": "String"
      },
      "subtitle": {
        "type": "String"
      },
      "intro": {
        "type": "String"
      },
      "content": {
        "type": "String"
      },
      "image": {
        "type": "object"
      }
    },
    "public": true,
    "dataSource": "db",
    "plural": "serviceCategories"
  }
}
```

When retrieving services with a request similar to `/api/serviceCategories/<id>/services` I get back objects that have a `serviceCategoryId` field with the string equivalent of a Mongo ID.  If a change is made to one of those retrieved documents and it is updated via a PUT request, what was an ObjectId is replaced with a string and Mongo loses the relationship. (i.e. the document is no longer retrievable via the original request.)

In a conversation over IRC rfeng suggested that creating a custom ObjectId type for Mongo might be a solution to this issue and that I should file a bug here for direction on how to go about that.  Thinking about the issue, I'm wondering if this should be handled when the initial relationship is defined, that appears to be where the foreign key field is implicitly created.  In either event, an ObjectId type is likely a requirement.

**Comment by codejie** [comment]
please check Role-Mapping model, I can not insert the principalId with ObjectId. And if it was not ObjectId, ACLs will not find this mapping between user and role.

{
    "_id" : ObjectId("58c2185a6024ee2f1705d1ec"),
    "principalType" : "USER",
    "principalId" : "58c1380699220526baa9477b",
    "roleId" : ObjectId("58c21117df1db02b1425882c")
}

**Comment by akapaul** [comment]
@codejie I have the same problem, but found a workaround:

1. install mixin https://www.npmjs.com/package/loopback-objectid-mixin
2. in some boot script, let's name it like modelModifier.js:
```javascript
let modelBuilder = app.dataSources.db.modelBuilder,
     RoleMapping = app.models.RoleMapping;

  modelBuilder.mixins.applyMixin(RoleMapping, 'ObjectidType', {
    "properties": ["principalId"]
  });
```

Now, any document inserted in RoleMapping model will have principalId field with type ObjectId

**Comment by ebarault** [comment]
better use this fix:
https://github.com/strongloop/loopback/pull/3198#issuecomment-280282535
