### ISSUE TITLE
belongsTo should not allow `create` when relation already established

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#581]
I think we need an option to prevent `create` on a `belongsTo` relationship, after it has already been created/assigned. It is usually undesirable to overwrite this.

This might apply to other relations as well, and can probably be generalized as such.

**Comment by jannyHou** [comment]
So now in a `belongsTo` relationship, function `create` does override the existed one.

```js
Parent.create({id: 10}, function(err, parent) {
  	console.log(err, parent);

  	parent.childones.create({id: 1}, function(err, child) {
  		console.log(err, child);

  		child.parent.create({id: 20}, function(err, newparent) {
  			console.log(err, new parent);
                        // child.parentId will be 20
  			console.log("id" + child.parentId);
  		});
  	});  	
  });
```

Probably need check the `belongsTo` model instance existed in this function:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1321
