### ISSUE TITLE
Fields order are not kept using filters in URI [Angular SDK][MongoDB][Indexes]

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback-datasource-juggler#585]
When I call my API using auto-generated Angular SDK: (I removed special chars for readability)
```
https://my-api.domain.com/Devices/count?where=sdk.id:abcd,deviceInfo.isTablet:true
```

Angular Code:
```js
Device.count({
			where: {
				'sdk.id': 'abcd',
				'deviceInfo.isTablet': true
			}
		})
```

MongoDB query is:
```js
{"$query":{"deviceInfo.isTablet":"<val>","sdk.id":"<val>"}}
```

This means the query will not use my indexes, and I have no way to build my indexes correctly because it depends of fields names ascending order (as far as I understand).

Is there any way to keep fields orders?

**Comment by loay** [comment]
Hi @PuKoren,

Are you still running into the same issue? Thanks.

**Comment by loay** [comment]
Hi @PuKoren 
Here is the solution: 
Have a look at this document for indexing: 
https://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes

 Once the index is defined for the model, dataSource.autoupdate() for mongodb will ensure the indexes.

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
