### ISSUE TITLE
Document `keyThrough` option for relations

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#593]
From https://github.com/strongloop/loopback-datasource-juggler/pull/281 it seems like `keyThrough` option applies to `hasMany`, `belongsTo` and Polymorphic `hasAndBelongsToMany` Through.

**Comment by crandmck** [comment]
Added:
- http://docs.strongloop.com/display/LB/HasManyThrough+relations#HasManyThroughrelations-Definingtheforeignkeyproperty

**Comment by raymondfeng** [comment]
LGTM
