### ISSUE TITLE
utils.isPlainObject breaks under REPL

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-datasource-juggler#605]
Due to running in a different vm context, the constructor comparison from isPlainObject (https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L413) breaks when called from under the REPL module. This happens at various inconvenient places where isPlainObject is passed some object that was constructed within the REPL context.

It seems that the comparison should  be changed to a string comparison instead of a reference check? See this comment: https://github.com/joyent/node/issues/1834#issuecomment-2312105

**Comment by loay** [comment]
Hi @doublemarked 
the code is outdated as L413 is pointing to something else now, but the current `isPlainObject` is implemented this way:

`function isPlainObject(obj) {
  return (typeof obj === 'object') && (obj !== null) &&
    (obj.constructor === Object);
}

`

**Comment by doublemarked** [comment]
Hey @loay - I cannot seem to reproduce this problem, either because it's been fixed or because my Issue here from last year is not helpful enough. It's probably a lesson for future Issues I file :)
