### ISSUE TITLE
Auto increment not working with embedsMany

### ISSUE THREAD

**Issue by mailuser41** [strongloop/loopback-datasource-juggler#606]
https://github.com/strongloop/loopback-datasource-juggler/issues/336#issuecomment-105097639

**Comment by loay** [comment]
Hi @mailuser41 
Did you try the fixes mentioned in the same repo? Thanks.

**Comment by loay** [comment]
Closing issue. solutions offered  in https://github.com/strongloop/loopback-datasource-juggler/issues/336
If still experiencing the same issue, please feel free to leave a comment and I will re-open the issue. Thanks.
