### ISSUE TITLE
Model.find calls the "all" method instead of "find"

### ISSUE THREAD

**Issue by Ijmir** [strongloop/loopback-datasource-juggler#608]
Why Model.find calls Connector.prototype.all instead of Connector.prototype.find?
Why Model.exists calls Connector.prototype.count instead of Connector.prototype.exists?

**Comment by raymondfeng** [comment]
Please see the explanation at https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L1018-L1031
