### ISSUE TITLE
Feature: Add model name to error messages

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-datasource-juggler#614]
Currently migrating a huge project to Loopback. Migrating mongoose models to loopback. Getting errors like: 

```
Error: Invalid type for property estimatedHours
```

Kind of a pain when there a ton of models.

Would be super awesome if these errors pointed to the specific model by including the model name. 

Maybe switching to something like [invariant](https://www.npmjs.com/package/invariant) would significantly increase usability of error messages.

ref: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L415

**Comment by loay** [comment]
Hi @BerkeleyTrue 
Still runinng into the same issue? was there a Pull request to fix the issue so I can have a look at?
Thanks.

**Comment by BerkeleyTrue** [comment]
Not that I know of. That project has been migrated over completely. This was more of a suggestion to increase the DX when it comes to these types of errors.

**Comment by loay** [comment]
@BerkeleyTrue Thanks. 
Looking into it.
