### ISSUE TITLE
nin condition with an empty array produces incorrect sql

### ISSUE THREAD

**Issue by rus0000** [strongloop/loopback-datasource-juggler#617]
I'm using loopback with postgresql-connector.
if `idList` is an empty array, I'm getting sql syntax error from postgres, if it is not empty, everything is OK.

``` javascript
var idList = [];
Model.destroyAll({
  and: [
    {
      parentId: 1
    },
    {
      id: {nin: idList}
    }
  ]
});
```

**Comment by 0candy** [comment]
Thank you for pointing out the bug. Would you like to contribute by submitting a PR?

**Comment by rus0000** [comment]
Sorry, no. I don't work with the juggler right now.
