### ISSUE TITLE
Include of referencesMany issues (after include refactoring)

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#622]
One of the key aspects of a referencesMany relation is that it should keep the order of the ids when inclusion fetches them. Effectively `findByIds` (here https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2966) makes sure that this is the case.

However, the refactoring here https://github.com/strongloop/loopback-datasource-juggler/commit/d009557a76cc8fe39314c2c1f1b4cdfe2520b4e2 does not take this into account.

I'm currently investigating other possibly include-related issues, as I now have many failing tests after this particular commit. 

/cc @raymondfeng

**Comment by fabien** [comment]
There's another issue hidden in there, take the following setup:

```
Image.referencesMany('users');
User.hasMany('images', { foreignKey: 'userIds' });

User.find({ include: 'images' }, function() { ... });

Uncaught TypeError: Cannot read property '__cachedRelations' of undefined
      at linkManyToOne (loopback-datasource-juggler/lib/include.js:520:16)
```

This happens because the `target[relation.keyTo]` will be an array with ids, not just a single id value in this case.

**Comment by fabien** [comment]
Turns out this was a very specific case, which worked thanks to MongDB's transparant handling of arrays - e.g. it doesn't matter if a property is an array or not when querying. In other words, it used to work, even with includes, but it has surfaced as a deeper issue. However, I do want to see this resolved. I'm working on it right now.

**Comment by fabien** [comment]
@ningsuhen please see #625 - perhaps we can come to a solution like that; the tests now pass. Even if we don't implement a `contains` operator, the new `linkManyToOne` implementation should safely handle it automatically in case of MongoDB. So it would be great to consider this change anyway.

**Comment by ningsuhen** [comment]
Thanks @fabien , I'll use #625 's linkManyToOne and fix #623 together. I'll leave the `contains` operator implementation for @raymondfeng to look into. Btw, feel free to send pull requests (with tests) if you have fixed the issue.

**Comment by ningsuhen** [comment]
This has been addressed in https://github.com/strongloop/loopback-datasource-juggler/pull/626 but the case of "hasMany -> referencesMany" doesn't have any documentation or test cases. @fabien, your test case change was breaking other tests and therefore, I haven't added the tests for referencesMany with hasMany.

**Comment by fabien** [comment]
@ningsuhen thanks, don't worry about the `hasMany -> referencesMany` case then. It appears you were able to change `linkManyToOne`, which probably means it will now work in MongoDB as before. I'll let you know as soon as I get a chance to try it with my codebase and tests.
