### ISSUE TITLE
Include includePolymorphic is broken

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#623]
The same targetIds are fed to `processPolymorphicType`, which have been clobbered here: 

https://github.com/strongloop/loopback-datasource-juggler/blob/d009557a76cc8fe39314c2c1f1b4cdfe2520b4e2/lib/include.js#L540

@raymondfeng @ningsuhen

**Comment by fabien** [comment]
Hotfix while I'm investigating the other include issues: add `var targetIds = targetIdsByType[modelType];`

at: https://github.com/strongloop/loopback-datasource-juggler/blob/d009557a76cc8fe39314c2c1f1b4cdfe2520b4e2/lib/include.js#L563

**Comment by fabien** [comment]
Furthermore `includePolymorphic` does not work with `belongsTo` at all. While I applaud the refactoring of this aspect of Juggler, I'm afraid it introduces quite some breaking changes.

**Comment by ningsuhen** [comment]
@fabien , thanks for reporting. I thought the existing tests must have covered it. I'll fix the issues along with tests asap. Can you also add the case includePolymorphic belongsTo? I remember it working for me.

**Comment by fabien** [comment]
@ningsuhen thanks for your prompt reply! Do you want me to add a test-case for the polymorphic belongsTo, or can you give it a shot first?

Unfortunately the existing tests apparently don't cover include-related functionality for all relation setups. Before it was no big deal, because it would work off the existing code, but your (much welcomed!) refactoring goes much deeper in implementing it independently.

Can you look at the other issue regarding referencesMany, too? Thanks!

**Comment by ningsuhen** [comment]
@fabien , I'll start working on the reported issues tonight IST. It would be great if you can add a test-case for polymorphic belongsTo before that. Else, I'll add the test-case and let you know to check if matches your case.

**Comment by fabien** [comment]
@ningsuhen great, I'll see if I can add such a test to a feature branch of mine. I'll update here with a link.

**Comment by fabien** [comment]
@ningsuhen I've added two failing test cases (marked // Fixme @ningsuhen) here:

https://github.com/fabien/loopback-datasource-juggler/tree/fix/include-refactor

Please review, and see if you can identify any other includes that were not covered by tests. I think the 2 additional tests cover hasOne and belongsTo (as inverse relations) now.
