### ISSUE TITLE
Implement `contains` operator to mimic MongoDB

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#625]
In order to resolve #622 I would like to propose a `contains` operator, which mimics the transparent handling of array matching in MongoDB. 

A feature branch lives here: https://github.com/fabien/loopback-datasource-juggler/tree/feature/query-contains

Currently, the logic of `contains` returns true if either case is true (based on `compare`):
- array `a` contains value `b`
- array `a` intersects with array `b` (you probably don't want to nest arrays for this anyway)

This is probably not 100% exactly like MongoDB, but I think we can make all connectors behave the same if we'd agree on adding `contains` as a new core operator.

/cc @raymondfeng @bajtos

**Comment by fabien** [comment]
It's important to note that we don't strictly need `contains` to resolve the `include` issue in MongoDB.

**Comment by bajtos** [comment]
I don't understand this topic enough to judge the proposed solution, I'll leave that task to @raymondfeng - I believe he is more familiar with this part of juggler. Adding a new operator "contains" looks like a good thing to me.

@fabien does you proposal include ability to nest operators inside `contains`? E.g. is it possible to say `array A contains value between B-C` or `array A contains an object value that has property B equal to C`?

**Comment by fabien** [comment]
@bajtos my proposal is rather simple, it's like an inverted `inq` in a way. Let's start simple and see if we can indeed nest - it's probably possible to do so, however, having all connectors support it is a different matter I guess.

**Comment by jannyHou** [comment]
@fabien do you still plan to work on this feature branch?
https://github.com/fabien/loopback-datasource-juggler/tree/feature/query-contains
Or any update thought about this feature?
Thanks.
