### ISSUE TITLE
Boolean attribute exists doesn't work

### ISSUE THREAD

**Issue by ernoaapa** [strongloop/loopback-datasource-juggler#628]
At the moment, it's not possible to find entities which doesn't have boolean field:
```
{
  where: {
    booleanField: {
      {exists: false}
    }
  }
}
```

At least with MongoDB it creates find query:
```
find({ booleanField: true })
```

Didn't find any workaround for this either.

**Comment by fabien** [comment]
The following might work - `$` keys should pass-through as-is. 
```
{
  where: {
    booleanField: {
      {$exists: false}
    }
  }
}
```

I think the query you had will be coerce the object to a boolean (= true).

**Comment by Amir-61** [comment]
Hey @ernoaapa,

Did Fabien's suggestion solved your problem?

**Comment by ernoaapa** [comment]
Don't know. I defined default value to the field and migrated our database to always have true/false value in the field. And I'm not working in the project anymore so cannot test easily.

**Comment by Amir-61** [comment]
Ok. Thanks! I'm closing this old issue... Please feel free to re-open the issue if you run into the same problem.

Thanks!
