### ISSUE TITLE
Pass through ilike and nilike parameters so they can be handled by connectors

### ISSUE THREAD

**Issue by jasonaden** [strongloop/loopback-datasource-juggler#633]
Every application needs to be able to search without case sensitivity. Other than regular expressions (not always supported) there isn't a good way to do this. See PR for fixing this in Postgres connector (https://github.com/strongloop/loopback-connector-postgresql/pull/93). This patch needs to be applied to the juggler as well.

**Comment by Amir-61** [comment]
Thanks for the patch...

I believe we already have support for [regexp](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Regularexpressions); is it safe to close this ticket?

**Comment by Amir-61** [comment]
I'm closing this old issue, due to inactivity and also we already have added [regexp](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Regularexpressions).

Thanks!

**Comment by duffn** [comment]
I'd like to have this opened back up. I'm working on a Redshift connector and as Redshift does not support case insensitive regexp, `ilike` and `nilike` are necessary.

**Comment by Amir-61** [comment]
`Redshift connector` is a community connector; please create an issue in their GH repository.

**Comment by duffn** [comment]
@Amir-61 I understand that. However, if `ilike` and `nilike` are not in juggler's `dao.js` then they won't work in the connector.

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1404

**Comment by superkhau** [comment]
@duffn Would you like to submit a PR with your proposal? We can chat more there. Please reference this issue when you do that so we can follow the conversation.
