### ISSUE TITLE
DataAccessObject.findById missing options if in place of filter

### ISSUE THREAD

**Issue by rus0000** [strongloop/loopback-datasource-juggler#639]
https://github.com/strongloop/loopback-datasource-juggler/blob/d495a26a76e000f8acde8fb4da67c51af672b0cd/lib/dao.js#L790
Here has to be `else` in case if options are in place of filter object

**Comment by raymondfeng** [comment]
`options` cannot be in place of `filter`. To support that, you need to pass in findById(id, filter, options).
