### ISSUE TITLE
DataAccessObject.updateOrCreate ignoring active transaction

### ISSUE THREAD

**Issue by rus0000** [strongloop/loopback-datasource-juggler#640]
https://github.com/strongloop/loopback-datasource-juggler/blob/d495a26a76e000f8acde8fb4da67c51af672b0cd/lib/dao.js#L508
Here we must pass active transaction if any.

**Comment by raymondfeng** [comment]
@rus0000 Good catch, can you submit a PR?

**Comment by rus0000** [comment]
https://github.com/strongloop/loopback-datasource-juggler/pull/642
We need some tests for transaction propagation.

**Comment by jannyHou** [comment]
I am closing this issue since pr https://github.com/strongloop/loopback-datasource-juggler/pull/642 to fix it  is merged.
Feel free to reopen it if you have further suggestion. Thanks.
