### ISSUE TITLE
Hook 'persist' not using context.data

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#649]
It appears that context.data is not always used when actually persisting the data through the connector, for example: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2394

I believe the best way would have been: `inst.constructor._forDB(context.data)` - in other places it will probably work, however, explicitly using `context.data` everywhere ensures that replacing the data within a `persist` hook works as expected.

/cc @bajtos @raymondfeng

**Comment by bajtos** [comment]
@PradnyaBaviskar could you please take a look? IIUC, @fabien says that `prototype.updateAttributes` is not using `ctx.data` provided by the "persist" hook, which looks like an unintended bug to me.

I think we should make one more change and set `ctx.data` initially to `typedData`, as that's closer to what is being persisted in the database. The difference will be visible for nested model instances, e.g. if you have

```
var p = new Product();
p.updateAttributes({ categories: [new Category("Cars"), new Category("Vehicles")] });
```

then `data` contains Category instances while `typedData` contains plain objects instead (if I am reading the code correctly).

**Comment by fabien** [comment]
Actually, I would find it much clearer if `ctx.data` would be used whenever `persist` is called, instead of relying on `data` still pointing to the same object as `ctx.data`. This might not always be the case.

**Comment by bajtos** [comment]
> Actually, I would find it much clearer if ctx.data would be used whenever persist is called, instead of relying on data still pointing to the same object as ctx.data. This might not always be the case.

+1 Let's move this discussion to #650 please

**Comment by 0candy** [comment]
Closing this issue as PR was merged.
