### ISSUE TITLE
Count with date comparison returns 0

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback-datasource-juggler#655]
Hello,

Until version ```2.30.1```, the following was working. As soon as I upgrade to ```2.31.0``` the ```/count``` built-in method returns always 0 when I use a date comparison:

```
/ModelName/count?where={"createdAt":{"lt": "2015-07-03T00:00:00.000Z"}}
```

My model has the following property:
```json
"properties": {
    "createdAt": {
      "type": "date"
    }
}
```

**Comment by raymondfeng** [comment]
should be fixed now by loopback-datasource-juggler@2.32.0
