### ISSUE TITLE
Hook 'loaded' called in non-async loop of find

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#656]
If I gather correctly, the `find` method calls the `loaded` hook in a non-async `for` loop. I would have expected `async.each` or similar here:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1385

/cc @raymondfeng @bajtos

**Comment by bajtos** [comment]
Good catch, @fabien!

@PradnyaBaviskar could you PTAL?

**Comment by fabien** [comment]
@PradnyaBaviskar could you have a look, please?

**Comment by bajtos** [comment]
This should have been fixed by #668.
