### ISSUE TITLE
How to create datasource dynamically on application start

### ISSUE THREAD

**Issue by aashuagg** [strongloop/loopback-datasource-juggler#658]
This seems to be a trivial issue but I am stuck in this for 2 days and could not find much help from google as well.

I am trying to create datasource at app start instead of hardcoding the parameters in datasources.json. Here is how my server.js looks like:

var loopback = require('loopback');
		var boot = require('loopback-boot');
		var DataSource = require('loopback-datasource-juggler').DataSource;

		var app = module.exports = loopback();

		app.start = function() {
		  // start the web server
		  return app.listen(function() {
		    app.emit('started');
		    console.log('Web server listening at: %s', app.get('url'));
		  });
		};

		// Bootstrap the application, configure models, datasources and middleware.
		// Sub-apps like REST API are mounted via boot scripts.
		boot(app, __dirname, function(err) {
		  	if (err) throw err;
		  	var dataSource;

		 	if(process.env.VCAP_SERVICES){
		 		var vcapServices = JSON.parse(process.env.VCAP_SERVICES)
		 		dataSource = new DataSource({
		 			connector: require('loopback-connector-mongodb'),
		 			url: vcapServices.mongolab[0].credentials.uri 
		 		})
		 	}else{
		 		dataSource = new DataSource({
				    connector: require('loopback-connector-mongodb'),
				    "host": "localhost",
				    "port": 27017,
				    "url": "",
				    "database": "Spordz",
				    "name": "MongoDB_Localhost"
				});
		 	}

		 	app.dataSource('MongoDB_Localhost', dataSource);

		  // start the server if `$ node server.js`
		  if (require.main === module)
		    app.start();
		});

and I have kept an empty entry in datasources.json:
      "MongoDB_Localhost": {
      },

Now when i start my app using slc run, I am getting an error:

        TypeError: Cannot read property 'name' of undefined
            at DataSource.columnMetadata (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:1688:74)
            at DataSource.defineForeignKey (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:1764:26)
            at Function.hasMany (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/relation-definition.js:631:24)
            at Function.hasMany (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/relations.js:68:29)
            at /Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:481:28
            at Array.forEach (native)
            at DataSource.defineRelations (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:442:28)
            at DataSource.setupDataAccess (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:521:8)
            at DataSource.attach (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/datasource.js:737:8)
            at Function.ModelClass.attachTo (/Users/aashuaggarwal1/spordz/node_modules/loopback-datasource-juggler/lib/model-builder.js:331:16)

I am very confused how to create datasource dynamically.

**Comment by raymondfeng** [comment]
1. You can use server/datasources.local.js to export objects representing datasource configuration. See http://docs.strongloop.com/display/LB/datasources.json#datasources.json-Environment-specificconfiguration. 

2. Try the following code:

```js
if(process.env.VCAP_SERVICES){
            var vcapServices = JSON.parse(process.env.VCAP_SERVICES)
            dataSourceConfig = {
                connector: require('loopback-connector-mongodb'),
                url: vcapServices.mongolab[0].credentials.uri 
            }
        }else{
            dataSourceConfig = {
                connector: require('loopback-connector-mongodb'),
                "host": "localhost",
                "port": 27017,
                "url": "",
                "database": "Spordz",
                "name": "MongoDB_Localhost"
            };
        }
```

**Comment by aashuagg** [comment]
I removed the DataSource constructor and thats how my server.js looks:

        var loopback = require('loopback');
	var boot = require('loopback-boot');
	var DataSource = require('loopback-datasource-juggler').DataSource;

	var app = module.exports = loopback();

	app.start = function() {
	  // start the web server
	  return app.listen(function() {
	    app.emit('started');
	    console.log('Web server listening at: %s', app.get('url'));
	  });
	};

	// Bootstrap the application, configure models, datasources and middleware.
	// Sub-apps like REST API are mounted via boot scripts.
	boot(app, __dirname, function(err) {
	  	if (err) throw err;
	  	var dataSource;

	 	if(process.env.VCAP_SERVICES){
	 		var vcapServices = JSON.parse(process.env.VCAP_SERVICES)
	 		dataSource = {
	 			connector: require('loopback-connector-mongodb'),
	 			url: vcapServices.mongolab[0].credentials.uri 
	 		}
	 	}else{
	 		dataSource = {
			    connector: require('loopback-connector-mongodb'),
			    "host": "localhost",
			    "port": 27017,
			    "url": "",
			    "database": "Spordz",
			    "name": "MongoDB_Localhost"
			};
	 	}

	 	app.dataSource('MongoDB_Localhost', dataSource)

	  // start the server if `$ node server.js`
	  if (require.main === module)
	    app.start();
	});

still i get the above exception on slc run. Is calling app.dataSource('MongoDB_Localhost', dataSource) the right way to attach datasource?

**Comment by sebfindling** [comment]
i also need to set datasources dynamically, any news  @raymondfeng ?

**Comment by joeauty** [comment]
According to this ticket https://github.com/strongloop/loopback-boot/issues/4 datasources now support dynamic variables (${SOME_STRING}). What Loopback version is this feature available in, and where are these variables set?

**Comment by Amir-61** [comment]
Hey @davidcheung ,

Is https://github.com/strongloop/loopback-boot/issues/4 ^ what you implemented?

**Comment by davidcheung** [comment]
@Amir-61 the feature for dynamic datasources currently only supports string, so for something that requires parsing thru js (eg `var vcapServices = JSON.parse(process.env.VCAP_SERVICES)`) it probably wouldn't work. 

but it might work on `datasource.local.js` as follow:
```
var dataSource;
if(process.env.VCAP_SERVICES){
  var vcapServices = JSON.parse(process.env.VCAP_SERVICES)
  dataSource = {
    connector: require('loopback-connector-mongodb'),
    url: vcapServices.mongolab[0].credentials.uri 
  }
}else{
  dataSource = {
    connector: require('loopback-connector-mongodb'),
    "host": "localhost",
    "port": 27017,
    "url": "",
    "database": "Spordz",
    "name": "MongoDB_Localhost"
  };
}

module.exports = {
  db: dataSource
}
```

**Comment by Amir-61** [comment]
@joeauty @sebfindling  Please see ^

Thanks @davidcheung!

**Comment by joeauty** [comment]
Okay, I'm having some problems here...

I upgraded to Loopback 2.28.0, put a file in my home directory called .env:

`MY_HOST=127.0.0.1`

Made sure these environment variables were loaded:

`source ~/.env`

Indeed they are:

```$ echo $MY_HOST
127.0.0.1```

In my datasources.json file I added:

```"myService": {
    "name": "myService",
    "connector": "rest",
    "debug": true,
    "json": true,
    "operations": [
      {
        "template": {
          "method": "POST",
          "url": "http://${MY_HOST}:3000/path/to/endpoint",
          "headers": {
            "accepts": "application/json",
            "content-type": "application/json"
          },
          "body": "{data}"
        },
        "functions": {
          "something": ["data"]
        }
      },
```

The API can be started, but when I try to access some data using this datasource I get:

`Cannot GET /$/path/to/endpoint`

So, obviously my environment variable isn't being picked up. What do I need to do to get this to work?

Thanks in advance!

**Comment by davidcheung** [comment]
@joeauty right now we only support the whole parameter being dynamic, not partially 

so what i would assume you have two options
- use dynamic variables for `datasource.json`
- use `datasource.local.js` 

If you use dynamic variables for `datasource.json`
you will need to do 
```json 
"url": "${MY_HOST}"
```
if it is a dynamic variable, it replaces the whole variable ([see implementation](https://github.com/strongloop/loopback-boot/blob/5eaa9090068ea99676ca081fc177e2a877ef9337/lib/executor.js#L367)) and you would have to do 
`MY_HOST=http://127.0.0.1:3000/path/to/endpoint nodemon`

**Comment by joeauty** [comment]
Hmmm... it doesn't appear that this technique works with URLs like:

`http://127.0.0.1:3000/api/core/info?id={id}`

I get:

```
/Users/joe/www/nanopay-api/node_modules/loopback-connector-rest/lib/rest-connector.js:58
            fn.accepts.push({arg: p, type: args[p].type,
                                                  ^
TypeError: Cannot read property 'type' of undefined
```

**Comment by joeauty** [comment]
Does this technique work with GET methods that use query strings? I have several far more complex than this... For example:

`?filter[where][accountType]=myAccount&filter[where][something]=somethingElse`

**Comment by davidcheung** [comment]
all the dynamic configuration does is it replaces that specific parameter in the `datasources.json`
then it registers the datasource with those variables

perhaps you can try something like 
`DEBUG=loopback:boot:executor MY_HOST=http://127.0.0.1:3000/path/to/endpoint/{p} node .`
to see if you get some useful debug information

**Comment by joeauty** [comment]
```$ DEBUG=loopback:boot:executor MY_HOST=http://127.0.0.1:3000/api/core/info?id={id} node .
/Users/joe/www/nanopay-api/node_modules/loopback-connector-rest/lib/rest-connector.js:58
            fn.accepts.push({arg: p, type: args[p].type,
                                                  ^
TypeError: Cannot read property 'type' of undefined
```

**Comment by davidcheung** [comment]
@joeauty  hmm thats weird, maybe your loopback-boot is outdated, 
you will need your loopback-boot to be [2.18.0](https://github.com/strongloop/loopback-boot/commit/cc551b0c0fd307f85a28a356f37ae3a61c6c5fca)+ 
you could probably find out by doing `npm ls --depth=1`

**Comment by joeauty** [comment]
Thanks @davidcheung that was indeed the issue!
