### ISSUE TITLE
defining relations between connectors

### ISSUE THREAD

**Issue by behrad** [strongloop/loopback-datasource-juggler#663]
Is this supposed to work if we relate two models defined in different data sources/connectors?

for example a mongo model `User` can have a belongsTo relation with `Status` model defined in redis or couchbase connector. !?

**Comment by raymondfeng** [comment]
Yes.

**Comment by behrad** [comment]
It doesn't seem to be working for me.

I configured 

```js
"relations": {
    "userStatus": {
      "type": "belongsTo",
      "model": "userStatus",
      "foreignKey": "statusId"
    }
}
```

in my `device.json` model which is defined on mongodb and ran `automigrate`.

and `userStatus` model is defined on redis as below:

```js
{
  "name": "userStatus",
  "base": "PersistedModel",
  "idInjection": false,
  "properties": {
    "id": {
      "type": "string",
      "required": true
    },
    "modifiedAt": {
      "type": "number",
      "required": true
    },
    "online": {
      "type": "boolean",
      "index": true
    },
    "badge": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

but I have no helper `device.userStatus` in my model and nothing is added to my models.
documents didn't tell me more on how to use/take advantage of `belongsTo` relations.
