### ISSUE TITLE
Relax the id (primary key) requirement for certain operations, such as find or updateAll

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#670]
https://github.com/strongloop-internal/scrum-cs/issues/309

**Comment by superkhau** [comment]
As discussed with @raymondfeng, the first task is to come up with a list of areas that need relaxing:

**Memory connector**
- https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/memory.js#L324

**Comment by raymondfeng** [comment]
> https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/memory.js#L324

This is fine as we check idNames.length

> https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2334-L2336

Is this link out of date?

> https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L986-L991

This is fine as it checks idNames.length

> https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L603-L608

This is fine as it checks idNames.length

> https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L670-L675

This is fine as it checks idNames.length

> https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L349-L354

This is fine as it checks idNames.length

> https://github.com/strongloop/loopback-connector-oracle/blob/master/lib/oracle.js#L469-L474

This is fine as it checks idNames.length
