### ISSUE TITLE
hasMany -> belongsTo relationship using includes with same foreign key as model

### ISSUE THREAD

**Issue by cooperjbrandon** [strongloop/loopback-datasource-juggler#672]
The `includes` filter doesn't work when we have a hasMany relationship on one model with a belongsTo on another when the foreignKey is the same as the table name.

Example. `organization` model hasMany `project`s, and `project`s belongsTo an `organization`. The foreign key here is `organization`, which is the same name as the model. So here are the relations:

organization table:
```
"relations": {
  "projects": {
     "type": "hasMany",
     "model": "project",
     "foreignKey": "organization"
  }
}
```

project table:
```
"relations": {
  "organization": {
     "type": "belongsTo",
     "model": "organization",
     "foreignKey": "organization"
  }
}
```

So when I do a call for `/organizations` and my query params are `{"include":"projects"}`, the response doesnt return any projects, just organizations.

This is due to line [534](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L534) of `lib/include.js` (the `linkManyToOne` function). What's happening is that the `target` is a `project` instance and `relation.keyTo` is the string `'organization'`. So essentially when we do `target[relation.keyTo]` aka `target.organization`, it returns a function: `function () { [native code] }`, when in fact it should return the ID of the organization. I believe, but not 100% sure, that this native function is the `organization` model, and that its getting confused.

When i change the foreign key to anything other than `organization`, `includes: projects` works.

As a quick fix I did:
```
var id = typeof target[relation.keyTo] !== 'function' ? target[relation.keyTo] : target._data[relation.keyTo];
var targetIds = [].concat(id);
```
however, I dont think using `__data` is the right way to go.

**Comment by raymondfeng** [comment]
The foreignKey cannot be the same as the name of the relation because both are properties of your model instance. For example,

order.userId --> The foreign key value
order.user(...) --> The relation method

**Comment by cooperjbrandon** [comment]
ahhhh I see now - was not clear before that this was on purpose. thanks raymond.
