### ISSUE TITLE
Include hasMany of relation does not return empty array

### ISSUE THREAD

**Issue by hotaru355** [strongloop/loopback-datasource-juggler#673]
This PR fixes an issue for the following situation (bug report is a duplicated on loopback-connector-mysql, [issue 100](https://github.com/strongloop/loopback-connector-mysql/issues/100)):

Passport --hasMany--> Owner --hasMany--> Post

if we search for a Passport that does not have any Owners ...
```
Passport.findOne("include": "owners")
```
... we will get the Passport with an empty array of Owners as expected.
```
{
  "passportId": 1,
  "owners": []
```

**However**, this behavior is broken for "deeper" relations (relations of a relation) with the refactoring in [commit d00955...](https://github.com/strongloop/loopback-datasource-juggler/commit/d009557a76cc8fe39314c2c1f1b4cdfe2520b4e2).

If we search for a Passport that has one Owner and that Owner has no Posts ...
```
Passport.findOne("include": {"owners": "posts"} )
```
... we will get the Passport with the Owner, but the Owner has **no** empty array of Posts
```
{
  "passportId": 1,
  "owners": [{
    "ownerId": 1
    // <-- missing "posts" array for owners without a post
  }]
```

Please see the test case that demonstrates the issue.

**Comment by bteres** [comment]
Any update on this issue?

**Comment by hotaru355** [comment]
The issue has been fixed (https://github.com/strongloop/loopback-datasource-juggler/pull/674) and should be closed. @bteres: Do still have problems with the latest release?

**Comment by superkhau** [comment]
Closing. @bteres Ping if you're still having problems with in the latest release.
