### ISSUE TITLE
Problem with simultaneous requests for embedded models

### ISSUE THREAD

**Issue by FelipeAguayo** [strongloop/loopback-datasource-juggler#677]
when inserting two instances simultaneously, only one is entered. An example of this situation is shown in the following example:

Customer.json
```json
{
  "name": "Customer",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {"type": "string" }
  },
  "relations": {
    "emails": {
      "type": "embedsMany",
      "model": "EmailAddress",
      "property": "emailList",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  }
}
```
Email-address.json
```json
{
  "name": "EmailAddress",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "label": {"type": "string"},
    "address": {"type": "string"}
  }
}
```

script.js
```javascript
var async = require('async');
module.exports = function(app) {
  var Customer = app.models.Customer;
  var emails = [
    {
      label: 'work',
      address: 'larry@xyz.com'
    },
    {
      name: 'home',
      address: 'larry@gmail.com'
    }
  ];
  Customer.create({ name: 'Larry Smith' }, function(err, customer) {
    console.log('Customer:', customer);
    // example of simultaneous requests
    async.parallel([
      //request example 1 (add new email 1):
      function (callback){
        Customer.findById(customer.id, function (err, _customer){
          _customer.emails.create(emails[0], callback);
          console.log("email1: ", _customer)
        });
      },
      //request example 2 (add new email 2):
      function (callback){
        Customer.findById(customer.id, function (err, _customer){
          _customer.emails.create(emails[1], callback);
          console.log("email2: ", _customer)
        });
      }
    ], 
     //result example:
     function(err) {
      Customer.findById(customer.id, function (err, _customer){
        console.log('Customer with emails:', _customer);
      });
    });
  });
};
```

console:
```javascript
Customer: { name: 'Larry Smith',
  emailList: [],
  id: 55c0352ee8eed600119c4de5 }

email2:  { name: 'Larry Smith',
  emailList:
   [ { name: 'home',
       address: 'larry@gmail.com',
       id: 'dd8574893114631c82278d61' } ],
  id: 55c0352ee8eed600119c4de5 }

email1:  { name: 'Larry Smith',
  emailList:
   [ { label: 'work',
       address: 'larry@xyz.com',
       id: 'f373f9f0bdf16aa9b4438a8d' } ],
  id: 55c0352ee8eed600119c4de5 }

Customer with emails: { 
  emailList:
   [ { label: 'work',
       address: 'larry@xyz.com',
       id: 'f373f9f0bdf16aa9b4438a8d' } ],
  name: 'Larry Smith',
  id: 55c0352ee8eed600119c4de5 }
```
any suggestions for this?

**Comment by raymondfeng** [comment]
Does it use in-memory DB?

**Comment by FelipeAguayo** [comment]
I did this in mongodb and memory db.

**Comment by raymondfeng** [comment]
Here is what's happening:

1. find user 1:  { name: 'Larry Smith', emailList: [], accountIds: [], id: 1 }
2. find user 1:  { name: 'Larry Smith', emailList: [], accountIds: [], id: 1 }
3. email1 created for user from 1
4. email2 created for user from 2 (It doesn't refresh from step 3).

Please note embedsMany relation will store embedded items as a whole. As a result, step 3 and step 4 will override each other. IMO, it's an application error.

**Comment by FelipeAguayo** [comment]
@raymondfeng: excuse me ... but my doubt is ... then you're going to fix this bug soon ?. Or should I opt for another solution?

**Comment by raymondfeng** [comment]
The scenario is very similar as you load the same record from DB twice, and add one array item to each of them and save to DB independently without merge. I don't think the framework can deal with the conflict. That's why I think it's an application error, not a loopback bug.

**Comment by raymondfeng** [comment]
You need to make findById and create email atomic to avoid such race conditions.

**Comment by FelipeAguayo** [comment]
ok, in that sense you are right (based in my example), but my real situation occurs with API requests. example:

two simultaneous requests:
[post] http://localhost:3000/api/Customers/55c17a197fe0b0c01b31d533/emails

sorry if my example does not clarify this situation. It was difficult to give a valid example for my problem.

**Comment by FelipeAguayo** [comment]
in my opinion, this is because loopback replaces 'emails' in the parent model with all changes (get a version of the model, make changes and save.), when it should work with the array elements.

**Comment by fabien** [comment]
@FelipeAguayo this is true, it's a limitation of the way it is currently implemented. Ideally this code should reside in a connector, so it can decide how to handle it more appropriately (think $push, $pull etc. in MongoDB for example). Right now, `emails` is treated no different from any other properties of your model, so the same caveats apply regarding concurrent/non-atomic writes.

**Comment by raymondfeng** [comment]
I agree with @fabien. Behind the REST API, LoopBack looks up the customer instance by id, add an email to the array, and save it back to DB (replacing instead of adding the array item).

We need to explore array operators in the future but unfortunately I don't see simple solutions if the DB is relational.
