### ISSUE TITLE
Override the default delete on juggler 2.30.1

### ISSUE THREAD

**Issue by jury89** [strongloop/loopback-datasource-juggler#680]
I need to override the default ```destroyAll``` and ```destroyById``` to implement the soft delete and i was watching the procedure described on http://docs.strongloop.com/display/public/LB/Customizing+models#Customizingmodels-Changetheimplementationofbuilt-inmethods

Now, if i well understand, with that procedure i am going to override the two methods after the persistent data source has been attached to the model and this force me to override ```destroyAll``` and ```destroyById``` in every single model i have.

I was wondering if instead there is a way to override ```destroyAll``` and ```destroyById``` before the persistent data source is attached to the model.

**Comment by raymondfeng** [comment]
You could potentially use mixins for this purpose.

- Create a mixin in `common/mixins` as `customizeDelete.js`:
```js
module.exports = function(Model, options) {
  // customize the methods
}
```

- In your model definitions, such as `common/models/note.json`, apply the mixin:
```
{
  "name": "note",
  ...
  "mixins": {"CustomizeDelete": {...}},
}
```

**Comment by jury89** [comment]
It works, i just have to define the mixin also in ```server/model-config.json```

```
"_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "../common/mixins"
    ]

  }
```

**Comment by raymondfeng** [comment]
If you use latest version of `slc loopback` to scaffold the app, the "mixins" is added to `server/model-config.json` by default.

**Comment by raymondfeng** [comment]
Docs WIP: http://docs.strongloop.com/display/LB/Defining+mixins

**Comment by jury89** [comment]
It requires a login which i'm not registered. Is there any public link?
