### ISSUE TITLE
RegExp objects in query should not be coerced to string

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#681]
See: https://github.com/strongloop/loopback-datasource-juggler/commit/b8f15987238bda922d3607203f2fdcdead4f250a#commitcomment-12537479

**Comment by raymondfeng** [comment]
I'm fine to treat it as a shortcut to the newly introduced `regexp`, for example:

`{name: /John.*/i}`should be normalized as `{name: {regexp: /John.*/i}}`
