### ISSUE TITLE
Document using regular expressions

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-datasource-juggler#685]
Need to update docs for using regex in queries.  See #552 and https://github.com/strongloop/loopback-connector/pull/26.

Presumably we need to add regex syntax to http://docs.strongloop.com/display/LB/Where+filter.
It would also be great to add some examples to one or more of the example apps.

@superkhau IIRC from your preso, the general syntax is:
```
MyModel.find({ where: {property: {regexp: 'expression'} } });
```
Where `expression` is the regular expression string.  Is that right?

And what does a REST query with a regex look like?

Also, is there any change in the use of the [like and nlinke operators](http://docs.strongloop.com/display/LB/Where+filter#Wherefilter-likeandnlike)?  I'm guessing these are unaffected, but I want to confirm.

**Comment by superkhau** [comment]
>Presumably we need to add regex syntax to http://docs.strongloop.com/display/LB/Where+filter.

Yes.

>It would also be great to add some examples to one or more of the example apps.

Definitely a good one to bring up during sprint planning. It's possible and I assume a few points, maybe 3.

>...IIRC from your preso, the general syntax is:...

That is correct.

>And what does a REST query with a regex look like?

This part I haven't tried out, but it should be the same as any where filter query. For example, using this filter in explorer:

```
{"where": {"email": {"regexp": "/^foo/"}}}
```

gives

```
http://localhost:3000/api/Accounts?filter=%7B%22where%22%3A%20%7B%22email%22%3A%20%7B%22regexp%22%3A%20%22%2F%5Efoo%2F%22%7D%7D%7D
```

Also, is there any change in the use of the like and nlinke operators? I'm guessing these are unaffected, but I want to confirm.

No changes to those two operators.

**Comment by crandmck** [comment]
Added https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Regularexpressions

**Comment by superkhau** [comment]
@crandmck Heads up, I'm adding a feature that lets you query regex like this:

```
{where: name: /John.*/i}
```

Notice the world 'regexp' is gone as if you use a RegExp literal/object directly, the code will automatically add in the 'regexp' keyword to your query. See https://github.com/strongloop/loopback-datasource-juggler/issues/681

**Comment by superkhau** [comment]
@crandmck Also, why did you assign to me? Is there something you need me to do? Maybe create a new issue that is not this doc issue?

**Comment by crandmck** [comment]
It's in Review state.  Please review the doc referenced above for accuracy and completeness.    That is S.O.P for doc issues.  Normally, if you don't have any comments you could just close the issue; but you can assign back to me to add the work from #681.  Then I can close it (unless you _want_ to review it again).

**Comment by superkhau** [comment]
TY for the SOP, understood. ;) I will ping you when I merge #681 and you could update it again. Please assign it to me then and I will review it all at once.

**Comment by superkhau** [comment]
@crandmck The feature has been merged. We can now do `{where: {name: /John/i}}`. Please update the docs accordingly and reassign to me when ready for review.

**Comment by crandmck** [comment]
OK @superkhau a couple questions:
- This new syntax is _in addition_ to that previously implemented (using the `regexp` "operator").
- Using the new syntax, the regular expression is NOT quoted.
- Can you use the new syntax in a REST query? If so, how, e.g. give me simple example here pls.

**Comment by superkhau** [comment]
Yes, in addition so the other `regexp` syntax is still there. New syntax must NOT be quoted or the code can't differentiate between a RegExp object or a string. So valid args would be `/John/i` or `new RegExp(/John/i), both of which are valid JS regex objects. This syntax does not support rest (this is the whole reason for having the `regexp` syntax as secondary. So we should let the user know that if they need a REST query, please use `regexp` operator syntax.

**Comment by crandmck** [comment]
OK @superkhau  I updated https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Regularexpressions with the new syntax.  PTAL at your convenience.  You can then either close or reassign back to me with comments (if they're straightforward, I'll fix & close; if not, will request a final review).

**Comment by superkhau** [comment]
>Using the first form above, the regular expression must be enclosed as quotes.

The first form accepts regular expression strings, literals and objects (ie. '^John', /John/, new RegExp(/John/)).

The second form doesn't not accept regular expression strings, only literals and objets (ie. /John/, new RegExp(/John/).

---

The rest LGTM.

**Comment by crandmck** [comment]
Thanks for the clarification.  I made the corresponding changes to the doc.

**Comment by superkhau** [comment]
@crandmck I looked a the docs again, the short syntax DOES NOT allow regex strings

```
{ where: {property: expression } } }
```

If you pass in `{where: {property: '^john'}}` it will fail, because we can't distinguish this from a regular string.

**Comment by crandmck** [comment]
Oops.  I understood that from your comment, but forgot to delete that line when I reformatted the section.  Thanks for double-checking.  I fixed it (for real).

**Comment by shubham201** [comment]
### Works well for string type. Having problem for number and date types.

I am having one issue related to this : 

> Tried querying `{ "where": {"name": RegExp(/^s/) } } ` & `{"where": {"name": {"regexp": RegExp(/^s/)}}}`  and These works fine.
> But, `{ "where": {"number": RegExp(/^1/) } }` & `{"where": {"number": {"regexp": RegExp(/^1/)}}}` don't work. And same is the case with date type properties.
> Consider i have the appropriate data for querying them.

**It is working well for string type but not number and date types.**
Is there any other way of querying for numbers and dates?

**Comment by Aibier** [comment]
Just try with {"where":{"property": {"regexp":"/keyword/i"}}}, dont miss "/" both before and after key word, just add keyword and add "/i" . 

This works file with me. 
If u use {"where":{"property": {"regexp":"*keyword*/i"}}} also works but keyword length must be greater than 2. 

Hope this helps you.
