### ISSUE TITLE
hasManyThrough relations have a malfunctioning modelInstance.relation.findOne method

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-datasource-juggler#688]
We have created a HasManyThrough relationship between two models. Consider, for example, models `ModelA`, `ModelB`, and a through model of `ModelConnector`. This creates a number of convenience methods on the models,

```
   modelAInstance.modelbs(...); // find related ModelB instances
   modelAInstance.modelbs.create(...); // create a related ModelB instance 
   modelAInstance.modelbs.findById(modelBId, ...); // locate a related ModelB instance by ID
   // some others 
   // and ...
   modelAInstance.modelbs.findOne(...); // Locate a single related ModelB instance
```

The last method does not work. Instead of returning a `ModelB` instance it returns a `ModelConnector` instance. 

Please see the following gist which contains a test snapshot,

   https://gist.github.com/doublemarked/3da120228c2a51a8afe4

**Comment by loay** [comment]
hi @doublemarked 
I will take a look at your gist for testing and get back to you

**Comment by doublemarked** [comment]
@loay thank you. To be honest, I have no recollection of even creating this Issue. Here's hoping that my snippet is useful... :)
