### ISSUE TITLE
embedsMany relations dont work with mongo ObjectID

### ISSUE THREAD

**Issue by mazesoul** [strongloop/loopback-datasource-juggler#695]
The embedsMany relation doesn't take into account mongo style ids. 

Here are some instances where the code uses `indexOf`and breaks with mongo object based ids:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2273
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2874
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L3014

Some working instances:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L3035

**Comment by raymondfeng** [comment]
Just to make sure: in your case, does the array contain the `equal` but not `same` ObjectID?

**Comment by mazesoul** [comment]
Exactly. The comparison occurs by identity in indexOf (`===`), and doesn't work with two ObjectID that contain the same string: 

```
var ids = [ObjectID('123')];
var id2 = ObjectID('123');

ids.indexOf(id2) !== 1
```

**Comment by raymondfeng** [comment]
We already have a utility to deal with id comparison - https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2280. It should be refactored into utils.js and use it for both places.

**Comment by mazesoul** [comment]
I did saw it but the full-blown refactoring seemed a bit above my head.
