### ISSUE TITLE
hasMany performance

### ISSUE THREAD

**Issue by wertlex** [strongloop/loopback-datasource-juggler#701]
Hi guys

We are building app with StrongLoop/Loopback and issue perfrormance problems with hasMany relations. We use Mongo, but this shouldn't really affect because all activity performed in juggler.

For ex: 
There are User which hasMany Permissions. If you will do call to GET /users everything will be fine. But once you call GET /users?filter={"include": "permissions"} it will just stuck. 

Diving into code show that includeHasMany(https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L489) is not really stuck, but extremely slow. I'm not very sure, but looks like nested async.each and async.parallel (one: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L537 , two: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L541 , three: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L554, four: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L99). Anyway we have one object processed in about 230 ms. 

Our test data consist of 104 users and 109 permissions totally, about one permission per user, but some of them have a bit more. I believe that this is not data problem, includeHasMany design problem - this method do a lot of things and some of them looks like overkill (though I didn't dig to much in other directions except this case). 

I've implement very simple includeHasMany2 which handles only hasMany without subIncludes and all that scheduled tasks magic. 

So question is: why simple join/include operation is so heavy and bloated? Did I miss something?

**Comment by superkhau** [comment]
@wertlex Did you lose interest in this issue? I just want to make sure you're getting the answer you need, but we usually don't answer questions on GitHub. Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by wertlex** [comment]
@superkhau I believe this behavior can be a part of https://github.com/strongloop/loopback-datasource-juggler/issues/698 

I'm not very confident in what exactly going on there as I'm Loopback newcommer, but those things I saw was a bit strange.

**Comment by superkhau** [comment]
I see. Yeah, this issue is probably a duplicate then. Thanks for the update. If you need more help, let me know. ;)
