### ISSUE TITLE
FK dataLength ignored

### ISSUE THREAD

**Issue by nennad** [strongloop/loopback-datasource-juggler#716]
If the PK has a definition like
```
      "mysql": {
        "dataType": "CHAR",
        "dataLength":36,
        "nullable":"N"
      }
```

dataLength is ignored when the PK is used as a foreignKey in other models

Possible fix https://github.com/strongloop/loopback-datasource-juggler/pull/715

**Comment by nennad** [comment]
https://github.com/strongloop/loopback-datasource-juggler/pull/715

**Comment by Amir-61** [comment]
Closing this issue since the PR has been landed and the problem got resolved.

Thanks for contribution!
