### ISSUE TITLE
Promises are broken

### ISSUE THREAD

**Issue by esco** [strongloop/loopback-datasource-juggler#719]
My Loopback app is broken after a deploy that updated node_modules. Based on the error it seems like the issue is with `loopback-datasource-juggler`.

Relevant dependencies
``` json
{
    "loopback-connector-mongodb": "^1.13.0",
    "loopback-datasource-juggler": "^2.39.0"
}
```

To replicate:

```
$ git clone https://github.com/ForbesMobile/promise-failure
$ npm i -g strongloop
$ cd promise-failure
$ npm i
$ slc run
```
> https://github.com/ForbesMobile/promise-failure made by @senorcris

Visit http://127.0.0.1:3000/explorer/#!/People/test press the "Try it out!" button. You will get the following error:

```
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot read property 'then' of undefined",
    "stack": "TypeError: Cannot read property 'then' of undefined\n    at Function.Person.test (/Volumes/Dev/servers/node/test/promise-failure/common/models/person.js:5:7)\n    at SharedMethod.invoke (/Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:248:25)\n    at HttpContext.invoke (/Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:384:12)\n    at /Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:620:11\n    at execStack (/Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:460:7)\n    at RemoteObjects.execHooks (/Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:464:10)\n    at /Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:617:10\n    at /Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/lib/application.js:357:13\n    at /Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/lib/model.js:313:7\n    at /Volumes/Dev/servers/node/test/promise-failure/node_modules/loopback/common/models/acl.js:465:23"
  }
}
```

Remote method being called:
```javascript
Person.test = function(cb) {
    Person.find({
      name: "Jake"
    }).then(function(p) {
      console.log('p: ', p);
      cb(null, p);
    }).catch(function(err) {
      console.log(err);
      cb(err);
    });
  };
```

Person is a PersistedModel
```json
{
  "name": "Person",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
Person.find should return a promise, but instead returns `undefined`

Any idea why PersistedModel.find isn't returning a promise?

Thanks!

**Comment by raymondfeng** [comment]
Do you have globals.Promise set?

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc. (An IBM Company)

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by esco** [comment]
Good catch, we have it in the app but not in the demo, I'll update to see if its reproducible in the demo. If not then it could be on our side.

**Comment by esco** [comment]
We're on node 0.12.7 which has Promises natively so theoretically the demo does have Promise in the global namespace, but we're using `bluebird` in our app so I'm going to update the demo to include `bluebird`.

**Comment by esco** [comment]
@raymondfeng I updated the test repo with bluebird set to `global.Promise`. I still get the same error. Thanks for looking into this.

**Comment by doublemarked** [comment]
Just to mirror what was said in Gitter about this - I was not able to reproduce the problems here, despite similarities in environment (OSX, Node 0.12.7, strongloop v5.0.0).

**Comment by doublemarked** [comment]
I figured out how to reproduce it, actually. When I run it as I normally run node apps on my workstation, `node .`, there are no problems. When I run it under the pm according to your instructions, `slc run`, I receive the same error you're reporting. Hm!

**Comment by senorcris** [comment]
@doublemarked I got similar results by running the app with `node` instead of `slc run`.

**Comment by esco** [comment]
Awesome, removing slc fixed the issue. I made another issue in the strongloop repo to track the bug. Thanks!
