### ISSUE TITLE
Discover other type of relations using `discoverSchemas`

### ISSUE THREAD

**Issue by eldefay** [strongloop/loopback-datasource-juggler#72]
The 'DataSource.prototype.discoverSchemas' only discovers relations of type 'belongsTo'. I can't find an way to determine relations of all types in Package?

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L992

**Comment by f0ysal** [comment]
@raymondfeng @eldefay @ritch  @bajtos 
Is there any update on this I am also getting only the "belongsTo" relations when running datasource.discoverSchema or datasource.discoverSchemas?

How to get the relations of a model??  i am running these steps:
1. datasource.discoverModelDefinitions
2. datasource.discoverSchema with {owner: 'dbo', views: true, all: true, relations: true} but still I am getting only the  "belongsTo" relations which is point to its own table.
