### ISSUE TITLE
Bug in mergeQuery util

### ISSUE THREAD

**Issue by esco** [strongloop/loopback-datasource-juggler#722]
I found some use for something like the [`mergeQuery`](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/utils.js#L161) util [loopback-datasource-juggler/lib/utils.js#L161](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/utils.js#L161) in my app and noticed a bug. It seems like the purpose of [`mergeQuery`](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/utils.js#L161) is to act as an [`_.extend`](http://underscorejs.org/#extend) for queries... basically to overwrite conditions in `base` with the values in `update` if they exist, while preserving all other conditions. 

The way conflicting where conditions are handled in [`mergeQuery`](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/utils.js#L161) is to create an `and` condition and populate it with the `base` and `update` condition. 

This works great if you have a conflicting condition:

``` json
// base 
{ "where": {  "startDate": {  "lte": 1444170309108 } } }

//update 
{ "where": {  "startDate": {  "gte": 1443306269771 } } }

// results in
{ 
    "where": {
        "and": [ { "startDate": { "lte": 1444170309108 } },  { "startDate": { "gte":1443306269771 } } ]
    }
}

```

But it breaks if that conflicting condition also has conflicting properties..ex:

``` json
// base 
{ "where": {  "startDate": {  "gte": 1444170309108 } } }

//update 
{ "where": {  "startDate": {  "gte": 1443306269771 } } }


// results in (notice both are 'gte')
{ 
    "where": {
        "and": [ { "startDate": { "gte": 1444170309108 } },  { "startDate": { "gte":1443306269771 } } ]
    }
}

```

In the above example, not only does "startDate" conflict, but "gte" also conflicts. Currently in mongodb if both of these conditions are in an `and` condition, this will result in the largest value for "gte" being applied. The desired effect is probably that the `update` condition overwrites the conflicting condition property in `base`.

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by mrbatista** [comment]
There is another issue:
```javascript
// base 
{where: {and: [ {prop1: {gte: value1}}, {prop2: value2] }}

//update 
{where: {prop1: {gte: value2}}}


// results in
{ 
    where: {
        and: [ {prop1: {gte: value2}}}, {and: [ {prop1: {gte: value1}}, {prop2: value2] }}]
    }
}
```
If necessary to check if  base `where` contain `and` condition.

**Comment by jannyHou** [comment]
^^ @raymondfeng PTAL :) Thanks.
