### ISSUE TITLE
Can not recreate super simpl SQL Query.

### ISSUE THREAD

**Issue by fifafu** [strongloop/loopback-datasource-juggler#728]
Hi,

I have a very simple use case and can't seem to get it to work with Loopback.

Setup: 
HasAndBelongsToMany relationship between models "Post" and "Tags". Now I need to get all posts that have specific tags. 

In SQL I'd just do  `SELECT Post.* FROM Posts,posts_tags  WHERE Post.id = posts_tags.postId AND posts_tags.tagId IN (2,3)`

Is this really not doable with Loopback?

**Comment by superkhau** [comment]
https://docs.strongloop.com/display/public/LB/HasAndBelongsToMany+relations

For future reference, please ask questions on one of our official channels. See https://github.com/strongloop/loopback/wiki/Questions. Closing.

**Comment by fifafu** [comment]
Well, I think this is a feature request as there is no method I can see in the documentation that would allow me to do what I want (which is in my opinion a pretty basic problem).

If there is a undocumented possibility to filter on related properties this should count as a enhancement request for the documentation.

The only solution I currently see is to query the tag model, use an include filter to include all posts and then afterwards filter out the duplicate posts manually. Or am I missing something?

**Comment by superkhau** [comment]
@crandmck Can you verify if we have docs for this?

@fifafu I'm reopening and marking duplicate and major for now as I've seen a few other people report issues with filtering related properties.

**Comment by crandmck** [comment]
AFAIK, we don't support filtering on related properties.  @raymondfeng can comment on the work involved to add this and if there is an existing issue.

**Comment by fifafu** [comment]
@superkhau, thanks a lot for reopening! I think almost every app has the need for such filtering, or am I mistaken? I think relations like Posts <=> Tags are very common in real world applications.

**Comment by superkhau** [comment]
@fifafu Yes, but unfortunately we have other priorities taking up our time. This issue has been around for awhile it seems: https://github.com/strongloop/loopback/issues/517
