### ISSUE TITLE
Missing callback call  in dao.js =>DataAccessObject.find => allCb

### ISSUE THREAD

**Issue by cleas** [strongloop/loopback-datasource-juggler#729]
See function allCb of DataAccessObject.find
if you have a query.collect, obj can be null in case related object does not exist. this results in async.each is not ending as the callback is not called for obj's that are null. 
It should be 
````
if(obj !==undefined ){
....
}
else{
callback();
}
````
In practice you will encounter this by requesting a hasAndBelongsToMany relation and the manytomany link table contains entries linking to non existing items, result will be a non returning api call.

**Comment by raymondfeng** [comment]
Good catch. Can you submit a patch?

**Comment by cleas** [comment]
yes, will take some time, (have to learn the patch process)

**Comment by 0candy** [comment]
Fixed by https://github.com/strongloop/loopback-datasource-juggler/commit/3028329126702456d59b42d6a88da17effe89919
Closing this issue.
