### ISSUE TITLE
missing check on fkId in relation-definition.js => HasMany.prototype.findById

### ISSUE THREAD

**Issue by cleas** [strongloop/loopback-datasource-juggler#734]
The function  HasMany.prototype.findById should check on fkId

```
 if (fkId == null || fkId === '') {
    process.nextTick(function () {
      cb(new Error('HasMany::findById requires the fkId argument'));
    });
    return;
  }
```

HasMany.prototype.findById makes use of findOne, this function will return first item if fkId is not defined.
I would expect an Error callback if function is called with undefined or empty fkId

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Amir-61** [comment]
Any update on this issue @cleas ?

**Comment by jannyHou** [comment]
`hasMany.prototype.findById` actually calls `modelTo.findOne()` to find the instance.
@Amir-61 Do you know is there any validation function in `DataAccessObject.findOne` or the function it eventually called `DataAccessObject.find` to check invalid(or undefined/null) fk in query? Thanks!
