### ISSUE TITLE
embedsMany concurrency problem

### ISSUE THREAD

**Issue by andressrg** [strongloop/loopback-datasource-juggler#737]
Hi,

I found a major issue with embedsMany concurrency.
I'm trying to create some models in parallel using the REST API, inside a embedsMany relationship, and some data gets lost.

I have tried with the MySQL and MongoDB connector and both fail the test.

This is my test case: https://github.com/andressrg/loopback-sandbox/blob/embedsMany-concurrency/test/embedded-creation.js#L13-L46

To reproduce the issue:
- clone and go to `embedsMany-concurrency` branch
- `npm install`
- setup mysql with this [config](https://github.com/andressrg/loopback-sandbox/blob/embedsMany-concurrency/server/datasources.json#L7-L12)
- `mocha`

Is there a way to enable transactions in this case?

**Comment by tbarho** [comment]
:+1:

**Comment by superkhau** [comment]
>Is there a way to enable transactions in this case?

https://docs.strongloop.com/display/public/LB/Using+database+transactions

**Comment by vanraizen** [comment]
@andressrg even if it worked with transactions the solution wouldn't cover Mongo users. Unless the create() call uses something like the Mongo $push extended operation I don't see how it would ever be safe to use concurrently because it looks like right now the function uses updateAttribute(). I'm facing this problem as well.

**Comment by swapnilg** [comment]
+1 using mongo and facing this issue , unable to use $push but will figure it out please add the default behavior for embedmany as push itself.

**Comment by jannyHou** [comment]
A sample from @sebastianhaas also run into same problem
https://github.com/strongloop/loopback-datasource-juggler/issues/1173 
For some reason I could not reproduce the error from his repo but will dig into it more since so many users have the same problem.

**Comment by sebastianhaas** [comment]
@jannyHou is there any way I could help you any further with this? I hope you guys understand that this is a major, critical and horrible issue. It renders embedded models de-facto unusable, and the worst part about it is, that there is not the slightest clue in the docs about these very serious limitations of the framework (ID generation, concurrency problems, no way to push single instances but arrays only etc.)
