### ISSUE TITLE
Can't canonicalize query: BadValue unknown operator from MongoDB

### ISSUE THREAD

**Issue by masalinas** [strongloop/loopback-datasource-juggler#738]
I add a organization to the administrator using this source code:

administrator.organizations.add(credentials.organization, function(err) {
                if (err) return err;

                console.log('organization ' + organization.name + ' registered');

                // return administrator created
                cb(err, administrator);
            });

I obtain this error:

name: MongoError
code: 17287
message: Can't canonicalize query: BadValue unknown operator: $name

What is the problem????

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
