### ISSUE TITLE
Model.create() making duplicate models

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-datasource-juggler#740]
Model.create() seems to be making duplicate models. I'm using it on my User model and it simultaneously persists two duplicate Users to the database, then fails on a duplicate email and username (on both models at once!)

I've done a bit of debugging and it seems that `ObserverMixin.notifyObserversOf` calls `ObserverMixin_notifyBaseObservers`, which then calls `ObserverMixin.notifyObserversOf` again etc until the validation error happens.

What could be causing this?

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Narrator** [comment]
+1
