### ISSUE TITLE
If datasource becomes unavailable, the callback is never invoked

### ISSUE THREAD

**Issue by SynerG** [strongloop/loopback-datasource-juggler#741]
I have found this problem in multiple ways, but it seems that it all boils down to not invoking the callback that expects the result from a datasource when the datasource becomes unavailable.

To reproduce the problem (using mongo as datasource):
- Run your mongod process
- Run your Loopback app (it will connect to mongo on boot) 
- Kill/stop your mongod process
- Invoke a method of an entity that is persisted on mongo.
  E.g: User.findOne({where: {email: "someemail@company.com"}}, function(err, user){
  // This function is never invoked
  // It should be invoked with an error, at least after a timeout
  });

This problem manifest itself in other scenarios:
- If you define a remoteMethod in a Model, and the method requires authentication. After losing connection with the datasource, the remoteMethod is never invoked (so the error cannot be handled inside the remoteMethod) . I guess Loopback is waiting for the accessToken validation to be resolved.
- Calls to REST API endpoints that require authentication never receive a response. They should receive an indication of the internal server error.

It is not related to Loopback waiting for connection retries to the datasource, because no result is provided even after all the retries have finished. Even if retries were still on going, the request should receive an error after a timeout.

**Comment by loay** [comment]
Hi @SynerG 
I am having a look. Do you have a sample repo I can use to reproduce? Thanks

**Comment by SynerG** [comment]
Thanks for having a look. I don't have a specific sample repo, but it should be easy to reproduce. Just take any Loopback app that uses a Mongo datasource (or a different database), and stop the database while the app is still running. 

You should find the issue described above (the callback is not called and no error provided) when you call any method of the model that requires the database. 

If you are not able to reproduce the issue with this basic setup, I will try to create a specific repo.
