### ISSUE TITLE
JSON Schema compatibility

### ISSUE THREAD

**Issue by amok** [strongloop/loopback-datasource-juggler#742]
Hi all!
Model definition looks like [JSON Schema](http://jsonapi.org/format/) but isn't. Available validators throw trying validate data using juggler definition schema, there is problem with "required" prop also. Are there any plans to adapt definitions to json-schema format?

**Comment by amok** [comment]
...I think, it'll be also good to give simple way to use adapters from mentioned JSON Schema or blueprint specs etc. is it so)?

**Comment by jannyHou** [comment]
@amok Model definition also contains functions I think.
I am trying to answer your question but I have something to confirm:

> Available validators

What do you mean by available validators?

>  there is problem with "required" prop also

Could you give me the link of the 'required prop' you refered?

And for a better debugging, could you provide a code to explain what's your concern?
To upload the code, please fork https://github.com/strongloop/loopback-sandbox and replace it with your code.
Thanks!
