### ISSUE TITLE
Protected properties should be included if the include filter is for yourself model

### ISSUE THREAD

**Issue by mrbatista** [strongloop/loopback-datasource-juggler#743]
I’m using the build-in User model and defined a protected e-mail property. If I call a custom remote method, such as User.login, with the include filter (i.e. /api/users/login?include=user) the response does not contain the e-mail property. Please add the possibility to remove protected properties only if the include filter is related with other relations and not with yourself.

Related to this pull request https://github.com/strongloop/loopback-datasource-juggler/pull/400.
@superkhau consider this an encanchement.
@raymondfeng I will happy to create a PR that implement this feature. Any suggestion?

**Comment by jannyHou** [comment]
I am closing this issue since https://github.com/strongloop/loopback-datasource-juggler/pull/400 merged 👍
