### ISSUE TITLE
Is it possible to determine when to use validation, and not automatically call it from create or update?

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-datasource-juggler#744]
I'm having a model that has to be validated only when it's getting published (via custom remote method).
When I use loopbacks built-in validation, isValid also get's executed on create and save.
I just want it to be executed in my remote method only

I tried first with validateUpsert-option set to false, and then use upsert for every creation, update-operation. That worked fine, but now I have to set my ACL's and in an upsert operation I cannot detect the owner of the model instance, so I have to use the other methods again. 

I think it would be better if the creation of the validation rules could be seperated from the execution.

Is there a quick solution for this?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See h    ttps://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by ernie58** [comment]
Hi superkhau

Would it be a good idea to implement above functionality with a setting in the json model definition.
For example: autoValidate (default true), which would automatically apply the validation rules on update or save, (like it is happening now), and when set to false, only would apply the rules when you call the isValid-function manually

If I'd make a pull-request, is there any chance it would be accepted.

Otherwise, I'd just use a custom validation library for now

Thx for your advice

**Comment by superkhau** [comment]
Sounds like a good idea to me. @bajtos @ritch @raymondfeng Any opinions on this feature before the user submits a PR?

**Comment by raymondfeng** [comment]
The CRUD methods now have the `options` argument. We should allow `disableValidation` at various levels.

**Comment by superkhau** [comment]
@ernie58 Would you like to give this a shot? We can comment further on the PR itself.

**Comment by ernie58** [comment]
Allright! I'll try to implement this tomorrow. Could you give me a hint, where to find the code concerning the CRUD method options?

**Comment by bajtos** [comment]
> Could you give me a hint, where to find the code concerning the CRUD method options?

Look in `lib/dao.js` - [create](https://github.com/strongloop/loopback-datasource-juggler/blob/46bdb063c46ec16543a7c6f7e16c1c8c1aca1776/lib/dao.js#L159) and [save](https://github.com/strongloop/loopback-datasource-juggler/blob/46bdb063c46ec16543a7c6f7e16c1c8c1aca1776/lib/dao.js#L1852).

The validation is implemented in `lib/validations.js` - see e.g. [isValid](https://github.com/strongloop/loopback-datasource-juggler/blob/46bdb063c46ec16543a7c6f7e16c1c8c1aca1776/lib/validations.js#L413)

I personally think both approaches - a method-level option (`options.validate)` and a model-level setting (`autoValidate`) - are valid, eventually we can implement both of them.
