### ISSUE TITLE
how to overlay the default scope in the model config

### ISSUE THREAD

**Issue by bboalimoe** [strongloop/loopback-datasource-juggler#748]
i set the model as follows：

```
 "poiProbLv2": {
      "type": "object",
      "required": true
    },
    "pois": {
      "type": "object",
      "required": true
    },
    "location": {
      "type": "geopoint",
      "required": true
    },
    "createdAt": {
      "type": "string",
      "required": true
    },
    "updatedAt": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {},
  "scope": {
    "order": "name",
    "limit": 100
  }
}
```

but when i start a request like this 

```
http://ip:3000/api/UserLocations?filter[limit]=2&filter[where][user_id]=5627226c00b09f851ff4a200&filter[fields][location]=true
```

the restapi limit filter didn't work as expected , it still outputs 100 items not 2 items

thanks a lot!

**Comment by superkhau** [comment]
@crandmck Do we have docs on this? I'm not sure if its even possible.

**Comment by crandmck** [comment]
Is this an excerpt from UserLocations model file, i.e. `common/models/UserLocations.json` ?

We have some docs on the `scopes` model property: https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes

First, the above excerpt has `scope` instead of `scopes`, but I'm not sure if that's what you're trying to accomplish--this is for a "named query" that you define in the JSON and reference in JS code, not REST.

**Comment by bboalimoe** [comment]
@crandmck yes. it's from UserLocation.
i use the knowledge from the below docs

```

Default scope
If you wish for a scope to be applied across all queries to the model, you can use the default scope for the model itself.
For example:
{
  "name": "Product",
  "properties": {
    ...
  }
  "scope": {
    "order": "name",
    "limit": 100
    "where": {
      "deleted": false
    }
  }
}

```

**Comment by crandmck** [comment]
I think that is a mistake in the docs.  Can you try changing `scope` to `scopes` and see if that works as expected.  If so, I will update the docs accordingly.

**Comment by bboalimoe** [comment]
i change as below , the scopes didn't function as scope.in the scope case, all query will be limited to 100,while in scopes case, query all not limited ...that is the scopes restriction didn't work~
@crandmck  
```
{
  "name": "Product",
  "properties": {
    ...
  }
  "scopes": {
    "order": "name",
    "limit": 100
    "where": {
      "deleted": false
    }
  }
}
```

**Comment by mrfelton** [comment]
There is a related issue with scoped limits here https://github.com/strongloop/loopback-datasource-juggler/issues/610

**Comment by crandmck** [comment]
@superkhau At this point, I don't think this is a doc issue.  If it is, I'm not sure how to address it.

**Comment by superkhau** [comment]
@crandmck The doc label can be removed now since you've confirmed with the issue is not a mistake in the docs. Putting back to triage since it looks like we need more flushing out.

**Comment by superkhau** [comment]
@bboalimoe Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by bboalimoe** [comment]
done  @superkhau  thanks
