### ISSUE TITLE
mongo connector has no return for updateAll/update

### ISSUE THREAD

**Issue by bowfeng** [strongloop/loopback-datasource-juggler#749]
I met an issue with update/updateAll, it has no return to tell me how many documents had been effected, through the dao.js I could tell it returns an object {count:**}, but from the remote access, I didn't see this kind of return.

**Comment by jannyHou** [comment]
@bowfeng I am trying to reproduce your error, could you fork https://github.com/strongloop/loopback-sandbox and provide a sandbox that reproduce it?
Thanks!

**Comment by jannyHou** [comment]
I am closing this issue due to missing details to reproduce it. Please feel free to reopen it if anyone still run into the problem with more details. Thanks.
