### ISSUE TITLE
linkOneToMany objList is undefined.

### ISSUE THREAD

**Issue by zmijevik** [strongloop/loopback-datasource-juggler#753]
I am getting the following error:

>TypeError: Cannot read property 'length' of undefined
>    at Object.async.each (/var/www/vhosts/greenback-api/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:152:17)
    at linkOneToMany (/var/www/vhosts/greenback-api/node_modules/loopback-datasource-juggler/lib/include.js:757:19)

The issue is coming from the following function:

        function targetLinkingTask(next) {
          async.each(targets, linkOneToMany, next);
          function linkOneToMany(target, next) {
            var targetId = target[relation.keyTo];
            var objList = objTargetIdMap[targetId.toString()];
            async.each(objList, function (obj, next) {
              if (!obj) return next();
              obj.__cachedRelations[relationName] = target;
              processTargetObj(obj, next);
            }, next);
          }
        }

For some reason objList is undefined. Is there a reason why this would happen and can you check if objList is undefined before attempting to iterate over it.

**Comment by zmijevik** [comment]
It turns out the following method triggered the issue:

>Model.all(params).then(function(items) {

params contains the following: 
<pre>
   { 
      skip: 10,
      limit: '10',
      include: [ 'offer', 'location' ],
      where: { subscriber_id: 3 } 
   } 
</pre>

This would have returned an empty result based on the offset because there are no more than 9 results based on the where filter


loopback-datasource-juggler/lib/include.js 153
>Inclusion.include = function (objects, include, options, cb) {

Model.all send an empty array of objects to the objects parameter which results in the issue in the above post.

Can you provide an early return when objects is an empty array?

**Comment by raymondfeng** [comment]
Patch pls?

**Comment by zmijevik** [comment]
@raymondfeng Are you asking me to provide a patch? I can provide one if you are able to replicate the issue. I wan't to be sure I am not doing something wrong here.

**Comment by raymondfeng** [comment]
Yes.
