### ISSUE TITLE
need Async node_module to 1.5 in package json

### ISSUE THREAD

**Issue by Malkiat-Singh** [strongloop/loopback-datasource-juggler#756]
need to update the     "async": "~1.0.0" to  "async": "~1.5.0" in package json
because this will install async 1.0.0 by default which cause crash due to check undefined array length

**Comment by superkhau** [comment]
Would you like to submit a PR?

**Comment by Malkiat-Singh** [comment]
yes I will submit to to change the pakage json

**Comment by dhmlau** [comment]
Currently, in package.json, `"async": "~2.1.4"`.
Closing this issue.
