### ISSUE TITLE
MongoDB connector debug flag has no effect

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-datasource-juggler#768]
My mongodb connection works fine, I wanted to debug queries, set the debug flag to true according to the docs, restarted the server and nothing happens.
```
  "db": {
    "host": "localhost",
    "database": "test",
    "name": "db",
    "connector": "mongodb",
    "debug":true
  },
```

**Comment by superkhau** [comment]
https://docs.strongloop.com/display/public/LB/Setting+debug+strings

**Comment by barocsi** [comment]
Thanks, wish it was referred from https://docs.strongloop.com/display/public/LB/MongoDB+connector

**Comment by superkhau** [comment]
@barocsi Let's get that fixed.

@crandmck ^

**Comment by crandmck** [comment]
Should I remove the `debug` property from https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-Properties?
Does that not work?  If so, is it a bug or mistake in docs?
