### ISSUE TITLE
limit filter ignored

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-datasource-juggler#769]
For some reason my limit filter is ignored (using mongodb connector).
Using the loopback-sandbox git, adding
```json
datasources.json:
"db": {
    "host": "localhost",
    "database": "test",
    "name": "db",
    "connector": "mongodb",
    "debug":true
  },
```
adding a post model, exposing a remote method for testing
```javascript
module.exports = function (Post) {

  Post.getNext = function (limit, cb) {
    var context = loopback.getCurrentContext();
    var http = context.get('http');
    var user = context.get('currentUser');
    console.log(limit)
    Post.find({
                  limit: 1
              }, cb);
  };

  Post.remoteMethod(
    'getNext',
    {
      accepts: [{arg: 'limit', type: 'string', required: false},
      ],
      returns: {arg: 'post', type: 'object'},
      http: {path: '/getNext', verb: 'get'}
    }
  );
}
```

the result ignores limit parameter and returns all items, always, even if hardcoded as in the example.
I am not sure where it went wrong or what would override it.
I am not able to debug since the debug flag has no effect at all as noted in https://github.com/strongloop/loopback-datasource-juggler/issues/768

**Comment by barocsi** [comment]
https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes

I have defined a default scope with limit. It was not clear for me, that the default scope is always active when defined and cannot be overridden.

**Comment by 0ff** [comment]
In fact I think this was not intended and I've just submitted PR #787 to change that :-)
