### ISSUE TITLE
"strict" validation fails on invalid relations mixed with valid relations

### ISSUE THREAD

**Issue by hotaru355** [strongloop/loopback-datasource-juggler#780]
When a model is defined with `strict = true/validate/throw`, the strict option is ignored in certain conditions.
Example:
- **correct**, validating a relation not defined in user's schema:
  
  ```
        var user = new User({name: 'John', extraInvalidRelation: [{invalidRelationId: 111}]});
        user.isValid(); // false
  ```
- **correct**, validating a relation that _is_ defined in the user's schema:
  
  ```
        var user = new User({name: 'John', posts: [{content: 'my post'}]});
        user.isValid(); // true
  ```
- **fail**, validating relations that are only partially defined in the user's schema:
  
  ```
        var user = new User({name: 'John', posts: [{content: 'my post'}], extraInvalidRelation: [{invalidRelationId: 111}]});
        user.isValid(); // true, BUT SHOULD BE false
  ```

The issue is caused by a single line, https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L196, of which I do not understand the purpose of. Could you please provide some information. The test case below demonstrates the issue.

https://github.com/strongloop/loopback-datasource-juggler/pull/781

**Comment by jannyHou** [comment]
Reproduced the error. 
Any update on pr https://github.com/strongloop/loopback-datasource-juggler/pull/781 ?

Could you take a look? @raymondfeng @fabien
