### ISSUE TITLE
Password with Numbers saving Null

### ISSUE THREAD

**Issue by mariohmol** [strongloop/loopback-datasource-juggler#782]
When I save a User model with a password containing just numbers it do not save the password, save null in password field. (using MySQL)

To solve that, I had to convert to string before  calling the User.create()

````
userObj.password=userObj.password.toString();
app.models.User.create(userObj 
...

````

Maybe because it will convert to a password hash (like md5 ...)

Is it the normal behaviour? Would be better to convert the password to string before passing to the gen hash?

**Comment by geekguy** [comment]
I use postgre connector. Facing the same issue in latest version.

**Comment by loay** [comment]
Hi @mariohmol and @geekguy 
Are you guys still having the same issue? I thought that was already fixed as per this comment: 
https://github.com/strongloop/loopback-sdk-angular/issues/44#issuecomment-43093894

I will have a look but is there a public repo I can use to reproduce? Thanks.

**Comment by mariohmol** [comment]
I cant remember now.. but i could fix it... i think that it was related to same validation (a field missing or somethin).. i dont know about @geekguy but to me you can close it

**Comment by loay** [comment]
Thanks @mariohmol 
@geekguy if you are having the same issue, please leave a comment and I will re-open the issue. Thanks.
