### ISSUE TITLE
Default scope applied to another scope

### ISSUE THREAD

**Issue by sklyukin** [strongloop/loopback-datasource-juggler#791]
I have `default` and `scopeDeleted` scopes. 
 ```json
"scopes": {
    "scopeDeleted": {
      "where": {
        "status": "deleted"
      }
    }
  },
"scope": {
    "where": {
      "status": "active"
    }
}
```

Now when I try to access deletedScope -  `MyModel.deletedScope({})` *DataAccessObject.applyScope* will actually generate 
> `{"where":{"and":[{"status":"deleted"},{"status":"active"}]}}`

And I always get 0 results. Is it intended to apply default scope for all scopes? In case it is not I can work on PR for this.

**Comment by sklyukin** [comment]
Seems this is intended, as scopes can be chained, so any custom scope "chain" default scope.
```js
  // Define scope-chaining, such as
  // Station.scope('active', {where: {isActive: true}});
  // Station.scope('subway', {where: {isUndeground: true}});
  // Station.active.subway(cb);
```
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L253-L256

I'm closing issue.

**Comment by loay** [comment]
Thanks. closing.
