### ISSUE TITLE
validatesUniquenessOf doesn't work correctly on bulk create with same values

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback-datasource-juggler#793]
I have a model `MyParam`
It has a property `name` that needs to be unique

When I post an array of new instances with the API-explorer, and two instances have the same `name` , and that `name` is not yet in the database, they both get inserted.

```
module.exports = function(MyParam) {
    MyParam.validatesUniquenessOf('name');
};
```

_POST_ /MyParams

```
[{
  "name": "notyetindatabase",
  "id": 0
},{
  "name": "notyetindatabase",
  "id": 0
}]
```

I would expect that at most one is inserted and an error is returned for the other, or that an error is returned for the entire array without inserting

**Comment by ernie58** [comment]
Is this considered as a valid bug ? Can I help to fix this?

**Comment by horiaradu** [comment]
I believe this is related to https://github.com/strongloop/loopback-datasource-juggler/issues/892

**Comment by 0candy** [comment]
Could you please fork the loopback-sandbox with a sample app to reproduce this issue? Thanks!
https://github.com/strongloop/loopback-sandbox

Please contribute by submitting  a PR. =)

**Comment by beeman** [comment]
I just found out about this issue and created this branch to reproduce it https://github.com/beeman/loopback-sandbox/tree/validate-uniqueness-of-issue

Another issue mentioning this is https://github.com/strongloop/loopback/issues/1452

**Comment by FelipeAguayo** [comment]
Any progress on this?

**Comment by CaptainMM** [comment]
Felipe. I find the validatesUniquenessOf works as expected as long as you define unique at the property level.
   
```
    "someValue": {
      "type": "string",
      "index": {
        "unique": true
      }
    }
```
