### ISSUE TITLE
relational database: source field name option in relation configuration

### ISSUE THREAD

**Issue by dpundir** [strongloop/loopback-datasource-juggler#794]
<b>Support of source(keyFrom) field name option in relation configuration i.e. source.sourceKey -> target.targetKey</b>

Example:
Table-> fields
Customer-> id(primary), addressid(fkey)
Address-> id(primary)

"Customer" model configuration can have below relation config:
"relations": {
"address":{
"type": "hasOne",
"model": "Address",
"foreignKey": "id"
}
}

This relation gets its foreignKey values from primary key("id") of the model i.e. Customer.id -> Address.id. 

<b>There should be "keyFrom" option to find "pk" like below:</b>
RelationDefinition.hasOne = function (modelFrom, modelTo, params) {
params = params || {};
modelTo = lookupModelTo(modelFrom, modelTo, params);

var pk = <b>params.keyFrom</b> || params.primaryKey || modelFrom.dataSource.idName(modelFrom.modelName) || 'id';

This "keyFrom" can be included in "relations" configuration like below:
"relations": {
"address":{
"type": "hasOne",
"model": "Address",
"foreignKey": "id",
<b>"keyFrom":"addressid"</b>
}
}
Customer.addressid -> Address.id which makes it truly relational.

**Comment by jannyHou** [comment]
Thank you for the suggestion @dpundir But I think in our relation definition, `keyFrom` means the primary key of modelFrom, I am confused why we need another keyFrom in your implementation?

And also, for example i create a relation: Customer hasMany Address, then Address has a foreign key 'customerId', not customer has a foreign id `addressid` :)

**Comment by dpundir** [comment]
Thank you for looking into this suggestion.
Right, _keyFrom_ means the primary key in model definition.
It depends on database design where we want to place the foreign key and how we want to retrieve the data using relations.

In your example too, you need to tell the logic that relation is from 'customerId' in Address model mapped to 'id' in Customer Model. 
Below logic will try to extract foreignkey field name in Address model which will be "id" not "customerid":
var pk = params.primaryKey || modelFrom.dataSource.idName(modelFrom.modelName) || 'id';

Here my suggestion is to reuse the configuration name "keyFrom" which clearly tells logic which field is acting as foreign key.

**Comment by dpundir** [comment]
What is the plan for this suggestion?

**Comment by jannyHou** [comment]
@dpundir Sorry for the late response, I think the feature you suggest is more like `referenceOne`.
loopback now has `referenceMany`: see doc https://loopback.io/doc/en/lb2/Embedded-models-and-relations.html#referencesmany
while hasn't implemented referenceOne yet.

cc @raymondfeng any idea on the suggestion?
