### ISSUE TITLE
hasManyThrough pivot table

### ISSUE THREAD

**Issue by mbouclas** [strongloop/loopback-datasource-juggler#799]
Is there a way to get the pivot table on a hasManyThrough query? Better yet, apply some filter or sort to it. A typical example 

```
Table products
id,title

Table categories
id,title

table products_categories
productsId, categoriesId, orderBy, main

```

So, in the above scenario, say you want to get all categories of product X that are (main = true) or you want to sort the the product categories by orderBy.

What happens now is a first SELECT on products to get the product data, a second SELECT on products_categories to get the categoriesId and a final SELECT on categories to get the actual categories. Ideally, filters and sort should be applied to the 2nd SELECT like 
```
SELECT `id`,`productsId`,`categoriesId`,`orderBy`,`main` FROM `products_categories` 

WHERE `productsId` IN (180) WHERE main = 1 ORDER BY `orderBy` DESC
```

Is that even possible?

**Comment by loay** [comment]
Hi @mbouclas 
I see you had few answers here: http://stackoverflow.com/questions/34412908/loopback-relational-database-hasmanythrough-pivot-table

Also, I am not sure which db are you using but if you are using mongoDB, you can extend the built-in models and configure your settings. Let me know if you require further assistance. Thanks.
