### ISSUE TITLE
MyModel.validatesLengthOf return always true unless the min or max are given explicitly as args

### ISSUE THREAD

**Issue by yassine-khachlek** [strongloop/loopback-datasource-juggler#802]
This is the file my-model.json
<pre>
...
  "properties": {
    "text": {
      "type": "string",
      "length": 512,
      "required": true
    }    
  },
...
</pre>
It seems that this validation method used inside my-model.js always returns true:
<pre>
module.exports = function(MyModel) {
  MyModel.validatesLengthOf('text');
};
</pre>
Unless the min or the max are explicitly given as args like that :
<pre>
module.exports = function(Tweet) {

	Tweet.validatesLengthOf('text', 
			{ 
			  max: 140,
			  message: { 
			    max: 'Text should be 140- characters' 
			  } 
			}
		);

};
</pre>

So, i think that this validation function should validate max length based in this given rules:

=> if given in arg.
	if not the defined length in my-model.json 
		if not the defaut string type length (512)

**Comment by loay** [comment]
Hi @yassine-khachlek 
That is the correct behavior. Here is how it works:
Validatable.validatesLengthOf(propertyName, Options)

Validate length. Require a property length to be within a specified range. Three kinds of validations: min, max, is.

Default error messages:

min: too short
max: too long
is: length is wrong
Example: length validations
```
User.validatesLengthOf('password', {min: 7});
User.validatesLengthOf('email', {max: 100});
User.validatesLengthOf('state', {is: 2});
User.validatesLengthOf('nick', {min: 3, max: 15});
```

You can find more info here:
https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validateslengthof

**Comment by loay** [comment]
if you are still experiencing the same issue, please feel free to leave a comment and I will re-open the case. Thanks.
