### ISSUE TITLE
Upsert failed to give error messages

### ISSUE THREAD

**Issue by QingYun** [strongloop/loopback-datasource-juggler#808]
I was trying to upsert some js objects parsed from a xml file into mongodb and I can only get those ones with empty body stored. For other ones, there was no error message but the result passed into my callback was null. After switching to model.create, I finally got the error message said that "$" fields were not allowed to be stored in mongodb.

**Comment by hotaru355** [comment]
Just encountered the same issue and have created a [PR](https://github.com/strongloop/loopback-datasource-juggler/pull/877). If a unit test is required, I need to know ...

- ... in what test file you would like to add the test. `test/basic-querying.test.js` seems to be fitting place and I would add it to the (currently [skipped](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js#L623) but apparently working) [`query` section](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js#L654)
- ... what mocking module to use, so I can mock/stub the connector to respond with an error.

Thanks

**Comment by Amir-61** [comment]
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/877

**Comment by Amir-61** [comment]
This has been fixed by [this PR](https://github.com/strongloop/loopback-datasource-juggler/pull/877)

Thanks a lot!
