### ISSUE TITLE
hasOne relation working issue with include filter

### ISSUE THREAD

**Issue by robinskumar73** [strongloop/loopback-datasource-juggler#811]
I am having issue using `find` method for `hasOne` with include filter.
I have two models

`Priority` model whose relations is `hasOne` with `Recipe` model

```
"name": "Priority",
"base": "PersistedModel",
...
...

"relations": {
    "recipes": {
      "type": "hasOne",
      "model": "Recipe",
      "foreignKey": ""
    }
  }
```

I have another model  `Recipe` in `hasOne` relation with `Priority` model

```
"name": "Recipe",
"base": "PersistedModel",
...
...

"relations": {
    "priorities": {
      "type": "hasOne",
      "model": "Priority",
      "foreignKey": ""
    }
  }
```

I am saving data like this.

```
var priorityModel = recipe.priorities.build(priorityData);
Priority.upsert(priorityModel, function(err, value){
    console.log("Recipe priority data saved succesfully");
})
```

Now when I am using `find` method with `include` it's working in one case but not in another

```
Using first method

/api/Recipes?filter={"include":["priorities"]} 

//Return the priority data along with recipes data. successfully
{
  "recipeName": "pizza",
  "priorities":{
     "priority": "high"
   }
}


//Second method
//But when I am fetching recipe using priority since both are with hasOne relationship
//IT FAILS it doesn't fetch the Recipe data assosiated with the priority.
//using Get request

/api/Priorities?filter={"include":["recipes"]}


```

**Comment by 0candy** [comment]
Could you please fork the loopback-sandbox with a sample app to reproduce this issue? Thanks!
https://github.com/strongloop/loopback-sandbox

**Comment by AThilenius** [comment]
I apologize in advance if I goofed something up, but I forked the loopback-sandbox https://github.com/AThilenius/loopback-sandbox and created the models `Foo - hasOne Bar`, `Bar - hasMany Baz` and `Baz`. I'm a big fan of creative naming, clearly. Models will be created in server.js for you.

The following
```curl -X GET --header "Accept: application/json" "http://localhost:3000/api/Foos/1/bar?filter=%7B%22incluide%22%3A%20%22bazes%22%7D"```
returns only `{"id":1,"fooId":1}`. More interestingly, there isn't even a 'filter' input box on the explorer for a hasOne relationship, so I suspect LoopBack is just ignoring the filter field.
![image](https://cloud.githubusercontent.com/assets/3269553/16597341/95bc2c56-42b5-11e6-8ee7-2d50c2d77766.png)
Please let me know if I can help out any more, I'm pretty new to the awesomeness that is LoopBack though.

**Comment by AThilenius** [comment]
## To expand
This is a problem in other places as well. For example, I have my ACL set up to only allow access to $owner, meaning that models must be accessed via the relationship API like `/parent/:id/child`. No problem, that works great. But what if I have a few thousand hasMany children and I only want to get one of them? No problem again, just use the `/parent/:id/child/:fk` API. However, you can't add an include filter with that as well.
The only workarounds I see are to add the include filter to a `/parent/:id/child` query *(not possible in my case, it would be hundreds of MB of data)*, or to manually do the includes once the parent resolves, adding tons of latency for deeply nested includes and a metric ton a boilerplate/callback hell.

**Comment by 0candy** [comment]
Thank you for pointing out the issue. `hasOne` currently does not take a filter parameter.
I am closing this issue as its being tracked here:
https://github.com/strongloop/loopback/issues/2304
