### ISSUE TITLE
DataAccessObject._coerce doesn't work for embedded properties 

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-datasource-juggler#813]
The coerce behavior is falling on embedded properties, preventing queries that need to be coerced from functioning.  Consider the following (analysis will follow):

``` javascript
loopback > ReportAuthor = ds.createModel('ReportAuthor', { foreignId: String, name: String }, { idInjection: false })
loopback > Report = ds.createModel('Report', { title: String, priority: String }, { relations: { reportAuthor: { type: 'embedsOne', model: 'ReportAuthor', property: 'author' } } })
loopback > Report.create({ title: 'Test Report', priority: 99, author: { foreignId: 1111, name: 'Heath' } })
{ title: 'Test Report',
  priority: '99',
  author: { foreignId: '1111', name: 'Heath' },
  id: 568bc27b12b693143b4b225c }
loopback > Report.findOne({where:{priority: 99}})
{ title: 'Test Report',
  priority: '99',
  id: 568bc0b42b23fee73aea137b }
loopback > Report.findOne({where:{'author.foreignId': 1111}})
null
```

Note:
- Correct embedded property coercion on create
- Incorrect embedded property coercion on query

Details: 
It is possible to apply a where filter to fetch records according to a standard model property field: `GET /api/Reports?filter[where][priority]=99`. When this is performed, strong-remoting evaluates the query string value (`"99"`) and coerces it into a numeric value (unavoidably?). The resulting where filter looks like: `{ priority: 99 }`, which strong-remoting hands off to `DataAccessObject.find`.

The `find` method needs to coerce properties used in the filter into the types used by the model. `DataAccessObject._coerce` rightly identifies that the `priority` is of type String (using model config) and coerces the filter into the following: `{ priority: "99" }`. All is good. 

Consider instead the following request: `GET /api/Reports?filter[where][author.foreignId]=111`. The `_coerce` method again is asked to coerce the filter (`{ "author.foreignId": 111 }`). However, there is no logic for identifying the type of author.foreignId - `_coerce` looks naively at `Report.definition.properties` for `author.foreignId`, and having failed to find it, surrenders: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1172-L1175

For the meantime we are using a regex query to avoid this issue.

**Comment by gausie** [comment]
Could be related to https://github.com/strongloop/loopback-datasource-juggler/pull/732

**Comment by gausie** [comment]
I've seen this happen on a lot of issues and I will just say that this
seems really bizarre - the fact that it hasn't been fixed doesn't mean it's
no longer a bug.
