### ISSUE TITLE
include filter is not fetching data with couch database but fetching data with memory db

### ISSUE THREAD

**Issue by gsateesh4u** [strongloop/loopback-datasource-juggler#816]
My Customer model is below
{
  "name": "Customer",
  "plural": "Customers",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "hub": {
      "type": "belongsTo",
      "model": "Hub",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}
 and my Hud model is below
{
  "name": "Hub",
  "plural": "Hubs",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "customers": {
      "type": "hasMany",
      "model": "Customer",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}
None of these reuturns related model data
http://localhost:3000/api/Customers?filter={"include":["hub"]}  is only returning customer information not including hub
http://localhost:3000/api/Hubs?filter={"include":["customers"]}   is only returning hub information not including customers of that hub.
I am using apache couch database. This is working fine if I use memory database. Can anybody please help.

**Comment by 0candy** [comment]
What couch connector are you using?

**Comment by Amir-61** [comment]
It seems [loopback-connector-couch](https://github.com/mattange/loopback-connector-couch) is a connector implemented by community; please open the issue in that repo.

Thanks
