### ISSUE TITLE
npm ERR! peerinvalid The package loopback-datasource-juggler@2.44.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/loopback-datasource-juggler#820]
npm ERR! Linux 3.19.0-43-generic
    npm ERR! argv "/home/polin/.nvm/versions/node/v4.2.4/bin/node" "/home/polin/.nvm/versions/node/v4.2.4/bin/npm" "install"
    npm ERR! node v4.2.4
    npm ERR! npm  v2.14.12
    npm ERR! code EPEERINVALID
    
    npm ERR! peerinvalid The package loopback-datasource-juggler@2.44.0 does not satisfy its siblings' peerDependencies requirements!
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/polin/github/selfiebeneficios/api/npm-debug.log

**Comment by loay** [comment]
Hi @paulomcnally 
Thanks for reporting the issue. Would it be possible to provide a repo on github to reproduce the issue?
Thanks.

**Comment by paulomcnally** [comment]
Hi @loay.

I have a private repository.

I added manuality last version (alpha repository) to package.json.

I solved using v2.44.0 on package.

Error is using alpha dependency.

Thanks
