### ISSUE TITLE
adding belongsTo relation inclusion to embedsOne relation

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-datasource-juggler#821]
Hi, 

I'd like to add support for belongsTo relation inclusion to embedsOne relation, in a similar way as it is supported by the embedsMany relation. 
Is there already some work in progress on this? is this already referenced somewhere?

Thks for comments.

**Comment by jannyHou** [comment]
@ebarault Thank you for your suggestion. Could you explain more about "support for belongsTo relation inclusion to embedsOne "? It's better if you can link where is the similar implementation in `embedsMany`.

@bajtos i remember you are working on some improvement of `embedsOne` and `embedsMany` relationship, do you have any plan to support the feature that @ebarault mentioned above? Thanks.

**Comment by bajtos** [comment]
We don't have plans to implement this feature (as I understand it) in the near future. We accept community contributions though and are happy to help you @ebarault along the way, if you decide to implement this feature yourself.

**Comment by ebarault** [comment]
hi @bajtos,

ok, i'll not be able in the very near feature to provide a contribution, but i'll do my best. Mostly i didn't want to breach into somebody else's work in progress here.

as a fallback we're using "embedsMany with belongsTo" anytime we need a belongsTo relation to be resolved nested inside an embedOne relation. The drawback though is that we need to handle arrays of unique objects (`[0]`) instead of a simple dot `.`

I wonder if i may: what is the status of embedsX relations in the product? is there a precise reason why starting with nested relations over embeds and then halt?

anyway, happy to help when possible, i'll be in touch when ready to start.

**Comment by bajtos** [comment]
> I wonder if i may: what is the status of embedsX relations in the product? is there a precise reason why starting with nested relations over embeds and then halt?

I *think* we started with embedsX relations becase that's what the original juggler module provided. Embedded relations were contributed only later by the community contributor & maintainer @fabien and they are mostly improved by community since then.
