### ISSUE TITLE
Remove legacy model hooks

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#824]
Remove legacy model hooks triggered via `inst.trigger`. Users should have migrated to new Operation hooks quite some time ago.

https://github.com/strongloop/loopback-datasource-juggler/pull/473

> **Model hooks**
> beforeValidate
> afterValidate
> beforeCreate
> afterCreate
> beforeSave
> afterSave
> beforeUpdate
> afterUpdate
> beforeDestroy
> afterDestroy

https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/hooks.test.js

**Comment by davidcheung** [comment]
- [ ] Remove use of [inst.trigger](https://github.com/strongloop/loopback-datasource-juggler/blob/5dca27278a37b1e2e0fa572c3ae20681cd500680/lib/dao.js#L2011-L2012)
- [ ] test would probably break because of this
- [ ] update documentation to relfect change 
- [ ] update `3.0-RELEASE-NOTES.md` to document breaking change

**Comment by 0candy** [comment]
After discussion with Miroslav, we decided not to include this change for 3.0 as this change is more than just removing deprecated code. There is a feature for `inst.triggerParent` in embedsMany that needs more consideration and possibly a rewrite for embedded relations to continue work. It is for updating the parent model if any changes are made to the relation. Also, embedsOne does not have this feature yet and it should be considered. This part needs a redesign and rewrite to consider the different cases and to make it all consistent.

Here's a proposed rewrite for `inst.triggerParent` which should also be added to other embeddedRelations.
https://github.com/strongloop/loopback-datasource-juggler/commit/d0cc791bc65e5ee7d2447698539da1d1ca0591ee
