### ISSUE TITLE
belongsTo method is not promisified

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback-datasource-juggler#827]
Using loopback-datasource-juggler 2.44 I have found the belongsTo getter method does not return a promise. 

For example, I have a model, say `Order` which has a belongsTo relationship with `Customer`.

This code does not work, although I would expect it to:

     order.customer().then(customer => {
         // do something with customer
     }

I've been using a promise-wrapping library to work around this, but it gets annoying everywhere I want to get the `customer` to first wrap the method and bind to the instance, then get the promise.

I know promises are a work in progress, but according to the [documentation](https://github.com/strongloop/loopback/issues/418) I would think the DAO-level code should work now.

**Comment by Neil-UWA** [comment]
```
order.customer.getAsync().then(....)

```

**Comment by IgorDavy** [comment]
Works like a charm :+1:

**Comment by jbcpollak** [comment]
yup, that works, thanks. Its a bit confusing, but it works.

**Comment by loay** [comment]
Issue resolved. Closing the issue. Thanks.

**Comment by jbcpollak** [comment]
Thanks for the tip, I know promises are still under development.

**Comment by loay** [comment]
@jbcpollak 
If you are still having the same problem or a question regarding it, please let us know or just leave a comment so and I will re-open the case to investigate further. 
Regards

**Comment by jbcpollak** [comment]
sorry, my last comment was vague, everything is fine. I wish the api didn't
require the getAsync(), but it works well.

**Comment by IgorDavy** [comment]
And what about adding customer to an order ?

I tried setAsync but it doesn't work
```
Customer.createAsync(...).then(customer => {
    order.customer(customer).setAsync.then(...)
}
```

**Comment by will-fgmnt** [comment]
This is *very* confusing. Can the docs be updated to explain this? Especially when...

... this works
```
MyModel.myHasManyRelation().then(...);
```

... but this doesnt.
```
MyModel.myBelongsToRelation().then(...);
```
