### ISSUE TITLE
Add connectors that support messaging APIs

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#83]
LoopBack models should be able to attach to datasources backed by messaging connectors to:
1. Send messages to a queue
2. Receive messages from a queue
3. Listen on messages from a queue
4. Publish to a topic
5. Subscribe to a topic.

**Comment by dhmlau** [comment]
@raymondfeng, since this issue was last updated about 2 years ago, I'd like to confirm with you whether `loopback-connector-mqlight` is the outcome of this discussion, and whether it's good to close.  Thanks.

**Comment by dhmlau** [comment]
Talked to @raymondfeng, might look at this in LB next.
