### ISSUE TITLE
MongoError not catched

### ISSUE THREAD

**Issue by dmellonch** [strongloop/loopback-datasource-juggler#830]
Hello everyone!

I've found a problem with MongoError not catched (duplicate key on index during updateOrCreate)
https://github.com/strongloop/loopback-datasource-juggler/blob/2.x-latest/lib/dao.js#L520-L531

The err object in done function (row 520) is the correct MongoError but err obj is not checked and error is not propagated.

**Comment by 0candy** [comment]
Could you please fork the loopback-sandbox with a sample app to reproduce this issue? Thanks!
https://github.com/strongloop/loopback-sandbox

**Comment by dmellonch** [comment]
Hi @0candy! 
The problem has already been fixed in release  2.x-latest.
For me the issue may be closed.
