### ISSUE TITLE
Update loopback-datasource-juggler API docs for promises

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback-datasource-juggler#833]
Parent: strongloop/loopback/issues/1409
Related: strongloop-internal/strong-docs/issues/63, strongloop-internal/scrum-loopback/issues/615

`scope.js`
ScopeDefinition.prototype.related
(seems lack doc page)

`dao.js`
Static methods:
[DataAccessObject.create](https://apidocs.strongloop.com/loopback/#persistedmodel-create)
DataAccessObject.updateOrCreate (alias of upsert)
[DataAccessObject.upsert](https://apidocs.strongloop.com/loopback/#persistedmodel-upsert)
[DataAccessObject.findOrCreate](https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate)
[DataAccessObject.exists](https://apidocs.strongloop.com/loopback/#persistedmodel-exists)
[DataAccessObject.findById](https://apidocs.strongloop.com/loopback/#persistedmodel-findbyid)
DataAccessObject.findByIds (alias of findById)
[DataAccessObject.find](https://apidocs.strongloop.com/loopback/#persistedmodel-find)
[DataAccessObject.findOne](https://apidocs.strongloop.com/loopback/#persistedmodel-findone)
DataAccessObject.remove (alias of destroyAll)
DataAccessObject.deleteAll (alias of destroyAll)
[DataAccessObject.destroyAll](https://apidocs.strongloop.com/loopback/#persistedmodel-destroyall)
DataAccessObject.removeById (alias of destroyById)
[DataAccessObject.destroyById](https://apidocs.strongloop.com/loopback/#persistedmodel-destroybyid)
DataAccessObject.deleteById (alias of destroyById)
[DataAccessObject.count](https://apidocs.strongloop.com/loopback/#persistedmodel-count)
DataAccessObject.update (alias of updateAll)
[DataAccessObject.updateAll](https://apidocs.strongloop.com/loopback/#persistedmodel-updateall)

Instance methods:
[DataAccessObject.prototype.save](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-save)
DataAccessObject.prototype.remove (alias of destroy)
DataAccessObject.prototype.delete (alias of destroy)
[DataAccessObject.prototype.destroy](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-destroy)
[DataAccessObject.prototype.updateAttribute](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattribute)
[DataAccessObject.prototype.updateAttributes](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattributes)
[DataAccessObject.prototype.reload](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-reload) ?

`datasource.js`
All of them are instance methods `DataSource.prototype.`
[automigrate](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-automigrate)
[autoupdate](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-autoupdate)
[discoverModelDefinitions](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discovermodeldefinitions)
[discoverModelProperties](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discovermodelproperties)
[discoverPrimaryKeys](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverprimarykeys)
[discoverForeignKeys](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverforeignkeys)
[discoverExportedForeignKeys](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverexportedforeignkeys)
[discoverSchema](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverschema)
[discoverSchemas](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-discoverschemas)

`relation-definition.js`
HasMany.prototype.findById
HasMany.prototype.exists
HasMany.prototype.updateById
HasMany.prototype.destroyById
HasManyThrough.prototype.findById
HasManyThrough.prototype.destroyById 
HasManyThrough.prototype.create
HasManyThrough.prototype.add
HasManyThrough.prototype.exists
HasManyThrough.prototype.remove
BelongsTo.prototype.create
BelongsTo.prototype.update
BelongsTo.prototype.destroy
BelongsTo.prototype.getAsync
HasOne.prototype.create
HasOne.prototype.update
HasOne.prototype.destroy
HasMany.prototype.create
HasOne.prototype.getAsync
EmbedsOne.prototype.embeddedValue
EmbedsOne.prototype.create
EmbedsOne.prototype.update
EmbedsOne.prototype.destroy
EmbedsMany.prototype.create
EmbedsMany.prototype.add
EmbedsMany.prototype.remove
ReferencesMany.prototype.findById
ReferencesMany.prototype.exists
ReferencesMany.prototype.updateById
ReferencesMany.prototype.destroyById
ReferencesMany.prototype.at
ReferencesMany.prototype.create
ReferencesMany.prototype.add
ReferencesMany.prototype.remove 

`observer.js`
[ObserverMixin.notifyObserversOf](https://apidocs.strongloop.com/loopback-datasource-juggler/#observermixin-notifyobserversof)

`transaction.js`
[TransactionMixin.beginTransaction](https://apidocs.strongloop.com/loopback-datasource-juggler/#transactionmixin-begintransaction)
[Transaction.prototype.commit](https://apidocs.strongloop.com/loopback-datasource-juggler/#transaction-prototype-commit)
[Transaction.prototype.rollback](https://apidocs.strongloop.com/loopback-datasource-juggler/#transaction-prototype-rollback)

**Comment by kjdelisle** [comment]
@davidcheung What exactly needs updating here? Are we updating the doc descriptions, or just the method signatures to ensure that they say `@returns Promise`?

**Comment by davidcheung** [comment]
@kjdelisle hmm i actually dont remember, i dont think i started it tho, perhaps @jannyHou might remember. I would assume it is to add jsdoc to the methods similar to https://github.com/strongloop/loopback/pull/2040

**Comment by jannyHou** [comment]
Follow the discussion in issue https://github.com/strongloop/strong-docs/issues/63 I believe we already support promise in jsdoc, but not sure why it doesn't show up in website.

I remember I tested the implementation before and it works. I need to investigate how to display promise annotation properly.

**Comment by kjdelisle** [comment]
Doc issue; shouldn't be stale.

**Comment by kjdelisle** [comment]
@crandmck This looks like it's still an issue, but in the JSDoc itself.
As an example:
The automigrate function is making use of our promise-or-callback strategy, but the JSDoc is missing the `@returns Promise<{type}>` symbol.
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L919

**Comment by crandmck** [comment]
OK, thanks for staying on top of it @kjdelisle.  Do you want to open a PR for this?  I can probably address it at some point, but if you want to get it fixed sooner rather than later.... :-)
