### ISSUE TITLE
Through relations inconsistently resolved

### ISSUE THREAD

**Issue by Resonance1584** [strongloop/loopback-datasource-juggler#835]
This is related to https://github.com/strongloop/loopback-datasource-juggler/issues/575

When including a relation in a .find method call, the results are returned from the cache.
When calling the relation method of an object the results are returned from the cache unless a non-null filter is passed.

Example (boot script on app startup):

In this example the database has been initialized with two permission objects (admin and coordinator), and one childPermission through object making coordinator a child of admin.

```
module.exports = function (app, cb) {
  const permission = app.models.permission

  // Find with include filter
  permission.find({
    include: 'children'
  }, (err, permissions) => {
    if (err) return cb(err)
    console.log('Result of find w/ include: "children"')
    permissions.forEach((permission) => {
      // Calling toJSON as per https://docs.strongloop.com/display/public/LB/Include+filter#Includefilter-Accessincludedobjects
      console.log(permission.toJSON())
    })

    // Call children relation
    Promise.all(permissions.map(permission => {
      return new Promise((resolve, reject) => {
        permission.children((err, children) => {
          if (err) return reject(err)
          resolve(children)
        })
      })
    }))
    .then(childrenArray => {
      console.log('Result of manually fetching children via relation method:')
      console.log(childrenArray)

      // Call chilren relation with non-null filter
      Promise.all(permissions.map(permission => {
        return new Promise((resolve, reject) => {
          permission.children({}, (err, children) => {
            if (err) return reject(err)
            resolve(children)
          })
        })
      }))
      .then(childrenArray => {
        console.log('Result of manually fetching children via relation method with non null filter object:')
        console.log(childrenArray)
        cb()
      })
      .catch(err => {
        cb(err)
      })
    })
    .catch(err => {
      cb(err)
    })
  })
}
```

Output:

```
Result of find with filter {include: "children"}
{ name: 'admin', id: 1, children: [] }
{ name: 'coordinator', id: 2, children: [] }
Result of manually fetching children via relation method:
[ [], [] ]
Result of manually fetching children via relation method with non null filter object:
[ [ { name: 'coordinator', id: 2 } ], [] ]
```

Through debugging we can see that here https://github.com/strongloop/loopback-datasource-juggler/blob/v2.44.0/lib/scope.js#L175 `self.__cachedRelations` is an empty object and is returned instead of fetching the related object from the database. The workaround is to pass a non-null filter (true works) when fetching the relationship. This is unexpected and undocumented behaviour.

loopback 2.26.2
loopback-datasource-juggler 2.44.0

**Comment by digitalsadhu** [comment]
@bajtos @raymondfeng any thoughts on this?

**Comment by Resonance1584** [comment]
Follow up - appears to be two different ways in that through relations are handled. One where the keyThrough property is used, which in my case was automagically generated as a property that does not exist, resulting in an empty __cachedRelations object. 

The other code path (triggered by the non-null filter) fails to match on the relation keyThrough but continues anyway... using ` filter.collect = throughRelationName || i8n.camelize(modelTo.modelName, true);`  (resolving as relationType) which eventually calls targetModel.find with the following params object
```
{
  collect: <relationType>,
  include: {
    relation: <relationType>
  },
  where: {
    <relationForeignKey>: id
  }
}
```
Which fetched the relation results we wanted.

So currently there are two different ways that through relations are handled - one where the automagical definition of keyThrough is significant, and one where if the type, and throughModel relation name is significant.

**Comment by loay** [comment]
Hi @Resonance1584 
Thanks for reporting the issue. I will check the boot script and get back to you ASAP. Thanks.

**Comment by mrjrdnthms** [comment]
This bug seems to have gotten me. I see intermittent missing includes when the relationship is a hasmany with a through model for the find/findone apis. Adding arious filters did not resolve the problem. In the end I was forced to use a second api call to return the related items. bummer.

**Comment by jannyHou** [comment]
two test cases are passing in juggler:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L666-L716

I manually test another scenario:
```js
physician.patients(function(err, ch) {
            should.not.exist(err);
            should.exist(ch);
            ch.should.have.lengthOf(3);
})
```
Also pass.
@Resonance1584 @mrjrdnthms can you double check the three scenario I mentioned above and see if following them can solve your issue?

**Comment by mrjrdnthms** [comment]
I have different models, of course, but in the context of the tests you have:

physician.patients(... works fine
physician.find({where{id:1},include:["patients"]}... I get no patients back most of time even if related patients exist.

**Comment by jannyHou** [comment]
@mrjrdnthms hmm weird. test case https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L3555 also passes.

Can you make sure you are using the latest 2.x version loopback-datasource-juggler@2.53.0? Or the new 3.x version loopback-datasource-juggler@3.1.0.

**Comment by Resonance1584** [comment]
@jannyHou I'm no longer using Loopback. The issue I reported was almost one year ago - I'm unsure if the current codebase still behaves in this way. The issue I had was that there were two different code paths resolving through relations: one where the definition of keyThrough is significant, and one where the type, and throughModel relation name is significant.
