### ISSUE TITLE
[v2.44.0] `nin` operator does not work with memory data source

### ISSUE THREAD

**Issue by terusus** [strongloop/loopback-datasource-juggler#838]
The model in question is defined with `"idInjection": true`. Models with ids from 1 to 5 are successfully created. The following code produces no results:

```javascript
Model.find({where: {id: {nin: [2]}}}, function(error, result) {
  console.log(error); \\ null
  console.log(result); \\ []
});
```

Same code works as expected with MySQL data source.

**Comment by horiaradu** [comment]
This should be fixed via: https://github.com/strongloop/loopback-datasource-juggler/pull/860

**Comment by Amir-61** [comment]
It seems this issue has been solved. I'm closing it; please feel free to re-open the ticket if you run into the same issue.

Thanks!
