### ISSUE TITLE
Dates are saved as string since update from .39 to .45

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback-datasource-juggler#840]
After updating to the .45 version the dates are now saved as strings and not as dates in MongoDB. Is there a solution?

**Comment by UlrichRaab** [comment]
+1 Have the same Problem

**Comment by smstromb** [comment]
+1 This happens with updateAttributes for me after upgrading

**Comment by julien-sarazin** [comment]
+1 Same problem, even with IDs for related models.

**Comment by Amir-61** [comment]
I believe this has been resolved. If not, could you please provide a sample repo reproducing the issue?

Thanks

**Comment by Amir-61** [comment]
I believe this issue has been resolved, so closing the ticket now. If you still encounter the same issue please feel free to re-open the ticket.

Thanks!
