### ISSUE TITLE
ObjectId are serialized as Strings since 2.45 on UpdateAttributes

### ISSUE THREAD

**Issue by julien-sarazin** [strongloop/loopback-datasource-juggler#845]
Model's relationships are filled as Strings after updates.

**Comment by pwwolf** [comment]
+1  This is a pretty serious issue.  It screwed up some of our data, and caused queries to stop working.

**Comment by jfurie** [comment]
+1

Its defiantly between  v2.44.0...v2.45.0

https://github.com/strongloop/loopback-datasource-juggler/compare/v2.44.0...v2.45.0

**Comment by mrfelton** [comment]
@jfurie you mention that this issue affects between v2.44.0...v2.45.0. Does that mean it is resolved in the recent v2.45.1? Or have you just not tested that. I'm a little scared to upgrade with this looming and potentially disastrous issue still open.

**Comment by Amir-61** [comment]
I believe this has been resolved. If not, could you please provide a sample repo reproducing the issue?

Thanks

**Comment by Amir-61** [comment]
I believe this has already been resolved, so closing this ticket. If you still encounter the same issue, please feel free to re-open the ticket.

Thanks!
