### ISSUE TITLE
updateAttributes adds missing properties with value undefined before storing

### ISSUE THREAD

**Issue by leolannenmaki** [strongloop/loopback-datasource-juggler#848]
In `before save` & `after save` hooks my object looks something like this:

```
{ name: 'test',
  embeddedList:
   [ { a: 100, c: 'Car' },
     { a: 200, c: 'Plane' },
     { a: 300, c: 'Boat' } ],
...
```

But in Mongo my object looks like this:

```
{ name: 'test',
  embeddedList:
   [ { a: 100, b: undefined, c: 'Car' },
     { a: 200, b: undefined, c: 'Plane' },
     { a: 300, b: undefined, c: 'Boat' } ],
...
```

The property `b` in the embedded model is defined like this:

```
    "b": {
      "type": "number",
      "description": "some description"
    },
```

There are no validations for `b`.

After adding logging inside [DataAccessObject.prototype.updateAttributes](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/dao.js#L2299) I can see that everything looks correct until the section commented as [// Convert the properties by type](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/dao.js#L2409). 

Before that section `data` looks like: 

```
{ name: 'test',
  embeddedList:
   [ { a: 100, c: 'Car' },
     { a: 200, c: 'Plane' },
     { a: 300, c: 'Boat' } ],
...
```

and after that `typedData` looks like: 

```
{ name: 'test',
  embeddedList:
   [ { a: 100, b: undefined, c: 'Car' },
     { a: 200, b: undefined, c: 'Plane' },
     { a: 300, b: undefined, c: 'Boat' } ],
...
```

I can "fix" this by adding one more `data = removeUndefined(context.data);` to [just before the actual](https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/dao.js#L2460) `connector.updateAttributes` call.

Not sure if that's the "proper fix", though.

**Comment by Amir-61** [comment]
Hey @leolannenmaki,

>I can "fix" this by adding one more data = removeUndefined(context.data); to just before the actual connector.updateAttributes call.

Would you like to send a patch fixing this? Also in your patch please add a test case which fails with the current implementation and it passes with your fix.

Thanks!
