### ISSUE TITLE
[Request] Document uuidv4 as defaultFn option

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback-datasource-juggler#850]
It appears there is an undocumented option for `defaultFn`, `uuidv4`. Both the [implementation](https://github.com/strongloop/loopback-datasource-juggler/blob/49c2bc214acb99fa6ec4bdefe59b3da095835795/lib/model.js#L288-L291) and a [corresponding test](https://github.com/strongloop/loopback-datasource-juggler/blob/3b9d3d0212ee44e6b033379082266b71a39ea4f8/test/manipulation.test.js#L1394-L1418) are found in this repo. Is there anything preventing this from being added to the [Model definition JSON file documentation](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file?src=search&src=search#ModeldefinitionJSONfile-Generalpropertyproperties)?

**Comment by crandmck** [comment]
This is already documented in https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties

In the table:
> "uuidv4": generate a new universally unique identifier using the UUID version 4 algorithm.

If that's incorrect or incomplete, please reopen and include appropriate details.
