### ISSUE TITLE
Unable to define polymorphic relations, Could not find "relation" relation for Model

### ISSUE THREAD

**Issue by sahilanguralla** [strongloop/loopback-datasource-juggler#851]
I am facing an issue with polymorphic relations. 
```
{
  "name": "Organisation",
...
  "relations": {
...
    "behalfWriteAuthorizations": {
      "type": "hasMany",
      "model": "WriteAuthorization",
      "polymorphic": {
        "as": "authority",
        "foreignKey": "authorityId",
        "discriminator": "authorityType"
      }
    }
...
```
This code raises an error saying

> Could not find "behalfWriteAuthorizations" relation for Organisation

While the same code in another model "Writer", it just works fine
```
{
  "name": "Writer",
...
  "relations": {
...
    "behalfWriteAuthorizations": {
      "type": "hasMany",
      "model": "WriteAuthorization",
      "polymorphic": {
        "as": "authority",
        "foreignKey": "authorityId",
        "discriminator": "authorityType"
      }
    }
...
```

**Comment by loay** [comment]
Hi @sahilanguralla 
Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by sahilanguralla** [comment]
Hey @loay I had already reported the same issue in main "**loopback**" repository and it has been marked as a bug. Thanks for replying btw.
[https://github.com/strongloop/loopback/issues/2051#issuecomment-182159433](https://github.com/strongloop/loopback/issues/2051#issuecomment-182159433

**Comment by loay** [comment]
Hi @sahilanguralla Thanks. Closing this one as a duplicate.
