### ISSUE TITLE
query _normalize removes second level properties from fields filter in strict mode

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-datasource-juggler#854]
I'm trying to access a second level property of a model. I'm using the dot notation `'field.subFeild': true`. While the `field` is defined in the model properties, it is defined an open object. 

Investigating why the field filter is empty, I find that in strict mode, if a key in the `fields` filter is supplied to a query that is not directly defined in model properties, `field.subfield`, it is removed from the query.

Is this something that should be supported by this project? Seems like second level data query is possible when not in strict mode.

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L267

``` js
  var fieldArray = [];
  if (excludeUnknown) {
    for (i = 0, n = result.length; i < n; i++) {
      if (properties.indexOf(result[i]) !== -1) { // if result[i] = 'field.subField', it will be ignored
        fieldArray.push(result[i]);
      }
    }
  } else {
    fieldArray = result;
  }
  return fieldArray;

```

possible solution

``` js
  var fieldArray = [];
  if (excludeUnknown) {
    for (i = 0, n = result.length; i < n; i++) {
      var topLevelField = result[i].split('.')[0]; // should account for result[i] being undefined or null.
      if (properties.indexOf(result[i]) !== -1) {
        fieldArray.push(result[i]);
      }
      if (topLevelField) {
        fieldArray.push(result[i]);
      }
    }
  } else {
    fieldArray = result;
  }
  return fieldArray;

```

**Comment by jannyHou** [comment]
A second level data query is also suggested in issue https://github.com/strongloop/loopback-datasource-juggler/issues/903

Thanks for your suggestion and solution, i label it as a feature.
