### ISSUE TITLE
Cannot create models with property named "trigger"

### ISSUE THREAD

**Issue by plmrry** [strongloop/loopback-datasource-juggler#855]
It seems that you cannot define a model property named "trigger":

``` javascript
var Test = app.loopback.createModel({
  name: 'Test',
  base: 'PersistedModel',
  strict: 'validate',
  properties: {
    trigger: String
  },
  idInjection: true
});

app.model(Test, { dataSource: 'mongo' });

app.models.Test.create([
  { trigger: 'foo' }
], function(e, d) {
  console.log(e,d) // TypeError: this.trigger is not a function
})
```

The error occurs [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L335), but may also be related to [inst.trigger](https://github.com/strongloop/loopback-datasource-juggler/blob/5dca27278a37b1e2e0fa572c3ae20681cd500680/lib/dao.js#L2011-L2012).

**Comment by 0candy** [comment]
Thank you for pointing out the bug. Actually it looks like your model property is being set hence it overrides the internal `inst.trigger` function that we had defined causing the error `is not a function`. Loopback should throw an error when the user tries to define a model property with the name `trigger` and any other `reserved names` that we may have.

Would you be interested in submitting a PR to fix the issue?

**Comment by malek0512** [comment]
Is there any fix for this issue?
I use loopback-datasource-juggler@4.17.0
