### ISSUE TITLE
Loopback / datasource-juggler browserify bundle does not work in IE11 ?

### ISSUE THREAD

**Issue by drywolf** [strongloop/loopback-datasource-juggler#863]
Hi,

I'm building a javascript app with loopback for the browser (using the browserify bundling). Everything works fine in Chrome/Firefox, but when I run the same code in Internet Explorer 11 (v11.103.10586.0) I hit an error in types.js at modelType.registerType() and the builtin types.

The error happens because IE11 does not seem to support the function().name attribute ?!
(see discussion here: http://stackoverflow.com/a/6903860)

At [line 47 of types.js](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/types.js#L47) the datasource-juggler tries to access this property and it resolved to `undefined` in IE11. This causes other parts of code in the juggler to crash.

I tried to fix the issue by initializing the `name` property manually if it is not defined, then the code continues to initialize, but in the end I receive the following error:

    Error while booting loopback AssertionError: must provide a valid SharedClass

This only occurs in IE though. Before I debug deeper into the issue I would like to know if those are known issues / if IE11 support is not up to date ? Is there something on the roadmap about IE11 support that I should know before I start working on a fix...

Thanks

**Comment by loay** [comment]
Hi @drywolf 
I have read that there are issues with IE11 for debugging purpose and I quote from here: https://www.npmjs.com/package/tsify

> The inlined sourcemaps that Browserify generates [may not be readable by IE 11](https://github.com/TypeStrong/tsify/issues/19) for debugging purposes. This is easy to fix by adding [exorcist](https://github.com/thlorenz/exorcist) to your build workflow after Browserify.

I am not sure if that is applicable to your case or that's different but thought that might help. AFAIT, there is not anything about IE11 support but I will keep you posted if I get some news.

**Comment by peterholcomb** [comment]
@drywolf Did you ever get this resolved?  I'm getting the same issue even though I've got exorcist included in the build as recommended by @loay

**Comment by drywolf** [comment]
@peterholcomb I fixed this by adding a proper polyfill for `function.prototype.name` to my project.

The code that causes the above error is located in [remote-objects.js](https://github.com/strongloop/strong-remoting/blob/5b3f5bd559f0d8cc8d4975953d32443ef44ca8e6/lib/remote-objects.js#L200)
And as you can see the error happens also because this code depends on `constructor.name` returning the actual function name / class name.

You can get the polyfill that I am using from [here](https://github.com/JamesMGreene/Function.name/blob/master/Function.name.js).
