### ISSUE TITLE
options.allowExtendedOperators doesn't work with updateAttributes

### ISSUE THREAD

**Issue by Valko54** [strongloop/loopback-datasource-juggler#867]
Hi,

After many tests, I can't use options.allowExtentedOperations with model.updateAttributes function.

Could you add the option.allowExtentedOperations in dao.js file (line: 2810) ?
`var allowExtendedOperators = connector.settings && connector.settings.allowExtendedOperators;`

I use "strict" option and my data variable is cleaned by this line: 
`if (strict && !allowExtendedOperators) {
      applyStrictCheck(self.constructor, strict, data, inst, validateAndSave);
    }`

The behavior is consistent but, is it correct ?

Thank you.

**Comment by Amir-61** [comment]
Hey @Valko54,
>Could you add the option.allowExtentedOperations in dao.js file (line: 2810)>
Please keep in mind context of the file keeps changing and line numbers are not valid; the better way is to add the link to the line of code you are referring to; however for this question I suggest you send a PR and discuss the changes in your patch... if they make sense we land the PR, or we can discuss further there...

Thanks... Please let me know if you agree and we can close this ticket...

**Comment by Amir-61** [comment]
Closing this ticket now.  As suggested please send a PR and discuss the changes in your patch...

Thanks!
