### ISSUE TITLE
Clear documentation for this module

### ISSUE THREAD

**Issue by jaumard** [strongloop/loopback-datasource-juggler#870]
It's possible to use this ORM outside loopback ? If yes where is the documentation about this module for use it in standalone ?

**Comment by 0candy** [comment]
It is not designed for use outside of loopback. There are some functionalities that you can use outside of loopback but some that are specific to loopback. What are you trying to do?

**Comment by jaumard** [comment]
@0candy I want to use this ORM in an other framework or only with Express without loopback. 
The functionality I need/want :  
- Models validations
- Create/Find/Update/Delete models with relations. 
- Models hooks

**Comment by 0candy** [comment]
You should be able to use those functionalities. Please be aware that we have deprecated model hooks but have operation hooks in place of it.
https://docs.strongloop.com/display/APIC/Operation+hooks

We do not support it for use as a standalone hence we don't have docs for that. However, you should be able to find docs on how to use the functionalities.

**Comment by dhmlau** [comment]
Seems like @0candy has provided the answer.  Closing this issue.  If you have more questions related to this issue, please reopen.  Thanks.
