### ISSUE TITLE
Extending User takes 3 times longer to run unit tests

### ISSUE THREAD

**Issue by dakotahNorth** [strongloop/loopback-datasource-juggler#871]
This issue discuss that extending user takes 20 times longer to fetch ... https://github.com/strongloop/loopback-datasource-juggler/issues/471 and that issue is closed. 

My experience using User with bcrypt (0.8.5) still results in unusually long times. I have 60 unit tests that normally takes a little less then 4 seconds to run (using in memory persistence.) When I switched to inheriting to User, resulted in unusually long times ... 12 seconds.

That is a huge increase in test run times from just inheriting from the User model. While this is much better than 20 times, this is still far too long to run.

**Comment by loay** [comment]
Hi @dakotahNorth 
Are you still experiencing the same issue? Thanks.

**Comment by loay** [comment]
Closing this issue. If you are still experiencing the same problem, please feel free to leave a comment and I will re-open the issue.
