### ISSUE TITLE
Update error message shown when connector is missing

### ISSUE THREAD

**Issue by gunjpan** [strongloop/loopback-datasource-juggler#872]
After creating datasource, if connector is missing, following message is displayed:
```console
WARNING: LoopBack connector "mssql" is not installed as any of the following modules:

 ./connectors/mssql
loopback-connector-mssql

To fix, run:

    npm install loopback-connector-mssql
```

> `npm install loopback-connector-mssql`

should be changed to:

>` npm install loopback-connector-mssql --save`

as this will also add the connector to `package.json` (which is a suggested way in [docs](https://docs.strongloop.com/display/public/LB/Connecting+models+to+data+sources#Connectingmodelstodatasources-Basicprocedure))

**Comment by superkhau** [comment]
@gunjpan Present for you.

https://github.com/strongloop/loopback-datasource-juggler/pull/874

**Comment by gunjpan** [comment]
@superkhau Thanks :)

**Comment by gunjpan** [comment]
PR merged. closing.
