### ISSUE TITLE
Why Model.getDatasource().name always return connector name?

### ISSUE THREAD

**Issue by ChopperLee2011** [strongloop/loopback-datasource-juggler#878]
I suppose it will return datasource's own name, but actually it return connector name.
Is it original designed, or bug?

**Comment by 0candy** [comment]
It should only use the connector name if datasource name is not set. Thank you for pointing out the bug. Name was not being passed in during creation.
https://github.com/strongloop/loopback/blob/master/lib/application.js#L434

If you would like, please contribute by submitting a PR.

**Comment by amismailz** [comment]
Any change here please, Model.getDatasource().name still returns connector name.
