### ISSUE TITLE
Invalid input throws AssertionError: lng must be <= 180

### ISSUE THREAD

**Issue by peek4y** [strongloop/loopback-datasource-juggler#883]
I've a property in a model X

```
"location": {
      "type": "geopoint"
    }
```

And I tried to query randomly with invalid input.

```
{ where: 
  { location: 
    { near: [180,231], maxDistance: 100, unit: 'kilometeres' } 
  }
}
```

 and it throws an AssertionError, and completely crashes the node process.

Is there a way I can handle it? and a way to pass it to a middleware?

**Comment by 0candy** [comment]
Could you please fork the loopback-sandbox with a sample app to reproduce this issue? Thanks!
https://github.com/strongloop/loopback-sandbox

**Comment by peek4y** [comment]
I can reproduce it, I'm using postgres connector btw.

**Comment by peek4y** [comment]
FYI The query - ```{"where":{"location":{"near":[180,231],"maxDistance":100,"unit":"kilometeres"}}}```

**Comment by peek4y** [comment]
Any updates?

**Comment by 0candy** [comment]
@peek4y I am unable to reproduce the issue. Could you please provide a sample app? Thanks.

**Comment by lintiwen** [comment]
I'm having the same issue, lat must <= 90 and lng must <= 180, otherwise it throws error and crashes node process.

Any updates here? I have a temporary hack which is to validate lat / lng in the remote hook, which works but this should be handled at framework level...
