### ISSUE TITLE
{"property" : boolean} and {"parent.child" : boolean} field filters don't work

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-datasource-juggler#903]
consider a model mapped on a mongodb collection which include json documents with several levels of nesting. for example: `{property : boolean}` or `{parent.child : boolean}`

say one wants to apply a filter of the following form on given query: 
`{fields: {parent.child : false}}`

While this is casual stuff with mongodb, the DataAccessObject._normalize method fails on such filters and return instead a filter including all declared properties of the given model.

[see here and below](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1323-L1327), this methods calls the `fieldsToArray`method from `utils` that tries to convert the object fields of the form `{property1: false, property2: false}` in an array of fields to include (sort of opposite filter, converting some "don't include" filters to only "include" filters)

```
  // normalize fields as array of included property names
  if (filter.fields) {
    filter.fields = fieldsToArray(filter.fields,
      Object.keys(this.definition.properties), this.settings.strict);
  }
```

consider the [fieldsToArray method](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L232-L280), the way it works
1. it can't work on {property: false} filters if all model properties are not defined in the model definition which is equivalent to run in strict mode
2. it can't interprete filters with more than 1 level of properties

I guess the logic behind this arrayToFilter transform comes from SQL db compatibility, but wouldn't that be possible to override this behavior when running noSQL db such as mongo?

as it stands, there's propably half the way done here since applying a default field filter directly on the model works with any level of nested properties. I guess it hits directly the native drive here instead of running through dao._normalize method.

Happy to help if guidance/suggestions are provided as it is really a show stopper to have to default to positive includes filters when playing with complex models:
any simple `{dont.include.me : false}` filter turns in a `[do.include.me, me.too, oh.and.me.too, ... i.wanna.join.the.party.too]` filter

i can provide a test repo if needed, but the code lecture is pretty straigh forward

**Comment by jannyHou** [comment]
@ebarault I fail to reproduce your error, mongodb works fine on my local.
I have a model attached to mongodb datasource:
```json
{
  "name": "test",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "boolean"
    },
    "name2": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

Result without filter:
```
[
  {
    "name": true,
    "name2": "strihkjhh",
    "id": "3"
  }
]
```

Result with filter `{"fields": {"name" : false}}`:
```
[
  {
    "name2": "strihkjhh",
    "id": "3"
  }
]
```

If I did anything wrong here or you still have problem with it, please fork https://github.com/strongloop/loopback-sandbox and replace with your code. 
Thanks.

**Comment by ebarault** [comment]
Please test:
-without defining name and/or name2 in your model
-with nested properties in your data: name.subname1, name.subname2

Neither of those 2 test cases works

**Comment by jannyHou** [comment]
@ebarault thank you i see.
So for " -without defining name and/or name2 in your model" I will regard it as a bug, we'd better add a check for it, maybe give a warning/throw an error when users includes non-existed property in filter.

"-with nested properties in your data: name.subname1, name.subname2" looks more like a feature. I think we don't support it now. I will dig into it then.

**Comment by dpundir** [comment]
Regarding the second part '"-with nested properties in your data: name.subname1, name.subname2" looks more like a feature'.
Are we looking to provide this feature?

**Comment by jannyHou** [comment]
@dpundir There is a community pr related to this feature: https://github.com/strongloop/loopback-connector-mongodb/pull/301
And there is a story in loopback to track the feature: https://github.com/strongloop/loopback/issues/517

**Comment by BoLaMN** [comment]
i had to remove this functionality in my fork as it basically breaks all of mongos projection querys 

eg. 

```
where:
  id: id
fields:
  days:
    $elemMatch:
      day: date.isoWeekday()
```

or 

```
where:
  id: id
  revisions:
    exists: true
    ne: []
fields:
  revisions:
    $slice: -1
```

might need some allowExtendedOperators code added to it
