### ISSUE TITLE
update, updateAll do not convert types

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-datasource-juggler#912]
`update`, `updateAll` do not convert types properly; the mentioned methods are static methods and not prototype methods, and therefore no access to instance which is required to call [convertSubsetOfPropertiesByType](https://github.com/strongloop/loopback-datasource-juggler/blob/7247b6637e098047daf8d73d4d864455d80a9566/lib/dao.js#L65-L77)

Possible failing test to reproduce the issue (in `test/manipulation.test.js`):

```
    it('should have updated password hashed with updateAll',
    function(done) {
      StubUser.create({ password: 'foo' }, function(err, created) {
        if (err) return done(err);
        StubUser.updateAll({id: created.id}, {password: 'test'}, function(err, info) {
          if (err) return done(err);
          StubUser.findById(created.id, function(err, found) {
            if (err) return done(err);
            found.password.should.equal('test-TEST');
            done();
          });
        });
      });
    });
```

Relate to https://github.com/strongloop/loopback-datasource-juggler/issues/946

**Comment by Amir-61** [comment]
It seems this is an issue for all static methods; I believe this is a bug for `replaceById` and `replaceOrCreate` as well.

**Comment by bajtos** [comment]
> the mentioned methods are static methods and not prototype methods, and therefore no access to instance which is required to call

I think the methods has access to an instance, because they create a new instance inside. An instance needed e.g. to run validations. 

Having wrote that, I agree it's a good idea to investigate this further and build better understanding on what exactly is happening under the hood.
