### ISSUE TITLE
related model fields are not included when using with root fields filter (PostgreSQL)

### ISSUE THREAD

**Issue by Ascarbek** [strongloop/loopback-datasource-juggler#915]
I want to get only the fields I needed from the model, so I use **fields** filter, but I also have included relations, and they get dropped off the result.

If I don't use fields filter, the related models **are** in the result.

The forked bug repository for reproducing the issue is [here](https://github.com/Ascarbek/loopback-sandbox)

STR:
1. create **test** database in PostgreSQL server.
2. run the **test_db.sql** script in the **test** database created.
3. change the **host** (and other fields if needed like user and password) in the **./server/datasources.json**
4. run the **./issue/issue.js** using **node**

In the output you can see that there is no field from the related model.
If you remove **fields** filter and leave only **include** it will output related model as expected.

P.S.
In my project I have a table with more than 50 fields and 20 related models, so sending out all the fields to frontend is very slow. Filtering fields out would help very much.

Thank you!

**Comment by bekl** [comment]
I'm facing the same issue, but could get it temporarily solved by including the foreign key field of the declaring model.

**Comment by jannyHou** [comment]
confirmed as a bug. Thanks @bekl and @Ascarbek ,really appreciate your sandbox!
