### ISSUE TITLE
Rework DAO.prototype.save() to call replaceById

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#916]
I am proposing to rework `DAO.prototype.save()` to call `replaceById` instead of `prototype.updateAttributes`. This should fix the following problem in the current implementation:

```js
MyModel.findById(someId).then(function(inst) {
  // inst: { name: 'Miroslav', handle: 'bajtos' }
  inst.unsetAttribute('handle');
  // inst: { name: 'Miroslav' }
  inst.save().then(function() {
    // unexpectedly, the record in the datasource is still 
    // { name: 'Miroslav', handle: 'bajtos' }
  }
});
```

Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/921

**Comment by bajtos** [comment]
@Amir-61 I think I got confused. Looking at #921, `prototype.save()` clearly does not call `prototype.updateAttributes()`, but it triggers all hooks on its own and then call `connector.save()`. I think it's not necessary to change that right now, even though it means we have to maintain three different but similar methods `replaceById`, `replaceOrCreate` and `prototype.save`.


As I was investigating this issue further, I realised the problem may be actually in the connectors.

 - mongodb replaces whole instance on `save()`
 - memory performs partial update
 - SQL connectors (e.g. mysql) perform partial update

In my opinion, we should unify the behaviour and fix all connectors to perform full replace when users call `save()`. There should be a unit-test added to the shared test suite to ensure all connectors comply with this requirement.

@raymondfeng @superkhau thoughts?

Here is a standalone script that can be used to test different connectors:

```js
var assert = require('assert');
var loopback = require('loopback');
var app = loopback();

var db = app.dataSource('db', { connector: 'mysql', database: 'test' });
var Person = app.registry.createModel('Person', { name: String, handle: String });
app.model(Person, { dataSource: 'db' });

var id;

db.automigrate()
  .then(function() {
    return Person.create({ name: 'Miroslav', handle: 'bajtos' })
  })
  .then(function(p) {
    id = p.id;
    p.unsetAttribute('handle');
    return p.save();
  })
  .then(function() {
    return Person.findById(id);
  })
  .then(function(p) {
    var data = p.toJSON();
    console.log('result', data);
    // both undefined and null are ok
    //   NoSQL can remove properties - the value should be undefined
    //   SQL have fixed columns - the value should be null
    assert.ok(data.handle == null);
    process.exit(0);
  })
  .catch(function(err) {
    console.error(err.stack);
    process.exit(1);
  });
```

**Comment by Amir-61** [comment]
@bajtos I perfectly understand your feeling when you proposed this feature. It would definitely make sense to rework on `prototype.save` method to call our newly created `replaceById`, if `save` did not have its own implementation in connectors and was calling `updateAttributes` or `updateOrCreate`. However, I believe this refactoring is not really possible due to some limitations, one of which is described [here](https://github.com/strongloop/loopback-datasource-juggler/pull/921#discussion_r62323580) or it is better to say at least it is out of scope or `replaceOrCreate` milestone.

However, I believe the compatibility of `save` methods in different connectors is something which should be addressed, but again thats out of scope of `replaceOrCreate` milestone and can be taken care of later after finishing more important tasks related to the milestone.

I agree with [your comment](https://github.com/strongloop/loopback-datasource-juggler/pull/921#issuecomment-217427560) to close the PR as well.

**Comment by superkhau** [comment]
>In my opinion, we should unify the behaviour and fix all connectors to perform full replace when users call save(). There should be a unit-test added to the shared test suite to ensure all connectors comply with this requirement.

We need to decouple the modules and centralize the shared testing deps (I have work in the juggler refactor epic for this -- bug this has been delayed for awhile). Whether the shared tests are in its own module or part of juggler (./test/api-compliance.test.js) is up for debate.

**Comment by bajtos** [comment]
> @superkhau We need to decouple the modules and centralize the shared testing deps (I have work in the juggler refactor epic for this -- bug this has been delayed for awhile). Whether the shared tests are in its own module or part of juggler (./test/api-compliance.test.js) is up for debate.

In my opinion, that's orthogonal to the discussion here. When I wrote "there should be a unit-test added to the shared test suite to ensure all connectors comply with this requirement", I meant that we should add a new unit-test along the existing unit test for `save`, one that will specifically check for patch-vs-replace difference in behaviour.

> @Amir-61 However, I believe the incompatibility of save methods in different connectors is something which should be addressed, but again thats out of scope of replaceOrCreate milestone and can be taken care of later after finishing more important tasks related to the milestone.

To me, it makes sense to keep this as part of "replaceOrCreate" milestone. My high-level point of view, 
when I was creating this milestone, was to clean up the API and make it clear which operation performs a full update (replace) and a partial update (patch).

However, I think I see what is concerning you, @Amir-61. Let's keep this item a part of the milestone, but let's move it towards the bottom of the backlog, so that we can finish all other items related to `replaceById` and `replaceOrCreate` first and  get a full vertical solution finally available.

**Comment by Amir-61** [comment]
@bajtos Thanks for the comment. I created [a task](mongodb replaces whole instance on save()
memory performs partial update
SQL connectors (e.g. mysql) perform partial update) for incompatibility between `save` methods in different connectors. And in this sprint I pull in another task ([exposing endpoints task](https://github.com/strongloop/loopback/issues/1979)) to finish the most important tasks sooner.

Thanks!

**Comment by superkhau** [comment]
>In my opinion, that's orthogonal to the discussion here. When I wrote "there should be a unit-test added to the shared test suite to ensure all connectors comply with this requirement", I meant that we should add a new unit-test along the existing unit test for save, one that will specifically check for patch-vs-replace difference in behaviour.

I see, I misunderstood what you meant then. I thought you were specifically discussing the API changes. I agree with you that there should be some tests in addition to verify the differences in behaviour between patch/replace.

**Comment by Amir-61** [comment]
>As I was investigating this issue further, I realised the problem may be actually in the connectors.

>mongodb replaces whole instance on save()
memory performs partial update
SQL connectors (e.g. mysql) perform partial update

Thinking of this task makes me wonder why we still should support three different methods (`connector.replaceById`, `connector.replaceOrCreate` and `connector.save`) in different connectors? What we are looking for is exactly `connector.replaceOrCreate` functionality for our `prototype.save` method in DAO; so I'm proposing to call `connector.replaceOrCreate` for our `prototype.save` method in DAO and remove all `save` methods implemented in different connectors... Does this make sense to you? The reason I'm proposing is that even if I end up fixing `save()` methods in the connectors to have a full replace as opposed to partial update, we may end up with exactly the same code for `connector.save()` and `connector.replaceOrCreate()` and duplicate codes...

Please correct me if I'm wrong...

Thanks

**Comment by Amir-61** [comment]
ummm... digging into the problem I noticed calling connector.replaceOrCreate() for prototype.save in DAO may not to work either, because we don't have the atomic implementation of replaceOrCreate for some connectors...That being said, still it may make sense to implement atomic implementation of replaceOrCreate for all connectors and remove connector.save() calls for prototype.save() in DAO and call prototype.replaceOrCreate() instead... thoughts? Although this may be be quite a bit of work but fixing connector.save() to have full replace ends up with the same amount of work I believe...

**Comment by bajtos** [comment]
The discussion continues here: https://github.com/strongloop/loopback/issues/2393
