### ISSUE TITLE
Spike: generate TypeScript Definition files

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#920]
Spike for https://github.com/strongloop/loopback/issues/1692

**Comment by ritch** [comment]
@Amir-61 can you look at this - this sprint?

@pthieu ??

**Comment by pthieu** [comment]
@ritch: sorry we've already planned our sprint, we'll throw it into the next one.

**Comment by pthieu** [comment]
sending to apex since they own the FA /cc @0candy @kjdelisle

**Comment by ssh24** [comment]
Closing this. Please follow here: https://github.com/strongloop-internal/scrum-apex/issues/40
