### ISSUE TITLE
Make strict option default to true for anonymous models

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-datasource-juggler#923]
When declaring the model definition JSON file, you can directly declare embedded document properites such as

```javascript
...
{
	"properties":{
		"range": {
			"min":"number",
			"max":"number"
		}
	}
}
```
and it works and also accepts only numbers. The problem with this is that it also accepts any other property in the **range** subdoc (strict option is set to false). This is due to **resolveType** in **model-builder.js** which creates an anonymous model for the subdocument defined (range). The problem is that resolveType defines the model with no strict option set, so it defaults to false. See [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L711)

I believe that the most common behaviour would be to only keep properties that are defined in the model.... So default behaviour for strict options should be set to true, and not have to declare a separate definition file for such a small schema like **range** just to declare the **strict** option.

**Comment by bajtos** [comment]
Makes sense to me. Would you like to contribute this change yourself, @mitsos1os?

**Comment by mitsos1os** [comment]
@bajtos Happy to see we are on the same page! Will do so yes

**Comment by mitsos1os** [comment]
Should I do it generally or only for mongoDB?

**Comment by mitsos1os** [comment]
Created pull request for this change here: https://github.com/strongloop/loopback-datasource-juggler/pull/940
