### ISSUE TITLE
Polymorphic HasAndBelongsToMany references incorrect discriminator on Model.find

### ISSUE THREAD

**Issue by beaglez** [strongloop/loopback-datasource-juggler#927]
In the example provided in the documentation on https://docs.strongloop.com/display/public/LB/Polymorphic+relations#Polymorphicrelations-HasAndBelongsToManypolymorphicrelations, the following does not work:

`Picture.find(
    {
        include: 'Author'
    },
    cb
);`

The query is looking for imageable='Picture', instead of imageable='Author' in PictureLink. I believe the defect is on the following lines:

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L408-L409

**Comment by jannyHou** [comment]
@beaglez when you create relation `hasAndBelongsToMany`, the default relationship name for both directions are in plural. 
So you need to call `Picture.find( { include: 'Authors' }, cb);`
Please update info here if you still have problems.

**Comment by loay** [comment]
Closing issue. Please feel free to leave a comment if you are still experiencing the same problem.
