### ISSUE TITLE
Doc of findOrCreate is wrong?

### ISSUE THREAD

**Issue by jkvim** [strongloop/loopback-datasource-juggler#932]
As the [document](http://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate) say, when findOrCreate match the where filter, `created` SHOULD be true, but after reading the source code of [findOrCreate](https://github.com/clarkorz/loopback-datasource-juggler/blob/master/lib/dao.js#L664-L681), it is opposite.

**Comment by Amir-61** [comment]
Thanks @jkvim for helping us to improve the documentation; right now I see the doc for 'created' in `callback`says: "True if the instance matching the where filter was created.". which could be correct, but may be better to say 'True if the instance does not exist and gets created'. @crandmck you are an expert and have a better idea...

@crandmck I just wanted to update JSdoc, however I don’t see such a thing in JSdoc (https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L821-L826)... am I missing something?

**Comment by crandmck** [comment]
So, just to be clear, the `created` argument to the callback _should be_ true if the method does not find an existing instance that matches the filter, and therefore the method creates a new instance.  @jkvim Are you saying that's not the case?

@Amir-61 Assuming that the method does behave as described above, then your suggested change to the wording is fine--feel free to go ahead and make it.  If it the method does not behave that way, then I think that is bug and should be logged as such.

As far as the API doc comment, it is at: https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L118-146.
PersistedModel simply delegates to dao object, and the doc comments in `dao.js` are no longer used for API docs, AFAIK.  We should probably just remove them to avoid future confusion--better yet, replace them with a comment that notes where the API doc comments are.

**Comment by Amir-61** [comment]
Thanks I sent a [PR](https://github.com/strongloop/loopback/pull/2349) to make it clearer.

**Comment by jkvim** [comment]
@crandmck yes that‘s what i say.

@Amir-61 thanks for answer.

**Comment by Amir-61** [comment]
@jkvim Thanks!

But [based on the code](https://github.com/clarkorz/loopback-datasource-juggler/blob/master/lib/dao.js#L664-L681) it should work as expected; it should return `true` if the instance does not exist and gets created and `false` if it finds an existing instance. Could you please provide a sample repo reproducing the issue; you can use memory connector with `file` option which saves the data in a JSON file to populate data to reproduce the issue.

Thanks!

**Comment by Amir-61** [comment]
This does not seem a bug; Closing it now; however if you see any issues please use our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue and re-open the ticket.

Thanks!
