### ISSUE TITLE
automigration of *-change models doesn't work

### ISSUE THREAD

**Issue by kaktus42** [strongloop/loopback-datasource-juggler#933]
Change models from here: https://docs.strongloop.com/display/public/LB/Synchronization#Synchronization-Setup

with definition of `"trackChanges": true` and no extra entry in `model-config.json` auto migration in boot script fails

```
module.exports = function(app) {
  var ds = app.datasources.myPostgres;
  var Todo = app.models.Todo;
  var TodoChange = app.models.Todo.Change;

  ds.automigrate(["Todo", "Todo-change"], function(err) {
    console.log(err);
  });
}
```

no error from this callback, but the table `todo-change` is not created. => error later on `error: relation "public.todo-change" does not exist`

**Comment by kaktus42** [comment]
it seems that the Change Model subscribed an event when SQL query is executed.
But in that listener it seems to call SQLConnector.all.

This leads to a all query when (even before) the table gets deleted with automigrate().

Can someone with more insight here, please help me out?

**Comment by kaktus42** [comment]
Found this: strongloop/loopback-connector-postgresql#82
Also no solution so far... The workaround doesn't work for me

**Comment by Amir-61** [comment]
Is this just an issue with Postgres or all SQL connectors?
Could you please provide a sample repo reproducing the issue; you can use our [loopback-sandbox](https://github.com/sebastianhaas/loopback-sandbox) to reproduce the issue.

Thanks

**Comment by kaktus42** [comment]
[kaktus42/loopback-sandbox](https://github.com/kaktus42/loopback-sandbox)
