### ISSUE TITLE
Fields filter on missing fields

### ISSUE THREAD

**Issue by MarkAndrewJohnson** [strongloop/loopback-datasource-juggler#935]
I seem to have hit a problem while testing optional filter.fields settings based on whether the current user is a member of a group or not.  This is using a MongoDB backend and the function returns an array of records.  For the purposes of the issue I'm only describing a single record here.

For example a sample record is as follows:
`{
    "status": "approved",
    "id": "572815ae23207d2966221577",
    "userId": "570c45f517de904f4626d819",
    "groupId": "570b040b0f84734a7edfa11e"
  }`

Now let's say I apply the following filter:
`{"fields":{"userId":false}}`
I get the following:
`{
    "status": "approved",
    "id": "572815ae23207d2966221577",
    "groupId": "570b040b0f84734a7edfa11e"
  }`
Great.  Field filter works.

Now, let's say I want to hide the form property, which may or may not be set:
`{"fields":{"form":false}}`
This produces the following result:
`{
    "status": "approved",
    "id": "572815ae23207d2966221577",
    "userId": "570c45f517de904f4626d819"
  }`

groupId is now missing!

Upon further testing it seems that for each field that you've set to false in the fields filter, and that property does not exist for a given record, the last property of a record is removed.  This therefore makes it awkward to apply such a filter to sparse fields.

**Comment by jannyHou** [comment]
@MarkAndrewJohnson thank you I reproduced this issue, the result is a little different from yours but a filter with an non-existed field false does hide another property.

Here is my result with mongodb:
1. A model with property status, userId, groupId, and the default id
2. filter `{"fields":{"userId":false}}`
```
[
  {
    "status": "string",
    "groupId": "stri",
    "id": "573b425946be52d42ec793fd"
  },
  {
    "status": "string",
    "groupId": "stri",
    "id": "573b425946be52d42ec793fe"
  },
  {
    "status": "string",
    "groupId": "stri",
    "id": "573b43ad46be52d42ec793ff"
  }
]
```
works well
3. filter `{"fields":{"form":false}}`
```
[
  {
    "status": "string",
    "userId": "string",
    "groupId": "stri"
  },
  {
    "status": "string",
    "userId": "string",
    "groupId": "stri"
  },
  {
    "status": "string",
    "userId": "string",
    "groupId": "stri"
  }
]
```
So id is missing

I will post the link to sample sandbox later

**Comment by thovden** [comment]
This is still a problem - just ran into it.
