### ISSUE TITLE
Search by id of the model related via hasAndBelongsToMany 

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#94]
Consider the use-case described in #85: a product hasAndBelongsToMany categories.

One can get all products of a category CAT-ID without category data by calling

```
GET /api/categories/CAT-ID/products
```

To keep the API consistent with what is available for "product belongsTo category" relationship, LoopBack should support also a request similar to this one:

```
GET /api/products?filter[where][categoryId]=CAT-ID
```

The where expression should probably allow multiple ids, something along the lines "where categoryIds include {id-list}".

**Comment by jonathan-casarrubias** [comment]
+1 on this feature...

I have a hasMany through relationship  for Task and Products, every task can have many products assigned and every product can be on any task.

So, what I want to achieve is to find a task depending on the products assigned, in a mongo like query  would be something like

```javascript
Task.find({
    where: {
        // consider id is part of the through table
        'product.id': id 
    }
});
```

that would be really helpful for querying related models, another use case could be searching not in the through table but in the related model..

example:

```javascript
Task.find({
    where: {
        // consider property name to be attribute of Product collection
        'product.name':  'a name' 
    }
});
```

That last one would be more than awesome, but not sure about performance and other kind of stuff not visible in my scope.

Please advice.

Cheers,
john

**Comment by lushibi** [comment]
+1, any update on this issue? I have a product hasAndBelongsToMany tags relation, but how to do: find all products with a specific tag?

**Comment by holbora** [comment]
+1 
updates on this issue?

**Comment by altais** [comment]
+1
