### ISSUE TITLE
EmbedsOne save does not call parent save to update parent model with changes

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-datasource-juggler#945]
see https://github.com/strongloop/loopback/issues/2376 ...

**Comment by 0candy** [comment]
The .trigger function is deprecated and will be removed in LB 3.0. 
Please use operation hooks for replacement.

https://docs.strongloop.com/display/APIC/Operation+hooks

**Comment by mitsos1os** [comment]
OK so how will nestRemoting work? Since I do not see any other reference of `prepareEmbeddedInstance` which is how the parent model gets notified for the child changes right??? 
It overrides the .trigger to first call the action on the embedded's model parent

**Comment by 0candy** [comment]
nestRemoting is done here:
https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/lib/model.js#L685

The `prepareEmbeddedInstance` was added so that a separate `save` call was not needed when updating a relation.
https://github.com/strongloop/loopback-datasource-juggler/commit/96a276a12b4a75a85b1092ccbd4ad0b31c5fd056

I think you're right, I don't think the EmbedOne has the parent save. You will have to make a separate call to parent save.

Could you please fork the loopback-sandbox with a sample app so I can better understand what you're trying to do? Thanks!
https://github.com/strongloop/loopback-sandbox

**Comment by mitsos1os** [comment]
@0candy I am sorry but I made a mistake. nestRemoting has nothing to do with it, I was trying it like that and I was too tired, and thought the issue was related.... nestRemoting works correctly at exposing inner model relationships... The problem is as you mentioned that embedsOne does not call the parent save when you call save on the embedded model. In contrast, embedsMany does this correctly through overriding the .trigger I mentioned in prepareEmbeddedInstance... If this is going to be deprecated, then somewhere else for both embedding relations, the save of parent should be also called... 

I have created a repository showing the difference between these two relationships work here:
https://github.com/mitsos1os/loopback-sandbox/tree/embedsone-parent-save

I have created an override that also implements the prepareEmbeddedInstance in embedsOne, but if this is to be deprecated, it is also nogo....

**Comment by 0candy** [comment]
Thank you for creating the repository. We will definitely look for a replacement if we remove the deprecated code. I will label this as a feature to add it to embedsOne.

**Comment by mitsos1os** [comment]
@0candy This right now isn't working correctly, and it is actually a bug and not a feature, because updating the embedded model (in embedsOne relationship) does not update the parent..
Would you like me to issue a pull request on the 2.x branch so that is it fixed in this version, and when later trigger hooks are deprecated you should update the functionality in both embesMany and embedsOne relationships?

Thanks

**Comment by 0candy** [comment]
I put it as a feature because it wasn't something that was originally working and stopped working. That would be a bug. Last time someone contributed a PR for embedsMany which is why it works for that. Please feel free to submit a PR for embedsOne. Thank you!

**Comment by mitsos1os** [comment]
I have just issued a pull request for what we talked about here: https://github.com/strongloop/loopback-datasource-juggler/pull/949

**Comment by mitsos1os** [comment]
https://github.com/strongloop/loopback-datasource-juggler/pull/949 was accepted so closing issue
