### ISSUE TITLE
Model included in other model through operation hook is not updated on PUT

### ISSUE THREAD

**Issue by vroudge** [strongloop/loopback-datasource-juggler#963]
Hello,

I've just started using loopback, and I'm really amazed by the framework. Thanks a lot!

Here's my issue. I've got a _Cart_ model and an _Address_ model.
When using PUT on Cart to update the addressId it references, Cart gets updated, the addressId gets updated, but the Address iobject ncluded in the result of the request is not updated.

I'm using the following to include it via the `access` operation hook.

```
Cart.observe('access', includeEntries);

function includeEntries(ctx, done){
    if (ctx.query && ctx.query.include && Array.isArray(ctx.query.include)) {
        ctx.query.include.push('address', 'other', 'otherother');
    } else if (ctx.query.include){
        ctx.query.include = [ctx.query.include,'address', 'other', 'otherother'];
    } else {
        ctx.query.include = ['address', 'other', 'otherother'];
    }
    return done();
}
```

There is the relation referenced in `cart.json`:

```
"address": {
      "type": "belongsTo",
      "model": "address",
      "required": false
    },
```

and here is what `Cart` looks like:

```
{
    "cartId": "123123123",
    "createdAt": "2016-06-03T00:00:00.000Z",
    "updatedAt": "2016-06-03T16:37:48.041Z",
    "expired": false,
    "expiresAt": "2016-06-03T00:00:00.000Z",
    "status": "active",
    "addressId": 1,
    "address": {
      "id": 1,
      "streetNumber": "271",
      "address": "Rue de honhon",
      "city": "Paris",
      "zipCode": "75000",
      "country": "France",
      "name": "herpa derp",
      "note": "",
      "customerId": 1
    }
  }
```

We've been thinking that this is probably because includes are not resolved at the model update. What do you think?

**Comment by vroudge** [comment]
No feedback ? :(

**Comment by jannyHou** [comment]
@vroudge I am trying to reproduce your problem, could you fork https://github.com/strongloop/loopback-sandbox and upload your code? Thanks!
