### ISSUE TITLE
Mongo specific operator data stored in Model instances when using updateAttributes

### ISSUE THREAD

**Issue by leolannenmaki** [strongloop/loopback-datasource-juggler#967]
I have a call like: `myModel.updateAttributes({'$inc': {'myProperty': 10}})`
That goes just fine through datasource-juggler and mongo-connector and get's persisted as it should to the database as per https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-UsingMongoDBoperatorsinupdateoperations

The only problem is that if I inspect `myModel` after the operation it has a property `$inc`. I think the problem is here https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2890

Before that line `myModel` looks like:

```
{ __cachedRelations: {},
  __data:
   { email: 'foo.bar@baz.com',
     username: null,
     password: '$2a$10$MT0PD.A0Fbf8lO0vsssXZugraJFCAkU5czu4O3blf94KhJ5cy7hW2',
     emailVerified: true,
     created: '2016-06-08T09:06:35.412Z',
     modified: '2016-06-08T09:06:36.736Z',
     myProperty: 20
     id: '5757e01b0671632b2e336ebc' },
  __dataSource: undefined,
  __strict: true,
  __persisted: true }
```

After that line:

```
{ __cachedRelations: {},
  __data:
   { email: 'foo.bar@baz.com',
     username: null,
     password: '$2a$10$MT0PD.A0Fbf8lO0vsssXZugraJFCAkU5czu4O3blf94KhJ5cy7hW2',
     emailVerified: true,
     created: '2016-06-08T09:06:35.412Z',
     modified: '2016-06-08T09:06:36.736Z',
     myProperty: 20
     id: '5757e01b0671632b2e336ebc' },
  __dataSource: undefined,
  __strict: true,
  __persisted: true,
  '$inc': { myProperty: 10} }
```

See added `$inc` property on the bottom that shouldn't really be there in my opinion. This can cause problems if I now `myModel.save()` as I think LB will try to persist that property and then Mongo complains that no key can start with a $ character.

**Comment by Amir-61** [comment]
Hey @leolannenmaki 

Would you like to submit a patch fixing this? Also in the patch please call `myModel.save()` to see the extra fields cause problems.

Thanks
