### ISSUE TITLE
Exposure of information

### ISSUE THREAD

**Issue by daankets** [strongloop/loopback-datasource-juggler#971]
Upon certain datasource errors (connector specific), the datasource juggler forwards error details to the calling layer, that should not be exposed. For example, when using mongoDB, and executing <model>.create({...}) with data that violates a unique index, the datasource juggler will forward the data structure that was supposed to be inserted. This way, certain (for example hidden) fields that must never be exposed to the end user are disclosed in the error message to the client:

**Example**
```javascript
{
  "error": {
    "code": 11000,
    "index": 0,
    "errmsg": "E11000 duplicate key error index: someDb.someColelction.$someIndex dup key: { : \"value1\", : \value2\" }",
    "op": {
      "a": "value1",
      "b": "value2",
      "status": "new",
      "hiddenApiClientId": "H1rMIXDV",
      "hiddenApiSecretKey": "5759a60dbad24e4393c8984b"
    }
  }
}
```

In my opinion, such errors must always be logged to the console, and then propagated in a reduced and sanitised form (referring to the id or timestamp of the log entry).

**Comment by Amir-61** [comment]
Hey @daankets,

Thanks for bringing this to our attention. I believe this is debatable; I agree It may be a security leak in some scenarios. I propose that we introduce a flag by which we can mute the error which returns from the connector and instead we show an appropriate error message. @bajtos @superkhau any thought?

Thanks

**Comment by superkhau** [comment]
Sounds like we need something like log levels to limit the verbosity of the returned results. It's a feature request, but a very broad one that may not be so actionable (until we get an exhaustive list of which connectors and which methods to fix, etc). @bajtos Thoughts?

**Comment by daankets** [comment]
I have (for now) implemented a global afterRemoteError component that will
capture errors that have either status 500 or no status, and that will
'sanitise' them - and log them to the error log with a reference. The error
that is then propagated to the client refers to the log reference.
On Tue, 14 Jun 2016 at 18:22, Simon Ho <notifications@github.com> wrote:

> Sounds like we need something like log levels to limit the verbosity of
> the returned results. It's a feature request, but a very broad one that may
> not be so actionable (until we get an exhaustive list of which connectors
> and which methods to fix, etc). @bajtos <https://github.com/bajtos>
> Thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/strongloop/loopback-datasource-juggler/issues/971#issuecomment-225935969>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACLKMVZ1qVLVht_NcypUr7_ZNouH2XOqks5qLtVGgaJpZM4IyN7M>
> .
>

-- 
*Disclaimer*
This message is *confidential* and only intended for the originally 
intended recipient(s). It may also be privileged or otherwise protected by 
work product immunity or other legal rules. *If you think you have received 
this message by mistake*, please let us know by e-mail reply and delete it 
from your system; you must not copy this message or disclose its contents 
to anyone other than the intended recipients.

**Comment by bajtos** [comment]
Hello, we are already working on a fix for this problem. The solution we have in mind is to use a different error handling middleware that will not leak any sensitive information when running in production, but providing a configuration option that allows the user to enable detailed debug responses containing all sensitive information. See https://github.com/strongloop/loopback/issues/1650.

I am proposing to close this issue as a duplicate.

**Comment by Amir-61** [comment]
Great... closing this ticket in favour of WIP https://github.com/strongloop/loopback/issues/1650
