### ISSUE TITLE
Scopes should be able to accept arguments

### ISSUE THREAD

**Issue by jameslk** [strongloop/loopback-datasource-juggler#972]
In other frameworks such as Ruby on Rails or Laravel, scopes can take arguments to build their query (i.e. dynamic scopes). In Loopback, it seems they cannot take any arguments because those arguments go straight to the finder instead of the scope function:

https://github.com/strongloop/loopback-datasource-juggler/blob/v3.0.0-alpha.4/lib/scope.js#L176

Instead, if the scope is a function, I suggest the scope function should be given the arguments for it to refine its query. If the query should be further refined, then the `.find` method can be called with additional conditions.

For example:

``` javascript
House.scope('topTenByType', (type) => {
  return {
    where: {type: type},
    order: 'popularity DESC',
    limit: 10
  };
}

House.topTenByType('singleFamilyHome').find(() => { ... });

House.topTenByType('duplex').find({where: {zipCode: 80303}, () => { ... });
```

This would also lend itself to becoming chainable:

``` javascript
House.topTenByType('condo').inCitiesOf('boulder', 'denver', 'arvada').find(() => { ... });
```

I understand this might not play very well with the existing API, so perhaps a new method called `dynamicScope` can be introduced to prevent breaking existing code.

**Comment by Amir-61** [comment]
Hey @jameslk,

Thanks for proposing this feature. It seems interesting; I decided to put a `feature` label for this ticket. Also please note that we welcome community controbution. So please feel free to send a patch for this feature.

Thnaks

**Comment by jameslk** [comment]
@Amir-61 Thanks for considering it. I'll see if I have some bandwidth to iterate on it here in the coming week or so.

**Comment by Amir-61** [comment]
@jameslk Please ping me in the PR so I make sure it gets reviewed and landed ASAP.

**Comment by jameslk** [comment]
Will do, thanks @Amir-61!

**Comment by jmls** [comment]
@jameslk : did you get anywhere with this ? I was needing similar functionality

**Comment by jameslk** [comment]
@jmls We switched to using GraphQL over REST which largely made the querying more simple, and consequently our needs for more thorough scopes less important, so unfortunately I have not worked on this
