### ISSUE TITLE
Memory Backend is very Slow when Writing 

### ISSUE THREAD

**Issue by vanthome** [strongloop/loopback-datasource-juggler#974]
I have a dataset of 2MiB with data like this:

``` json
{
    "timestamp": "2014-01-31T23:15:00.000Z",
    "value": 0
}
```

The corresponding model looks like this:

``` json
{
  "name": "Ds4",
  "plural": "ds4",
  "base": "Base",
  "options": {
    "validateUpsert": false
  },
  "properties": {
    "timestamp": {
      "type": "String"
    },
    "value": {
      "type": "Date"
    }
  },
  "validations": [],
  "relations": {
  },
  "acls": [],
  "methods": {}
}
```

whether I try to create each object individually or supply an array of all objects to `ModelClass.create()` it takes ages to write this data. 
It would be great if this could be enhanced to be more efficient.
I also don't understand why this is so slow as the backend seems to have a queueing mechanism for writes.

A related issue is this, but this one is not specific for the Memory backend:

https://github.com/strongloop/loopback/issues/1275

**Comment by superkhau** [comment]
Can you provide the sample data set so we can reproduce this issue on our end?

**Comment by vanthome** [comment]
Well it's really as simple as I wrote in the original issue. Just repeat the object 35000 times then you have roughty my data set.

**Comment by superkhau** [comment]
More specifically, can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by superkhau** [comment]
@vanthome Are you still working on this?

**Comment by superkhau** [comment]
Closing as abandoned, please feel free to ping if you're still interested in working on this @vanthome. We can reopen the issue then.
