### ISSUE TITLE
Adopt a fail-fast approach for findOrCreate

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-datasource-juggler#977]
I would like to propose a usecase where validating the query passed to `findOrCreate` in loopback would serve the greater interest (I hope). cc @bajtos and @doublemarked and @aquid

The following are all valid ways to invoke:

```
findOrCreate({}, ...) // a. match all ... sort of defeats the purpose of findOrCreate but maybe it has merit for someone out there
findOrCreate({ where:{} }, ...) // b. again match all ... sort of defeats the purpose of findOrCreate but maybe it has merit for someone out there
findOrCreate({ forgot:true }) // c. a complete and total unintended mistake because the developer forgot the *where* clause ... this is a great candidate for a fail-fast validation`
```

I recently had to suffer the horror of point-C because the code just flows naturally and if an application's end-2-end tests don't catch it (mine only tested the same user across all workflows, never multiple users logging in and working one after another) then that bug slips through, too easily.

I think it would be reasonable to consider the following fix as backward compatible and future-proof:

> if the `query` contains more than zero keys and none of them match `where` or any of the other keywords in loopback then `findOrCreate` should fail-fast with an error.

I could submit a PR for this and I think it would involve edits made to:
`DataAccessObject.findOrCreate = function findOrCreate(query, data, options, cb) { ...`

but if I'm barking up the wrong tree, please set me straight.

**Comment by pulkitsinghal** [comment]
Oh and it would serve as self-correcting by telling the developer what's wrong, wouldn't it be nice to avoid threads like: https://github.com/strongloop/loopback-connector-postgresql/issues/107

**Comment by doublemarked** [comment]
We've also encountered problems stemming from lack of validation of filter and other arguments. This is not limited to findOrCreate. You'll need a config directive to implement validation without breaking existing code, but perhaps it's something acceptable to enable by default for future versions. I know a similar discussion took place in an Issue regarding `undefined`. Perhaps some of the decisions there are relevant to this issue.

**Comment by pulkitsinghal** [comment]
@doublemarked - I haven't been able to narrow down the search and find the `undefined` issue in question. If you ever happen to come across the issue number or link in your notes, please do share.

**Comment by bajtos** [comment]
> if the query contains more than zero keys and none of them match where or any of the other keywords in loopback then findOrCreate should fail-fast with an error.

I think this is a great idea! Can we push it a bit more and validate the `filter` argument in all methods, not only in `findOrCreate`? I am looking at the `find` method in particular.

It's ok to work on this incrementally, start by improving `findOrCreate` and then contribute other improvements as time & will allows.

My main concern is about backwards compatibility, for example with applications extending syntax of `filter` object with their own top-level keys that are handled e.g. by remoting hooks.

@raymondfeng @ritch @fabien what do you think?

**Comment by pulkitsinghal** [comment]
@bajtos and @doublemarked given:
> My main concern is about backwards compatibility, for example with applications extending syntax of filter object with their own top-level keys that are handled e.g. by remoting hooks

I think that it is perhaps perfect to add a:
> config directive to implement validation without breaking existing code

... because when that is turned on, there will be an option for the developer to specify `their own top-level keys` and hopefully the documentation will stress that they think about this seriously rather than hand-waive the optional configuration and then face-palm due to test failures later.
