### ISSUE TITLE
No options passed in validation causes big concurency problems with postgres

### ISSUE THREAD

**Issue by robinbiondi** [strongloop/loopback-datasource-juggler#984]
Validation problems because no options given:
=====================================

Facts:
-------
When I want to update an object which needs a validation, the validation is called in the datasource-juggler but the options of my request are not given to the validation function.

The validation function makes a query without my eventual current transaction which should be in the options.

Big concurency problems:
----------------------------------
The connection pool of  postgres-connector has a limited amount of connection. (10 by default)
If  I have a remoteMethod starting a transaction in order to update a model, and if 10 users call this endpoint at the exact same time, then my 10 connection in my connection pool will be used for the 10 different transactions.
It's not a problem most of the time.

But, if my model needs a validation (ex: ValidateUniquenessOf email on a user), then before saving my model, the validation function will make a select query out of my transaction context. My transaction will wait for the result in order to continue.

As my 10 connections are already taken by the transactions, postgre-connector will queue my request until a connection is released. which will never be the case because my transactions are waiting for this validation request.

We are in a **deadlock** situation.

**This make loopback not suitable for production with postgres**

Proposition:
----------------

The datasource-juggler should take an `option` parameter which would potentially be passed to the connector if the connector is suitable with options.
This mean we should modify all the validation functions in `validation.js` (`isValid`, `validationFailed`,`ModelConstructor.validateUniqueness`, ...)

Conclusion:
----------------
This is a big problem which causes serious issues. I will start a PR. Let me know if my solution seems good to you.

**Comment by Amir-61** [comment]
Hi @robinbiondi,

It seems the [PR#986](https://github.com/strongloop/loopback-datasource-juggler/pull/986) has been landed. Is the problem solved? Can we close the issue?

Thanks!

**Comment by robinbiondi** [comment]
Hi @Amir-61 . Yes the problem is solved. I close the issue.
Cheers!
