### ISSUE TITLE
3 Level Nested hasMany Query Returning Empty Array

### ISSUE THREAD

**Issue by tetter36** [strongloop/loopback-datasource-juggler#988]
I'm trying to do a nested query as per the instructions and examples here:
https://docs.strongloop.com/display/public/LB/Include+filter
https://github.com/strongloop/loopback/issues/735

but it is not working like I expected it to. I have an Account, that can have many Branches, that can have many Incidents, Risk Assessments and Claims. I have created a custom endpoint for the Branch to query the related Incidents, Risk Assessments, and Claims, but I can't get the information from the Account level.

Here is the working code for the Branch:

    Branch.find({
            where: {
                id: id
            },
            include: [
                {
                    relation: 'incidents',
                    scope: {
                        where: {
                            incidentDate: {
                                between: [
                                    beginDate,
                                    today
                                ]
                            }
                        }
                    }
                },
                { relation: 'riskAssessments' },
                { relation: 'claims' }
     }, function (err, obj) {
            if (err) return cb(err);
            cb(null, obj);
    });

Here is the code that I would expect to work for the Account:

    Account.find({
            where: {
                id: id,
            },
            include: {
                relation: 'branches',
                scope: {
                    include: [
                        {
                            relation: 'incidents',
                            scope: {
                                where: {
                                    incidentDate: {
                                        between: [
                                            beginDate,
                                            today
                                        ]
                                    }
                                }
                            }
                        },
                        { relation: 'riskAssessments' },
                        { relation: 'claims' }
                    ]
                }
            }
        }, function (err, obj) {
                if (err) return cb(err);
                cb(null, obj);
        });

However, this only gives me the Account and an empty array of Branches. If I run it with this code:

    Account.find({
            where: {
                id: id,
            },
            
            include: {
                relation: 'branches',
            }
     },function (err, obj) {
                if (err) return cb(err);
                cb(null, obj);
     });

It gives me the Account with the related Branches. Whenever I add the 

    scope: {
        include: {
            relations: 'riskAssessments',
        }
    }

it doesn't work, and returns the empty Branch array. I can add other parameters in the scope like fields, where, etc and they work as expected, it's just when I add the include that it becomes an empty array.

I'm assuming this is a bug since it works perfectly in a single nested query for Branch. I'll continue looking into the issue to see if I can offer up a potential solution.

Here are the versions I'm using:
    "loopback": "^2.29.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.1.0",
    "loopback-component-storage": "^1.8.1",
    "loopback-connector-postgresql": "^2.4.1",
    "loopback-datasource-juggler": "^2.46.1",

**Comment by tetter36** [comment]
Closing as this is related to the issue that can be found here: https://github.com/strongloop/loopback/issues/2356

**Comment by kranthitechie** [comment]
@tetter36 I am facing the same issue. Have you been able to resolve this?

Also, Aren't these two separate issues?
Don't see how https://github.com/strongloop/loopback/issues/2356 is related to the issue reported in this thread.
