### ISSUE TITLE
query using where filter with exists

### ISSUE THREAD

**Issue by tsanjoto** [strongloop/loopback-datasource-juggler#997]
Hi, I have an issue on trying checking on particular model if it have a specific property for mongoDB

Say I have a model 'Task', it only have 2 properties. Title and Description. where the description is optional.
and the auto-generate model files from slc loopback:model generated task.json

`

```
"properties": {
  "taskTitle": {
    "type": "string",
    "required": true
  },
  "taskDescription":{
    "type": "string"
  }
```

`

I want to use the StrongLoop explorer 'where' filter to fetch on all Tasks that have the "taskDescription" parameter in existence. So I would use this filter

`{"where":{"taskDescription":{"exists":true}}}`
or for no taskDescription
`{"where":{"taskDescription":{"exists":false}}}`

BUT it will always gives the wrong result.

if I completely remove "taskDescription" json block in common/models/task.json, or change the type to "Any" it will behave perfectly correct

`

```
  "taskDescription":{
    "type": "Any"
  }
```

`

But doing so would eliminate the DataType validation.

This problem also stretches to all different DataTypes like Dates. such as #592

**Comment by KevinMongiello** [comment]
👍
